### ISSUE TITLE
Linkedin option is not working in social buttons widget

### ISSUE THREAD

**Issue by jainnidhi** [elementor/elementor#10098]
Hello team,

Linkedin URL is not working in social buttons widget. It's showing the message 

> I's not you. It's us. Give it another try, please. Try again

Can you please help me out?

**Comment by ideasandpixels** [comment]
I'm having the same issue. All of my share buttons work except for LinkedIn. It says: 

> Invalid HTTP Request
Could not process this client request HTTP method request for URL. Please double-check the URL (address) you used, or contact us if you feel you have reached this page in error.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9.7
Feel free to update

Thanks!

**Comment by DouglasTTG** [comment]
![image](https://github.com/elementor/elementor/assets/141744546/60f521f3-d3bc-472f-b6e5-ada4bffd061f)
The problem is still happening

**Comment by kuruvi008** [comment]
> I'm having the same issue. All of my share buttons work except for LinkedIn. It says:
> 
> > Invalid HTTP Request
> > Could not process this client request HTTP method request for URL. Please double-check the URL (address) you used, or contact us if you feel you have reached this page in error.

I faced the same issue with the LinkedIn share button not working on my site. All other buttons are fine, but LinkedIn doesn’t seem to function. Is there a solution for this problem now?
