### ISSUE TITLE
Include/Exclude Context toggle button in "Archive Title" module don't work as expected in search templates

### ISSUE THREAD

**Issue by DrumFredo** [elementor/elementor#10424]
Hi! The toggle button for include/exclude "context" in the archive title module when using a condition for search templates in Theme Builder seems to be unset.

The problem seems to be inside the class _Utils_ in file _elementor-pro/classes/utils.php_ 
The if statement for **is_search()** inside the method: _public static function get_page_title( $include_context = true )_
missing an if statement for: **if ( $include_context ){....}**

**Comment by karimhossenbux** [comment]
having the issue even on Page, Post, Archives, or WooCommerce Product.
The checkbox doesn't hide the context

**Comment by PedroTiagoSimao** [comment]
> having the issue even on Page, Post, Archives, or WooCommerce Product.
> The checkbox doesn't hide the context

Also having this issue on Elementor v3.0.16 and Elementor Pro v3.0.9

**Comment by JasonBroderick** [comment]
Still having this issue, Elementor v3.1.1 and Elementor Pro v3.0.9

Toggling "Include Context" to "Off" has no effect, full archive and search context is displayed.

**Comment by websplash** [comment]
Still existing bug

**Comment by DigitalBerry** [comment]
Come one Elementor! FIX THESE TINY ISSUES WHICH MAKE YOUR CUSTOMERS LIVES A PAIN IN THE ASS!!!!!

Still a bug in April 2021!

No doubt we'll get gradient buttons before this is fixed 👎

**Comment by Yanis705** [comment]
Still having this issue, Elementor v3.2.1 and Elementor Pro v3.2.1
Toggling "Include Context" to "Off" has no effect, full archive and search context is displayed.

**Comment by petermann** [comment]
My temporary solution, use a custom shortcode in the title.

```
/**
 * Custom title for Archives without prefix.
 */
add_shortcode('cm_single_term_title', 'fn_cm_single_term_title');

function fn_cm_single_term_title()
{
	if (is_category()) {
		$title = single_cat_title('', false);
	} elseif (is_tag()) {
		$title = single_tag_title('', false);
	} elseif (is_author()) {
		$title = '<span class="vcard">' . get_the_author() . '</span>';
	} elseif (is_year()) {
		$title  = get_the_date(_x('Y', 'yearly archives date format'));
	} elseif (is_month()) {
		$title  = get_the_date(_x('F Y', 'monthly archives date format'));
	} elseif (is_day()) {
		$title  = get_the_date(_x('F j, Y', 'daily archives date format'));
	} elseif (is_tax()) { //for custom post types
		$title = sprintf(__('%1$s'), single_term_title('', false));
	} elseif (is_post_type_archive()) {
		$title = post_type_archive_title('', false);
	} else {
		$title = get_the_archive_title();
	}
	return $title;
}
```

**Comment by alamaxjashek** [comment]
Aug 2021, Elementor Pro Versión 3.3.5, The same problem!

**Comment by mapsmarketing** [comment]
Hilarious. 

It's September 2021 and still not fixed...

**Comment by BrockwayProd** [comment]
+1 - Will this take as long as clickable columns ?

**Comment by semmtex** [comment]
Still a problem in 3.5.0. Please fix!

**Comment by vincenzolopalo** [comment]
> My temporary solution, use a custom shortcode in the title.
> 
> ```
> /**
>  * Custom title for Archives without prefix.
>  */
> add_shortcode('cm_single_term_title', 'fn_cm_single_term_title');
> 
> function fn_cm_single_term_title()
> {
> 	if (is_category()) {
> 		$title = single_cat_title('', false);
> 	} elseif (is_tag()) {
> 		$title = single_tag_title('', false);
> 	} elseif (is_author()) {
> 		$title = '<span class="vcard">' . get_the_author() . '</span>';
> 	} elseif (is_year()) {
> 		$title  = get_the_date(_x('Y', 'yearly archives date format'));
> 	} elseif (is_month()) {
> 		$title  = get_the_date(_x('F Y', 'monthly archives date format'));
> 	} elseif (is_day()) {
> 		$title  = get_the_date(_x('F j, Y', 'daily archives date format'));
> 	} elseif (is_tax()) { //for custom post types
> 		$title = sprintf(__('%1$s'), single_term_title('', false));
> 	} elseif (is_post_type_archive()) {
> 		$title = post_type_archive_title('', false);
> 	} else {
> 		$title = get_the_archive_title();
> 	}
> 	return $title;
> }
> ```

Thanks!!! It works for me!

**Comment by Agalaxie** [comment]
Hello

Still having issues Elementor pro 3.7.2

`/**
 * Custom title for Archives without prefix.
 */
add_shortcode('cm_single_term_title', 'fn_cm_single_term_title');

function fn_cm_single_term_title()
{
	if (is_category()) {
		$title = single_cat_title('', false);
	} elseif (is_tag()) {
		$title = single_tag_title('', false);
	} elseif (is_author()) {
		$title = '<span class="vcard">' . get_the_author() . '</span>';
	} elseif (is_year()) {
		$title  = get_the_date(_x('Y', 'yearly archives date format'));
	} elseif (is_month()) {
		$title  = get_the_date(_x('F Y', 'monthly archives date format'));
	} elseif (is_day()) {
		$title  = get_the_date(_x('F j, Y', 'daily archives date format'));
	} elseif (is_tax()) { //for custom post types
		$title = sprintf(__('%1$s'), single_term_title('', false));
	} elseif (is_post_type_archive()) {
		$title = post_type_archive_title('', false);
	} else {
		$title = get_the_archive_title();
	}
	return $title;
}

I copy paste this code in function.php`and then added a new shortcode widget called [cm_single_term_title] in my search result template page but it only display the word "Archive" on the reslut page.

Maybe i missed something ?

**Comment by petermann** [comment]
> Hello
> 
> Still having issues Elementor pro 3.7.2
> 
> ```
> /**
>  * Custom title for Archives without prefix.
>  */
> add_shortcode('cm_single_term_title', 'fn_cm_single_term_title');
> 
> function fn_cm_single_term_title()
> {
> 	if (is_category()) {
> 		$title = single_cat_title('', false);
> 	} elseif (is_tag()) {
> 		$title = single_tag_title('', false);
> 	} elseif (is_author()) {
> 		$title = '<span class="vcard">' . get_the_author() . '</span>';
> 	} elseif (is_year()) {
> 		$title  = get_the_date(_x('Y', 'yearly archives date format'));
> 	} elseif (is_month()) {
> 		$title  = get_the_date(_x('F Y', 'monthly archives date format'));
> 	} elseif (is_day()) {
> 		$title  = get_the_date(_x('F j, Y', 'daily archives date format'));
> 	} elseif (is_tax()) { //for custom post types
> 		$title = sprintf(__('%1$s'), single_term_title('', false));
> 	} elseif (is_post_type_archive()) {
> 		$title = post_type_archive_title('', false);
> 	} else {
> 		$title = get_the_archive_title();
> 	}
> 	return $title;
> }
> ```
> 
> I copy paste this code in function.php`and then added a new shortcode widget called [cm_single_term_title] in my search result template page but it only display the word "Archive" on the reslut page.
> 
> Maybe i missed something ?

Hello,

This code was made for use in archives only.

**Comment by dygaomarques** [comment]
Same problem here too, this worked for me.

> Still a problem in 3.5.0. Please fix! I now use this quick fix to change/remove the text:
> 
> ```
> add_filter( 'elementor/utils/get_the_archive_title','archive_callback' );
> function archive_callback( $title ) {
>  if ( is_search() ) { 
>    return '' . get_search_query() ; 
>  } 
>    return $title; 
> }
> ```

**Comment by puregraphx** [comment]
Still a problem in 3.9.1.
Almost THREE !! years after the initial bug report.
@nicholaszein 
![image](https://user-images.githubusercontent.com/10434048/208499739-a4184cb0-0eb2-495f-adcc-1c725aff68dd.png)
![image](https://user-images.githubusercontent.com/10434048/208499804-a7d6cd6b-c76c-4f34-9446-fdca02e664a5.png)

**Comment by haidinhtran** [comment]
The issue still occurred in 3.12.2

**Comment by puregraphx** [comment]
of course it is still a bug, it's only 3 years old.

**Comment by BrockwayProd** [comment]
🎂🎂🎂

Some things deserve to be celebrated :p

**Comment by bdayelementor** [comment]
Still... not... working...

**Comment by bdayelementor** [comment]
Happy birthday Elementor Bug!

**Comment by puregraphx** [comment]
Hey, at least we now have AI to fix this bug for us :)

**Comment by rorydesign** [comment]
Still a bug.... However I have a little workaround for the search results archive.

Using the 'Heading' widget, set the dynamic tag to 'Request Parameter' (found under Site in the dropdown). Next, set the 'Type' to 'GET' and in the parameter name simple place the letter 's'.

You can build upon this by going into 'Advanced' and setting the before text to 'Results for "' (note the single quotation mark at the end), and also add a single quotation mark in the 'after' box (this wrap quotations around the search query).

The output will be:

_**Results for "keyword"**_

Hope that helps. Looks a bit simpler and neater IMO.


<img width="372" alt="Screenshot 2023-09-07 at 13 19 34" src="https://github.com/elementor/elementor/assets/75035909/9f949823-7eac-4f7b-b3ff-04ebc9ee3a98">

**Comment by ali4hk** [comment]
> Still a bug.... However I have a little workaround for the search results archive.
> 
> Using the 'Heading' widget, set the dynamic tag to 'Request Parameter' (found under Site in the dropdown). Next, set the 'Type' to 'GET' and in the parameter name simple place the letter 's'.
> 
> You can build upon this by going into 'Advanced' and setting the before text to 'Results for "' (note the single quotation mark at the end), and also add a single quotation mark in the 'after' box (this wrap quotations around the search query).
> 
> The output will be:
> 
> _**Results for "keyword"**_
> 
> Hope that helps. Looks a bit simpler and neater IMO.
> 
> <img alt="Screenshot 2023-09-07 at 13 19 34" width="372" src="https://user-images.githubusercontent.com/75035909/266313903-9f949823-7eac-4f7b-b3ff-04ebc9ee3a98.png"> <img alt="Screenshot 2023-09-07 at 13 21 20" width="371" src="https://user-images.githubusercontent.com/75035909/266314305-be6acd5b-0a6a-40ae-b52a-56df5b290205.png">

nicly creative worked

**Comment by AhmadxAli** [comment]
> Still a bug.... However I have a little workaround for the search results archive.
> 
> Using the 'Heading' widget, set the dynamic tag to 'Request Parameter' (found under Site in the dropdown). Next, set the 'Type' to 'GET' and in the parameter name simple place the letter 's'.
> 
> You can build upon this by going into 'Advanced' and setting the before text to 'Results for "' (note the single quotation mark at the end), and also add a single quotation mark in the 'after' box (this wrap quotations around the search query).
> 
> The output will be:
> 
> _**Results for "keyword"**_
> 
> Hope that helps. Looks a bit simpler and neater IMO.
> 
> <img alt="Screenshot 2023-09-07 at 13 19 34" width="372" src="https://private-user-images.githubusercontent.com/75035909/266313903-9f949823-7eac-4f7b-b3ff-04ebc9ee3a98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwODgwNzEsIm5iZiI6MTcxODA4Nzc3MSwicGF0aCI6Ii83NTAzNTkwOS8yNjYzMTM5MDMtOWY5NDk4MjMtN2VhYy00ZjdiLWIzZmYtMDRlYmM5ZWUzYTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA2MzYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3YzI1ZjVhZjRiNDNmOGM5MTJiYzhkODNjNjRiODhlYzM1ZGFhODFlZWE4N2FhNDRhZjJlZTU0OGYxNTcwMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bGZtBVrttCY6x2svh6OJFd7wRdvtZTihPmQRD7m271E"> <img alt="Screenshot 2023-09-07 at 13 21 20" width="371" src="https://private-user-images.githubusercontent.com/75035909/266314305-be6acd5b-0a6a-40ae-b52a-56df5b290205.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwODgwNzEsIm5iZiI6MTcxODA4Nzc3MSwicGF0aCI6Ii83NTAzNTkwOS8yNjYzMTQzMDUtYmU2YWNkNWItMGE2YS00MGFlLWI1MmEtNTZkZjViMjkwMjA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA2MzYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2Nzc4M2ZmYjY1NmIxOWU1ZTQyZTgwNzJmMjQ5NWNlZWYxNGMwZjhkNWFiOTQwYmJmNDU3NTE4YmY0NjUwM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kC8iyMHo8ACZfeoS_Lj5igfxf4PGHhD06_yh7HuKCJM">
thanks
