### ISSUE TITLE
Elementor seems to break swiperJS (5.3.0) breakpoint settings (swiper navigation not working)

### ISSUE THREAD

**Issue by vollyimnetz** [elementor/elementor#10525]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Elementor seems to mess with the swiperJS breakpoint settings. While all work fine when no breakpoint settings are set, the swiper is broken once the breakpoint settings are used. Elementor currently uses swiper 5.3.0 - i tried with Swiper 5.3.1 and 5.2.0 with the same results.

A very strange bug. Did Elementor use monkey patching to override some swiper code on the fly?

## Steps to reproduce
- Add an HTML-Widget on any elementor page.
- Paste the following code
- Check / Test
  - navigation (left/right arrows) are visible but not clickable
  - pagination bubbles are not in the correct number
- You may switch the breakpoint settings off by add a opening multiline-comment ("/*") in line 35. Then the swiper will work as intended - but will have no breakpoint control.
```
<div class="swiper-container test-swiper-container" style="width: 100%; height: 300px;">
    <div class="swiper-wrapper">
        <div class="swiper-slide" style="background:#f00">Slide 1</div>
        <div class="swiper-slide" style="background:#0f0">Slide 2</div>
        <div class="swiper-slide" style="background:#00f">Slide 3</div>
        <div class="swiper-slide" style="background:#a00">Slide 4</div>
        <div class="swiper-slide" style="background:#900">Slide 5</div>
        <div class="swiper-slide" style="background:#300">Slide 6</div>
        <div class="swiper-slide" style="background:#000">Slide 7</div>
        <div class="swiper-slide" style="background:#fff">Slide 8</div>
        <div class="swiper-slide" style="background:#f3f">Slide 9</div>
        <div class="swiper-slide" style="background:#f9f">Slide 10</div>
    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination"></div>
    <!-- If we need navigation buttons -->
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>
</div>

<script>

jQuery(document).ready(function($) {
    var swiper = new Swiper('.swiper-container', {
        slidesPerView: 1,
        spaceBetween: 10,
        // init: false,
        pagination: {
            el: '.swiper-pagination',
            clickable: true,
        },
        navigation: {
            nextEl: '.swiper-container .swiper-button-next',
            prevEl: '.swiper-container .swiper-button-prev',
        },
        
        breakpoints: {
            640: {
                slidesPerView: 2,
                spaceBetween: 20,
            },
            768: {
                slidesPerView: 4,
                spaceBetween: 40,
            },
            1024: {
                slidesPerView: 5,
                spaceBetween: 50,
            },
        }//*/
    });
});
</script>
```

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment
Wordpress 5.3.2
Elementor 2.9.0

**Comment by syk0ne** [comment]
Having exact the same issue. Needs to be fixed asap please!

**Comment by vollyimnetz** [comment]
With Elementor Version 2.9.1 the situation improved but is not fixed completely.
- Breakpoint-Settings are not destroy the slider initialization (**CHECK**)
- Breakpoint-Settings are still ignored - or partly ignored (**TODO**)

```
<div class="swiper-container test-swiper-container" style="width: 600px; height: 300px;">
    <div class="swiper-wrapper">
        <div class="swiper-slide" style="background:#f00">Slide 1</div>
        <div class="swiper-slide" style="background:#0f0">Slide 2</div>
        <div class="swiper-slide" style="background:#00f">Slide 3</div>
        <div class="swiper-slide" style="background:#a00">Slide 4</div>
        <div class="swiper-slide" style="background:#900">Slide 5</div>
        <div class="swiper-slide" style="background:#300">Slide 6</div>
        <div class="swiper-slide" style="background:#000">Slide 7</div>
        <div class="swiper-slide" style="background:#fff">Slide 8</div>
        <div class="swiper-slide" style="background:#f3f">Slide 9</div>
        <div class="swiper-slide" style="background:#f9f">Slide 10</div>
    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination"></div>
    <!-- If we need navigation buttons -->
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>
</div>

<script>

jQuery(document).ready(function($) {
    var swiper = new Swiper('.swiper-container', {
        slidesPerView: 3,
        spaceBetween: 10,
        // init: false,
        pagination: {
            el: '.swiper-pagination',
            clickable: true,
        },
        navigation: {
            nextEl: '.swiper-container .swiper-button-next',
            prevEl: '.swiper-container .swiper-button-prev',
        },
        
        breakpoints: {
            500: {
                slidesPerView: 1,
                spaceBetween: 20,
            },
            700: {
                slidesPerView: 2,
                spaceBetween: 40,
            },
            1400: {
                slidesPerView: 5,
                spaceBetween: 40,
            }
        }//*/
    });
});
</script>
```

For solving the first issue the following tickets are mentined in the release notes:
- https://wordpress.org/support/topic/carrousel-is-blocked-with-version-2-9/
- https://github.com/elementor/elementor/issues/10508

The ongoing issue is especialy problematic for plugin/theme authors who want to use swiperslider for an custom widget.

**Comment by xmaop** [comment]
Same issue, I downgrade version to 2.8.5 and now works fine.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9.2

Feel free to update

Thanks!

**Comment by mackyangeles** [comment]
I’m still having the same issue. I have already Elementor 2.9.2 I can’t show 1 post on carousel for mobile. It gives me a default number of post. Any fix on this?

**Comment by mackyangeles** [comment]
> This issue has been resolved in Elementor v2.9.2
> 
> Feel free to update
> 
> Thanks!

Looks like it’s bot yet fixed..

**Comment by vollyimnetz** [comment]
@shilo-ey the bug is not fixed in Elementor v2.9.2, do you even test with the code?
What's the reason elementor crushes the swiper library anyways? Swiper slider has a very solid api, which allows many totally different slideshow on the same page. Or is another component mess with the code?

If you need help or a review of the way elementor uses the swiper api, let me know. Simply paste links to the file where the swiper is used by elementor.

**Comment by vollyimnetz** [comment]
@shilo-ey please reopen the ticket.

**Comment by xmaop** [comment]
I downgrade from 2.9.2 to 2.8.5, the issue is still there

**Comment by mackyangeles** [comment]
@shilo-ey any fix?

**Comment by xmaop** [comment]
works with my first breakpoint  1024, but no with 600, I think is a conflict with responsive

**Comment by vollyimnetz** [comment]
@shilo-ey Thank you!
Ok, as far as i can see the the upcoming version will have an additional variable in all own swiper usecases. If `handleElementorBreakpoints : true, ` the override of the default swiper breakpoints by elementor kicks in. So, its an "opt in" to the elementor adjustments. Code that do not use that variable will handle the swiper slider breakpoints as in the swiper slider API.

I think that's a good way to handle the problem. **Thank you, for your work.** 

For anybody who want to check the code:
(Current status: Pull-Request -> https://github.com/elementor/elementor/pull/10642/files)

**elementor/assets/dev/js/frontend/utils/swiper.js**
Contains the elementor adjustments. Also, that's the position where you can see that 			handleElementorBreakpoints: true, is needed for the adjustments to kick in.

These are the points inside elementor that make use of the variable:
- assets/dev/js/frontend/handlers/background-slideshow.js
- assets/dev/js/frontend/handlers/image-carousel.js
- assets/dev/js/frontend/utils/lightbox/lightbox.js

**Comment by jaimyvangerrevink** [comment]
At what moment will this additional variable be published?

**Comment by vollyimnetz** [comment]
@jaimyvangerrevink there is an open pull-request from @udidol which fixes the problem.
@KingYes and @kobizz are requested to review more than 3 days ago. But did not react until now. I wrote an reminder inside the pull-request one minute ago. I hope to get this into elementor fast.

**Comment by mackyangeles** [comment]
Still no fix? Any update?

**Comment by shilo-ey** [comment]
This issue is fixed in Elementor v2.9.5 and Elementor Pro v2.8.5

Feel free to update

Thanks

**Comment by xmaop** [comment]
Please reopen, the issue is still there, my custom slider doesn't work on mobile(500).
Versión **2.9.6**
Por Versión **2.8.5** 

```
var swiper = new Swiper('.caja-swiper > .elementor-container', {
      slidesPerView: 6,
      spaceBetween: 20,
      slidesPerGroup: 1,
      loop: true,

      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
      breakpoints: {
        500: {
          slidesPerView: 2,
          spaceBetween: 5
        },
        1024: {
          slidesPerView: 4,
          spaceBetween: 5
        },
      }
    });
```

**Comment by jaimyvangerrevink** [comment]
You need 
`handleElementorBreakpoints : true `
To make this fix work.

Issue is fixed just add the code above.

**Comment by vollyimnetz** [comment]
@xmaop 
I can confirm that Elementor 2.9.6 fixes (prevent) the custom override of the swiper slider by default.

If you want to use the elementor customization you need to add `handleElementorBreakpoints : true` to the settings of the swiper call.
If you want to use the plain swiper library without the elementor breakpoint override, you do not have to add any extra code. 
Make sure you use the swiper slider parameters correctly: https://swiperjs.com/api/#parameters

**Comment by xmaop** [comment]
@vollyimnetz @jaimyvangerrevink 
Hi, Thank you for your help. Do you mean this:

```
var swiper = new Swiper('.caja-swiper > .elementor-container', {
     **handleElementorBreakpoints : true**
      slidesPerView: 6,
      spaceBetween: 20,
      slidesPerGroup: 1,
      loop: true,

      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
      breakpoints: {
        500: {
          slidesPerView: 2,
          spaceBetween: 5
        },
        1024: {
          slidesPerView: 4,
          spaceBetween: 5
        },
      }
    });
```

**Comment by udidol** [comment]
Note that `handleElementorBreakpoints` will only work if you use Elementor's own breakpoints, which you can view by editing or viewing an Elementor document, going to the developers console, and running the query `elementorFrontend.config.breakpoints`.

**Comment by xmaop** [comment]
@udidol Thanks a lot, that saved my days.
This is my code, I change 500 to 480 and now it works really good.
   ```
 var swiper = new Swiper('.caja-swiper > .elementor-container', {
      handleElementorBreakpoints: true,
      slidesPerView: 6,
      spaceBetween: 20,
      slidesPerGroup: 1,
      loop: true,

      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
      breakpoints: {
        480: {
          slidesPerView: 2,
          spaceBetween: 5
        },
        1024: {
          slidesPerView: 4,
          spaceBetween: 5
        },
      }
    });
```

**Comment by latheeshvmv** [comment]
@KingYes Why did you close that? The navigation does not work. Which developer's idea was to modify the core of the swiper files? Better don't use the swiper library then ..create your own library and use it.

**Comment by latheeshvmv** [comment]
@xmaop whether your arrow navigation is working?

**Comment by vollyimnetz** [comment]
@latheeshvmv the problem is fixed in version 2.9.6. Elementor will no longer override swiper library (elementor will only override if you add handleElementorBreakpoints: true to the settings).

If you still have a problem you should open a new bug report with a detailed explanation and testcode.

**Comment by xmaop** [comment]
@latheeshvmv yes, this is my testing site https://caja.k-globalis.com/

**Comment by latheeshvmv** [comment]
@vollyimnetz @xmaop Thank you that solves most of the issues. I had to set it false. As I have customized the arrows to a custom icon, those stopped working after this update, Have to check what's going wrong.

**Comment by xmaop** [comment]
@latheeshvmv this video helped me to build my custom slider https://youtu.be/r6aZ246cwcw

**Comment by basandrai-archita** [comment]
Elementor slider is not working on mobile. Not picking up Elementor settings. Anyone can help or facing the same issue
