### ISSUE TITLE
Review Carousel widget problem on tablet mobile

### ISSUE THREAD

**Issue by dibeja** [elementor/elementor#10540]
Hello,
Elementor 2.9.1
Elementor Pro 2.8.3

On the Review Carousel Widget when I change the Slide Count parameter for tablet and mobile nothing happens. Both on the frontend and the Elementor editor it always shows the Desktop setting.

**Comment by mlenders** [comment]
> Hello,
> Elementor 2.9.1
> Elementor Pro 2.8.3
> 
> On the Review Carousel Widget when I change the Slide Count parameter for tablet and mobile nothing happens. Both on the frontend and the Elementor editor it always shows the Desktop setting.

Same issue here. Can't adjust the number of slider per view in Media Carousel widget (tablet and mobile)

**Comment by artsmm** [comment]
The update broke related product slider in Konte theme.

**Comment by shilo-ey** [comment]
Hi @dibeja 

This issue has been resolved in Elementor v2.9.5

Feel free to update

Thanks!

**Comment by xmaop** [comment]
Please reopen, the issue is still there, my custom slider doesn't work on mobile(500).
Versión **2.9.6**
Por Versión **2.8.5** 

`
var swiper = new Swiper('.caja-swiper > .elementor-container', {
      slidesPerView: 6,
      spaceBetween: 20,
      slidesPerGroup: 1,
      loop: true,

      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
      breakpoints: {
        500: {
          slidesPerView: 2,
          spaceBetween: 5
        },
        1024: {
          slidesPerView: 4,
          spaceBetween: 5
        },
      }
    });
`
