### ISSUE TITLE
Woocommerce Add To Cart Payment Request

### ISSUE THREAD

**Issue by jimyaghi** [elementor/elementor#10617]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

On front-end, the "Woocommerce Add to Cart" widget displays incorrectly with odd alignment and does not show the Payment Request button when it should be showing. The DIV which contains the Payment Request button has a zero width.

![add to cart](https://user-images.githubusercontent.com/15869425/74936635-c9b8b700-53ea-11ea-94af-11ab04850f2b.png)

Note the "--OR--" part which only makes sense if the payment request button appears before it. Alternatively, the --OR-- part should be hidden along with the Payment Request button. Additionally, i think the vertical alignment of the quantity field should be in line with the button as is shown in the elementor editor.

## Steps to reproduce

1. In Theme Builder, create a Single Product Page template
2. Insert the Woocommerce Add To Cart widget on the page without altering any of its settings.
3. Save
4. Load a single product page on the front-end

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

This bug cannot be reproduced without Woocommerce plugin also active.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.29 (Ubuntu)
	MySQL version: (Google) v5.7.25
	PHP Version: 7.3.14-6+ubuntu18.04.1+deb.sury.org+1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.2
	WP Multisite: Yes
	Max Upload Size: 49 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.2.2
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.100 Safari/537.36

== Active Plugins ==
	Admin Menu Editor
		Version: 1.9.3
		Author: Janis Elsts

	bbPress
		Version: 2.6.4
		Author: The bbPress Contributors

	BBPress Course Forums for Sensei
		Version: 2.5.14
		Author: YaghiLabs

	CMS Tree Page View
		Version: 1.6
		Author: Pär Thernström

	Disable Comments
		Version: 1.10.2
		Author: Samir Shah

	Elementor
		Version: 2.9.2
		Author: Elementor.com

	Elementor Pro
		Version: 2.8.4
		Author: Elementor.com

	Happy Elementor Addons
		Version: 2.6.1
		Author: weDevs

	Happy Elementor Addons Pro
		Version: 1.4.0
		Author: weDevs

	Inline JS block for Gutenberg
		Version: 1.0.0
		Author: WPBrigade

	Jetpack by WordPress.com
		Version: 8.2.1
		Author: Automattic

	Mailster - Email Newsletter Plugin for WordPress
		Version: 2.4.8
		Author: EverPress

	Meta Box
		Version: 5.2.7
		Author: MetaBox.io

	Miscellaneous Tweaks for YaghiLabs Learning Center
		Version: 2.5.14
		Author: YaghiLabs

	Orbit Fox Companion
		Version: 2.9.2
		Author: Themeisle

	Sensei Lesson Attachments Add-On
		Version: 2.5.14
		Author: YaghiLabs

	Sensei LMS
		Version: 2.4.0
		Author: Automattic

	Sensei WooCommerce Paid Courses
		Version: 1.2.4
		Author: Automattic

	SES Postfix Delivery Add-On for Mailster
		Version: 2.5.14
		Author: YaghiLabs

	WooCommerce
		Version: 3.9.2
		Author: Automattic

	WooCommerce Admin
		Version: 0.25.1
		Author: WooCommerce

	WooCommerce Cart Abandonment Recovery
		Version: 1.2.4
		Author: CartFlows Inc

	Woocommerce Interest Segments Add-On for Mailster
		Version: 2.5.14
		Author: YaghiLabs

	WooCommerce Stripe Gateway
		Version: 4.3.2
		Author: WooCommerce

	WooCommerce Subscriptions
		Version: 3.0.1
		Author: WooCommerce


== Network Plugins ==
	Jetpack by WordPress.com
		Version: 8.2.1
		Author: Automattic


== Elements Usage ==
	
	archive : 1
		archive-posts : 1
	bbpress : 1
		theme-post-content : 1
		theme-post-title : 1
	footer : 1
		heading : 1
		nav-menu : 1
	header : 1
		button : 2
		image : 1
		nav-menu : 1
		search-form : 2
		theme-site-logo : 1
		woocommerce-menu-cart : 1
	page : 6
		heading : 1
	popup : 4
		form : 4
		heading : 7
		text-editor : 3
	product : 2
		woocommerce-breadcrumb : 1
		woocommerce-product-add-to-cart : 2
		woocommerce-product-content : 1
		woocommerce-product-images : 1
		woocommerce-product-price : 2
		woocommerce-product-rating : 1
		woocommerce-product-related : 1
		woocommerce-product-short-description : 1
		woocommerce-product-title : 1
	section : 1
		button : 1
		price-table : 1
		text-editor : 1
	single : 6
		author-box : 1
		heading : 2
		lesson-attachments : 1
		post-info : 3
		post-navigation : 3
		posts : 1
		theme-post-content : 4
		theme-post-excerpt : 2
		theme-post-featured-image : 2
		theme-post-title : 5
		video : 1
		wp-widget-interests_subscribe : 1
	wp-post : 1
		text-editor : 6
	wp-page : 20
		alert : 1
		button : 11
		call-to-action : 1
		ha-testimonial-carousel : 1
		heading : 19
		html : 11
		icon : 6
		image : 2
		image-box : 1
		nav-menu : 1
		posts : 1
		price-table : 8
		social-icons : 1
		text-editor : 25
		wc-elements : 2


== Log ==
	
```
		
</details>

**Comment by harzkinddev** [comment]
I have the same Problem. Elementor is not correctly displaying the payment request button the "Stripe" plugin adds for Apple Pay, Google Pay, etc.

When correctly displayed it should look something like this:
![Screenshot 23-5-2020 00-16-04](https://user-images.githubusercontent.com/24677815/82713251-9e17c800-9c8a-11ea-83d1-b2301fa9058f.png)

Elementor somehow screws this up. It would be really great if this could get fixed.

**Comment by ftc-toliver2786** [comment]
How is this STILL a problem after MONTHS? 

It's like they want to force their users to convert less sales by removing the button all together

**Comment by giladrom** [comment]
Has this been resolved? I'm having the same issue and have been unable to fix it so far.

**Comment by gonarg90** [comment]
This is still not working guys. It's a horrible bug.

**Comment by pasog** [comment]
same problem @jimyaghi commented on 20 Feb 2020 
listed by
only we have this problem? !!

**Comment by robertableson** [comment]
This has been ongoing for a while and is still an issue. To anyone experiencing this and not finding any solution, here is a workaround.

1. Make the .woocommerce-variation-add-to-cart element display as block and not flex.
2. Make quantity field and parent div take 100% width.
3. Add top margin to Add To Cart button.
4. (Optional) Make Add To Cart button bigger.
5. Adjust styling according to your website's style.

Full code to fix the issue visually:

```
.woocommerce-variation-add-to-cart{
    display: block !important;
}
div.quantity, div.quantity input.qty{
    min-width: 100%;
}
button.single_add_to_cart_button{
    margin-top: 10px !important;
    min-width: 100%;
    padding: 20px !important;
}
```

Hope it helps someone.

**Comment by cds-71** [comment]
This is STILL an issue. I submitted a support ticket, but judging from this thread, I'm not optimistic that there will be a fix. I tried @robertableson 's CSS, but unfortunately it did not fix the issue in my template. Crazy this is still an unanswered/unfixed issue for over a year. I recently purchased Oxygen, so maybe I'll try a rebuild with that and see if the results are any different.

**Comment by cds-71** [comment]
If no suggestions above work for anyone... try this CSS: 
`.woocommerce div.product.elementor form.cart.variations_form .woocommerce-variation-add-to-cart, .woocommerce div.product.elementor form.cart:not(.grouped_form):not(.variations_form) {flex-direction: column} or: .woocommerce div.product.elementor form.cart.variations_form .woocommerce-variation-add-to-cart, .woocommerce div.product.elementor form.cart:not(.grouped_form):not(.variations_form)
{display:block;}`

It seems to have fixed the issue for me. I hope it helps you, too!

**Comment by gonarg90** [comment]
Hi Christ,

Just a quick question. Where do you add the code? 

Under appearance > Customize > Custom CCS?
or 
Directly in the page?

**Comment by cds-71** [comment]
> Hi @cds-71
> 
> Just a quick question. Where do you add the code?
> 
> Under appearance > Customize > Custom CCS?
> or
> Directly in the page?

@gonarg90 Add the code to the Custom CSS area (appearance > Customize > Custom CCS). That should do the trick!

**Comment by gonarg90** [comment]
Hi @cds-71

Thank you. I've one last question, I promise.

I work amazingly in Desktop view, but I don't see the request buttons in mobile.

Does it work for you on mobile as well?

**Comment by cds-71** [comment]
> Hi @cds-71
> 
> Thank you. I've one last question, I promise.
> 
> It worked amazingly in Desktop view, but I don't see the request buttons in mobile.
> 
> Does it work for you on mobile as well?

@gonarg90 haha no worries! For me, I do see the buttons on mobile. I'm using Elementor's Hello theme if that makes any difference.

**Comment by gonarg90** [comment]
Weird... we are using Hello as well. Could you share a link of the site?

**Comment by cds-71** [comment]
@gonarg90 Sure thing. https://biowellnessx.com/product/10mg-organic-delta-8-gummies-2/ 

You may need to reach out to Elementor for extra help. I found their chat help to be the most efficient (support tickets often go unanswered). They actually helped me with this code within a couple minutes. Go to https://my.elementor.com/support/ and click that little icon in the bottom right corner of the screen.

**Comment by pdfrequest3** [comment]
I am also having the same Issue! 
![apeemcmomjaknnmh](https://user-images.githubusercontent.com/72587161/125801585-166329fe-3d97-486e-9757-5323becba35c.png)

**Comment by pdfrequest3** [comment]
> If no suggestions above work for anyone... try this CSS:
> `.woocommerce div.product.elementor form.cart.variations_form .woocommerce-variation-add-to-cart, .woocommerce div.product.elementor form.cart:not(.grouped_form):not(.variations_form) {flex-direction: column} or: .woocommerce div.product.elementor form.cart.variations_form .woocommerce-variation-add-to-cart, .woocommerce div.product.elementor form.cart:not(.grouped_form):not(.variations_form) {display:block;}`
> 
> It seems to have fixed the issue for me. I hope it helps you, too!

@cds-71, can I apply this css only on mobile devices? 'Coz in desktop, the add to cart button is really stretched below and no longer beside the quantity selector.

**Comment by d19dotca** [comment]
I started experiencing this issue too. Hopefully Elementor fixes this, pretty big deal to not have the ability to add Apple Pay to the single product add-to-cart process.

**Comment by azkalex** [comment]
Soon to be 2 years since this was started, how is this normal?

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor Pro v3.6.6

Feel free to update

Thanks!

**Comment by steblood** [comment]
This has still not been fixed, unfortunately... @avivu
![gpay](https://user-images.githubusercontent.com/107085449/172505891-4842f561-b79c-4529-baf2-fc0bb8a397d3.png)

Elementor is on version 3.6.5
Elementor Pro is on version 3.7.1

It would be a huge help if I could possibly get some assistance.

**Comment by EdwardOak** [comment]
After 2 years with zero signs of incoming support. 

I THINK IT IS SAFE TO SAY TO ANYONE READING THIS:

**THIS ISSUE WILL NEVER BE RESOLVED. FIND A SOLUTION SOMEWHERE ELSE.**

THIS ISSUE HAS BEEN KNOWN AND UNFIXED FOR YEARS.

**Comment by EdwardOak** [comment]
> Hello, This issue has been resolved in Elementor Pro v3.6.0
> 
> Feel free to update
> 
> Thanks!

No. It has not.

**Comment by EdwardOak** [comment]
> @pasog @gonarg90 @giladrom @ftc-toliver2786 @harzkinddev @jimyaghi
> 
> This has been ongoing for a while and is still an issue. To anyone experiencing this and not finding any solution, here is a workaround.
> 
> 1. Make the .woocommerce-variation-add-to-cart element display as block and not flex.
> 2. Make quantity field and parent div take 100% width.
> 3. Add top margin to Add To Cart button.
> 4. (Optional) Make Add To Cart button bigger.
> 5. Adjust styling according to your website's style.
> 
> Full code to fix the issue visually:
> 
> ```
> .woocommerce-variation-add-to-cart{
>     display: block !important;
> }
> div.quantity, div.quantity input.qty{
>     min-width: 100%;
> }
> button.single_add_to_cart_button{
>     margin-top: 10px !important;
>     min-width: 100%;
>     padding: 20px !important;
> }
> ```
> 
> You may also want to add this to a media query for mobile.
> 
> Should look something like this after:
> 
> <img alt="pay" width="147" src="https://user-images.githubusercontent.com/23560139/112706822-38cdce00-8e7d-11eb-939e-21670fe15acd.PNG">
> 
> Hope it helps someone.

Doesn't work.
