### ISSUE TITLE
Elementor Pro v2.9 Beta 3 (RC) Release 📣

### ISSUE THREAD

**Issue by shilo-ey** [elementor/elementor#10718]
===========

# [Beta 3 UPDATED - PLEASE READ BELOW!](https://github.com/elementor/elementor/issues/10718#issuecomment-599227211)

===========

Hi Elementor beta testers,

We׳re getting ready to release Elementor Pro v2.9, with a groundbreaking **Full Site Editing** feature.

We would like to ask you to help us test Elementor Pro v2.9 Beta, with 4 new features:

- Full Site Editing
- Global Custom CSS
- Dynamic Colors
- Site Parts HTML Wrapper Tags

**Before you test, please make sure you are using:**
- Elementor v2.9.3
- Elementor Pro v2.9.0 beta1

## Introducing Full Site Editing: Design header, footer, and content all in one place! (#4985)

![editing](https://user-images.githubusercontent.com/45009641/75629887-bf6a9a00-5bee-11ea-8998-1e8c7f5314ef.gif)

Even in 2020, editing a site is still divided and all over the place.
You edit the header, back to the dashboard screen, then the content page, then the header again, switch over to the footer. Sheesh!

**Introducing Full Site Editing, design your entire site, all from one place.**

As a designer, you can now enjoy a seamless experience of designing the entire page, header to footer included, all from one screen. It will save you time, effort, and a lot of redundant clicks. 

When designers work, they often need to get into the flow, after having their creative juices flowing. In this upcoming version we offer a unified experience in one place, without any interruptions to your workflow mid way to switch to another screen and allowing you to design the site top to bottom. At the same time, we maintained the distinction between the different site parts: header, single, content and footer, so you know exactly what you are editing at each point of the design process.

After you start using the new Full Site Editing feature, you’ll be able to quickly switch between the different site parts. It’s a huge UX improvement, and we hope it will do wonders for your workflow.

**How It Works**
While editing a page, hover over the area you wish to change and click on the orange handle to edit that site part (header, single post, single page, footer, etc...).

Done editing a certain area? Save your changes and continue to the next one.

**Test Flow:**

1. Create a header using Elementor and import one from the Template Library
2. Publish and set conditions to Entire Site
3. Create a footer using Elementor and import one from the Template Library
4. Publish and set conditions to Entire Site
5. Create a Single Post using Elementor and import your desired layout from the Template Library
6. Publish and set conditions to All Posts
7. Create a new post and drag in some widgets
8. Hover over the header and click “Edit Header”
9. Make changes to that header
10. Do the same for the Single Post part and for the Footer part
11. Make sure everything works as expected on Frontend and in Preview mode

## Meet Custom CSS Rules for Your Entire Site (#3345)

![global custom css](https://user-images.githubusercontent.com/45009641/75629913-f2ad2900-5bee-11ea-92d3-2606238fc141.gif)

Speaking of full site editing, here’s another related time-saver feature that will give you extra flexibility.

One of our most requested features we get is the ability to set Custom CSS globally. With Elementor Pro v2.9, you can add custom CSS rules which will apply to your entire site.

Simply enter the Theme Style menu and open the Custom CSS section. Simple as that!

**Test Flow:**

1. Create a new page using Elementor
2. Drag in a heading widget
3. Go to Advanced tab and fill in `roses-headings` in CSS Class and `violet-heading` in CSS ID fields
4. Click Publish
5. Enter Theme Style menu and go to Custom CSS section
6. Fill in `.elementor .roses-headings h2 { color: red; }` and `#violet-heading { background: blue; }` to the code field
7. Make sure your preview updates according to the specified colors (blue background and red text color)
8. Make sure everything works as expected on Frontend

 
## New Dynamic Tag Support: Dynamic Colors (#6485)
![dynamic color](https://user-images.githubusercontent.com/45009641/75629964-749d5200-5bef-11ea-8328-cecf48b61d24.png)

The third addition to version 2.9 pro also relates to a global design feature - dynamic content. 
If you recall, with Dynamic Content, you can create advanced websites like directories and catalogs without coding. This is done by taking content from custom fields and other sources, and dynamically displaying it on the page.  

Until now, dynamic tags were restricted to textual and numeric inputs. With the new ‘Dynamic Color’ option, you can embed dynamic color values in any widget that has a color field. The new Color Dynamic control supports ACF color fields as well as Custom field keys.

Want to create an Ecommerce site where the product pages change color according to which product page is viewed? With this feature, you can!

**Test flow:**
1. Drag a Heading widget to your page
2. Next to each Color field there is a Dynamic Tag control, click on it and select your preferred source of dynamic color
3. Do the same flow other widgets
4. Make sure everything works as expected on Frontend

## Wrapper HTML Tags - Set `<header>`, `<footer>`, `<aside>`, `<main>` or `<article>` wrapper tags to Your Site Parts (#9293)
Until today, when creating a header, footer or a regular page template using Theme Builder, you could only set HTML tags per section. Because most content you create with Elementor consists of several sections, it made it difficult to assign one HTML tag across a whole area.

From now on, you can set HTML tags per theme part. Assign your entire header with `<header>` tag, your entire content area with `<main>` tag and your footer with `<footer>` tag.

By assigning a relevant HTML tag for each theme element, you improve accessibility and HTML semantics and improve your on-page SEO. 

**Test Flow:**

1. Create a header using Elementor and import one from the Template Library
2. Click on the settings cog icon and select your desired HTML tag 
3. Publish and set conditions to Entire Site
4. Create a footer using Elementor and import one from the Template Library
5. Click on the page settings cog icon and select your desired HTML tag 
6. Publish and set conditions to Entire Site
7. Create a Single Post using Elementor and import your desired layout from the Template Library
8. Click on the page settings cog icon and select your desired HTML tag 
9. Publish and set conditions to All Posts
10. Go to frontend post page and make sure the selected tags are displayed correctly using your browser inspection tool
-------------

# More Improvements

- Tweak: Added Link Attributes support to Pro widgets (#5716, #3642, #9225, #9079)
- Tweak: Added Theme Style support in Theme Builder parts (#10564)
- Tweak: Avoid creating empty Custom Font
- Tweak: Added `aria-expanded` attribute to Menu Cart widget
- Tweak: Moved Link Actions module to Core plugin
- Tweak: Changed the name of “TypeKit Web Fonts by Adobe” to “Adobe Fonts”
- Tweak: Added inline editing capability to title and description to Price List widget
- Tweak: Removed redundant display conditions from Blockquote, Flipbox, Price Table, and Search Form widgets
- Tweak: Pro widgets are not draggable unless Elementor license has been activated
- Tweak: Remove redundant `label_block` parameters from several controls
- Tweak: Converted controls selectors to CSS variables in Gallery widget
- Tweak: Replaced Stumbleupon with Mix in Reviews widget recommended icons (#10099)
- Tweak: Added Mix to the Share Buttons network list (#10099)
- Tweak: Added "Open in new tab" option to Posts widget
- Tweak: Upgraded Font Awesome Pro library to v5.12.0
- Tweak: Added new Lightbox compatibility for Gallery and Media Carousel widgets
- Tweak: Expose external API for Swiper instances
- Tweak: Added compatibility to JS API in Theme Builder, Popups, Form widget and Global widget
- Tweak: Replaced nerd icons with new Elementor emojis
- Tweak: Added specific `color` attribute to header title in Table of Contents widget
- Fix: Line break issues in Animated Headline widget (#10585)
- Fix: Share button widgets show Font Awesome 4 icons on first drag in Editor
- Fix: Image ratio parameter visible in some edge cases in Posts widget
- Fix: Image missing when sharing to Pinterest using Share Buttons widget
- Fix: Theme Style Link color setting override the list style in Table of Content widget
- Deprecated: See all deprecations to this version in our [Developers Deprecations Post](https://developers.elementor.com/v2-9-0-planned-deprecations/) 

------

## How to Install the Beta Version
If you still haven't enabled beta testing in Elementor, please follow these steps:

1. Go to Elementor > Tools > Versions
2. Enable the beta tester feature
3. Go to Dashboard > Updates and update to the latest beta version.

This will get you set up to test the new Elementor Pro 2.9 Beta.

## Notes
For bugs and remarks, please reply with a comment on the specific issue here on GitHub.
**Please keep this related to the Current beta Only! Any other issue or feature request, feel free to open a new issue.**

Designated time for release: `March 17, 2020` (Estimated)
 
Many thanks for your support and help!
 
_The Elementor Team_

**Comment by rodolphebertozzo** [comment]
Very good job !
When I am on a page (not in editor mode), move the mouse over Edit with Elementor and click on Header or Footer, the header/footer edition opens but not on the page in question.

**Comment by michaelwright74** [comment]
Is there an alternative way to get the beta files?

I'm using Local Lightning by Flywheel as my dev environment and it always fails to install Elementor Pro updates (regular updates, not just the beta ones).

**Comment by mohammadr3z** [comment]
Problem with handle button in RTL language
![Screenshot_3](https://user-images.githubusercontent.com/7595716/75634137-248ab380-5c20-11ea-8948-cc1765941a2a.png)

**Comment by jazir5** [comment]
@rodolphebertozzo 

> Very good job !
> When I am on a page (not in editor mode), move the mouse over Edit with Elementor and click on Header or Footer, the header/footer edition opens but not on the page in question.

The expected behavior should be opening the page to edit and having the header or footer section selected by default as the editing area when those links are clicked via the admin toolbar links from the frontend correct? Basically it should jump to the header or footer sections in the editor as shown in the screenshot posted by @shilo-ey above, but you can switch back to editing the main page contents. 

If it currently is doing the behavior you posted above @rodolphebertozzo then i completely agree it needs to be fixed, the new features behavior/access should be consistent. Trying to edit the header or footer from the front end should jump straight to editing those templates when the link to edit them is clicked within the admin toolbar while still being able to edit the main page contents of the page that the link was clicked on as well.

i.e. If i try to edit the header on the homepage, i should immediately be taken to the editor for the header, but i can the click the edit button for the main page contents as in the screenshot above to immediately return to editing the main page contents, rather than have to return to the page via another method. Otherwise we still retain the disjointed editing experience that this feature intends to solve.

**Comment by mickviller** [comment]
Categories Dynamic Colour Support

Support dynamic colours assigned to Categories via ACF, i have tested it and it won't pull the colours.

**Use case:**

- Dynamic Badge on the post archive widget or post widget changes colour depending on what category is being displayed. can be for other ideas but this is a starting point.

**Steps Took:**

- Create two colour boxes - Background and Text in ACF, assigned to taxonomy, added colours to three test categories.

**Tested on:**

- Used the post widget on a page and tried to dynamically change the badge colours and it won't pull colours from the custom fields.

- Used the archive post widget on a post template and tried to dynamically change the badge colours and it won't pull colours from the custom fields.

- Also created a colour field assigned to post and pages and it also was not pulled in.

<img width="719" alt="Screenshot_2020_03_02_17_00_19" src="https://user-images.githubusercontent.com/55477537/75652657-598e1900-5ca7-11ea-8da3-83c9aef72aee.png">

**Comment by Psmeg** [comment]
When assigning a dynamic colour inside the Theme Style panel, the dynamic values (taken from an ACF Options meta field) is not changing the color or saving inside the Theme Styles panel in the Key field of the chosen colour.

This is ONLY evident in the Theme Style panel and not in the settings for widgets.

To recreate:

- Install ACF Pro and set up an options meta field group.
- Add a field for color picker
- Insert a value or set a fallback value
- Open up a page in the Elementor Pro editor
- Open the Theme Styles panel and choose any dynamic color tag
- Set the data type to ACF Color Picker
- Save

- Refresh the page and reload the Elementor editor
- Go into the Theme Styles option
- Open the previously set Dynamic Tag field for the colour
- Expand to shop the Key and it is empty.

This is tested inside the latest version of Chrome browser

**Comment by Tvhawk** [comment]
Header edit handle is not showing up: https://hawks.media/GGuNr866

**Comment by haemeulrich** [comment]
**Full Site Editing**
For me the UX is little confusing. For example:

1. Create a new post (with Elementor)
2. Fill in some Content
3. Edit the Single Post Template

How to go back to the post which I created in #1? How can a user see when he is in the template and when he is in the post/page… itself?

**Comment by Jorihlen** [comment]
I receive an error when I try to update to the Beta version. I am testing in a local environment.
I uninstalled and reinstalled Elmtr Pro and the problem persists.

"An error occurred while updating Elementor Pro: Could not create directory. elementor-pro/modules/animated-headline/assets"

**Comment by michaelwright74** [comment]
> I receive an error when I try to update to the Beta version. I am testing in a local environment.
> I uninstalled and reinstalled Elmtr Pro and the problem persists.
> 
> "An error occurred while updating Elementor Pro: Could not create directory. elementor-pro/modules/animated-headline/assets"

If you're using Local by Flywheel this is a known issue.

**Comment by SniffleValve** [comment]
"Tweak: Pro widgets are not draggable unless Elementor license has been activated"

Tried my darnedest to find where this "tweak" has been requested ;)

**Comment by yasien-s** [comment]
CSS rules.  I had to tweak the instruction to get it working.  .elementor .roses-headings h1 { color: red; } #h1-violet-heading { background:  pink; }

If not, it applied background color to all h tags

Otherwise, I am enjoying this experience.

**Comment by steponme82** [comment]
Upper handle not working. Cannot get out of footer edit mode unless refreshing page

**Comment by veniko** [comment]
What exactly is the difference between the Theme Styles Global CSS option and the default WP core Additional CSS option  in the  Customizer.  They look the same to me.

**Comment by markhaven-music** [comment]
Updated Elementor and Elementor Pro and it broke the website.

These are the errors.

Warning: require(/home/soundm18/public_html/wp-content/plugins/elementor-pro/includes/modules-manager.php): failed to open stream: No such file or directory in /home/soundm18/public_html/wp-content/plugins/elementor-pro/plugin.php on line 94

Fatal error: require(): Failed opening required '/home/soundm18/public_html/wp-content/plugins/elementor-pro/includes/modules-manager.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/soundm18/public_html/wp-content/plugins/elementor-pro/plugin.php on line 94
There has been a critical error on your website. Please check your site admin email inbox for instructions.

Website: https://soundmasters.org

**Comment by godvsgodvs** [comment]
markhaven-music, On your actual site an error refers to the Zoa theme. Have you tried changing themes?

**Comment by kristiangl** [comment]
Any reason why there is no **Pods** support for dynamic colour fields?

**Comment by rodolphebertozzo** [comment]
In the page settings, I can't put an html tag, so I can't put the <main> tag for my page

**Comment by shilo-ey** [comment]
[**@rodolphebertozzo**](https://github.com/rodolphebertozzo) commented on [Mar 1, 2020, 7:41 PM GMT+2](https://github.com/elementor/elementor/issues/10718#issuecomment-593123696 "2020-03-01T17:41:34Z - Replied by Github Reply Comments"):
> Very good job !
> When I am on a page (not in editor mode), move the mouse over Edit with Elementor and click on Header or Footer, the header/footer edition opens but not on the page in question.

You can still access the specific site part (header/single/footer) as a separate part of your site. that's being said, you can now access them from any page. currently we won't block this option.


[**@mohammadr3z**](https://github.com/mohammadr3z) commented on [Mar 1, 2020, 11:22 PM GMT+2](https://github.com/elementor/elementor/issues/10718#issuecomment-593147391 "2020-03-01T21:22:55Z - Replied by Github Reply Comments"):
> Problem with handle button in RTL language
> ![Screenshot_3](https://user-images.githubusercontent.com/7595716/75634137-248ab380-5c20-11ea-8948-cc1765941a2a.png)

Thanks


[**@mickviller**](https://github.com/mickviller) commented on [Mar 2, 2020, 9:02 AM GMT+2](https://github.com/elementor/elementor/issues/10718#issuecomment-593251248 "2020-03-02T07:02:06Z - Replied by Github Reply Comments"):
> Categories Dynamic Colour Support
> 
> Support dynamic colours assigned to Categories via ACF, i have tested it and it won't pull the colours.
> 
> **Use case:**
> 
> - Dynamic Badge on the post archive widget or post widget changes colour depending on what category is being displayed. can be for other ideas but this is a starting point.
> 
> **Steps Took:**
> 
> - Create two colour boxes - Background and Text in ACF, assigned to taxonomy, added colours to three test categories.
> 
> **Tested on:**
> 
> - Used the post widget on a page and tried to dynamically change the badge colours and it won't pull colours from the custom fields.
> 
> - Used the archive post widget on a post template and tried to dynamically change the badge colours and it won't pull colours from the custom fields on the main archive page but will show colours on individual archive pages.
> 
> - Also created a colour field assigned to post and pages and it also was not pulled in.

Thanks, the current scope of this feature is basic dynamic capabilities, although we are working on an option to set the Post colors from the Category it's associated to, but I can't assure it will be included in this release.

 


[**@Psmeg**](https://github.com/Psmeg) commented on [Mar 2, 2020, 3:35 PM GMT+2](https://github.com/elementor/elementor/issues/10718#issuecomment-593404810 "2020-03-02T13:35:15Z - Replied by Github Reply Comments"):
> When assigning a dynamic colour inside the Theme Style panel, the dynamic values (taken from an ACF Options meta field) is not changing the color or saving inside the Theme Styles panel in the Key field of the chosen colour.
> 
> This is ONLY evident in the Theme Style panel and not in the settings for widgets.
> 
> To recreate:
> 
> - Install ACF Pro and set up an options meta field group.
> - Add a field for color picker
> - Insert a value or set a fallback value
> - Open up a page in the Elementor Pro editor
> - Open the Theme Styles panel and choose any dynamic color tag
> - Set the data type to ACF Color Picker
> - Save
> 
> - Refresh the page and reload the Elementor editor
> - Go into the Theme Styles option
> - Open the previously set Dynamic Tag field for the colour
> - Expand to shop the Key and it is empty.
> 
> This is tested inside the latest version of Chrome browser

Dynamic colors won't be supported in Theme Style and maybe will be added in the future.



[**@Tvhawk**](https://github.com/Tvhawk) commented on [Mar 3, 2020, 3:14 AM GMT+2](https://github.com/elementor/elementor/issues/10718#issuecomment-593715110 "2020-03-03T01:14:07Z - Replied by Github Reply Comments"):
> Header edit handle is not showing up: https://hawks.media/GGuNr866

[**@steponme82**](https://github.com/steponme82) commented on [Mar 4, 2020, 11:08 AM GMT+2](https://github.com/elementor/elementor/issues/10718#issuecomment-594405122 "2020-03-04T09:08:13Z - Replied by Github Reply Comments"):
> Upper handle not working. Cannot get out of footer edit mode unless refreshing page

Thanks. Try updating to Core v2.9.4 and let us know if that solved the issue for you.


[**@haemeulrich**](https://github.com/haemeulrich) commented on [Mar 3, 2020, 7:00 PM GMT+2](https://github.com/elementor/elementor/issues/10718#issuecomment-594057096 "2020-03-03T17:00:32Z - Replied by Github Reply Comments"):
> **Full Site Editing**
> For me the UX is little confusing for Single Post Template:
> 
> 1. Create a new post (with Elementor)
> 2. Fill in some Content
> 3. Edit the Single Post Template
> 
> How to go back to the post which I created in #1? How can a user see when he is in the template and when he is in the post/page… itself? It would be great to have an obvious info to see that you are in the template.

It's a bug we are working on resolving, you should be able to access the Post's content from the Header and Footer, not from the Single template.


[**@Jorihlen**](https://github.com/Jorihlen) commented on [Mar 4, 2020, 1:12 AM GMT+2](https://github.com/elementor/elementor/issues/10718#issuecomment-594219477 "2020-03-03T23:12:15Z - Replied by Github Reply Comments"):
> I receive an error when I try to update to the Beta version. I am testing in a local environment.
> I uninstalled and reinstalled Elmtr Pro and the problem persists.
> 
> "An error occurred while updating Elementor Pro: Could not create directory. elementor-pro/modules/animated-headline/assets"

Please make sure you have sufficient write privileges in your server user. If the issue persists, try changing the folder's write privileges. (thanks @michaelwright74)


[**@Veniko**](https://github.com/veniko) commented on [Mar 4, 2020, 12:38 PM GMT+2](https://github.com/elementor/elementor/issues/10718#issuecomment-594445852 "2020-03-04T10:38:15Z - Replied by Github Reply Comments"):
> What exactly is the difference between the Theme Styles Global CSS option and the default WP core Additional CSS option  in the  Customizer.  They look the same to me.

Elementor will add the Global CSS to every page Elementor is loaded on. besides it, much better workflow when editing your site.



[**@kristiangl**](https://github.com/kristiangl) commented on [Mar 5, 2020, 2:48 AM GMT+2](https://github.com/elementor/elementor/issues/10718#issuecomment-594968978 "2020-03-05T00:48:01Z - Replied by Github Reply Comments"):
> Any reason why there is no **Pods** support for dynamic colour fields?

Currently, we haven't added Pods support, but it will be added in later versions.


[**@rodolphebertozzo**](https://github.com/rodolphebertozzo) commented on [Mar 5, 2020, 10:07 AM GMT+2](https://github.com/elementor/elementor/issues/10718#issuecomment-595085446 "2020-03-05T08:07:53Z - Replied by Github Reply Comments"):
> In the page settings, I can't put an html tag, so I can't put the <main> tag for my page or are the tags just valid for models?

You can add HTML tags for Header, Footer, Archive, Single, Product, Products Archive and Popup documents.

Thanks.

====
Please try to update to Elementor Core v2.9.4 which addresses some of the issues raised and let us know what do you think.
====

**Please keep this related to the Current beta Only! any other [Issue Report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md) or [Feature Request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md) feel free to open a new issue.**

Thanks again to everyone for your great feedback.

**Comment by michaelwright74** [comment]
> [**@Jorihlen**](https://github.com/Jorihlen) commented on [Mar 4, 2020, 1:12 AM GMT+2](https://github.com/elementor/elementor/issues/10718#issuecomment-594219477):
> 
> > I receive an error when I try to update to the Beta version. I am testing in a local environment.
> > I uninstalled and reinstalled Elmtr Pro and the problem persists.
> > "An error occurred while updating Elementor Pro: Could not create directory. elementor-pro/modules/animated-headline/assets"
> 
> Please make sure you have sufficient write privileges in your server user. If the issue persists, try changing the folder's write privileges. (thanks @michaelwright74)
> 

@shilo-ey It's absolutely a Local by Flywheel issue as I also experience it with Elementor Extras and ThePlus Addons for Elementor as well as Elementor Pro, other plugins install fine.

I have a support thread here about the issue...
https://localwp.com/community/t/plugin-update-error-with-lightning-on-windows/16491/10

I was able to install the Beta by trying to do the update through the WP updates page and copying the URL given with the error message and pasting it in a new browser window which downloaded the install zip to my local machine and then doing a manual update.

**Comment by godvsgodvs** [comment]
The problem mentioned before where you can't see or clicking won't work on the Edit Header is caused by the following as near as I can tell:
Header section is set to Sticky Top.
This sets that section to z-index 99.
The z-index of the elementor-document-handle is 11 and therefore underneath the sticky section.
Depending on background, you either won't see the handle or clicking won't do anything.

If I go into developer tools Inspect and set the z-index to 999, the problem is solved.

**Comment by mnease** [comment]
### When editing a global button:

- The button becomes uneditable and reverts to default settings while in the editor. 
<img width="1207" alt="Screen Shot 2020-03-05 at 11 17 53 AM" src="https://user-images.githubusercontent.com/12618230/76007680-0a78fb80-5ed4-11ea-971b-5fd4e6d64da3.png">
<img width="316" alt="Screen Shot 2020-03-05 at 11 18 02 AM" src="https://user-images.githubusercontent.com/12618230/76007723-1d8bcb80-5ed4-11ea-94aa-d1363d667b8b.png">


- If a new instance of the same global editor is dragged back in, it works correctly. 

- The same global button displays correctly on the front end, so this is only occurring while editing.

<img width="1173" alt="Screen Shot 2020-03-05 at 11 19 30 AM" src="https://user-images.githubusercontent.com/12618230/76007758-2c727e00-5ed4-11ea-86a9-4a47a8460f0d.png">


**PHP:** 7.3.15
**Theme:** Hello Elementor 2.2.2
**User Agent:**  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36

**Comment by mbenady** [comment]
> 
> 
> **Full Site Editing**
> For me the UX is little confusing for Single Post Template:
> 
>     1. Create a new post (with Elementor)
> 
>     2. Fill in some Content
> 
>     3. Edit the Single Post Template
> 
> 
> How to go back to the post which I created in #1? How can a user see when he is in the template and when he is in the post/page… itself? It would be great to have an obvious info to see that you are in the template.

Same questions here !

**Comment by mbenady** [comment]
The navigator is not updating according to where you are (post / single / header / footer).
If the is a z index use and something for example cover the header tip you don't have a way to open it for editing. 
No indication that I see for what you are currently editing (post / single / header / footer).

**Comment by dudaster** [comment]
When I'm trying to create a Popup Template or a Header Template the Editor gets stuck:

```
Uncaught Error: Routes: `` not found.
    at Routes.error (common.min.js?ver=2.9.4:2)
    at Routes.beforeRun (common.min.js?ver=2.9.4:2)
    at Routes.beforeRun (common.min.js?ver=2.9.4:2)
    at Routes.run (common.min.js?ver=2.9.4:2)
    at Routes.to (common.min.js?ver=2.9.4:2)
    at API.route (common.min.js?ver=2.9.4:2)
    at Component.show (editor.min.js?ver=2.9.4:31)
    at Commands.run (common.min.js?ver=2.9.4:2)
    at API.run (common.min.js?ver=2.9.4:2)
    at Editor.openLibraryOnStart (editor.min.js?ver=2.9.4:7)
```
I'm runing only Elementor 2.9.4 and Elementor 2.9.0-beta1

**Comment by dudaster** [comment]
The same with Elementor 2.9.4 and Elementor  2.8.4

**Comment by godvsgodvs** [comment]
It's been 4 days since anyone has responded from Elementor. It would be nice to get some feedback.

**Comment by fabianenzensperger** [comment]
When will it finally be released? I'm waiting for dynamic colors..

**Comment by Jorihlen** [comment]
> 
> 
> > I receive an error when I try to update to the Beta version. I am testing in a local environment.
> > I uninstalled and reinstalled Elmtr Pro and the problem persists.
> > "An error occurred while updating Elementor Pro: Could not create directory. elementor-pro/modules/animated-headline/assets"
> 
> If you're using Local by Flywheel this is a known issue.
Really is...

Thanks @michaelwright74

**Comment by godvsgodvs** [comment]
The current update is now Beta 2 and the major problem mentioned by several above regarding the Edit Header Handle z-index is not fixed. When the header is set to Sticky Top you can't click on it.

Is anybody from Elementor reading this thread?

**Comment by black-eye** [comment]
In all honesty, what happened to the communication from the dev team on this Github? The beta 2 is out (for how long?) and it’s not even mentioned here.

The last update of the free version was a disaster, which had to be (silently) postponed and it wouldn’t be necessary, if the devs had listened to the beta feedback here. Please Elementor team, learn a lesson from it and not let this happen again. Please, give us at least a sign, you are still here.

**Comment by rodolphebertozzo** [comment]
On ne peut pas demander à tester une version et ne pas répondre ou que occasionnellement, il serait bien de communiquer sur la nouvelle version Bêta sortie il y a déjà 12 heures pour savoir à où en est le développement de la Pro 2.9, il ne faut pas se plaindre après s'il y a des bugs, l'équipe d'Elementor fait un travail formidable ! Mais avec 4M d'utilisateurs, il faut s'appliquer davantage et penser à être beaucoup plus réactif sur Github...

**Comment by shilo-ey** [comment]
We just released a new beta version, please update your version to Pro v2.9 Beta 2.

**Please make sure that you update your Elementor core to v2.9.5 because a major part of the fixes and improvements are patched there.**

This beta release includes:

- Tweak: Added an editor preloader when switching between site parts
- Fix: Advanced tab appears as blank when editing a Global Widget
- Fix: Missing handles in Full Site Editor site parts
- Fix: UI glitches in various situations in Full Site Editor site parts
- Fix: Wrong edit label when editing a site part directly
- Fix: Hidden responsive elements are not visible in the Editor
- Fix: Navigator not being updated when switching between site parts
- Fix: Widgets panel not being updated when switching between site parts
- Fix: Preview when editing a site part is leading to the wrong preview
- Fix: Theme Style Link color overrides the Table of Content list style
- Fix: Active state glitches when using Table of contents widget with Sticky mode
- Fix: "Graphic Element" section appears as empty in case of unmarked Graphic Element in Call to Action widget
- Fix: Page Title widget render glitches in the Editor

**Please keep this related to the Current beta Only!** any other [Issue Report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md) or [Feature Request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md) feel free to open a new issue.

**Thanks again to everyone.**

**Comment by godvsgodvs** [comment]
> * Fix: Missing handles in Full Site Editor site parts

The problem still exists. If the header is set to Sticky-Top then you can't click on the Edit Header handle. I have already posted the reason, but here goes again with the css files and lines causing the problem.

In preview.css starting at line 2:
.elementor-document-handle {z-index:11;}

In frontend.css starting at line 5217:
.elementor-sticky-active {z-index:99;}

This puts the handle beneath the header section and therefore not clickable. If the section has a non-transparent background you won't even see the handle.

This seems pretty high priority since it makes Full Site Editor useless.

**Comment by jdub850000** [comment]
It seems very quiet here now - Is the beta still in progress?

**Comment by Kishorchandth** [comment]
@jdub850000  yap beta is still in process.

To Install Beta release you can enabled under Elementor - Tools - Beta Tester - Enabled.

or If it is not possible - First login to Elementor - Go to Purchases - Click View Details and Downloads - Scroll down and download beta version

**Comment by jdub850000** [comment]
> @jdub850000 yap beta is still in process.
> 
> To Install Beta release you can enabled under Elementor - Tools - Beta Tester - Enabled.
> 
> or If it is not possible - First login to Elementor - Go to Purchases - Click View Details and Downloads - Scroll down and download beta version

I wasn't asking to enter the beta - I was referring how quiet it is.

**Comment by rodolphebertozzo** [comment]
La version pro 2.9 sort le 17 mars, dans quelques jours

**Comment by jdub850000** [comment]
> La version pro 2.9 sort le 17 mars, dans quelques jours

Yes, I'm also aware of that - thanks. I took part in the 2.9 beta and before jumping in to 2.9 Pro testing wanted to see if there was active conversation taking place and things were moving forward. I felt the last beta process could have progressed better.

**Comment by godvsgodvs** [comment]
If they release pro 2.9 in 4 days with the current bugs it will be another disaster like Elementor 2.9 was. They didn't seem to even read the beta testers comments and released a buggy version. Then, of course, regular users screamed and they had to withdraw it. It seems Elementor's QA is non-existent.

**Comment by sermalefico** [comment]
Errors in beta is normal. Dont use in production sites. This is hardwork

**Comment by jdub850000** [comment]
No one is talking about using beta software in production, we're talking about doing proper beta testing and reporting errors that need to be fixed before launch, in order to minimise issues with the non-beta using customers - and the product launching with those problems anyway in order to meet a pre-determined deadline. Marketing over engineering. Sheesh - I've been beta testing for 20 years.

**Comment by godvsgodvs** [comment]
jdub, you beat me to the punch. Obviously I was talking about the past release of Elementor 2.9 Final as well as not addressing the errors when they are brought to the attention of the developers while in beta.

**Comment by shilo-ey** [comment]
[**@godvsgodvs**](https://github.com/godvsgodvs) commented on [Mar 13, 2020, 6:22 PM GMT+2](https://github.com/elementor/elementor/issues/10718#issuecomment-598804746 "2020-03-13T16:22:58Z - Replied by Github Reply Comments"):
> If they release pro 2.9 in 4 days with the current bugs it will be another disaster like Elementor 2.9 was. They didn't seem to even read the beta testers comments and released a buggy version. Then, of course, regular users screamed and they had to withdraw it. It seems Elementor's QA is non-existent.

Any current bugs that you can direct us to please (besides the one you described earlier with the z-index issue)? 

Please note that some of the fixes were implemented on the Core version (v2.9.6) and some in Beta 2 of Elementor Pro.

Please let us know, we're here to listen and learn from you guys.

Cheers.

**Comment by godvsgodvs** [comment]
shilo-ey,

My recommendation would be to give us updates more often than 4 day intervals. I, and I'm sure others, would like to know we aren't wasting our time.

Thank You.

**Comment by jdub850000** [comment]
> shilo-ey,
> 
> My recommendation would be to give us updates more often than 4 day intervals. I, and I'm sure others, would like to know we aren't wasting our time.
> 
> Thank You.

I complete agree with this. If I am going to test, then I need to know there is fluid comms - that's how it works - and that's how we progress. If glaring issues are left without response, then I feel less inclined to offer feedback. We are here to help improve the product for us - and you.

**Comment by jdub850000** [comment]
> > * Fix: Missing handles in Full Site Editor site parts
> 
> I am on Beta 2 and the problem still exists. If the header is set to Sticky-Top then you can't click on the Edit Header handle. I have already posted the reason, but here goes again with the css files and lines causing the problem.
> 
> In preview.css starting at line 2:
> .elementor-document-handle {z-index:11;}
> 
> In frontend.css starting at line 5217:
> .elementor-sticky-active {z-index:99;}
> 
> This puts the handle beneath the header section and therefore not clickable. If the section has a non-transparent background you won't even see the handle.
> 
> This seems pretty high priority since it makes Full Site Editor useless.

So is this issue fixed yet?

**Comment by shilo-ey** [comment]
It will be fixed in the RC version that will release soon.

**Comment by godvsgodvs** [comment]
Beta 3 is now available and the z-index issue is fixed it appears. I haven't checked much else yet.

**Comment by shilo-ey** [comment]
We just released a new beta version, please update your version to v2.9 Beta 3.

**This is our Release Candidate version (issues and bug fixes will be addressed if necessary).**

This beta release includes:
- Fix: Editing handle `z-index` issue when a Site Part is in Sticky positioning
- Fix: Widgets inside Post Content widget can be inline edited when outside of post


**Please keep this related to the Current beta Only!** any other [Issue Report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md) or [Feature Request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md) feel free to open a new issue.

**Thanks again to everyone.**

**Comment by jdub850000** [comment]
Okay, so I backed up a site in development and installed 2.90b3 Pro. The site was working correctly until this point. 

Upon installing, I now get an error on my archive posts page with iOS Safari and Mac Firefox. The site works fine in Mac OS Safari and Vivaldi. Browsers all latest version.

I've cleared caches, but apart from the swiper.min.js.map missing resource error (still there!), I can't see anything wrong. So, I rolled back to 2.85 and things are all working correctly again.

Here's the error page and system info.

Uncaught Error: Call to a member function get_component() on null in <domain>...wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/page-title.php on line 36

    render()
    wp-content/plugins/elementor/core/dynamic-tags/tag.php:35
    get_content()
    wp-content/plugins/elementor/core/dynamic-tags/manager.php:230
    get_tag_data_content()
    call_user_func_array()
    wp-content/plugins/elementor/core/dynamic-tags/manager.php:123
    parse_tag_text()
    wp-content/plugins/elementor/core/dynamic-tags/manager.php:88
    Elementor\C\D\{closure}()
    preg_replace_callback()
    wp-content/plugins/elementor/core/dynamic-tags/manager.php:87
    parse_tags_text()
    wp-content/plugins/elementor/includes/controls/base-data.php:81
    parse_tags()
    wp-content/plugins/elementor/includes/base/controls-stack.php:1196
    parse_dynamic_settings()
    wp-content/plugins/elementor/includes/base/controls-stack.php:1053
    get_parsed_dynamic_settings()
    wp-content/plugins/elementor/core/files/css/post.php:290
    render_styles()
    wp-content/plugins/elementor/core/dynamic-tags/dynamic-css.php:112
    add_controls_stack_style_rules()
    wp-content/plugins/elementor/core/files/css/post.php:290
    render_styles()
    wp-content/plugins/elementor/core/dynamic-tags/dynamic-css.php:112
    add_controls_stack_style_rules()
    wp-content/plugins/elementor/core/files/css/post.php:290
    render_styles()
    wp-content/plugins/elementor/core/files/css/post.php:172
    render_css()
    wp-content/plugins/elementor/core/files/css/base.php:596
    parse_content()
    wp-content/plugins/elementor/core/files/base.php:141
    get_content()
    wp-content/plugins/elementor/core/dynamic-tags/dynamic-css.php:69
    get_meta()
    wp-content/plugins/elementor/core/files/css/base.php:191
    enqueue()
    wp-content/plugins/elementor/core/files/css/post.php:193
    enqueue()
    wp-content/plugins/elementor/core/dynamic-tags/manager.php:446
    after_enqueue_post_css()
    wp-includes/class-wp-hook.php:288
    apply_filters()
    wp-includes/class-wp-hook.php:312
    do_action()
    wp-includes/plugin.php:478
    do_action()
    wp-content/plugins/elementor/core/files/css/base.php:260
    enqueue()
    wp-content/plugins/elementor/core/files/css/post.php:193
    enqueue()
    wp-content/plugins/elementor/includes/frontend.php:599
    enqueue_styles()
    wp-content/plugins/elementor-pro/modules/theme-builder/classes/locations-manager.php:90
    enqueue_styles()
    wp-includes/class-wp-hook.php:288
    apply_filters()
    wp-includes/class-wp-hook.php:312
    do_action()
    wp-includes/plugin.php:478
    do_action()
    wp-includes/script-loader.php:2670
    wp_enqueue_scripts()
    wp-includes/class-wp-hook.php:288
    apply_filters()
    wp-includes/class-wp-hook.php:312
    do_action()
    wp-includes/plugin.php:478
    do_action()
    wp-includes/general-template.php:2879
    wp_head()
    wp-content/themes/hello-elementor/header.php:21
    require_once()
    wp-includes/template.php:722
    load_template()
    wp-includes/template.php:671
    locate_template()
    wp-includes/general-template.php:41
    get_header()
    wp-content/plugins/elementor/modules/page-templates/templates/header-footer.php:9
    include()
    wp-includes/template-loader.php:98
    require_once()
    wp-blog-header.php:19
    require()
    index.php:17

There has been a critical error on your website.

-----------------

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.16.1
	MySQL version: Ubuntu 18.04 v5.6.46-86.2
	PHP Version: 7.4.3
	PHP Max Input Vars: 2000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.2
	Site URL: https://staging.carldawsonhair.com
	Home URL: https://staging.carldawsonhair.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 768M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-GB
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.2.2
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.136 Safari/537.36

== Active Plugins ==
	Beehive Pro
		Version: 3.2.3
		Author: WPMU DEV

	Cool Timeline Pro
		Version: 3.3.4
		Author: Cool Plugins

	Disable Gutenberg
		Version: 2.0
		Author: Jeff Starr

	Elementor
		Version: 2.9.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.9.0-beta3
		Author: Elementor.com

	Element Pack
		Version: 4.6.1
		Author: BdThemes

	Essential Addons for Elementor
		Version: 3.8.5
		Author: WPDeveloper

	Forminator Pro
		Version: 1.11.4
		Author: WPMU DEV

	Hummingbird Pro
		Version: 2.4.1
		Author: WPMU DEV

	Limit Login Attempts Reloaded
		Version: 2.10.1
		Author: WPChef

	MC4WP: Mailchimp for WordPress
		Version: 4.7.5
		Author: ibericode

	PowerPack Lite for Elementor
		Version: 1.2.8.7
		Author: IdeaBox Creations

	Premium Addons for Elementor
		Version: 3.11.7
		Author: Leap13

	Query Monitor
		Version: 3.5.2
		Author: John Blackbourn

	Smush Pro
		Version: 3.6.1
		Author: WPMU DEV

	Styler for WPForms
		Version: 2.0
		Author: Sushil Kumar

	Ultimate Addons for Elementor
		Version: 1.23.1
		Author: Brainstorm Force

	UpdraftPlus - Backup/Restore
		Version: 1.16.22
		Author: UpdraftPlus.Com, DavidAnderson

	WPForms
		Version: 1.5.9.2
		Author: WPForms

	WPMU DEV Dashboard
		Version: 4.8.1
		Author: WPMU DEV

	WP User Avatar
		Version: 2.2.5
		Author: flippercode


== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		theme-archive-title : 1
	footer : 1
		form : 1
		heading : 2
		social-icons : 1
		text-editor : 2
	header : 1
		image : 1
		nav-menu : 1
		search-form : 1
	page : 2
		archive-posts : 1
		heading : 1
		text-editor : 1
		theme-archive-title : 1
	product : 0
		woocommerce-breadcrumb : 2
		woocommerce-product-add-to-cart : 2
		woocommerce-product-data-tabs : 2
		woocommerce-product-images : 2
		woocommerce-product-meta : 2
		woocommerce-product-price : 2
		woocommerce-product-rating : 2
		woocommerce-product-related : 2
		woocommerce-product-short-description : 2
		woocommerce-product-title : 4
		woocommerce-product-upsell : 2
	section : 4
		button : 1
		global : 1
		nav-menu : 1
		shortcode : 1
		theme-site-logo : 1
	single : 1
		author-box : 1
		facebook-comments : 1
		heading : 2
		post-info : 2
		share-buttons : 1
		theme-post-content : 1
	widget : 0
		heading : 1
	wp-post : 0
		global : 1
		theme-post-featured-image : 1
	wp-page : 24
		bdt-cookie-consent : 1
		bdt-offcanvas : 1
		blockquote : 2
		button : 1
		ctl-addon : 1
		gallery : 1
		global : 6
		google_maps : 1
		heading : 23
		image : 30
		image-carousel : 6
		posts : 1
		social-icons : 1
		spacer : 8
		testimonial-carousel : 1
		text-editor : 28
		theme-archive-title : 2
		uael-table : 1
		video : 8
		woocommerce-products : 1


== Log ==
	
Log: showing 20 of 302019-12-16 09:25:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.0-beta2',
  'to' => '2.8.1',
)]
2019-12-16 15:35:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.1',
  'to' => '2.8.2',
)]
2019-12-18 07:44:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.7.3',
  'to' => '2.8.0-beta2',
)]
2019-12-18 07:45:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.0-beta2',
  'to' => '2.8.0',
)]
2019-12-18 20:00:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.0',
  'to' => '2.8.1',
)]
2020-01-03 14:16:19 [info] elementor::elementor_updater Started 
2020-01-03 14:16:19 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Start  
2020-01-03 14:16:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.2',
  'to' => '2.8.3',
)]
2020-01-03 14:16:20 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Finished 
2020-01-03 14:16:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.2',
  'to' => '2.8.3',
)]
2020-01-21 06:14:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.3',
  'to' => '2.8.4',
)]
2020-02-03 08:04:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.4',
  'to' => '2.8.5',
)]
2020-02-20 12:18:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.5',
  'to' => '2.9.2',
)]
2020-02-20 12:21:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.1',
  'to' => '2.8.4',
)]
2020-03-03 10:37:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.2',
  'to' => '2.9.3',
)]
2020-03-05 20:27:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.3',
  'to' => '2.9.4',
)]
2020-03-10 01:11:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.4',
  'to' => '2.9.5',
)]
2020-03-12 19:49:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.5',
  'to' => '2.9.6',
)]
2020-03-12 19:49:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.4',
  'to' => '2.8.5',
)]
2020-03-16 08:15:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.5',
  'to' => '2.9.0-beta3',
)]

JS: showing 10 of 10JS: 2019-11-05 11:15:38 [error X 4][https://carldawsonhair.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.5:32:64106] this.ui.apply.add is not a function 
JS: 2019-11-14 14:32:38 [error X 1][http://carldawsonhair.local/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view829\") has already been destroyed and cannot be used. 
JS: 2019-11-14 15:01:10 [error X 1][http://carldawsonhair.local/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view847\") has already been destroyed and cannot be used. 
JS: 2019-11-22 15:55:21 [error X 1][https://staging.carldawsonhair.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.7.5:2:39895] n.attributes[e.name].each is not a function 
JS: 2019-11-23 16:29:36 [error X 3][https://staging.carldawsonhair.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view728\") has already been destroyed and cannot be used. 
JS: 2019-11-25 19:42:22 [error X 1][https://staging.carldawsonhair.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view11651\") has already been destroyed and cannot be used. 
JS: 2019-11-26 07:23:27 [error X 2][https://staging.carldawsonhair.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.5:2:46150] Cannot read property \'select2\' of undefined 
JS: 2019-12-16 18:28:17 [error X 1][https://staging.carldawsonhair.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.8.2:7:20346] undefined is not an object (evaluating \'this.ui.columnInner.removeClass\') 
JS: 2019-12-18 15:58:59 [error X 1][https://staging.carldawsonhair.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.8.2:31:42262] null is not an object (evaluating \'e.message\') 
JS: 2020-01-15 20:57:11 [error X 1][https://staging.carldawsonhair.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=2.8.3:2:68514] undefined is not an object (evaluating \'this.swiper.update\') 

PHP: showing 2 of 2PHP: 2020-02-03 08:04:57 [notice X 1][/var/www/vhosts/carldawsonhair.com/staging.carldawsonhair.com/wp-content/plugins/elementor-pro/modules/theme-elements/widgets/breadcrumbs.php::38] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-12 19:51:21 [notice X 9][/var/www/vhosts/carldawsonhair.com/staging.carldawsonhair.com/wp-content/plugins/elementor/includes/base/controls-stack.php::1447] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by rodolphebertozzo** [comment]
Finally, is Elementor Pro available or not? On the extension details, there is a list of modifications with a release on the 15th (yesterday), so I can't install the official 2.9 version.

**Comment by michaelwright74** [comment]
> Finally, is Elementor Pro available or not? On the extension details, there is a list of modifications with a release on the 15th (yesterday), so I can't install the official 2.9 version.

I think availability at the moment depends where you are in the world. It seems to be a slow staged roll out.

**Comment by shilo-ey** [comment]
Thanks @jdub850000 , we issued a fix for this issue.

Elementor Pro v2.9 is rolling out, until tomorrow you should see the update in your site.

Thanks

**Comment by michaelwright74** [comment]
> Thanks @jdub850000 , we issued a fix for this issue.
> 
> Elementor Pro v2.9 is rolling out, until tomorrow you should see the update in your site.
> 
> Thanks

You're a tease lol. I see 2.9.1 is released now but still nothing in the UK.

**Comment by godvsgodvs** [comment]
I'm getting Elementor Pro 2.9.1 now. I had to turn Beta mode off and then saw reinstall 2.9.1 in version control.

**Comment by rodolphebertozzo** [comment]
Yes, all is good! Elementor Pro 2.9 is avaible (with 2.9.1 version)

**Comment by jazir5** [comment]
![full site editing broken](https://user-images.githubusercontent.com/31750063/76810286-bf4fca00-67aa-11ea-8bd3-d38baba7f964.PNG)


Full site editing is currently broken on the header and the styling for the selector on the footer is as well. You'll notice in the screenshot above the circled areas where the design is broken. The header section selector is completely broken an unselectable, it does not appear when i mouse over the header, the orange outline however *does*.

![header](https://user-images.githubusercontent.com/31750063/76810332-f1f9c280-67aa-11ea-9c4a-b244d74e924e.png)

It seems like the top part of it is cut off, but the bottom works, as evidenced by the orange outline at the bottom of the header.

**Comment by fabianenzensperger** [comment]
I'm still waiting for the update (Germany)..

**Comment by jdub850000** [comment]
> Thanks @jdub850000 , we issued a fix for this issue.
> 
> Elementor Pro v2.9 is rolling out, until tomorrow you should see the update in your site.
> 
> Thanks

Thanks for that - appreciated. Upgraded and working as expected!

**Comment by shilo-ey** [comment]
**Thank you all for your feedback!**

Elementor v2.9 is out, feel free to update!

If you find any other bug, feel free to create a new [Issue Report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md) or [Feature Request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md).

Thanks again to everyone.

**Comment by sermalefico** [comment]
Can reflect the header footer edit in the navigator?
