### ISSUE TITLE
✅ 🐞 Browser Console Warnings for missing Swiper.min.js.map script maps appear when SCRIPT_DEBUG is enabled in wp-config.php

### ISSUE THREAD

**Issue by mcrowell** [elementor/elementor#10764]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

I'm noticing a warning in chrome with the latest Elementor version:

DevTools failed to parse SourceMap: https://XXXXXX.com/wp-content/plugins/elementor/assets/lib/swiper/swiper.min.js.map

## Steps to reproduce

Inside Chrome console this warning is showing.

DevTools failed to parse SourceMap: https://XXXXXX.com/wp-content/plugins/elementor/assets/lib/swiper/swiper.min.js.map

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

**Comment by srcek** [comment]
I have this warning on all my sites. Didn't notice any issues, though.

**Comment by sergiopmigoya** [comment]
Same warning. But with Bridge theme and without Elementor plugin installed:

DevTools failed to parse SourceMap: https://XXXXXXXXX.com/wp-content/themes/bridge/js/plugins/swiper.min.js.map

**Comment by vivekrp** [comment]
I have the same issue, in Chrome, Firefox & Safari all Developer Tools see this warning. 

I have Hello Elementor theme and the plugin.

**Comment by gravnetic** [comment]
I can confirm that this issue does exist and it is a .map declaration after the url filetype of .js which is likely due to a webpack config issue.

DevTools failed to parse SourceMap: /wp-content/plugins/elementor/assets/lib/swiper/swiper.min.js.map

**Comment by badcat** [comment]
This has been around since min 2018.  Solution here:
https://github.com/elementor/elementor/issues/5151

**Comment by s5t5n** [comment]
+1 (and now swiper animations of plugins like Crocoblock - JetEngine (Listings) / JetElements IS DEAD) came to me from last Elementor Update

**Comment by s5t5n** [comment]
> +1 (and now swiper animations of plugins like Crocoblock - JetEngine (Listings) / JetElements IS DEAD) came to me from last Elementor Update

Just found out, that it's SLICK.JS causes troubles in Crocoblock.

**Comment by burblestudio** [comment]
@s5t5n I'm experiencing issues with crocoblock sliders, where did you hear this and is there a resolution? thanks

**Comment by oliverf72** [comment]
Same problem here...Elementor Pro 2.9.2

**Comment by anythingituk** [comment]
I left a comment on another thread:
https://github.com/elementor/elementor/issues/7082#issuecomment-613274404

**Basically:**
Editing the file **swiper.min.js** in folder _wp-content/plugins/elementor/assets/lib/swiper_ and remove this:

`//# sourceMappingURL=swiper.min.js.map` 

has removed the parsing error from the DevTools log for me

**Comment by nisiwi** [comment]
Same problem with Elementor Pro 2.9.3 + Elementor 2.9.7.
Regenerating files did not resolve the issue.
Disabling cache (and minification or combine) did not resolve the issue.
Appears to be a bug.

**Comment by anythingituk** [comment]
> Same problem with Elementor Pro 2.9.3 + Elementor 2.9.7.
> Regenerating files did not resolve the issue.
> Disabling cache (and minification or combine) did not resolve the issue.
> Appears to be a bug.

Did you try:

Editing the file swiper.min.js in folder wp-content/plugins/elementor/assets/lib/swiper and remove this:

//# sourceMappingURL=swiper.min.js.map

**Comment by sergiopmigoya** [comment]
Any permanent solution that not disappear when the plugin or the theme is updated, please?

**Comment by vilm725** [comment]
Hi everyone 👋🏼 I've a "possible fix" : copy the swiper.min.js of the December 19, 2018 (Swiper 4.4.6) and past in swiper.min.js.

You can download this version here : https://framabin.org/p/?7bf051363cb9e235#IceeN6cL0X1yx7aC+Ll5GHet4BsNMwGZVXJfM+Jws4k=

For me, it's work ! It's not a perfect solution but it's work. You can check the console in this vps : https://3v12gablsu.preview.infomaniak.website

P.S : It's just time to wait a new update from elementor, it's not perfect

> Any permanent solution that not disappear when the plugin or the theme is updated, please?

**Comment by fonderco** [comment]
This error has been around since... Forever. +1 vote to get it fixed.  See issue #5151 and #5313 

Yes, you can copy the file into the folder to stop the error.  But, it is kinda annoying to have to do it for every install.  Elementor is awesome, but please help us out! LOL

**Comment by gwmbox** [comment]
Will this be fixed? Surely since it has been around 2018 they are aware of it.  When can a fix be expected.

**Comment by fonderco** [comment]
I hope soon. It is annoying to have to add the file to manually to every installation.

**Comment by gwmbox** [comment]
Reply From Elementor

I want to let you know that this parse error/warning is caused because there are no .map files in Elementor and Chrome recently added this support.

This filetype is mainly used for developing games using the Quake engine.
Ref: https://fileinfo.com/extension/map

Please check out this StackOverflow thread to disable it in Chrome.
https://stackoverflow.com/questions/36051891/esri-failed-to-parse-source-map

**Comment by fonderco** [comment]
@gwmbox - you are correct, but that isn't the point.  The point is that the file should be in the folder with Elementor as web developers can't tell every user to just disable it in their chrome.  I think the frustrations rises from this being literally a 2 second fix for the next version.  Copy the file into the folder. Close issue.

**Comment by anythingituk** [comment]
> Reply From Elementor
> 
> I want to let you know that this parse error/warning is caused because there are no .map files in Elementor and Chrome recently added this support.
> 
> This filetype is mainly used for developing games using the Quake engine.
> Ref: https://fileinfo.com/extension/map
> 
> Please check out this StackOverflow thread to disable it in Chrome.
> https://stackoverflow.com/questions/36051891/esri-failed-to-parse-source-map

In my case, I simply removed the commented line at the bottom of the file:

> Editing the file swiper.min.js in folder wp-content/plugins/elementor/assets/lib/swiper and remove this:
> 
> //# sourceMappingURL=swiper.min.js.map

The error went away. This should not be done manually but should be implemented as a 'fix' by Elementor and as @gwmbox says, this should be implemented by Elementor not every single user.

This might seem like a minor issue but to those of us who work hard to deliver websites without errors, then this is annoying.

**Comment by prantu** [comment]
Yeah. This is annoying. Please fix this.

**Comment by badcat** [comment]
Seems like Elementor's build process is auto-generating the .map files - or at least including them. Wouldn't changing the build process to strip the .map files make more sense for the production / user needs?

**Comment by bartistiek** [comment]
Same issue here. I manually download the file, but this should not be necessary.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9.9

Feel free to update

Thanks!

**Comment by karlemilnikka** [comment]
> This issue has been resolved in Elementor v2.9.9
> 
> Feel free to update
> 
> Thanks!

The issue persists on our site after upgrading to Elementor Core 2.9.9 (Elementor Pro 2.9.5).

**Comment by nabaleka** [comment]
I have seen the error. I am currently running Elementor V2.9.9

**Comment by shilo-ey** [comment]
Thanks for reporting. **Reopened**.

We will address this issue again in the next patch version.

**Comment by rodolphebertozzo** [comment]
has_pr

**Comment by salvia34** [comment]
Same problem here, with last version v2.9.9.

**Comment by BigBearLio** [comment]
Not a guru, so not sure if this is the same error but I have :

DevTools failed to load SourceMap: Could not load content for https://*****.com/wp-content/plugins/elementor/assets/lib/swiper/swiper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE_

with Hello theme and Elementor 2.9.9 and 2.9.5.

**Comment by Next-Door-Tech** [comment]
My solution was to download `swiper.min.js.map` and `swiper.js.map` from [the Swiper repo at the v5.3.6 commit](https://github.com/nolimits4web/swiper/tree/71efce4731e9ee6ac9544ef3b7bc25c1e52388fe/package/js) (v5.3.6 is the swiper.js version currently packaged with Elementor v2.9.9) and install them in `/wp-content/plugins/elementor/assets/lib/swiper/`. In the future Elementor should include these files (at the appropriate version) in their plugin packages.

**Comment by fonderco** [comment]
@Next-Door-Tech - that is what everybody is saying.  That this bug is an easy fix. Just put the file in the folder for the next release.  I figure if we keep mentioning it here they will do it???  So for its been 2 years. #5151

**Comment by BlackHeartur666** [comment]
Hi,

same here, Elementor Pro up-to-date

`DevTools failed to load SourceMap: Could not load content for /elementor/assets/lib/swiper/swiper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

**Comment by rodolphebertozzo** [comment]
Fix in v.2.10

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9.10

Feel free to update

Thanks!

**Comment by jhweb2** [comment]
isnt fixed... 2.9.10

DevTools failed to load SourceMap: Could not load content for /wp-content/plugins/elementor/assets/lib/swiper/swiper.min.js.map: HTTP error: status code 404, net :: ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by BlackHeartur666** [comment]
> same here, Elementor Pro up-to-date

**Comment by babasteve** [comment]
1. Try to synchronize the library in the tools of the Elementor extension, and empty the cache of your browser.
2. Refresh your page again and normally the error will be gone.

For me this bug is fixed.
Thank you so much.

**Comment by babasteve** [comment]
1. Try to synchronize the library in the tools of the Elementor extension, and empty the cache of your browser.
2. Refresh your page again and normally the error will be gone.

With this method, for me this bug is fixed. ;)

> isnt fixed... 2.9.10
> 
> DevTools failed to load SourceMap: Could not load content for /wp-content/plugins/elementor/assets/lib/swiper/swiper.min.js.map: HTTP error: status code 404, net :: ERR_HTTP_RESPONSE_CODE_FAILURE

1. Try to synchronize the library in the tools of the Elementor extension, and empty the cache of your browser.
2. Refresh your page again and normally the error will be gone.

With this method, for me this bug is fixed. ;)

**Comment by JamboMedia** [comment]
Not fixed:

/assets/lib/swiper/swiper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by lukidev88** [comment]
Hi!
Anybody know, when the bug will be fix? I use elementor in 2.9.13 version and bug still occurs. This is a big problem form me, because my slider dosen't work.

**Comment by peefour** [comment]
error still there in latest elementor:
DevTools failed to load SourceMap: Could not load content for https://supportblabla.com/wp-content/themes/pinkmart/assets/js/swiper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

please fix

**Comment by roly151** [comment]
Still an issue almost 2 years later.

**Comment by barttermorshuizen** [comment]
Why is this issue closed?

**Comment by fonderco** [comment]
IMO there are 3 things that it blows my mind Elementor hasn't done.  1. Allow me to chose specific header/footer inside the page editor.  Don't make apply specific pages to headers/footer by editing each header/footer.  2. Why can't custom CSS be responsive.  Don't make me use the data-elementor-device-mode tag.  Come on!  3. THIS STUPID ISSUE.  Put the swiper.min.js.map file in the stupid zip file.  How hard is it????

**Comment by tripledm** [comment]
this issue still not resolved by elemementor and I have it on a few websites

**Comment by SoozaV** [comment]
Hi, why is this issue closed? @shilo-ey the error is still there... Elementor 3.15.1

**Comment by garyseo4** [comment]
Still getting this error

**Comment by bespokechat2** [comment]
Still getting this error

**Comment by ahmedhaffez** [comment]
error present even in lated version 3.20.0

**Comment by csloz** [comment]
Still present in 3.21.3   

Fix your production pipeline please.  This is 4 years now from first report.

.map references should not be requested at all, only in dev.

**Comment by raabmar** [comment]
Came across it and confirm - still and issue in July 2024

**Comment by BabilDesign** [comment]
Almost 5 years & still no fix, not good elementor

**Comment by BluFurr** [comment]
Still an issue for me on Safari and elementor 3.26.3 and elementor pro 3.26.2

**Comment by vbcnv5eknx** [comment]
Same here. Please help to fix

**Comment by tonydehnke** [comment]
Seeing this issue too - Elementor 3.27.2

**Comment by blockmonkey** [comment]
Seeing the same error as well 😓

**Comment by DanielBustillos** [comment]
Same error in version 3.27.6. WP version 6.7.2

**Comment by thinkof4** [comment]
5 years and no fix, poor Elementor.

**Comment by nicholaszein** [comment]
Hello.

If you are still seeing browser console warnings regarding missing script maps. Please make sure you have **`SCRIPT_DEBUG`** disabled in your **`wp-config.php`** file. 

These maps indicate where each script is located in the development tree and where should they go. They serve no other purpose, nor have any effect on script loading. 

When the plugin is compiled, they are removed from the final zip package as they are completely useless, and just take space. However, they are still referenced as comments in the un-minified versions of all scripts (which are included in the plugin as best practice recommendations from WordPress). 

Un-minified JS files are loaded when **`SCRIPT_DEBUG`** is set to **`true`** in your WordPress environment, and the scripts will attempt to download the maps, which are not included in the package.

Unless you're performing script debugging, **there is really no reason to have `SCRIPT_DEBUG` enabled on a production website.**

Just add the following snippet to the **`wp-config.php`** file located in the root folder of your WordPress installation right above the comment that says `/* That's all, stop editing! Happy publishing. */`:

```php
define( 'SCRIPT_DEBUG', false );
```

Make sure there is no other declaration for the same constant on this file, or you may break WordPress. Backup your site before editing the **`wp-config.php`** file (and save an unmodified copy of this file too). If anything goes wrong, you can restore the file and your backup too. 

----

This issue was closed several years ago. For this reason I am locking the comments. 

If you still think this is a bug caused by Elementor and can confirm it affects the functionality of the scripts on your site, feel free to [open a new 🐞 Bug Report](https://elemn.to/gh-new-bug-report) following our [Contribution Guidelines](https://elemn.to/gh-contributing-bug-reports) with concrete evidence of the problem, and we will be happy to evaluate your new issue. 

### For now that's all we can help with. 👍

Best regards
