### ISSUE TITLE
Image ratio shown in the archive/post

### ISSUE THREAD

**Issue by vgstef** [elementor/elementor#10874]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

The Image ratio is shown at the bottom the the Archive Widget on the front end and the back end.

## Steps to reproduce

Add a post archive to a page and you'll see the Image Ratio shown at the bottom of the widget.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

It happens on all my websites.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by aidanweltner** [comment]
+1 I am also seeing this issue with a similar setup

**Comment by wpnewaz** [comment]
I am also facing this problem. Is it new bug?

**Comment by calvinhanson** [comment]
I have the same thing happening. I found it randomly in a :after related to the specific elementor archive post grid element class. Yours will be different (than mine below) but you can search the inspector and find he :after styling. I

here's how I solved it:
.elementor-658 .elementor-element.elementor-element-b40b6f5:after {display: none; }

**Comment by Nicoduweb** [comment]
Hello,

I've exactly same problem.
It doesn't happened if i check mansonry

**Comment by rodolphebertozzo** [comment]
#10920

**Comment by Akira-Wat** [comment]
Hi

I've exactly same problem.
.elementor-166 .elementor-element.elementor-element-2a30e7e:after {display: none; }

**Comment by rodolphebertozzo** [comment]
This issue has been resolved in Elementor Pro 2.9.2 !

**Comment by klebozo** [comment]
Dear all, the issue persists, even though using lastest version. Does someone find a solution?

**Comment by barttermorshuizen** [comment]
again there in version 3.14.1

**Comment by srestre** [comment]
I've updated everything and am still getting this issue
