### ISSUE TITLE
Elementor frontend.css figure margin makes Gutenberg image block alignment style no longer work(conflict) added via Post Content widget

### ISSUE THREAD

**Issue by realstephenzhao** [elementor/elementor#11081]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

In `/wp-content/plugins/elementor/assets/css/fontend.css` and `/wp-content/plugins/elementor/assets/css/fontend.min.css`, there is code below:
```
.elementor .elementor-widget:not(.elementor-widget-text-editor) figure {
    margin:0
}
```

It conflicts with css created by Gutenberg editor if we set alignment(for example align to center) to the image block. The css code disabled by elementor figure margin setting is like this below:
```
.wp-block-image .aligncenter {
    margin-left: auto;
    margin-right: auto;
}
```
Then image block alignment wouldn't work any more in frontend because figure element has been presetted to `display: table;` in built-in WordPress stylesheet of Gutenberg editor located in `/wp-includeds/css/dist/block-library/style.css` and `/wp-includeds/css/dist/block-library/style.min.css`.

Please note, Gutenberg preset `display` property of image figure elements to `table`, and `text-align: center;` created by Gutenberg editor work only with its content but not table itself (See [Center a table with CSS](https://www.granneman.com/webdev/coding/css/centertables)). So we need `margin-left: auto; margin-right: auto;` to make table level elements align to center.

Please remove or alter figure margin setting in elementor to make Gutenberg image alignment work.

## Steps to reproduce

1. Create a single post template using elementor;
2. Add Post Content to the template;
3. Add a new post, insert an image block(image width should be less then content width or set to smaller size using editor option), align it to center, then publish;
4. You would see that image wouldn't align to center in the front page, it displays just like you doesn't set the alignment in Gutenberg editor;
5. Inspect the image figure element using development tool of your browser, you would see `margin-left: auto; margin-right: auto;` is disabled. It can work again if we remove the figure margin css code from Elementor;

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
Lastest Firefox and Chrome browsers on lastest Windows 10 OS
```
</details>

**Comment by realstephenzhao** [comment]
Don't expect Elementor Official would take action to improve the core experience, they're busy in marketing not developing.

Actually this so-called Ajax filter bar is not necessary if you use Nav Menu like [WPEXPLORER](https://www.wpexplorer.com/blog/). Just apply the same template to CPT Taxonomy(Display Condition), then you'll get SEO-friendly slugs for Taxonomy Pages.

![](https://i.imgur.com/GDogT7W.png)

**Comment by eybel** [comment]
Was this fixed on the last upgrades?

**Comment by gonzonia** [comment]
Still seems broken to me on latest. I created a Single Post Template. Then created a post with Gutenberg editor and aligned an image center. Use the Posts widget the image is not centered. It is centered on the single post page.

**Comment by coadr93** [comment]
Yep. Pretty big issue, should be fixed by either Elementor team or WP team. Most stylings for buttons text or images don't work.

**Comment by daviddang91** [comment]
I also have this issue.

**Comment by SKevo18** [comment]
I can confirm that this still happens on WordPress 6.3 and Elementor 3.15.2. The CSS rule is redundant, and should be removed IMO.

FYI for everyone stumbling upon this issue, this can be fixed (at least for the center layout) by applying this CSS code globally to your theme (e. g.: Admin panel > Themes > Customize > Additional CSS > Paste):

```css
.wp-block-image .aligncenter {
    margin-left: auto !important;
    margin-right: auto !important;
}
```

**Comment by nhutplus** [comment]
Still happens
- Elementor 3.25.9 
- Elementor Pro 3.25.4
