### ISSUE TITLE
Price in Custom Add To Cart (Pro)

### ISSUE THREAD

**Issue by qwik3r** [elementor/elementor#11801]
- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

It would be great to be able to add a price dynamically to the Woocommerce Custom Add To Cart (Pro). For example, I create advertisements that I put on custom product pages, the advertisements are for other products and I'd like to be able to pull in the price for the item (to display it) Right now that isn't a way to do that. 

**Describe the solution you'd like**

Show the price of the item on the button and/or add a price widget

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor Pro v3.7.0

Feel free to update

Thanks!

**Comment by Gregpro103** [comment]
What was the solution for this issue? I am using the latest version of Elementor PRO and there is no option to display the price along with the Custom Add to Cart button.

**Comment by muhammadmoazzam** [comment]
I am at the latest update but still can't see any pricing with custom add to cart widget...
