### ISSUE TITLE
Elementor pro - Posts archive template not used after update to wordpress 5.5

### ISSUE THREAD

**Issue by annettePixie** [elementor/elementor#12127]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description
The website is set up with a static homepage and a blog archive "posts page".

Following an update to wordpress 5.5, the elementor posts archive template is not being used for the blog archive page but rather the default theme layout. The display conditions in the elementor editor for the posts archive template remain the same - ie include "posts". 

If I delete the Blog "posts page" in "pages", the archive template is used.

## Steps to reproduce

Update from wordpress from 5.4 to 5.5

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.25-28
	PHP Version: 7.3.20
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: UTC
	Debug Mode: Inactive
```
</details>

**Comment by thehervy** [comment]
Same here. But it seems like it is connected to this one: https://github.com/elementor/elementor/issues/12126

**Comment by annettePixie** [comment]
> Same here. But it seems like it is connected to this one: #12126

Its similar but may not be exactly the same bug - the whole post archive template is not being used here at all.

**Comment by arielk** [comment]
This issue has been resolved in Elementor Pro v3.0.0

Feel free to update

Thanks!

**Comment by VonJot** [comment]
Sorry @arielk , but the pagination is NOT working.
WP 5.5 & 5.5.1, Elementor 3.0.5 & Elementor Pro 3.0.3.
Followed every possible dubug procedure. Still not working.

**Comment by arielk** [comment]
@VonJot can you please send us more info about your site environment (System Info etc..)

**Comment by VonJot** [comment]
> @VonJot can you please send us more info about your site environment (System Info etc..)

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.7.27
	PHP Version: 7.4.9
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.1
	Site URL: https://www.staging.vonjot.nl
	Home URL: https://www.staging.vonjot.nl
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: nl
	Timezone: Europe/Amsterdam
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: nl_NL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36 Edg/85.0.564.44

== Active Plugins ==
	Akismet Anti-Spam
		Version: 4.1.6
		Author: Automattic

	Autoptimize
		Version: 2.7.7
		Author: Frank Goossens (futtta)

	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Ele Custom Skin
		Version: 3.0.0
		Author: Dudaster.com

	Elementor
		Version: 3.0.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.3
		Author: Elementor.com

	Enable jQuery Migrate Helper
		Version: 1.0.1
		Author: The WordPress Team

	Flexible Elementor Panel
		Version: 2.2.2
		Author: WebMat

	Head, Footer and Post Injections
		Version: 3.2.1
		Author: Stefano Lissa

	Jetpack by WordPress.com
		Version: 8.9
		Author: Automattic

	Make Column Clickable Elementor
		Version: 1.3.1
		Author: Fernando Acosta

	Rank Math SEO
		Version: 1.0.47.1
		Author: Rank Math

	Reading Time WP
		Version: 2.0.10
		Author: Jason Yingling

	reSmush.it Image Optimizer
		Version: 0.3.10
		Author: reSmush.it

	UpdraftPlus - Backup/Restore
		Version: 1.16.28
		Author: UpdraftPlus.Com, DavidAnderson

	UsageDD
		Version: 1.4.7
		Author: Dion Designs

	WP-Optimize - Clean, Compress, Cache
		Version: 3.1.2
		Author: David Anderson, Ruhani Rabin, Team Updraft

	WP Downgrade | Specific Core Version
		Version: 1.2.2
		Author: Reisetiger

	WP Mail SMTP
		Version: 2.3.1
		Author: WPForms


== Elements Usage ==
	
	archive : 4
		archive-posts : 1
		heading : 1
		image : 1
		posts : 3
		wp-widget-tag_cloud : 1
	footer : 1
		global : 2
		heading : 1
		share-buttons : 1
	header : 1
		nav-menu : 1
		search-form : 1
	loop : 1
		button : 1
		post-info : 1
		shortcode : 1
		text-editor : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	page : 2
		heading : 2
	popup : 1
		button : 1
		heading : 1
		image : 1
	section : 4
		form : 1
		google_maps : 1
		heading : 1
		posts : 1
		wp-widget-tag_cloud : 1
	single : 3
		button : 1
		heading : 3
		image : 1
		post-comments : 1
		post-info : 1
		post-navigation : 2
		shortcode : 1
		theme-post-content : 1
		theme-post-title : 1
	widget : 0
		icon : 24
	wp-page : 6
		form : 1
		google_maps : 1
		heading : 12
		image : 19
		table-of-contents : 2
		template : 2
		text-editor : 15
		video : 1
		wp-widget-recent-comments : 1
		wp-widget-recent-posts : 1
		wp-widget-tag_cloud : 1


== Log ==
	
Log: showing 20 of 342020-08-24 01:54:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.3',
  'to' => '3.0.0',
)]
2020-08-24 01:54:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.0',
)]
2020-08-24 01:54:02 [info] elementor::elementor_updater Started 
2020-08-24 01:54:02 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-08-24 01:54:02 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-08-24 01:54:02 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-08-24 01:54:02 [notice] System colors are disabled. nothing to do. 
2020-08-24 01:54:02 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-08-24 01:54:02 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-08-24 01:54:02 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-08-24 01:54:02 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-08-24 01:54:02 [notice] System typography is disabled. nothing to do. 
2020-08-24 01:54:02 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-08-24 01:54:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.0',
)]
2020-09-02 20:55:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.0',
  'to' => '3.0.5',
)]
2020-09-02 20:55:16 [info] elementor::elementor_updater Started 
2020-09-02 20:55:16 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Start  
2020-09-02 20:55:16 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Finished 
2020-09-02 20:55:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.0',
  'to' => '3.0.5',
)]
2020-09-02 21:21:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.0',
  'to' => '3.0.3',
)]

JS: showing 3 of 3JS: 2020-06-01 01:39:55 [error X 10][https://www.staging.vonjot.nl/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view91\") has already been destroyed and cannot be used. 
JS: 2020-06-01 11:56:30 [error X 4][https://www.staging.vonjot.nl/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1:1:74235] Cannot read property \'destroy\' of undefined 
JS: 2020-09-02 19:26:44 [error X 4][https://www.staging.vonjot.nl/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view90\") has already been destroyed and cannot be used. 

PHP: showing 5 of 5PHP: 2020-06-01 03:42:36 [notice X 3][/home/vonjot1q/staging.vonjot.nl/wp-content/plugins/elementor/includes/template-library/sources/local.php::692] ob_end_clean(): failed to delete buffer. No buffer to delete [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-06-01 03:48:35 [warning X 2][/home/vonjot1q/staging.vonjot.nl/wp-content/plugins/elementor/includes/base/controls-stack.php::1201] Cannot assign an empty string to a string offset [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-06-15 08:16:01 [warning X 711][/home/vonjot1q/staging.vonjot.nl/wp-content/plugins/elementor/includes/base/controls-stack.php::1201] Illegal string offset 'url' [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-24 01:55:22 [notice X 1][/home/vonjot1q/staging.vonjot.nl/wp-content/plugins/elementor/includes/managers/image.php::86] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-24 01:57:14 [notice X 15][/home/vonjot1q/staging.vonjot.nl/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
