### ISSUE TITLE
"Edit with Elementor" button links do not work on EVERY page

### ISSUE THREAD

**Issue by TomRaraAvis** [elementor/elementor#12175]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Some pages missing "Edit with Elementor" link. Just text — no link. Some pages are fine & the link functions as it should. I do not understand why certain ones are functional and others are not functional? Link saves us time so we can edit with Elementor without needing to go through dashboard.

I reported this in Elementor v3 Beta 6, but another user said this is an issue that also exists outside of Beta. Another github user quote: "I don't think this is a beta version issue specifically as I've had this issue too well before the beta started, probably noticed it maybe 3 or so months ago. Definitely hope it's fixed regardless."

![no-link-edit-with-elementor](https://user-images.githubusercontent.com/1435355/90840081-08daad00-e327-11ea-954b-daa1c887caa2.png)

**Comment by arielk** [comment]
Duplicate of https://github.com/elementor/elementor/issues/11728

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.8

Feel free to update

Thanks!

**Comment by arkadygold** [comment]
I did the last update and still not aspiring on the admin bar :(
