### ISSUE TITLE
Column & Section Elements fires 'elementor/element/after_add_attributes' early

### ISSUE THREAD

**Issue by ibndawood** [elementor/elementor#12185]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The action `elementor/element/after_add_attributes` for elements `Column` and `Section` fires early like this:
https://github.com/elementor/elementor/blob/master/includes/elements/column.php#L992 and this
https://github.com/elementor/elementor/blob/master/includes/elements/section.php#L1469

As you can notice in the above lines, the `elementor/element/after_add_attributes` which is fired in the parent `Element_Base` class is added before adding attributes. The code calling the parent method should be called at the bottom allowing plugin developers to override attributes added to `Column` and `Section`.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.2

Feel free to update

Thanks!

**Comment by aawinther** [comment]
Nope, sorry still doesn't work - I'm afraid - problems with sections and columns. Have reset the css and delete cashe, still having problems after update
