### ISSUE TITLE
Custom repeater not working in the sections ( Elementor v.3.0 )

### ISSUE THREAD

**Issue by kaskad88** [elementor/elementor#12221]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
When using custom repeaters in the section's settings, there're JS errors appeared in the console https://prnt.sc/tl6g49

This problem was observed in the beta version, and unfortunately, it remained in the release version https://prnt.sc/u5k5z4.

**Comment by shilo-ey** [comment]
This is due to invalid implementation of repeater controls, we will add an exclusion for this enforcement for now and will release a developers blog post regarding the proper way of using it.

Thanks.

**Comment by latheeshvmv** [comment]
@shilo-ey Would someone mind providing a solution?

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.2, we added some backwards compatibility.

Feel free to update

A doc with proper instructions will be published soon

Thanks!

**Comment by simrandeep** [comment]
@shilo-ey Thank you for the update but unfortunately, the bug is still not resolved. I am still getting the same console error.

**Comment by easin-xs** [comment]
@shilo-ey the issues is still present in elementor v-3.0.2

**Comment by enamul-hoque** [comment]
Hi @shilo-ey, after the update, editors are showing this error. I need a fix for this asap.

**Comment by prappo** [comment]
issue still exists in 3.0.2
