### ISSUE TITLE
3.0.1 – Headings – Global Font Size Problem

### ISSUE THREAD

**Issue by wpbft** [elementor/elementor#12245]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

1.

When global fonts are applied, all headings inherit the “Primary” settings, including font size – even when no font size is defined for “Primary”.

This causes all headings to have the same font size. Trying to override it in theme settings does not work, as “Primary” has priority and overrides theme settings.

2.
Also, the global fonts can’t be applied to theme settings.

This is tested with a clean install with only WP 5.5, Elementor 3.0.1 and Hello Theme. Refresh CSS is tried. Also tried to “Disable/enable default fonts” and refreshing css.

## Steps to reproduce
- Create a new site with WP 5.5, Elementor 3.0.1 and Hello Theme
- Add a heading to page
- Define a custom global font
- Apply to any header (for example H1) in theme settings

## Isolating the problem
- [x] This bug happens with only Elementor plugin active
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

https://pastebin.com/azdckP4Z

**Comment by wpbft** [comment]
I wish this could be confirmed as a bug. It's been widely reported by several users on the WordPress forums and can easily be reproduced with a fresh install.

**Comment by slwirth** [comment]
I have a similar problem with E3.0.2 and EP3.0.1
I cannot reset the style of a headline to default in the page editor (FF and Chrome)
Changing the global styles doesn't affect the actual style displayed.
In short, global styles are not working properly (was a beta tester, so am familiar with the interface)
Thanks

![image](https://user-images.githubusercontent.com/40966578/91414891-7cac1680-e84d-11ea-82c1-17e39019dbe8.png)

**Comment by slwirth** [comment]
The issue in Style settings is solved and was my mistakes, kind of.

I checked the following boxes and it worked.

![image](https://user-images.githubusercontent.com/40966578/91531787-a6c50d80-e90d-11ea-8f89-8597ac9cf114.png)

Yet, the text of the those boxes doesn't make sense to me as it states the opposite of what I expect ticking these boxes to do. Please note I am using Hello theme.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.4

Feel free to update

Thanks!

**Comment by Juuppilainen** [comment]
Hey. Updated to v.3.0.4 and did all the steps (migrate fonts, rebuild css etc.) but still having the problem.

**Comment by thehervy** [comment]
Hi. EP 3.0.4 - the problem is still there. Different fonts on frontend (bad ones!) and backend (right ones!) ...

**Comment by slwirth** [comment]
Hi,

Still issues as well. The font should be white and it is black:

![image](https://user-images.githubusercontent.com/40966578/91724221-45b36900-eb9d-11ea-8d38-d2bb1362f379.png)

![image](https://user-images.githubusercontent.com/40966578/91724299-65e32800-eb9d-11ea-8a70-d46a26c23993.png)

Thanks and best

**Comment by mcrowell** [comment]
I can confirm that V3.0.5 still has this bug. The frontend doesn't render the same global styles from the backend.

**Comment by ksurmann** [comment]
Several issues. Here it goes:

I select PRIMARY HEADLINE for the page title, yet it continues to disappear. Also select a color (white) and it changes to some brown color. The sizes also continue to change from what I set them to on tablet and mobile. I have a tab widget on one page and it does not show the first tab content when you first get on the page. You have to click on the second tab and then back on the first tab.

Website is https://foresthunter.com

**Comment by slwirth** [comment]
Part of the issues (title color) was solved with regenerating CSS. 
Therefore, I wonder if Elementor could not introduce an automatic CSS regeneration when updating to a new version.
Further the issue regarding text of same format being displayed differently remains.
![image](https://user-images.githubusercontent.com/40966578/91836564-3d196c00-ec4b-11ea-99d2-b6508f2efd86.png)
There seem to be a class "elementor-kit" removing the weight for the bullets,
![image](https://user-images.githubusercontent.com/40966578/91836948-c892fd00-ec4b-11ea-8e07-3194f9dd0272.png)

![image](https://user-images.githubusercontent.com/40966578/91836938-c29d1c00-ec4b-11ea-956e-84dbc9ae6d38.png)

**Comment by mbaierl** [comment]
> The issue in Style settings is solved and was my mistake, kind of.
> 
> I checked the following boxes and it worked.
> 
> ![image](https://user-images.githubusercontent.com/40966578/91531787-a6c50d80-e90d-11ea-8f89-8597ac9cf114.png)
> 
> Yet, the text of the those boxes doesn't make sense to me as it states the opposite of what I expect ticking these boxes to do. Please note I am using Hello theme.

Yes, I agree, those checkboxes do not make any sense. 
There are still lots of bugs with the settings of global fonts and the typography settings. VERY unreliable :(

**Comment by megabrian** [comment]
I made a breakthrough on an issue that seems to match this.

I was unable to change font-size of H1 and H3 from the site settings area.

After several hours of testing things I finally got it to work, it seemed to be a combination of unchecking "default colors" and "default fonts" on main elementor settings screen in wp-admin, in addition to this trick - clicking "back to default" icon under each of those font settings.  After that, I was able to tweak the font-size after resetting h1 and h3.  

![Backtodefault](https://user-images.githubusercontent.com/32440630/126525195-b459c6dc-b3cd-45c3-8eab-297e0f822872.png)

I still have no clue what they are talking about with enable / disable default elementor fonts/colors.  It's super confusing.  I guess the font-sizes under the headings are the "not defaults", but on another site I can still use those even with the checkboxes checked off so it's very inconsistent at best.  

You would think "theme fonts and colors" would actually come from your stylesheet, and not just another settings tab in elementor site settings.

**Comment by yuk75** [comment]
This is still broken and despreately needs to be reopened. When you ONLY select a custom font the size is being overwritten for all headings.

**Comment by vcpaige** [comment]
I just ran into this issue and was able to fix it.

I went to **Site Settings > Global Fonts**, clicked on the pencil icon for the Primary Headline and clicked the 'back to default' icon at the top right. Then **SAVED** the settings, refreshed and my font sizes were working properly again. I was able to then go in and set up my Primary Headline font styling and it worked without overriding the font size with an empty value.

My theory is that if at some point you add a "size" value in the Primary Headline and then remove it, sometimes Elementor still tries to pull that value.

I hope this helps someone else!

**Comment by muneerWebDev** [comment]
> The issue in Style settings is solved and was my mistake, kind of.
> 
> I checked the following boxes and it worked.
> 
> ![image](https://user-images.githubusercontent.com/40966578/91531787-a6c50d80-e90d-11ea-8f89-8597ac9cf114.png)
> 
> Yet, the text of the those boxes doesn't make sense to me as it states the opposite of what I expect ticking these boxes to do. Please note I am using Hello theme.

this worked for me, thanks

**Comment by xbor17** [comment]
> > The issue in Style settings is solved and was my mistake, kind of.
> > I checked the following boxes and it worked.
> > ![image](https://user-images.githubusercontent.com/40966578/91531787-a6c50d80-e90d-11ea-8f89-8597ac9cf114.png)
> > Yet, the text of the those boxes doesn't make sense to me as it states the opposite of what I expect ticking these boxes to do. Please note I am using Hello theme.
> 
> this worked for me, thanks

Had the same issue now on Elementor on a WordPress 6.2.2, Hello Elementor 2.8.1 working through a Child Theme and Elementor 3.14. The bug is still there. Was fighting for 30 minutes trying to figure out why headings didn't change size when changing heading type till I found this thread.
For me it worked checking the boxes on **WordPress Menu > Elementor Options > Settings > General** (even though like some other guys above said that checking those options is doing the opposite of what is stated) and then saving again the options on **Elementor > Site Settings**

**Comment by cdsaenz** [comment]
Two years later I still find that I need to check both boxes for this to work as expected, contraintuitive in my opinion.
