### ISSUE TITLE
Global colors not applied to site.

### ISSUE THREAD

**Issue by wwdes** [elementor/elementor#12249]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Global colors are not being applied to frontend CSS. Additionally, color styling that was previously set for any widget using global colors does not appear in editor either. Only once user visits Menu(hamburger) > Site Settings do global colors suddenly render as expected.

## Steps to reproduce
Use global colors for style on any widget. Save. View on frontend. CSS variables are there, but the CSS for widget does not specify any color parameters.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.23
	PHP Version: 7.4.8
	PHP Max Input Vars: 10000
	PHP Max Post Size: 8000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5
	Site URL: https://xxx
	Home URL: https://xxx
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: xxx
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36

== Active Plugins ==
	Duplicate Page
		Version: 4.2
		Author: mndpsingh287

	Elementor
		Version: 3.0.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.0
		Author: Elementor.com

	Members
		Version: 3.0.10
		Author: MemberPress

	Open Graph and Twitter Card Tags
		Version: 3.0.0
		Author: Webdados

	Post SMTP
		Version: 2.0.15
		Author: Yehuda Hassine

	String Locator
		Version: 2.4.1
		Author: Clorith

	TranslatePress - Extra Languages Add-on
		Version: 1.0.1
		Author: Cozmoslabs, Razvan Mocanu

	TranslatePress - Multilingual
		Version: 1.8.1
		Author: Cozmoslabs, Razvan Mocanu, Madalin Ungureanu, Cristophor Hurduban

	TranslatePress - SEO Pack Add-on
		Version: 1.3.0
		Author: Cozmoslabs, Razvan Mocanu

	WP File Manager
		Version: 6.7
		Author: mndpsingh287

== Must-Use Plugins ==
	installatron_hide_status_test.php
		Version: 
		Author: 

== Elements Usage ==
	
	footer : 1
		button : 1
		form : 2
		heading : 3
		html : 3
		icon-list : 1
		text-editor : 2
	header : 1
		nav-menu : 2
		theme-site-title : 1
	popup : 1
		button : 1
		heading : 1
	widget : 0
		button : 1
	wp-post : 0
		copyright : 1
		divider : -11
		heading : -47
		image : -26
		shortcode : 1
		text-editor : -28
	wp-page : 3
		button : 1
		divider : 2
		heading : -2
		icon : 1
		image : 1
		posts : 2
		text-editor : 2

== Log ==
	
JS: showing 14 of 14JS: 2020-04-18 12:16:31 [error X 1][https://xxx/wp-admin/post.php?post=1370&action=elementor#:2:67] Unexpected token \&#039;{\&#039; 
JS: 2020-04-18 12:20:00 [error X 8][https://xxx/wp-admin/post.php?post=1370&action=elementor#:2:45] Cannot set property \&#039;onclick\&#039; of null 
JS: 2020-04-18 12:20:49 [error X 1][https://xxx/wp-admin/post.php?post=1370&action=elementor#:2:5] Unexpected token \&#039;.\&#039; 
JS: 2020-04-18 12:20:56 [error X 1][https://xxx/wp-admin/post.php?post=1370&action=elementor#:2:14] Failed to execute \&#039;querySelector\&#039; on \&#039;Document\&#039;: \&#039;.\&#039; is not a valid selector. 
JS: 2020-04-18 12:21:19 [error X 3][https://xxx/wp-admin/post.php?post=1370&action=elementor#:2:76] Unexpected token \&#039;;\&#039; 
JS: 2020-04-18 12:37:44 [error X 2][https://xxx/wp-admin/load-scripts.php?c=0&loadchunk_0=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,underscore,backbone&ver=5.4:4:30645] Cannot read property \&#039;pageYOffset\&#039; of undefined 
JS: 2020-05-07 22:58:08 [error X 2][https://xxx/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.8:31:70343] elementorFrontend is not defined 
JS: 2020-05-08 14:39:43 [error X 15][https://xxx/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.8:7:46971] Cannot read property \&#039;currentView\&#039; of undefined 
JS: 2020-05-10 20:58:30 [error X 8][https://xxx/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,shortcode,utils,wp-util,wp-backbo&loadchunk_1=ne,media-models,moxiejs,plupload,wp-plupload,jquery-ui-sortable&ver=5.4.1:4:1831] cannot call methods on resizable prior to initialization; attempted to call method \&#039;destroy\&#039; 
JS: 2020-05-10 20:58:45 [error X 1][https://xxx/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.8:7:75423] Cannot read property \&#039;addClass\&#039; of undefined 
JS: 2020-05-10 22:59:11 [error X 1][https://xxx/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.8:31:204198] this.manager.setPage(...).showView is not a function 
JS: 2020-06-05 12:40:05 [error X 4][https://xxx/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.11:31:162562] Cannot read property \&#039;isDesignable\&#039; of undefined 
JS: 2020-08-25 07:48:43 [error X 1][https://xxx/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=2.9.14:2:195519] Cannot read property \&#039;map\&#039; of undefined 
JS: 2020-08-25 19:19:11 [error X 6][https://xxx/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.0.1:2:55861] Cannot read property \&#039;global\&#039; of undefined 

Log: showing 20 of 212020-06-04 11:06:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.8',
  'to' => '2.9.11',
)]
2020-06-04 11:06:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.4',
  'to' => '2.9.5',
)]
2020-06-09 17:42:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.5',
  'to' => '2.10.0',
)]
2020-08-10 12:33:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.11',
  'to' => '2.9.14',
)]
2020-08-10 12:33:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.0',
  'to' => '2.10.3',
)]
2020-08-25 18:29:54 [info] elementor::elementor_updater Started 
2020-08-25 18:29:54 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-08-25 18:29:54 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-08-25 18:29:54 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-08-25 18:29:54 [notice] System colors are disabled. nothing to do. 
2020-08-25 18:29:54 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-08-25 18:29:54 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-08-25 18:29:54 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-08-25 18:29:54 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-08-25 18:29:54 [notice] System typography is disabled. nothing to do. 
2020-08-25 18:29:54 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-08-25 18:29:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.0',
)]
2020-08-25 18:29:54 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.0',
)]
2020-08-25 18:30:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.3',
  'to' => '3.0.0',
)]
2020-08-25 18:31:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.0',
  'to' => '3.0.1',
)]

PHP: showing 7 of 7PHP: 2020-05-08 19:01:36 [notice X 5][/home/admin1/xxx/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::218] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-08 21:37:30 [error X 2][/home/admin1/xxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::259] Uncaught Error: Call to a member function update_meta() on null in /home/admin1/xxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:259
Stack trace:
#0 /home/admin1/xxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(180): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions(1145, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/admin1/xxx/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/admin1/xxx/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#4 /home/admin1/xxx/wp-includes/class-wp-hook.php(311): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#5 /home/admin1/xxx/wp-includes/pl [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-09 10:19:11 [error X 1][/home/admin1/xxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::259] Uncaught Error: Call to a member function update_meta() on bool in /home/admin1/xxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:259
Stack trace:
#0 /home/admin1/xxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(180): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/admin1/xxx/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/admin1/xxx/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#4 /home/admin1/xxx/wp-includes/class-wp-hook.php(311): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#5 /home/admin1/xxx/wp-includes/pl [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-06-05 10:36:57 [notice X 3][/home/admin1/xxx/wp-content/plugins/elementor/modules/usage/module.php::79] Undefined index: publish [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-14 08:44:31 [error X 1][/home/cyber/domains/xxx/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::259] Uncaught Error: Call to a member function update_meta() on null in /home/cyber/domains/xxx/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:259
Stack trace:
#0 /home/cyber/domains/xxx/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(180): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions(1145, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/cyber/domains/xxx/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/cyber/domains/xxx/public_html/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#4 /home/cyber/domains/xxx/public_html/wp-includes/cla [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-22 17:31:04 [warning X 1][/home/cyber/domains/xxx/public_html/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::181] unlink(map-marker-alt-solid.svg): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-25 18:34:33 [notice X 2][/home/cyber/domains/xxx/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

```
</details>

**Comment by danielpetrovic** [comment]
Same problem here. After it auto upgraded to Elementor 3.0 this problem started happening. We are using Astra theme. So it is not the Theme causing it, but definitely Elementor 3.0 .

**Comment by beniciot** [comment]
I have the same problem it changed the whole colours of my website since the new updated.

**Comment by pvgilbertsd** [comment]
Same thing.  What is really odd is that when I am in the Elementor editor, everything looks fine.  View the page online and it's all messed up.  Fonts and colors are both not displaying as they were before the 3.0.1 update

**Comment by 15101570** [comment]
Same issue. In the Elementor editor, everything looks fine. View the page online and it's not right. This update renders editor / pagebuilder useless for us.

**Comment by skompini** [comment]
I'm not sure if this is the same _exact_ issue, but it is relational. Saved colors/global colors don't work. They show in the Elementor editor, but not when you view the site in any browser. However, if you pick a new color using the color picker, or enter a hex value by hand or copy and paste it, it does work. It's just the saved colors don't seem to work when you click and choose.

**Comment by JanWed** [comment]
Same issue, using the Hello Theme and no other plugins activated. Global colors AND fonts are not being applied to frontend CSS. Everything looks fine in the editor, but both fonts and colors are messed up when viewing the site online.

**Comment by gsusI** [comment]
I've been able to find a workaround for this:

On Elementor > tools, click "Regenerate Files"

![image](https://user-images.githubusercontent.com/4558016/91503154-bfa7d180-e8c1-11ea-84b1-7a90919f802f.png)

I'm however stuck with https://github.com/elementor/elementor/issues/12275

**Comment by ingoratsdorf** [comment]
Same issue here, however "Regenerate Files" as above did not do anything for me. Most notably global colours for me are not applied to any section backgrounds, but not only. Seems random at times.

**Comment by whokneadsdough** [comment]
Global Colors and Fonts seem to fall apart randomly. Here's a screen recording of it happening when attempting to change a font [https://youtu.be/46jXoqpQTqY](https://youtu.be/46jXoqpQTqY). The history and Regenerate Files button have no success. Sometimes I can start making changes to Global Colors and Fonts and the setting changes will start to take. Then BAM, visually it falls apart. The Global settings don't reset, but aren't reflected visually on the front-end. Using the inspector on Chrome and Safari show the CSS code for the Global settings are there, but the pages don't reflect it.

<img width="1280" alt="Screen Shot 2020-08-27 at 10 47 05 PM" src="https://user-images.githubusercontent.com/70361848/91527185-19a49900-e8ba-11ea-9f79-c300718f5850.png">

This WordPress installation is a clean installation, more details below:
Plugins: Elementor 3.0.3, Elementor Pro 3.0.1, Smush

Tried using themes Hello and Astra, results are the same. Tried checked and unchecked "Disable Default Colors" and "Disable Default Fonts" with no success. Tried "CSS Print Method" both internal and external. Tried "Optimized DOM Output" default, enabled, and disabled.

**Comment by mister-mst** [comment]
Same issue

**Comment by petranca** [comment]
Same here

**Comment by gmariani** [comment]
Elementor just decided to stop adding colors to the style sheet after working all day yesterday. Now i can't get it to generate properly. Everything else is in there, formatting, background images, fonts, etc. But colors, nah... No errors generated.

**Comment by gmariani** [comment]
Manually rolled back to elementor 3.0.0 and elementor 3.0.0 and re-saved all templates and viewed each main template and that allowed the css to be generated properly. Whatever you guys did in the recent updates broke something.

**Comment by ingoratsdorf** [comment]
> Manually rolled back to elementor 3.0.0 and elementor 3.0.0 and re-saved all templates and viewed each main template and that allowed the css to be generated properly. Whatever you guys did in the recent updates broke something.

Did the rollback as well, but does also not work. Breakage must be in the original 3.0.0 version. Anything that has a global colour does not render. I checked the source view in Chrome and anything in the CSS that has global colours is not in there, so no color=, background-color= etc. All other attributes are there.

Meaning to me that the js part in the elementor editor is working for the live updates, but the PHP "render" part is not working for global colours as it should.

**Comment by whokneadsdough** [comment]
I uploaded a screen recording [https://youtu.be/0HNljn7uoUE](https://youtu.be/0HNljn7uoUE) of many strange behaviors of Global Colors and Fonts, time stamps are below.
(Installation details: Elementor 3.0.3, Elementor Pro 3.0.1, Theme: Hello)

Global Colors and Fonts, Site Settings Strange Behaviors Time Stamps
- 1:20 - Colors and fonts not displaying on live site.
- 1:53 - H1 font-size can be changed, but H2 cannot.
- 3:05 - Changing H3 to a Global Color causes all typography to lose colors and font family settings.
- 3:45 - Changing H1 font-size causes H2 and H3 to inherit secondary Global Color.
- 4:18 - Changing H2 font-size causes H2 and H3 to lose Global Color.
- 4:41 - Changing H1 font-size causes H2 and H3 to re-inherit Global Color.
- 5:45 - After modifying Global Colors, typography settings are lost.
- 5:50 - Global Colors magically appear in typography settings, but are not being applied in the editor.
- 5:57 - Changing Body Text Color to a different Global Color causes the editor to display Global Colors correctly. But some headings and body text revert to a serif font family never specified by user.
- 6:40 - Changing Body Typography to Global Fonts Text causes colors to be lost, font-families change from sans-serif to serif.
- 7:04 - Clicking on the Font-Size field causes font-family to change.
- 8:47 - All previous Typography settings spontaneously.
- 8:51 - Typography settings magically appearing.
- 9:11 - Clicking Body Typography causes editor to display Global Fonts settings.
- 9:30 - Live page shows the Global Fonts and Colors settings are in the CSS, but Chrome is choosing to render something else.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.4

Feel free to update

Thanks!

**Comment by skompini** [comment]
This doesn't appear to be fixed, for me. Fonts are still staying at whatever the system default is, not the global font I specified. Same with global colors. They're simply not sticking. They show in the editor, but not in any browser. Still same issue and I am on 3.0.4 with Hello basic theme.

**Comment by whokneadsdough** [comment]
I'm still experiencing the same issue. Upgraded to 3.0.4, Regenerated CSS, tried Hello and Astra, problems persist.

Changes in editor not reflected: https://youtu.be/EQw3IclYiFA?t=109 
Time stamps of other notable erratic behaviors below, same video as above:
1:49 - Site Setting changes not reflected on live site.
3:56 - Changing Global Font causes colors and fonts to be dropped.
5:00 - Changing Text to Global Color causes lost colors and fonts to be reapplied.
8:26 - Several requests get cancelled.
9:15 - Font size specific em size not being applied to H1.
10:41 - Clicking on H2 em size causes fonts and colors to be dropped.
15:30 - pickr.min.js.map error 404

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.23
	PHP Version: 7.4.9
	PHP Max Input Vars: 10000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5
	Site URL: https://stage.leonelcalara.com
	Home URL: https://stage.leonelcalara.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 1G
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Los_Angeles
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.0.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.1
		Author: Elementor.com


== Elements Usage ==
	
	header : 1
		heading : 3
	wp-page : 1
		heading : 6
		text-editor : 1


== Log ==
	
Log: showing 10 of 102020-08-27 14:53:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.3',
  'to' => '3.0.1',
)]
2020-08-27 12:39:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.2',
  'to' => '3.0.3',
)]
2020-08-29 11:48:42 [notice] Re-migrate 3.0.0 globals: Start 
2020-08-29 11:48:42 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_typography_to_kit 
2020-08-29 11:48:42 [notice] System typography is disabled. nothing to do. 
2020-08-29 11:48:42 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_colors_to_kit 
2020-08-29 11:48:42 [notice] System colors are disabled. nothing to do. 
2020-08-29 11:48:42 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_saved_colors_to_kit 
2020-08-29 11:48:43 [notice] Re-migrate 3.0.0 globals: End 
2020-08-30 09:41:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.3',
  'to' => '3.0.4',
)]

PHP: showing 3 of 3PHP: 2020-08-27 12:32:37 [notice X 4][/home/nelcalara/stage.leonelcalara.com/wp-content/plugins/elementor/includes/managers/image.php::86] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-29 11:48:43 [notice X 2][/home/nelcalara/stage.leonelcalara.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-29 12:19:43 [error X 2][/home/nelcalara/stage.leonelcalara.com/wp-content/plugins/elementor/core/upgrade/elementor-3-re-migrate-globals.php::77] Uncaught Error: Cannot unset string offsets in /home/nelcalara/stage.leonelcalara.com/wp-content/plugins/elementor/core/upgrade/elementor-3-re-migrate-globals.php:77
Stack trace:
#0 /home/nelcalara/stage.leonelcalara.com/wp-content/plugins/elementor/core/upgrade/elementor-3-re-migrate-globals.php(21): Elementor\Core\Upgrade\Elementor_3_Re_Migrate_Globals->run()
#1 [internal function]: Elementor\Core\Upgrade\Elementor_3_Re_Migrate_Globals->ajax_re_migrate_globals(NULL, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/nelcalara/stage.leonelcalara.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, NULL, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/nelcalara/stage.leonelcalara.com/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/nelcalara/stage.leonelcalara.com/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#5 /home/nelcalara/stage.leonelcalara.com/wp-includ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2020-08-29 18:41:08 [error X 1][https://stage.leonelcalara.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.3:2:329019] elementorFrontend is not defined 


				
</details>

**Comment by skompini** [comment]
I've got another thing to add about the fonts... the following is what I see in Chrome when I am looking at a particular element's fonts - or trying to anyway:

.elementor-kit-2811 {
    --e-global-color-primary: #060606;
    --e-global-color-secondary: #54595F;
    --e-global-color-text: #7A7A7A;
    --e-global-color-accent: #DED9E0;
    --e-global-typography-primary-font-family: "Lato";
    --e-global-typography-primary-font-weight: 400;
    --e-global-typography-secondary-font-family: "Lato";
    --e-global-typography-secondary-font-weight: 400;
    --e-global-typography-text-font-family: "Open Sans";
    --e-global-typography-text-font-weight: 400;
    --e-global-typography-accent-font-family: "Roboto";
    --e-global-typography-accent-font-weight: 500;
    color: #7A7A7A;

This isn't helpful. It's all the global fonts I set, and I have to figure out which one goes with the element I chose. None of them are actually working, but it was much better when it would just tell me what font was being used on that element. Like this:

.elementor-widget-heading .elementor-heading-title {
    color: #060606;
    font-family: "Lato", Sans-serif;
    font-weight: 400;
}

So much better than now. We need to fix this as well please, I think it's part of the same issue with all global element settings. Thanks!

**Comment by Juuppilainen** [comment]
Hey! Updated elementor to 3.0.4 bus same issue continues. Nor global fonts or colors show. The correct fonts and colors ale visible in the backend but frontend still messed up. The browser just picks a system font and the default (grey) color to the headings.

**Comment by thehervy** [comment]
Hi. EP 3.0.4 - the problem is still there. Different fonts on frontend (bad ones!) and backend (right ones!) ...

**Comment by whokneadsdough** [comment]
Problem still persists with 3.0.5 / Pro 3.0.2
<details><summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.23
	PHP Version: 7.4.9
	PHP Max Input Vars: 10000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5
	Site URL: https://stage.leonelcalara.com
	Home URL: https://stage.leonelcalara.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 1G
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Los_Angeles
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36

== Active Plugins ==

	Elementor
		Version: 3.0.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.2
		Author: Elementor.com

== Elements Usage ==
	
	header : 2
		heading : 3
		nav-menu : 1
		theme-site-logo : 1
	wp-page : 2
		heading : 6
		text-editor : 1


== Log ==
</details>

**Comment by mcrowell** [comment]
+1

**Comment by alessandrolosacco** [comment]
+1

**Comment by kangomedia** [comment]
+1

**Comment by charisti** [comment]
+1

**Comment by rchrdsin** [comment]
+1 problem still present

**Comment by webenadam** [comment]
Still here, and no sign from Elementor. this through out updates approach is so bad! check basic stuff before you release updates. can't work with it and can't go back because then my client will have to deal with it in the future...

**Comment by whokneadsdough** [comment]
See #12363

**Comment by pouya-0098** [comment]
i finde 
A method to fix the problem
The only solution and easiest way to upload the WordPress Upload folder except for the image folders

Add-on folders that are located in the Opero Folder

https://s4.uupload.ir/files/screen_shot_1400-03-30_at_20.01.58_y8ss.png


I got all the folders ristor from the back of the app that I created before
Elman was able to properly load font and color for me

------------------------------------------------------------
I did the following procedure and destroyed Global files
On Elementor > tools, click "Regenerate Files"

------------------------------------------------------------

restor Folder. uploads

**Comment by guarmo** [comment]
Hard refreshing the browser solved the issue in my case.

**Comment by gitDk70** [comment]
Try changing the colors and/or typography in elementor site settings. Change the primary color for example, it should work

**Comment by ArnaudLavallee** [comment]
Found the solution ! You have to add <?php body_class() ?> in the <body> tag of your child theme. 

Just like this : 
```
<body <?php body_class() ?>
```

**Comment by rblackfox** [comment]
> In my case, I tried everything and nothing worked. I opened global colors clicked on colors and saved, Wow it worked and background images came back as well.
> 
> This fix also when I transfer the website of my clients to their hosting after approval.

We tried everything under the sun and this was what fixed it. Thanks AceeBaba!
