### ISSUE TITLE
Frontend.min.js error after updating to 3.02

### ISSUE THREAD

**Issue by qwik3r** [elementor/elementor#12275]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

After updating to Elementor 3.02 I received an error in the console about frontend.min.js: https://share.getcloudapp.com/bLuRBzzW.

This subsequently broke things like the vertical scroll animation on elements

## Steps to reproduce

Update to from 3.0 to 3.02

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '32', Revision '56bce88' v5.7.29-32
	PHP Version: 7.4.6
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5
	Site URL: https://xxxxx.wpengine.com
	Home URL: https://xxxxx.wpengine.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Admin Email: 
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty
	Version: 1.5
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.0.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.1
		Author: Elementor.com


== Must-Use Plugins ==
	Force Strong Passwords - WPE Edition
		Version: 1.6.4
		Author: Jason Cosper

	LearnDash LMS Multisite
		Version: 1.0.0
		Author: LearnDash

	WP Engine Seamless Login Plugin
		Version: 1.5.5
		Author: WP Engine

	WP Engine Security Auditor
		Version: 1.0.9
		Author: wpengine

	WP Engine System
		Version: 4.0.0
		Author: WP Engine


== Elements Usage ==
	
	page : 3
		accordion : 2
		button : 10
		divider : 3
		ha-infobox : 3
		heading : 42
		icon-list : 5
		image : 17
		shortcode : 1
		spacer : 3
		text-editor : 19
	section : 1
		divider : 1
		heading : 1
		image : 1
		text-editor : 1
	wp-post : 0
		accordion : 1
		button : 1
		divider : 1
		heading : 30
		icon : 2
		icon-list : 6
		image : 9
		shortcode : 1
		spacer : 3
		star-rating : 1
		text-editor : 9
		video : 1
		wfacp_form : 2
		wfacp_form_summary : 2
	wp-page : 1
		accordion : 1
		button : 7
		divider : 1
		heading : 18
		icon : 1
		icon-list : 3
		image : 7
		shortcode : 1
		spacer : 3
		text-editor : 5


== Log ==
	
JS: showing 8 of 8JS: 2020-08-19 16:47:40 [error X 9][https://xxxxx.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.14:31:89241] Cannot read property \&#039;value\&#039; of undefined 
JS: 2020-08-19 16:47:47 [error X 8][https://xxxxx.wpengine.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:4698] Cannot read property \&#039;match\&#039; of undefined 
JS: 2020-08-19 23:49:55 [error X 168][https://xxxxx.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.14:2:111837] Cannot read property \&#039;get\&#039; of undefined 
JS: 2020-08-20 16:27:01 [error X 1][https://xxxxx.wpengine.com/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=2.9.14:2:9012] container or containers are required. 
JS: 2020-08-24 22:13:39 [error X 1][https://xxxxx.wpengine.com/wp-admin/load-scripts.php?c=0&loadchunk_0=jquery&ver=5.5:2:1825] cannot call methods on resizable prior to initialization; attempted to call method \&#039;destroy\&#039; 
JS: 2020-08-25 22:32:56 [error X 2][https://xxxxx.wpengine.com/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1:1:74235] Cannot read property \&#039;destroy\&#039; of undefined 
JS: 2020-08-25 22:55:57 [error X 5][https://xxxxx.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.1:2:469692] Cannot read property \&#039;document\&#039; of undefined 
JS: 2020-08-26 23:50:22 [error X 42][https://xxxxx.wpengine.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.0.0:2:46561] Failed to execute \&#039;observe\&#039; on \&#039;IntersectionObserver\&#039;: parameter 1 is not of type \&#039;Element\&#039;. 

PHP: showing 1 of 1PHP: 2020-08-25 15:56:24 [notice X 1][/nas/content/live/creativemakeup/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/add-to-cart.php::142] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 14 of 142020-08-25 22:45:40 [info] elementor::elementor_updater Started 
2020-08-25 22:45:40 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-08-25 22:45:40 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-08-25 22:45:40 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-08-25 22:45:40 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-08-25 22:45:40 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-08-25 22:45:40 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-08-25 22:45:40 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-08-25 22:45:40 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-08-25 22:45:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.1',
)]
2020-08-25 22:45:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.1',
)]
2020-08-25 22:45:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.3',
  'to' => '3.0.0',
)]
2020-08-26 19:50:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.1',
  'to' => '3.0.2',
)]
2020-08-26 19:50:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.0',
  'to' => '3.0.1',
)]






```
</details>

**Comment by thegonnalive** [comment]
I am getting same errors: https://imgur.com/a/5G1Owyo 

Vertical motion effects stopped working. 
I see also missing Headings and sections on Front-End. In the editor everything looks fine. 
Trying to clear cache, disable plugins and change theme didn't help. 
Trying to revert to the 2.10v from the Dashboard threw other errors. 
This happened to all websites that were updated yesterday. 

One of the affected websites is a live site, therefore only a backup restore helped bringing it up and running. 
(the Elementor version on the backup is 2.10 and WP 5.5)

Opened a ticket with Elementor, still no response.

**Comment by DenisFlorin** [comment]
I have the same problem, my site is broken now after the last update....

**Comment by qwik3r** [comment]
Also had to revert my site back to a backup because using Elementor tools to go back to 3.0 messed the site up. When I would save a post it would say "error updating - view elementor logs" (something like that). So obviously the upgrade tweaks something in the database and downgrading doesn't reverse that.

**Comment by shilo-ey** [comment]
Please set in your `wp-config.php` the following parameters:
```
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG', true );
define( 'SCRIPT_DEBUG', true );
define( 'CONCATENATE_SCRIPTS', false );
```

And share the specific error.

Thanks

**Comment by qwik3r** [comment]
> Please set in your `wp-config.php` the following parameters:
> 
> ```
> define( 'WP_DEBUG_LOG', true );
> define( 'WP_DEBUG', true );
> define( 'SCRIPT_DEBUG', true );
> define( 'CONCATENATE_SCRIPTS', false );
> ```
> 
> And share the specific error.
> 
> Thanks

Doing this doesn't show any new information or errors. The error is in the console and I already shared it with the link in my OP, so check there.

**Comment by gsusI** [comment]
+1

Elementor - 3.0.3
Elementor Pro - 3.0.1

**Comment by mavericksthinker** [comment]
I am getting this same error after updating to Elementor : 3.0.3

Revering back to Elementor : 2.9.14 Elementor Pro :  2.10.3 and regenerating css didnt help. Is there any proper fix or workaround for this.
<img width="337" alt="Screen Shot 2020-08-28 at 11 09 19 AM" src="https://user-images.githubusercontent.com/38578359/91520235-fc55e600-e91e-11ea-8909-c197c425af5e.png">

**Comment by Zymeth** [comment]
I have the same problem

**Comment by PuxianAlHazred** [comment]
same probleme

**Comment by thegonnalive** [comment]
**To clarify, here I'm copy pasting the console log:** 

Uncaught TypeError: Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'.
    at _default.setElementInViewportObserver (VM19 frontend.js:4499)
    at _default.__construct (VM19 frontend.js:4482)
    at init (frontend-modules.js:4989)
    at _default.Module (frontend-modules.js:5126)
    at new child (frontend-modules.js:5144)
    at _default._createSuperInternal (VM19 frontend.js:171)
    at new _default (VM19 frontend.js:4467)
    at _default._createSuperInternal (VM19 frontend.js:171)
    at new _default (VM19 frontend.js:7436)
    at Object.<anonymous> (VM19 frontend.js:7311)
setElementInViewportObserver @ VM19 frontend.js:4499
__construct @ VM19 frontend.js:4482
init @ frontend-modules.js:4989
Module @ frontend-modules.js:5126
child @ frontend-modules.js:5144
_createSuperInternal @ VM19 frontend.js:171
_default @ VM19 frontend.js:4467
_createSuperInternal @ VM19 frontend.js:171
_default @ VM19 frontend.js:7436
(anonymous) @ VM19 frontend.js:7311
each @ jquery.js:2
runInteractions @ VM19 frontend.js:7310
onInit @ VM19 frontend.js:7387
Module.trigger @ frontend-modules.js:5111
self.<computed> @ frontend-modules.js:4974
init @ frontend-modules.js:4993
Module @ frontend-modules.js:5126
child @ frontend-modules.js:5144
_createSuperInternal @ VM19 frontend.js:171
_default @ VM19 frontend.js:7168
activate @ VM19 frontend.js:7029
(anonymous) @ VM19 frontend.js:7054
toggle @ VM19 frontend.js:7046
(anonymous) @ frontend.js:6325
self.<computed> @ frontend-modules.js:4974
dispatch @ jquery.js:3
r.handle @ jquery.js:3

**These typo errors come from:** 
wp-content/plugins/elementor-pro/assets/js/frontend.js
wp-content/plugins/elementor/assets/js/frontend-modules.js
wp-includes/js/jquery/jquery.js 

**These two can be seen in Elementor -> System info:** 
JS: 2020-08-27 15:39:08 [error X 2][https://en.xaradesign.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.1:2:469692] Cannot read property \'document\' of undefined 
JS: 2020-08-27 18:01:35 [error X 54][https://en.xaradesign.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.0.1:2:46559] Failed to execute \'observe\' on \'IntersectionObserver\': parameter 1 is not of type \'Element\'.  

Now, here is a website you can use to test on the Console and replicate the problem: en.xaradesign.com 
This one is where the vertical scrolling doesn't work and sections are missing on front end. 
And I confirm as well, adding the debug in wp-config didn't show anything new.

**Comment by gsusI** [comment]
Hey, @shilo-ey , seems that we're quite a few people affected by this bug. 

What feedback/information is needed? Is there any way we could help getting this fix? 

This bug is kind of a dealbreaker...

**Comment by qwik3r** [comment]
Maybe now they'll officially acknowledge it.

**Comment by adverman** [comment]
Same here!

**Comment by gsusI** [comment]
Enabling "Optimized DOM Output" and using "Empty Cache and Hard Reload" in Chrome fixes the issue for me. 

My settings look like this:
![image](https://user-images.githubusercontent.com/4558016/91623899-60b38c80-e995-11ea-8560-06ffbb6d6f3d.png)

**Comment by thegonnalive** [comment]
This worked for me as well,  Thank you for sharing!!!

**Comment by qwik3r** [comment]
> Enabling "Optimized DOM Output" and using "Empty Cache and Hard Reload" in Chrome fixes the issue for me.
> 
> My settings look like this:
> ![image](https://user-images.githubusercontent.com/4558016/91623899-60b38c80-e995-11ea-8560-06ffbb6d6f3d.png)

So this fixed the frontend.min.js errors you were receiving?

**Comment by gsusI** [comment]
> > Enabling "Optimized DOM Output" and using "Empty Cache and Hard Reload" in Chrome fixes the issue for me.
> > My settings look like this:
> > ![image](https://user-images.githubusercontent.com/4558016/91623899-60b38c80-e995-11ea-8560-06ffbb6d6f3d.png)
> 
> So this fixed the frontend.min.js errors you were receiving?

In my case it does solve them (I was seeing the error with the observable)

**Comment by portrayaloflife** [comment]
Same issues here, tons of errors. Looks fine in editor but not in front end

![image](https://user-images.githubusercontent.com/24360965/91644199-8c6b5c80-e9ff-11ea-9b24-29a0143a418e.png)

**Comment by qwik3r** [comment]
> Same issues here, tons of errors. Looks fine in editor but not in front end
> 
> ![image](https://user-images.githubusercontent.com/24360965/91644199-8c6b5c80-e9ff-11ea-9b24-29a0143a418e.png)

Did you try what @gsusI did? I haven't yet but curious if it's a relevant fix. 

I have no confidence in what Elementor is doing about this. It's been largely silent but it's quite obvious that there are a nUMBER of people having issues with this specifically, in addition to the multitude of other oddities. Perhaps it can all be traced back to one javascript issue hopefully.

**Comment by gsusI** [comment]
Quick note, although I got to the point where by changing _"Optimized DOM Output"_ I could enable/disable the error, before that I followed the troubleshooting they published in their FAQs

[Elementor 3.0 troubleshooting](https://docs.elementor.com/article/677-faq-for-elementor-3-0)

**Comment by shilo-ey** [comment]
This issue has been fixed - it's related to the motion effects when are set on Column element, when Optimized DOM is disabled.

A patch will release soon

Thanks!

**Comment by portrayaloflife** [comment]
Can some better explain this whole Optimized Dom being enabled or disabled? Are we suppose to enable it? I feel like it's gonna lead to more bugs down the road.

**Comment by qwik3r** [comment]
I'm also interested in more info about Optimized Dom setting, and if we are to re-enable it after the next patch.

**Comment by drawcard** [comment]
Here's some information about Optimised DOM output: https://docs.elementor.com/article/673-what-is-the-optimized-dom?utm_source=settings&utm_campaign=learn&utm_medium=wp-dash

And a deeper breakdown of what is optimised (removed) when enabling it: https://developers.elementor.com/dom-improvements-ahead-html-wrappers-removal-from-v3-0/

Basically if you used Elementor pre-3.0, the page elements would have had a lot of DIV wrappers that are now redundant moving forward. If you choose to optimise the DOM on those sites, it will remove those wrappers, and clean up the DOM output for page layout.

In my case I discovered that this also affects CSS classes (eg. if you had written a class to target a particular wrapper class, which no longer exists). So some refactoring is required on your CSS stylesheets if that's the case. A good lesson, to get in the habit of writing unique CSS classes for any element you want to target (rather than relying on general purpose DOM element classes). 

And, another good lesson, read https://developers.elementor.com/ before upgrading major releases...!

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.5 and Elementor Pro v3.0.2

Feel free to update

Thanks!

**Comment by drawcard** [comment]
HI @shilo-ey 

I can confirm the issue is still occurring after updating (WP 5.5.1, E 3.0.5, E Pro 3.0.3)

![image](https://user-images.githubusercontent.com/1435638/92318480-db427300-f04b-11ea-8091-bf2e50b4b9d4.png)

**Comment by qwik3r** [comment]
I'm fully updated to 3.06 and Pro: but getting this error in the console while in the editor. 

![Screen Shot 2020-09-07 at 5 46 04 PM](https://user-images.githubusercontent.com/421637/92417787-043d3380-f132-11ea-80ee-36776800612c.png)

**Comment by qwik3r** [comment]
I'm experiencing global colors not always working on the front end. In some instances they do, others they do not. I have to click on the color swatch and change the color for it to show. I think I read somewhere that people were experiencing similar issue? Is Elementor aware of this? I am fully updated btw.

**Comment by codevu** [comment]
Updated to the latest 3.0.7 and still getting the frontend js error... 

![elementor frontend](https://user-images.githubusercontent.com/32885675/92629405-20041f00-f283-11ea-81f3-2a2e2900c070.jpg)

**Comment by qwik3r** [comment]
I like how this was closed when people are still getting errors! Open it up again!!!

**Comment by shilo-ey** [comment]
This issue is resolved. the described issues are most likely due to server cache.

Please try to delete Elementor, clear cache and re-install it.

Thanks

**Comment by dalmasonto** [comment]
> Enabling "Optimized DOM Output" and using "Empty Cache and Hard Reload" in Chrome fixes the issue for me.
> 
> My settings look like this: ![image](https://user-images.githubusercontent.com/4558016/91623899-60b38c80-e995-11ea-8560-06ffbb6d6f3d.png)

It just worked! Just opening it a new tab the elementor frontend js problems were fixed
