### ISSUE TITLE
Elementor Data Updater Issue ( v3.0.3 )

### ISSUE THREAD

**Issue by chkserv** [elementor/elementor#12305]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

The following notice is stuck since 3.0.3
Elementor Data Updater – Database update process is running in the background.

When " Click here to run it now " it then give a error: There has been a critical error on your website.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I've rolled back versions and re-updated and the message still visible.

## Environment

WP: 5.5
PHP: 7.4.5

**Comment by PeterHolscher** [comment]
Exactly the same with my installation.

**Comment by PeterHolscher** [comment]
![Elementor2](https://user-images.githubusercontent.com/48182946/91646973-75eff000-ea55-11ea-8a06-0229fd625836.png)
![Elementor3](https://user-images.githubusercontent.com/48182946/91647011-fb73a000-ea55-11ea-8bc8-4ec122c7e544.png)
Would you please tell me what to do about this. Or will this problem be solved in an update in the next few days?

**Comment by torpix** [comment]
I’ve tried lots of things and no luck, so I say it’s a bug.

**Comment by PeterHolscher** [comment]
Yeah, wait and see.
Forgot to mention that downgrading to previous versions neither didn't help. Also tried everything. Tired now, after two days.

**Comment by shilo-ey** [comment]
@torpix Can you please share your system info log file? you can find it under Elementor > System info

**Comment by PeterHolscher** [comment]
[system-info-www.area-composer.de-30-08-2020.txt](https://github.com/elementor/elementor/files/5146662/system-info-www.area-composer.de-30-08-2020.txt)
Sure, here it is.
Thank your for the reply
Peter

**Comment by torpix** [comment]
This is a clients site of mine with the issue.
					
== Server Environment ==
	Operating System: Linux
	Software: Apache 2.4.25
	MySQL version: mariadb v10.3.21
	PHP Version: 7.4.5
	PHP Max Input Vars: 3000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5
        WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 256M

== Theme ==
	Name: SuperMagPro Child
	Version: 3.0.2.1592606285
	Author: acmethemes
== Log ==
	
2020-08-30 11:22:14 [info] elementor::elementor_updater Started 
2020-08-30 11:22:14 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-08-30 11:22:14 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-08-30 11:22:14 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-08-30 11:22:14 [notice] System colors are disabled. nothing to do. 
2020-08-30 11:22:14 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-08-30 11:22:14 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-08-30 11:47:12 [info] elementor::elementor_updater Started 
2020-08-30 11:47:12 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-08-30 11:47:12 [notice] General Settings already exist. nothing to do. 
2020-08-30 11:47:12 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-08-30 11:47:12 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-08-30 11:47:12 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-08-30 11:47:12 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-08-30 11:53:57 [info] elementor::elementor_updater Started 
2020-08-30 11:53:57 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-08-30 11:53:57 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-08-30 11:53:57 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-08-30 11:53:57 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-08-30 11:53:57 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
PHP: showing 1 of 1

PHP: 2020-08-30 11:14:16 [error X 5][/public_html/wp-content/plugins/elementor/core/upgrade/upgrades.php::803] Uncaught Error: Call to undefined method Elementor\Core\DocumentTypes\Post::add_repeater_row() in /public_html/wp-content/plugins/elementor/core/upgrade/upgrades.php:803
Stack trace:
#0 /public_html/wp-content/plugins/elementor/core/upgrade/upgrades.php(883): Elementor\Core\Upgrade\Upgrades::Elementor\Core\Upgrade\{closure}()
#1 /public_html/wp-content/plugins/elementor/core/upgrade/upgrades.php(811): Elementor\Core\Upgrade\Upgrades::move_settings_to_kit()
#2 [internal function]: Elementor\Core\Upgrade\Upgrades::_v_3_0_0_move_saved_colors_to_kit()
#3 /public_html/wp-content/plugins/elementor/core/base/background-task.php(277): call_user_func()
#4 /public_html/wp-content/plugins/elementor/core/base/background-task.php(181): Elementor\Core\Base\Background_Task->task()
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by PeterHolscher** [comment]
Updated to Elementor 3.0.4, didn't change the situation. I'm afraid updating Elementor will not help, because it seems to be a problem with Elementor Pro. When I deactivate Pro, it's fine, but no final solution of course.

**Comment by torpix** [comment]
@PeterHolscher Thats strange. My client's site isn't using Elementor Pro ( just the free one )

**Comment by PeterHolscher** [comment]
Yes, can be, I'm not sure. I really have no idea what's wrong there. I have tons of errors in the Elementor system log file. Thanks god I could solve the problems I had with my site circumventing them by not using Elementor's features, but simple CSS. My client didn't even notice :-) Now I'm waiting ...

I have some more clients sites, using only the free version, no problems there. Next time I will be a bit more patient updating major versions, I'll be checking the forums first. 

But your'e absolutely right, that's strange!

**Comment by chkserv** [comment]
Elementor Data Updater – Database update process is running in the background. ( still stuck ) in 3.0.5

Anyone from Elementor suggest anything I can do / check? I've rolled back to previous versions ( then it disappears )
then soon as I re-upgrade to the latest 3.0.x version it re-appears and stays.

**Comment by PeterHolscher** [comment]
The same in my installation :-(

**Comment by chkserv** [comment]
Done a Debug ( with no plugins active - only Elementor ) this is what returned.

[31-Aug-2020 16:03:20 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method Elementor\Core\DocumentTypes\Post::add_repeater_row() in /public_html/wp-content/plugins/elementor/core/upgrade/upgrades.php:803
Stack trace:
#0 /public_html/wp-content/plugins/elementor/core/upgrade/upgrades.php(924): Elementor\Core\Upgrade\Upgrades::Elementor\Core\Upgrade\{closure}()
#1 /public_html/wp-content/plugins/elementor/core/upgrade/upgrades.php(811): Elementor\Core\Upgrade\Upgrades::move_settings_to_kit()
#2 [internal function]: Elementor\Core\Upgrade\Upgrades::_v_3_0_0_move_saved_colors_to_kit()
#3 /public_html/wp-content/plugins/elementor/core/base/background-task.php(277): call_user_func()
#4 /public_html/wp-content/plugins/elementor/core/base/background-task.php(181): Elementor\Core\Base\Background_Task->task()
#5 /public_html/wp-content/plugins/elementor/core/upgrade/upgrades.php on line 803

**Comment by bootmintheme** [comment]
Same for me, I have a few plugins installed, but it happens with or without those plugins and have been happening even though Elementor and Elementor Pro was the first plugins i installed. Please fix.

[system-info-31-08-2020.txt](https://github.com/elementor/elementor/files/5152577/system-info-31-08-2020.txt)

**Comment by PeterHolscher** [comment]
Every Update installed, including the Jet Elements. The issue still remains:
![Elementor-issue](https://user-images.githubusercontent.com/48182946/91827482-34bb3400-ec3f-11ea-9c39-08be1a95061b.png)
Here is the latest System Info:
[system-info-www.area-composer.de-01-09-2020(1).txt](https://github.com/elementor/elementor/files/5154919/system-info-www.area-composer.de-01-09-2020.1.txt)

**Comment by chkserv** [comment]
Updated the patch for WordPress ( 5.5.1 )
Running the latest version of elementor and still got the same issue.

**Comment by cc-ross** [comment]
I'm running into the same issue on both a local and production site.

Elementor version 3.0.5 / Elementor Pro version 3.0.2

I also tried firing up WP CLI and tried to run the Elementor database update from there for a more in-depth error message.

Here's what happened:

<img width="1046" alt="Screenshot 2020-09-02 at 12 16 59" src="https://user-images.githubusercontent.com/70703023/92116820-4130bf80-edec-11ea-9552-76185f4dd856.png">

**Comment by chkserv** [comment]
Just tried the exact same cmd and got the same result.

/elementor/core/upgrade/upgrades.php on line 803

**Comment by miaosun** [comment]
Have the exact same problem with elementor 3.0.x, I also have elementor pro installed, but it seems it's related to the free version. Sent a support ticket 10 days ago, haven't got any reply yet.

**Comment by rodolphebertozzo** [comment]
Hi, I saw that version 3.0.6 normally fixed this problem, except that this PR is not merged, is that normal? @shilo-ey

**Comment by shilo-ey** [comment]
[**@Rodolphe Bertozzo**](https://github.com/rodolphebertozzo) commented on [Sep 6, 2020, 6:36 PM GMT+3](https://github.com/elementor/elementor/issues/12305#issuecomment-687821947 "2020-09-06T15:36:37Z - Replied by Github Reply Comments"):
> Hi, I saw that version 3.0.6 normally fixed this problem, except that this PR is not merged, is that normal? @shilo-ey

Hi @rodolphebertozzo, we did resolve a part of the issue, but we will release another patch with a fix for this issue later this week.

Elementor v3.0.6 reduces conflicts with other plugins (such as Hubspot for WooCommerce) and reduces occurrences of server overload.

Thanks

**Comment by Stretto74** [comment]
i have the same issue I've tried all versions from of new v3 and even rolled back to before 2.9. I'm on Pro. have even tried uninstall and reinstall. Elementor test team fail. if you want my error logs happy to list them but let please explain how.

**Comment by chkserv** [comment]
@Stretto74 I believe it will be fixed in Elementor 3.0.7

**Comment by cc-ross** [comment]
Fingers crossed!

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.7

Feel free to update

Thanks!

**Comment by cc-ross** [comment]
It works! Thank you guys 👍

**Comment by PeterHolscher** [comment]
Yessss, it's done! Thanks!

**Comment by demsone** [comment]
Yeah nah still getting same errors after 3.0.7 update

**Comment by bootmintheme** [comment]
Mine worked, THANK YOU - "Elementor Data Updater – The database update process is now complete. Thank you for updating to the latest version!"

**Comment by balynna** [comment]
I have updated Elementor and Elementor Pro, still having this issue. Theme OceanWP. What would you recommend?

**Comment by chkserv** [comment]
@balynna 

( Backup your site first ) Roll Elementor back to 2.9.9 then re update to the latest version 3.0.9

Elementor > System > Tools > Version Control

If you've tried that and no luck, then click Rerun Update Script.

**Comment by rilofree** [comment]
We have had this message showing up on our site since last year around the 2.7.1 update we think. 

Nothing we try fixes it and it has persisted through all the updates since then including the most recent update of 3.0.15. This is on a site running OceanWP, but it is quite clear this has been an ongoing issue for quite a long long time and not just with OceanWP sites.

Any movement on this would be much appreciated.

**Comment by nadworks** [comment]
Just started getting it - literally only plugin is Elementor and Elementor Pro. Would appreciate a fix.

**Comment by chkserv** [comment]
@nadworks try and roll back to the previous version and then re-do the update, hopefully it will work

**Comment by frankomator** [comment]
I've found the problem on two production sites recently. Looking at the error log in the Elementor System Info it seems to be a conflict with the installed SEOPress plugin. I've deactivated SEOPress (temporarily) and pushed the button to run the Elementor Data Updater. Success, this solved the problem on both installations for me. So I would recommend to check for incompatibilites with other plugins first.

**Comment by rilofree** [comment]
> 
> 
> . . . I would recommend to check for incompatibilites with other plugins first . . .

Good suggestion. I will try that the next time I encounter this issue.

Thank you

**Comment by manislyseals** [comment]
I have the same problem. When I update Elementor Pro from V.3.2.2 to V.3.3.0, the message “Database update process is running in the background. Will it take a while?” Appears. This does not go away. Here is my log:

== Log ==
	
Log: showing 20 of 342021-07-26 21:55:40 [info] elementor-pro::elementor_pro_updater Started 
2021-07-26 21:55:40 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start (x2) 
2021-07-26 22:03:06 [info] elementor-pro::elementor_pro_updater Started 
2021-07-26 22:03:06 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start (x2) 
2021-07-26 22:39:27 [info] elementor-pro::elementor_pro_updater Started 
2021-07-26 22:39:27 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start (x2) 
2021-07-26 22:44:39 [info] elementor-pro::elementor_pro_updater Started 
2021-07-26 22:44:39 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start (x2) 
2021-07-26 23:10:59 [info] elementor-pro::elementor_pro_updater Started 
2021-07-26 23:10:59 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start (x2) 
2021-07-26 23:24:38 [info] elementor-pro::elementor_pro_updater Started 
2021-07-26 23:24:38 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start (x2) 
2021-07-26 23:25:39 [info] elementor-pro::elementor_pro_updater Started 
2021-07-26 23:25:39 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start (x2) 
2021-07-26 23:42:38 [info] elementor-pro::elementor_pro_updater Started 
2021-07-26 23:42:38 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start (x2) 
2021-07-27 04:55:25 [info] elementor-pro::elementor_pro_updater Started 
2021-07-27 04:55:25 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start (x2) 
2021-07-27 06:24:08 [info] elementor-pro::elementor_pro_updater Started 
2021-07-27 06:24:08 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start (x2) 

PHP: showing 8 of 8PHP: 2021-07-06 13:32:45 [error X 3][/home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor/includes/managers/elements.php::68] Uncaught TypeError: Argument 1 passed to Elementor\Elements_Manager::create_element_instance() must be of the type array, string given, called in /home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor/core/base/document.php on line 811 and defined in /home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor/includes/managers/elements.php:68
Stack trace:
#0 /home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor/core/base/document.php(811): Elementor\Elements_Manager->create_element_instance('1172a25f')
#1 /home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(461): Elementor\Core\Base\Document->get_elements_raw_data(Array, false)
#2 /home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor/modules/usage/module.php(567): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_elements_raw_data(Array)
#3 /home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/e [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-07-08 06:01:08 [notice X 1][/home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-07-26 21:42:48 [error X 13][/home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor-pro/modules/forms/submissions/data/endpoints/index.php::10] Uncaught Error: Class 'ElementorPro\Data\Base\Endpoint' not found in /home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor-pro/modules/forms/submissions/data/endpoints/index.php:10
Stack trace:
#0 /home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor-pro/plugin.php(141): include()
#1 [internal function]: ElementorPro\Plugin->autoload('ElementorPro\\Mo...')
#2 /home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor/data/base/controller.php(206): spl_autoload_call('ElementorPro\\Mo...')
#3 /home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor-pro/modules/forms/submissions/data/controller.php(266): Elementor\Data\Base\Controller->register_endpoint('ElementorPro\\Mo...')
#4 /home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor/data/base/controller.php(260): ElementorPro\Modules\Forms\Submissions\Data\Controller->register_internal_endpoints()
#5 /home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor-pro/m [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-07-26 21:44:37 [error X 14][/home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor/includes/managers/elements.php::68] Uncaught TypeError: Argument 1 passed to Elementor\Elements_Manager::create_element_instance() must be of the type array, string given, called in /home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor/core/base/document.php on line 826 and defined in /home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor/includes/managers/elements.php:68
Stack trace:
#0 /home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor/core/base/document.php(826): Elementor\Elements_Manager->create_element_instance('1172a25f')
#1 /home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(461): Elementor\Core\Base\Document->get_elements_raw_data(Array, false)
#2 /home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor/modules/usage/module.php(567): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_elements_raw_data(Array)
#3 /home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/e [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-07-26 21:46:15 [notice X 3][/home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor-extras/modules/display-conditions/module.php::226] Undefined index: ee_condition_operator [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-07-26 21:51:26 [notice X 1][/home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor-pro/modules/forms/classes/recaptcha-v3-handler.php::101] Undefined index: recaptcha_badge [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-07-27 06:24:56 [notice X 1][/home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor-pro/license/updater.php::83] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-07-27 09:00:36 [error X 2][/home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor/includes/managers/elements.php::68] Uncaught TypeError: Argument 1 passed to Elementor\Elements_Manager::create_element_instance() must be of the type array, string given, called in /home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor/core/base/document.php on line 826 and defined in /home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor/includes/managers/elements.php:68
Stack trace:
#0 /home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor/core/base/document.php(826): Elementor\Elements_Manager->create_element_instance('1172a25f')
#1 /home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(427): Elementor\Core\Base\Document->get_elements_raw_data(Array, false)
#2 /home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/elementor/modules/usage/module.php(567): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_elements_raw_data(Array)
#3 /home/irugumeh/www/elearning.musik-aktiv.ch/wp-content/plugins/e [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by da-022412** [comment]
Getting the same issue with Elementor v3.6.0+ only installed.

2022-04-08 15:10:42 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-08 15:14:30 [info] elementor::elementor_updater Started 
2022-04-08 15:14:30 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-08 15:17:30 [info] elementor::elementor_updater Started 
2022-04-08 15:17:30 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-08 15:19:19 [info] elementor::elementor_updater Started 
2022-04-08 15:19:19 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-08 15:24:17 [info] elementor::elementor_updater Started 
2022-04-08 15:24:17 [info] Elementor/Upgrades - _on_each_version Start  
2022-05-06 12:30:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-05-06 12:30:59 [info] elementor-pro::elementor_pro_updater Started 
2022-05-06 12:30:59 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-05-06 12:30:59 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-05-06 12:30:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-05-06 12:31:13 [info] elementor::elementor_updater Started 
2022-05-06 12:31:13 [info] Elementor/Upgrades - _on_each_version Start  
2022-05-06 12:56:19 [info] elementor::elementor_updater Started 
2022-05-06 12:56:19 [info] Elementor/Upgrades - _on_each_version Start  
2022-05-06 13:03:06 [info] elementor::elementor_updater Started 
2022-05-06 13:03:06 [info] Elementor/Upgrades - _on_each_version Start

**Comment by derrickmg** [comment]
This issue is still happening for me on 3.11.5.
As described above it will still occur with Just elementor activated and no other plugins and with a default theme.


Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | LiteSpeed |  
MySQL version: | MariaDB Server v10.5.19 |  
PHP Version: | 7.4.33 |  
PHP Memory Limit: | 2048M |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 2G |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected |  

</div>
</body>
</html>Server Environment		
Operating System:	Linux	
Software:	LiteSpeed	
MySQL version:	MariaDB Server v10.5.19	
PHP Version:	7.4.33	
PHP Memory Limit:	2048M	
PHP Max Input Vars:	1000	
PHP Max Post Size:	2G	
GD Installed:	Yes	
ZIP Installed:	Yes	
Write Permissions:	All right	
Elementor Library:	Connected	
WordPress Environment		
Version:	6.1.1	
Site URL:	https://cegcoaching.com/cegDEV	
Home URL:	https://cegcoaching.com/cegDEV	
WP Multisite:	No	
Max Upload Size:	64 MB	
Memory limit:	40M	
Max Memory limit:	2048M	
Permalink Structure:	/%postname%/	
Language:	en-US	
Timezone:	0	
Admin Email:	admin@avidcreation.com	
Debug Mode:	Inactive	
Theme		
Name:	Twenty Twenty-Three	
Version:	1.0	
Author:	the WordPress team	
Child Theme:	No	If you want to modify the source code of your theme, we recommend using a [child theme](https://go.elementor.com/wordpress-child-themes/).
User		
Role:	administrator	
WP Profile lang:	en_US	
User Agent:	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

**Comment by bluestarstudios** [comment]
For anyone else still having this issue, you have to go to the Elementor –> Tools page, and on the "General" tab you will most likely find a "Recreate Kit" button. This means that an active default kit was never created by Elementor. Once you click do this, you'll be able to run the Database update without any issues. Hope this helps!

**Comment by tobiolusa** [comment]
I am still facing the issue and recreated the kit, but it was not resolved.

**Comment by hitjethva** [comment]
I am using the Elementor pro 3.13.3 version and still facing the same issue. Let me know if anyone has a solution for this bug.
