### ISSUE TITLE
Remove autogenerated screenshots of templates from Media Library (Still happening in Pro 3.0.1)

### ISSUE THREAD

**Issue by MichaelDarko** [elementor/elementor#12304]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Problem
I opened an issue #12300 about removing the autogenerated Theme Builder screenshots from the Media Library, but it was quickly closed because the problem is solved in the Pro 3.0.1 version. But it isn't, so I'm opening a new issue.

My previous issue was related to the 3.0.1 version. I updated from 2.(something) directly to the 3.0.1 and the screenshot problem is still there.

## Steps to reproduce

- After updating to 3.0.1 autogenerated screenshots are added to Media Library.
- Deleting the screenshots results in Theme Builder displaying "missing image" icon.
- Editing the template regenerates the screenshot and it's again added into the media library.

The behavior is a bit weird because the Theme Builder is pulling the images from /wp-content/uploads/elementor/screenshots/, but these images somehow disapear from the Theme Builder when you delete them form the Media Library and appear in the Media Library when they are regenerated.

It seems you might've tweaked the location of the images to /wp-content/uploads/elementor/screenshots/ in the 3.0.1 update, but the connection to the media library is somehow still there.

-> Or maybe you tried to exclude these images from the Media Library but this only resulted in image files now being displayed as "blank" files without thumbnails in the library. (See the screenshot in #12300)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>	</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Ubuntu 18.04 v5.6.46-86.2
	PHP Version: 7.2.31-1+ubuntu18.04.1+deb.sury.org+1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5
	Site URL: https://moneyworld.cz
	Home URL: https://moneyworld.cz
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: cs
	Timezone: Europe/Prague
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: cs_CZ
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36

== Active Plugins ==
	All-in-One WP Migration
		Version: 7.26
		Author: ServMask

	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Code Snippets
		Version: 2.14.0
		Author: Code Snippets Pro

	Elementor
		Version: 3.0.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.1
		Author: Elementor.com

	JetBlog For Elementor
		Version: 2.2.9
		Author: Crocoblock

	Limit Login Attempts Reloaded
		Version: 2.15.1
		Author: WPChef

	WP In Post Ads
		Version: 1.2.2
		Author: MyThemeShop


== Must-Use Plugins ==
	installatron_hide_status_test.php
		Version: 
		Author: 


== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		posts : 1
		shortcode : 1
		theme-archive-title : 1
	footer : 2
		form : 1
		heading : 4
		icon : 1
		text-editor : 1
		wp-widget-nav_menu : 1
	header : 1
		image : 1
		nav-menu : 1
		search-form : 1
		social-icons : 1
	page : 1
		heading : 4
		icon-list : 1
	popup : 1
		button : 1
		heading : 1
	section : 1
		heading : 1
		posts : 2
		shortcode : 1
	single : 4
		button : 1
		heading : 3
		post-info : 3
		posts : 4
		share-buttons : 2
		shortcode : 5
		theme-post-content : 3
		theme-post-featured-image : 1
		theme-post-title : 3
	wp-page : 2
		heading : 5
		icon-list : 1
		jet-blog-smart-tiles : 1
		posts : 2
		shortcode : 1


== Log ==
	
Log: showing 15 of 152020-07-21 21:14:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.2',
  'to' => '2.10.3',
)]
2020-08-28 11:47:44 [info] elementor::elementor_updater Started 
2020-08-28 11:47:44 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-08-28 11:47:44 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-08-28 11:47:44 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-08-28 11:47:44 [notice] System colors are disabled. nothing to do. 
2020-08-28 11:47:44 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-08-28 11:47:44 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-08-28 11:47:44 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-08-28 11:47:44 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-08-28 11:47:44 [notice] System typography is disabled. nothing to do. 
2020-08-28 11:47:44 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-08-28 11:47:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.3',
)]
2020-08-28 11:47:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.3',
)]
2020-08-28 11:47:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.3',
  'to' => '3.0.1',
)]

PHP: showing 3 of 3PHP: 2020-07-22 01:03:58 [notice X 9][/data/web/virtuals/202311/virtual/www/domains/magazin.mbdemo.cz/wp-content/plugins/elementor-pro/modules/posts/widgets/posts.php::31] Undefined index: posts_post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-08 17:57:46 [notice X 3][/data/web/virtuals/202311/virtual/www/domains/magazin.mbdemo.cz/wp-content/plugins/elementor/includes/template-library/sources/local.php::692] ob_end_clean(): failed to delete buffer. No buffer to delete [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-28 11:48:45 [notice X 11][/var/www/hosting/moneyworld.cz/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2020-08-18 13:55:43 [error X 1][https://magazin.mbdemo.cz/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view426\") has already been destroyed and cannot be used. 
JS: 2020-08-18 14:00:05 [error X 1][https://magazin.mbdemo.cz/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view2631\") has already been destroyed and cannot be used. 
JS: 2020-08-27 13:21:52 [error X 1][https://moneyworld.cz/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view295\") has already been destroyed and cannot be used. 
JS: 2020-08-27 13:28:02 [error X 4][https://moneyworld.cz/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.14:31:89241] Cannot read property \'value\' of undefined 
JS: 2020-08-27 13:28:07 [error X 22][https://moneyworld.cz/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:4698] Cannot read property \'match\' of undefined 


				
</details>

**Comment by MichaelDarko** [comment]
Now tested on other sites. Happening everywhere.

**Comment by black-eye** [comment]
+1
Previews still in the library.

**Comment by fabianenzensperger** [comment]
3.0.3 still there.

**Comment by fabianenzensperger** [comment]
Core 3.0.5 + Pro 3.0.3 still there …

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.0.4

Feel free to update

Thanks!

**Comment by aureliePrd** [comment]
Hi @shilo-ey ! Can we manually delete all the autogenerated screenshots of templates from Media Library ? Thank you very much

**Comment by Jarpiino** [comment]
Issue is still here as of elementor 3.5.4 & elementor pro 3.5.2.

**Comment by fabianenzensperger** [comment]
> Issue is still here as of elementor 3.5.4 & elementor pro 3.5.2.
> I really don't know how this can be marked as solved.

I don't know, so it was solved for me a long time ago. Since 3.1 or 3.2 😊

**Comment by klitsios** [comment]
Still having the same problem with both **Elementor v3.17.3** and **Elementor Pro v3.17.1** installed

**Comment by danielvigh** [comment]
I'm having the same problem with **Elementor v3.18.3** and **Elementor Pro v3.18.2**.

**Comment by krlabs** [comment]
The same issue. Today, I accidentally saw a mysterious folder /elemenor in my wordpress uploads folder, and in it folder /screenshots... I don't know who made this feature and why?

**Comment by klitsios** [comment]
Got tired of waiting for a fix, so I switched all my projects to Bricks and canceled my Elementor Pro subscription.

**Comment by robhozio** [comment]
Elementor 3.33.0 / Elementor Pro 3.10.2
I had this issue with my image sitemap, had this one elementor screenshot in it. I cleared cache, elementor cache, cloudflare cache, clean transients, checked the screenshots folder and found nothing. I found and deleted it from wp_postmeta data in the db and then checked the db some more, nothing found. Still didn't remove it. So, i rewrote the image sitemap that I made to ignore elementor screenshots from anywhere on the website or db.

It's still technically somewhere but not going be found as a 404 by anything anymore.
