### ISSUE TITLE
Uncaught TypeError: Cannot read property ‘getEditModel’ of null when editing a page with Elementor

### ISSUE THREAD

**Issue by shaneonabike** [elementor/elementor#12385]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

Basically, after the latest update and latest WP update it seems that Elementor Pro is throwing nasty little bug. The only resolution is to actually rollback the plugin to 2.9.9

`Uncaught TypeError: Cannot read property ‘getEditModel’ of null
at addCustomCss (elementor-custom-css.js?ver=1.9.1:13)
at _runHook (editor.min.js?ver=3.0.1:2)
at Object.applyFilters (editor.min.js?ver=3.0.1:2)
at child.addStyleToDocument (editor.min.js?ver=3.0.1:2)
at child.e.each.r.<computed> [as addStyleToDocument] (common-modules.min.js?ver=3.0.1:2)
at _default.renderGlobalsDefaultCSS (editor.min.js?ver=3.0.1:2)
at Editor.<anonymous> (editor.min.js?ver=3.0.1:2)
at p (load-scripts.php?c=1&load[chunk_0]=underscore,shortcode,utils,jquery,backbone,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jquery-ui-core,jquery-u&load[chunk_1]=i-widget,jquery-ui-mouse,jquery-ui-sortable&ver=5.5:14)
at f (load-scripts.php?c=1&load[chunk_0]=underscore,shortcode,utils,jquery,backbone,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jquery-ui-core,jquery-u&load[chunk_1]=i-widget,jquery-ui-mouse,jquery-ui-sortable&ver=5.5:14)
at l (load-scripts.php?c=1&load[chunk_0]=underscore,shortcode,utils,jquery,backbone,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jquery-ui-core,jquery-u&load[chunk_1]=i-widget,jquery-ui-mouse,jquery-ui-sortable&ver=5.5:14)`

This can also be referenced here https://wordpress.org/support/topic/elementor-not-loading-anything-and-broke-my-site-error-in-code/

## Steps to reproduce

1. Download latest Pro and Elementor
2. Try to edit a page and kablam

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
``
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.14.0
	MySQL version: (Ubuntu) v5.7.31
	PHP Version: 7.2.24-0ubuntu0.18.04.6
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.1
	Site URL: http://dev.example.com
	Home URL: http://dev.example.com/fr
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 256M
	Permalink Structure: Plain
	Language: en-US
	Timezone: 0
	Admin Email: webmaster@example.com
	Debug Mode: Inactive

== Theme ==
	Name: LBGF Elementor Child
	Version: 1.0.1
	Author: Shane Bill
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.0
	Parent Theme Author: Elementor Team

== Active Plugins ==
	Advanced Custom Fields Multilingual
		Version: 1.7.3
		Author: OnTheGoSystems

	Advanced Custom Fields PRO
		Version: 5.9.0
		Author: Elliot Condon

	Custom Post Type UI
		Version: 1.8.0
		Author: WebDevStudios

	Ele Custom Skin
		Version: 3.0.0
		Author: Dudaster.com

	Elementor
		Version: 2.9.9
		Author: Elementor.com

	Elementor Pro
		Version: 2.9.4
		Author: Elementor.com

	Members
		Version: 3.1.1
		Author: MemberPress

	Sticky Header Effects for Elementor
		Version: 1.3.2
		Author: Rwattner

	UpdraftPlus - Backup/Restore
		Version: 1.16.28
		Author: UpdraftPlus.Com, DavidAnderson

	WPML Media
		Version: 2.6.0
		Author: OnTheGoSystems

	WPML Multilingual CMS
		Version: 4.4.0
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.1.0
		Author: OnTheGoSystems

	WPML Translation Management
		Version: 2.10.0
		Author: OnTheGoSystems

	Yoast SEO
		Version: 14.9
		Author: Team Yoast

	Yoast SEO Multilingual
		Version: 1.2.3
		Author: OnTheGoSystems

== Elements Usage ==
	

== Log ==
	
Log: showing 13 of 132020-09-01 14:56:43 [info] elementor::elementor_updater Started 
2020-09-01 14:56:43 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-09-01 14:56:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.8',
  'to' => '3.0.5',
)]
2020-09-01 14:56:45 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-09-01 14:56:45 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-09-01 14:56:45 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-09-01 14:56:45 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-09-01 14:56:45 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-09-01 14:56:46 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-09-01 14:56:46 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-09-01 14:56:46 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Start  
2020-09-01 14:56:46 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Finished 
2020-09-01 14:56:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.8',
  'to' => '3.0.5',
)]

JS: showing 1 of 1JS: 2020-09-02 11:46:42 [error X 8][http://dev.example.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.9.4:2:6587] Cannot read property \&#039;getEditModel\&#039; of null 

`
</details>

**Comment by keshavbhatt** [comment]
Same issue here.

**Comment by montrealks** [comment]
Same

**Comment by ashomokdev** [comment]
Same!

**Comment by shaneonabike** [comment]
Yep looks like they resolved this with the latest update between the time I posted this issue and now. I'm going to close it and indicate that updating is the key!

**Comment by merajsahebdar** [comment]
I also faced the same issue as well, but with different steps to reproduce:

## Steps to Reproduce
1. Upgrade from 2.9.9 to 3.0.10
2. Install the ElementsKit & Activate it
3. Face the error
4. Deactivate the ElementsKit
5. No Error!

## Steps to Not facing the Error
1. Rollback to 2.9.9
2. Activate ElementsKit
3. No Error!
---
Does it seem there is a compatibility issue with this addon?!!

**Comment by designinsist** [comment]
Facing issue right now, any help ?`common.min.js?ver=3.0.10:2 TypeError: Cannot read property 'model' of null
    at value (editor.min.js?ver=2.10.2:2)
    at _runHook (editor.min.js?ver=3.0.10:2)
    at Object.applyFilters (editor.min.js?ver=3.0.10:2)
    at child.addStyleToDocument (editor.min.js?ver=3.0.10:2)
    at child.e.each.r.<computed> [as addStyleToDocument] (common-modules.min.js?ver=3.0.10:2)
    at _default.renderGlobalsDefaultCSS (editor.min.js?ver=3.0.10:2)
    at Editor.<anonymous> (editor.min.js?ver=3.0.10:2)
    at Editor.<anonymous> (load-scripts.php?c=0&load[chunk_0]=underscore,jquery-core,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,wp-api-request,shortcode,utils,wp-util,wp-backbo&load[chunk_1]=ne,media-models,moxiejs,plupload,wp-plupload,jquery-ui-sortable&ver=5.5.1:10)
    at Editor.<anonymous> (load-scripts.php?c=0&load[chunk_0]=underscore,jquery-core,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,wp-api-request,shortcode,utils,wp-util,wp-backbo&load[chunk_1]=ne,media-models,moxiejs,plupload,wp-plupload,jquery-ui-sortable&ver=5.5.1:2)
    at p (load-scripts.php?c=0&load[chunk_0]=underscore,jquery-core,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,wp-api-request,shortcode,utils,wp-util,wp-backbo&load[chunk_1]=ne,media-models,moxiejs,plupload,wp-plupload,jquery-ui-sortable&ver=5.5.1:10)`

**Comment by 234578** [comment]
I have excactly the same problem as @designinsist. Elementor will not load not even in safe mode. My System:
WP: 5.5.1
PHP 7.2.24
Elementor v3.0.10
512 MB Ram for PHP
Theme Name: OceanWP Version: 1.8.9

My last Log:

```
PHP: 2020-05-29 12:35:20 [notice X 2][/var/www/vhosts/user6368/httpdocs/wordpress/wp-content/plugins/elementor/includes/template-library/sources/local.php::1032] Trying to get property 'post_type' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-06-12 12:31:36 [notice X 1][/var/www/vhosts/user6368/httpdocs/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-06-19 18:35:46 [warning X 1][/var/www/vhosts/user6368/httpdocs/wordpress/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::180] unlink(Button Almanach Leading GC.jpg): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-07-02 14:54:18 [error X 3][/var/www/vhosts/user6368/httpdocs/wordpress/wp-content/plugins/elementor/includes/managers/widgets.php::305] Uncaught Error: Call to a member function is_editable_by_current_user() on boolean in /var/www/vhosts/user6368/httpdocs/wordpress/wp-content/plugins/elementor/includes/managers/widgets.php:305
Stack trace:
#0 [internal function]: Elementor\Widgets_Manager->ajax_render_widget(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#1 /var/www/vhosts/user6368/httpdocs/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/vhosts/user6368/httpdocs/wordpress/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#3 /var/www/vhosts/user6368/httpdocs/wordpress/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#4 /var/www/vhosts/user6368/httpdocs/wordpress/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#5 /var/www/vhosts/user6368/httpdocs/wordpress/wp-admin/admin-ajax.php(17 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-09-07 13:57:02 [notice X 5][/var/www/vhosts/user6368/httpdocs/wordpress/wp-content/plugins/elementor/modules/usage/module.php::79] Undefined index: publish [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-09-17 12:11:33 [notice X 2][/var/www/vhosts/user6368/httpdocs/wordpress/wp-content/plugins/elementor/includes/managers/image.php::33] Undefined index: size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-09-29 14:19:28 [warning X 1][/var/www/vhosts/user6368/httpdocs/wordpress/wp-content/plugins/elementor-pro/core/admin/admin.php::104] Invalid argument supplied for foreach() [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-09-29 14:21:48 [notice X 3][/var/www/vhosts/user6368/httpdocs/wordpress/wp-content/plugins/elementor-pro/license/admin.php::445] Trying to get property 'email' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
JS: showing 12 of 12
JS: 2020-06-12 10:21:58 [error X 60][https://www.user6368/wordpress/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.9:31:224004] Ungültiges Argument. 
JS: 2020-07-27 15:03:44 [error X 1][https://www.user6368/wordpress/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view13173\") has already been destroyed and cannot be used. 
JS: 2020-07-27 15:15:02 [error X 1][https://www.user6368/wordpress/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view13462\") has already been destroyed and cannot be used. 
JS: 2020-07-27 15:15:04 [error X 1][https://www.user6368/wordpress/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view13558\") has already been destroyed and cannot be used. 
JS: 2020-08-26 08:43:09 [error X 303][https://www.user6368/wordpress/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.9.1:2:6571] t is null 
JS: 2020-08-26 08:43:25 [error X 16][https://www.user6368/wordpress/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.0.1:2:55844] e[o] is undefined 
JS: 2020-08-28 09:13:34 [error X 35][https://www.user6368/wordpress/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.9.1:2:6573] Cannot read property \'getEditModel\' of null 
JS: 2020-08-28 09:14:55 [error X 4][https://www.user6368/wordpress/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.0.1:2:55861] Cannot read property \'global\' of undefined 
JS: 2020-09-07 11:05:33 [error X 2][https://www.user6368/wordpress/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.6:2:470568] this.container is undefined 
JS: 2020-09-16 09:24:35 [error X 21][https://www.user6368/wordpress/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.0.6:2:0]  
JS: 2020-09-16 09:24:35 [error X 8][https://www.user6368/wordpress/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.6:2:469806] elementorFrontend.elements.window.jQuery is not a function 
JS: 2020-09-16 10:59:10 [error X 6][https://www.user6368/wordpress/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.0.6:2:60279] r is undefined 
```

**Comment by 234578** [comment]
The only thing was help is to rollback on version 2.2.9. With this version everything works again.

**Comment by designinsist** [comment]
> The only thing was help is to rollback on version 2.2.9. With this version everything works again.

Just Elementor or  Elementor Pro ?

**Comment by designinsist** [comment]
> > The only thing was help is to rollback on version 2.2.9. With this version everything works again.
> 
> Just Elementor or Elementor Pro ?

I have Elementor Pro Version 2.10.2 and  Elementor  Version 3.0.10

**Comment by 234578** [comment]
Thank you. I roll back to that version and now everything works again. Still, I'm afraid that problems will arise again in the future :-(.

**Comment by tinyCoder32** [comment]
Same here, i've shouldn't update.

**Comment by mulik91** [comment]
Hi,
after an update,
all the pages i've want to edit:
"Cannot read property 'getEditModel' of null"

**Comment by SeriForte** [comment]
Same here, after activating update for _Elementor_ and _Elementor Elements_ the edit page remains grey.

**Errors**
- `'getEditModel' of null` in common.min.js?ver=3.0.11:2
- `'getEditModel' of null` in editor.min.js?ver=2.8.3:2
- `'remove' of null` in preloader.js?ver=1.0:19

**Versions**
- the plugin update for Elementor was succsessful to version 3.0.11
- the plugin update for _Elementor Elements_ from version 2.8.3 to version 3.0.5 failed 

**System**
- WP 5.4.2

After downgrading to Elementor 2.9.9 as suggested it worked as before.

**Comment by drbullock** [comment]
Same Issue with the latest version

**Comment by nadia-am** [comment]
I use elementor 3.0.11 and elementor pro version 2.8.4, I downgrade my elementor but problem didnt solved and another errors comes up!
how can i get ride of this error?

befor Downgrading elementor:
![image](https://user-images.githubusercontent.com/11175468/95863850-8a701980-0d71-11eb-804c-59a158bed76f.png)
After Downgrade it to version 2.9.9
![image](https://user-images.githubusercontent.com/11175468/95863913-9b208f80-0d71-11eb-97b5-d6bfea7be248.png)

**Comment by 8BitSigdom** [comment]
@nadia-am I have the same problem. 

Elementor: Version 3.0.12
Elementor Pro: Version 2.9.4

![95863850-8a701980-0d71-11eb-804c-59a158bed76f](https://user-images.githubusercontent.com/7969604/97485734-c9e65a80-195a-11eb-8060-c8ca4ed48043.png)

**Comment by nadia-am** [comment]
@8BitSigdom I fix the problem by updating both elementor and elementor pro.

**Comment by maurisrx** [comment]
> @nadia-am I have the same problem.
> 
> Elementor: Version 3.0.12
> Elementor Pro: Version 2.9.4
> 
> ![95863850-8a701980-0d71-11eb-804c-59a158bed76f](https://user-images.githubusercontent.com/7969604/97485734-c9e65a80-195a-11eb-8060-c8ca4ed48043.png)
> 
> If I deactivate Elementor Pro the edit page works again.

I have the exact same versions and errors. Deactivating Elementor Pro makes the editor loads again.

**Comment by BaNguyen047** [comment]
Elementor: Version 3.0.12
Elementor Pro: Version 2.9.2

I have the exact same versions and errors. Deactivating Elementor Pro makes the editor loads again.

**Comment by 234578** [comment]
Unfortunately, no developer seems to care here. :-/. At some point the last working version will be too old.

**Comment by 8BitSigdom** [comment]
> Unfortunately, no developer seems to care here. :-/. At some point the last working version will be too old.

Agree. My biggest problem is that the pro version on our site is bought by a guy that is no longer reachable. So we cant use @nadia-am solution.

You might be able to though?

**Comment by zgcasas** [comment]
> @8BitSigdom I fix the problem by updating both elementor and elementor pro.

Updating elementor and elementor pro to version 3 fixed my problem as @nadia-am mentioned
Both should be version 3+ to work correctly

**Comment by drbullock** [comment]
This issue if fixed in the latest release, so just update it.

**Comment by benjo456** [comment]
I am still having this issue on latest release, and the rollback is broken

**Comment by 8BitSigdom** [comment]
> I am still having this issue on latest release, and the rollback is broken

I can confirm that the error is still there!

**Comment by redfox05** [comment]
Im having the same issues too.

**Comment by xaja** [comment]
same here
Version 3.0.14

**Comment by amazzonix** [comment]
Downgrade to 2.9.9 is a workaround but does anybody found out why is this happening and what to do in order to actually fix it? 

Thanks!

**Comment by amazzonix** [comment]
This topic should be reopened.

Leaving a plugin outdated is not a very safe and smart way on fixing the problem, it’s just a workaround. There is something causing it and it’s affecting many people.

Did anyone found a REAL solution?

Thanks!

My setup:

Elementor Version 3.0.15
Elementor Pro Version 3.0.8

Once I install the pro version, the left Elementor Edit column stays hanging and you cannot do anything, but disabling the Elementor Pro plugin or downgrading Elementor to Version 2.9.9 which is not ideal.

Thanks!

**Comment by redfox05** [comment]
My solution was as follows.
First tried downgrade to have both elementor and elementor Pro at the same
version that your license allows. This was okay for a while. But not ideal
as our hosting provider now forces automatic updates. So normal would
upgrade while Pro would not. So out of sync.

Then I decided with the better, safer option. Pay for the pro version and
upgrade both elementor and elementor Pro to the latest versions. Problem
gone.

**Comment by Richi2293** [comment]
Same problem for me too, if I disable Elementor Pro then it works.
But it doesn't seem like a great solution to me

**Comment by DevStevenWillett** [comment]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Expected behaviour - While trying to edit a page with Elementor, I would normally open the page to edit through the CMS and on clicking the page name this open with the option to edit using Elementor. When I click the Elementor button in the middle of the page, this would typically load the editor for editing including the contents of the current page.

I have updated to the latest stable version 3.1.1, I have reverted to the earlier version and still, the same issue persists all the way back until I go to version 2.9.9. 

I have also installed the latest -dev version also to see if this is resolved in the latest edition but still the same outcome.

I have attempted multiple times to flush the cache and only upon reverting back to version 2.9.9 can I even use the Elementor editor with WordPress anymore.

This problem has been around for some time now and the key reason I walked away from Elementor some time back, had really hoped this had been resolved, appears not.

The full error is outlined below in a hope to help progress this further:

Bug/Error: ```Uncaught (in promise) TypeError: Cannot read property 'getEditModel' of null``` 
Linked to file (Elementor V 3.2.0-dev1): ```editor.js?ver=7.3.2:1```

**Already attempted the following:**

- Disabling all plugins except Elementor
- Reverting to the default WordPress Twenty Twenty-One theme
- Flushing Server  Browser Cache's
- Performing checks throughout the new WordPress Site Health section.

This persistent issue is seen over many releases going back to 2.9.9 being the last working instance, this bug is disabling the entire Elementor tool making it unusable entirely without using safe mode.

## Steps to reproduce
- Run an instance of WordPress 5.6.1
- Install Elementor FREE edition V 3.1.0 or  3.1.1 (to see the latest version of the issue)
- *Extra - Upgrade/Install Elemetnor Dev BETA instance also and the bug still remains (V 3.2.0-dev1)
- Try to edit a normal page of content using Elementor editor while Guttenberg is still active.
- Check dev tools while trying to load a page in the CMS to edit and you will then see the error: ```

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (Not using Elementor Pro so irrelevant).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment
<details>
<summary>System Info</summary>

```
- Ubuntu 18.04.5 LTS
- Nginx 1.14.0
- WordPress 5.6.1
- Elementor 3.1.0 | 3.1.1 | 3.2.0-dev1
- MySQL V14.14 Distribution 5.7.33
```
</details>
