### ISSUE TITLE
If tab/panel in widget does not have controls panel is not shown as empty but previous panel

### ISSUE THREAD

**Issue by andreasnrb** [elementor/elementor#12658]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
A tab without controls inherit controls from previously viewed tab.

## Steps to reproduce
Adding a section with a tab like TAB_CONTENT and then not having any controls shown due to conditions results in the panel for the tab containing the controls from the previously viewed tab in the widget. That is if I am on style tab and then click och content tab(which does not have controls) the controls from the style panel is shown instead of a gray empty box.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by arielk** [comment]
I'm not sure that I understand you correctly, can you please share us your code or more information?

**Comment by andreasnrb** [comment]
I have a tab content where controls are displayed based on conditions in
the layout tab depending om selection of skin. Some skins don't add any
controls to the Content tab. So when you click Layout then Content panel
shows Layout panel. if you click Style tab then Content it shows Style
panel. It seems without controls a panel is not added or something. In
reality it would be best if a tab weren't shown at all if no controls or
could be controlled using conditions but that is a separate issue.
[image: Skärmavbild 2020-09-25 kl. 10.02.09.png][image: Skärmavbild
2020-09-25 kl. 10.02.16.png]
[image: Skärmavbild 2020-09-25 kl. 10.02.25.png][image: Skärmavbild
2020-09-25 kl. 10.02.33.png]






Den fre 25 sep. 2020 kl 09:38 skrev Ariel Klikstein <
notifications@github.com>:

**Comment by arielk** [comment]
I've merged some of your issues into this discussion so we could deal with it more efficiently. 
In order for us to help you effectively please share with us the code you are writing (examples will be fine).

Thanks

**Comment by andreasnrb** [comment]
I have made an example widget with comments.

https://gist.github.com/andreasnrb/726565f362c63c514c476aa0394ef181

Den sön 27 sep. 2020 kl 12:08 skrev Ariel Klikstein <
notifications@github.com>:

**Comment by andreasnrb** [comment]
There is another issue that is new and that is that you can no longer target other elements in other panels with the JS hook '_panel/open_editor/widget/widgetname_' except for the one that is opened first.

* So if Content tab is the one that is opened first then you can target elements in that panel.
* If you switch to another panel with same widget still opened the panel/open_editor is not rerun and therefor the JS can't be reapplied for the widgets in that panel
* If you open a tab (A) other than content, and the click on another widget, then click back to the widget with the JS code then it gets triggered since the tab A is opened.

You should add a new JS hook like _panel/open_editor/widget/widgetname/panelname_ that is triggered when people switch between tabs.

**Comment by andreasnrb** [comment]
I found in the JS files where the default tab is set but I can't figure out how you can set the default tab when making a custom widget. I added defaultEditSettings and editTab to the get_default_data array in my widgets.

In elements.js

https://github.com/elementor/elementor/blob/11369acbe84184aec11927a3769ab721ab1276b2/assets/dev/js/editor/elements/models/element.js#L11

In the component JS class it uses defaultEditRoute as the tab config. It seems there was a change in one file but not the other ones.

https://github.com/elementor/elementor/blob/6cab1b39dc8a8366783686c5bb7030fb262446d3/assets/dev/js/editor/regions/panel/pages/editor/component.js#L51 

What I tried to add in my widget to see if it worked.

```
protected function get_default_data() {
        $data = parent::get_default_data();
        $data['editSettings']=[];
	$data['editSettings']['editTab'] = 'query';
	$data['editSettings']['defaultEditRoute'] = 'query';
        $data['defaultEditSettings']=[];
	$data['defaultEditSettings']['editTab'] = 'query';
	$data['defaultEditSettings']['defaultEditRoute'] = 'query';
        return $data;
}
```

**Comment by lior-sh** [comment]
Hi @andreasnrb,

Thanks for reporting.
We will address this issue soon and release a patch.
Please follow this thread for updates.
Thanks!

**Comment by udidol** [comment]
Fixed by #12807

**Comment by andreasnrb** [comment]
@udidol Is this is a fix for the open panel trigger issue as well? I can't tell from the code changes that this issue is also fixed.

**Comment by udidol** [comment]
No. The open panel trigger should be working (it is used in Elementor Core itself). You should open a separate issue for that.

**Comment by andreasnrb** [comment]
@udidol Ok. SInce all my tabs related issues was merged into this one I just commented in this one.
https://github.com/elementor/elementor/issues/12658#issuecomment-699914225
But sure I'll make a separate issue.

**Comment by andreasnrb** [comment]
@udidol @arielk It seems that #12646 was not fixed. Not sure the whole merging was a good idea. The other issue #12645 seems to be fixed.

Also testing the Elementor git version I get another error with the empty panel.

PHP Notice:  Trying to access array offset on value of type null in [...]elementor/includes/base/controls-stack.php on line 1567
This code:
 		$args['tabs_wrapper'] = $this->current_tab['tabs_wrapper'];

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.12

Feel free to update

Thanks!
