### ISSUE TITLE
Popup selector appears as small box, can't select which popup to use.

### ISSUE THREAD

**Issue by whokneadsdough** [elementor/elementor#13257]
![Screen-Shot-2020-12-08-at-9 14 14-PM](https://user-images.githubusercontent.com/70361848/101589092-9c9abc80-399c-11eb-9654-3a145b39780e.jpg)

## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce
1. Change link to Popups
2. Click wrench
3. Enter a few characters
4. Small box appears in upper-left corner, can't select needed popup.

**_Problem happens with WP Core 5.6. Did not experience this bug with WP Core 5.5.3._**

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.23
	PHP Version: 7.4.13
	PHP Max Input Vars: 10000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.6
	Site URL: https://www.lineagewine.com
	Home URL: https://www.lineagewine.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 1G
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Los_Angeles
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15

== Active Plugins ==
	All In One WP Security
		Version: 4.4.5
		Author: Tips and Tricks HQ, Peter Petreski, Ruhul, Ivy

	Asset CleanUp: Page Speed Booster
		Version: 1.3.7.2
		Author: Gabriel Livan

	Cloudflare
		Version: 3.8.7
		Author: Cloudflare, Inc.

	Defender
		Version: 2.3.2
		Author: WPMU DEV

	Duplicate Page
		Version: 4.3
		Author: mndpsingh287

	Elementor
		Version: 3.0.14
		Author: Elementor.com

	Elementor Addon Elements
		Version: 1.7.2
		Author: WP Vibes

	Elementor Contact Form DB
		Version: 1.5
		Author: Sean Barton - Tortoise IT

	Elementor Pro
		Version: 3.0.8
		Author: Elementor.com

	Erident Custom Login and Dashboard
		Version: 3.5.8
		Author: Libin V Babu

	Google Analytics for WordPress by MonsterInsights
		Version: 7.13.2
		Author: MonsterInsights

	Hotjar
		Version: 1.0.9
		Author: Hotjar

	LiteSpeed Cache
		Version: 3.5.2
		Author: LiteSpeed Technologies

	MailOptin - Lite
		Version: 1.2.34.0
		Author: MailOptin Team

	Popup Maker
		Version: 1.13.1
		Author: Popup Maker

	Query Monitor
		Version: 3.6.5
		Author: John Blackbourn

	Simple Page Ordering
		Version: 2.3.4
		Author: Jake Goldman, 10up

	Slider Revolution
		Version: 6.2.9
		Author: ThemePunch

	WP Server Stats
		Version: 1.6.9.1
		Author: Saumya Majumder, Acnam Infotech

	Yoast SEO
		Version: 15.4
		Author: Team Yoast


== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		search-form : 1
		theme-archive-title : 1
	footer : 1
		button : 1
		divider : 1
		form : 1
		heading : 19
		social-icons : 1
	header : 2
		button : 2
		icon : 2
		nav-menu : 2
		search-form : 4
		theme-site-logo : 2
	popup : 1
		button : 1
		heading : 1
	section : 3
		button : 3
		form : 1
		heading : 3
		html : 1
	single : 1
		heading : 3
		search-form : 1
	wp-post : 6
		button : 6
		divider : 18
		facebook-comments : 6
		heading : 6
		html : 1
		icon : 6
		post-info : 18
		posts : 6
		share-buttons : 6
		spacer : 6
		text-editor : 18
	wp-page : 11
		button : 22
		divider : 1
		form : 2
		google_maps : 1
		heading : 52
		html : 2
		icon : 1
		icon-box : 1
		image : 13
		posts : 2
		slider_revolution : 1
		spacer : 6
		text-editor : 51
		video : 2


== Log ==
	
JS: showing 2 of 2JS: 2020-08-08 23:38:54 [error X 32][https://www.lineagewine.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=2.9.14:2:65602] e.elementorWaypoint is not a function 
JS: 2020-09-29 14:28:06 [error X 2][https://www.lineagewine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.10:2:473913] Cannot read property \'document\' of undefined 

Log: showing 20 of 392020-09-01 07:14:53 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-09-01 07:14:53 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-09-01 07:14:53 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-09-01 07:14:53 [notice] Custom colors already exist. nothing to do. 
2020-09-01 07:14:53 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-09-01 07:14:53 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-09-01 07:14:53 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-09-01 07:14:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.3',
  'to' => '3.0.5',
)]
2020-09-01 07:14:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.1',
  'to' => '3.0.2',
)]
2020-09-05 21:50:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.2',
  'to' => '3.0.3',
)]
2020-09-06 21:40:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.5',
  'to' => '3.0.6',
)]
2020-09-09 15:55:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.6',
  'to' => '3.0.7',
)]
2020-09-09 15:59:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.3',
  'to' => '3.0.4',
)]
2020-09-28 07:31:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.7',
  'to' => '3.0.10',
)]
2020-09-28 07:33:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.4',
  'to' => '3.0.5',
)]
2020-10-26 21:18:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.10',
  'to' => '3.0.12',
)]
2020-11-05 07:41:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.12',
  'to' => '3.0.13',
)]
2020-11-05 07:42:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.5',
  'to' => '3.0.6',
)]
2020-11-26 11:55:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.13',
  'to' => '3.0.14',
)]
2020-12-08 20:20:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.6',
  'to' => '3.0.8',
)]

PHP: showing 2 of 2PHP: 2020-09-02 19:25:10 [notice X 55][/home/nelcalara/lineagewine.com/wp-content/plugins/elementor/includes/conditions.php::90] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-10-02 19:18:43 [notice X 1][/home/nelcalara/lineagewine.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by thejungletiger** [comment]
The same problem applies to the Internal Page options for links. The search box appears but is broken. Adding the jQuery Migrate plugin resolves the problem in WordPress 5.6.

**Comment by DorShahar** [comment]
Hi
Are you still seeing this issue after the 3.0.15 version update?

**Comment by whokneadsdough** [comment]
The problem still persists. A temporary work-around I've been using was suggested by @thejungletiger, downgrade the jQuery version to 1.12.4. It doesn't seem to be the right answer since it relies on using an outdated version.

**Comment by DorShahar** [comment]
Hi @whokneadsdough 
I couldn't reproduce the bug. 
Can you try and disable the other plugins and check if the problem occurs? 

Happy new year

**Comment by thejungletiger** [comment]
I have a clean WP install with just Elementor and Hello theme and the problem is there. Occurs on Query section boxes for selecting terms as well without the JQuery Migrate plugin.

**Comment by whokneadsdough** [comment]
Tried a clean install with only Elementor and Pro activated, with Hello 2.3.1. Here's a screen recording.

https://youtu.be/P9v4HJQ_aUk

**Comment by DorShahar** [comment]
Thanks @whokneadsdough 
I'll take it with our QA and Devs

**Comment by DorShahar** [comment]
This issue has been resolved in Elementor v3.1.0
Feel free to update
Thanks!

**Comment by whokneadsdough** [comment]
@DorShahar Problem still persists with Elementor 3.1.1 / Pro 3.0.10

With Chrome Inspector and selecting below
```
<ul class="select2-results__options" role="tree" id="select2-elementor-control-default-c1081-results" aria-expanded="true" aria-hidden="false"><li class="select2-results__option select2-results__option--highlighted" role="treeitem" aria-selected="true" data-select2-id="13">Popup (Template)</li></ul>
``` 
and removing `overflow-y: auto;` in the CSS for that UL, I'm able to see and select the available popup. Changing it to `overflow-y: visible;` also allows for seeing and selecting the popup.

Screen recording of the process is at https://youtu.be/xZ2-xd6StwA 

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.23
	PHP Version: 7.4.14
	PHP Max Input Vars: 10000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.6
	Site URL: https://elementor.leonelcalara.com
	Home URL: https://elementor.leonelcalara.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 1G
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.10
		Author: Elementor.com


== Elementor - Compatibility Tag ==
	
	Elementor Pro: header_not_exists

== Elements Usage ==
	
	header : 1
		text-editor : 2
	popup : 1
		button : 1
		heading : 2
	wp-page : 1
		button : 1
		google_maps : 1
		heading : 4
		icon-list : 3


== Log ==
	
PHP: showing 1 of 1PHP: 2020-12-31 19:31:09 [notice X 1][/home/nelcalara/elementor.leonelcalara.com/wp-content/plugins/elementor/includes/template-library/classes/class-import-images.php::154] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 2 of 22021-02-03 05:44:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.15',
  'to' => '3.1.1',
)]
2021-02-03 05:47:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.9',
  'to' => '3.0.10',
)]


				
</details>

**Comment by whokneadsdough** [comment]
@DorShahar In addition to my recent reply, the following was observed in some code:

```
<span class="select2-dropdown select2-dropdown--below" dir="ltr" style="width: 0px;">
```

If `style=width: 0px;` is removed or increased to 100px, the selector becomes visible.

**Comment by DorShahar** [comment]
Thanks for the video @whokneadsdough - We'll check that out

**Comment by dss001** [comment]
This error still occurs in Pro Version 3.0.10.  It has NOT been fixed.

**Comment by Holeycow** [comment]
I've just come across this issue today. 
Very frustrating. I'm on version 3.1.1/ Pro 3.1.0. Whokneadsdough's workaround seems to work (thanks for that @whokneadsdough), ...but it's pretty painful having to go through that process.

**Comment by DorShahar** [comment]
Hey all,

This issue has been resolved in Elementor v3.2.0

Feel free to update!

**Comment by hayden664** [comment]
The issue persists with Elementor v3.5.5 with Pro v3.6.1. I had to downgrade the free version to v3.5.5 because there has been an infinite loading editor issue. 

Anyway, my popup doesn't search for things and it always says "No results found".

**Comment by DaanG47** [comment]
This issue is back, I'm using Elementor 3.19.4 and Elementor Pro 3.19.3.
I have several Pop-ups configured, but when I want to select them when editing a page or post, I type something to search the popup and a message "no popups found'' is displayed.

It is now not possible at all to display a popup via a button or link.
