### ISSUE TITLE
Javascript code + Elementor Pop up that blocks Google Ads before consent is given

### ISSUE THREAD

**Issue by BearWood28** [elementor/elementor#13679]
Hi All,

I am trying to implement similar code in the video with the combination of beautiful Elementor Pop up button.
Let say we give an ID to a button "giveCookieConsentButton", and when the user clicks, only then website will show google ads.
Please see the video here: https://www.youtube.com/watch?v=94MTh4E54ww

I have created an Elementor Pop up with a button id "giveCookieConsentButton".
Then I placed Google Ad script in the middle of the article:

```
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Square Ad in Article -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-XXXXXXXXXXXXXXXX"
     data-ad-slot="6957910960"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
```

Below is the script that I am inserting in the head of the page:

```
<script>
function handleCookieConsentGiven(key) {
setCookie("consentgiven2513834176315", true);
 
// load adsense script
var script = document.createElement('script');
script.src = "//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js";
document.head.appendChild(script);
(adsbygoogle = window.adsbygoogle || []).push({
google_ad_client: "ca-pub-XXXXXXXXXXXXXXXX",
enable_page_level_ads: true
});
}
 
document.getElementById("giveCookieConsentButton").addEventListener("click", handleCookieConsentGiven);
});
</script>
```

Execution: The page is still loading the Google ad and nothing is blocking it. 
Do I need to change something in the Ad code that google provides or what I am doing wrong?

P.S Maybe there will be an Elementor feature soon that will allow to insert custom js codes easily?

Thanks you!

**Comment by DorShahar** [comment]
Hi @BearWood28 
We will release that kind of feature (Custom Code) in Pro v3.1.0.

If you can, check it in the Beta version. So I merged this issue with #13633 (The beta post). 
Let us know how it works for you. 

Thanks

**Comment by BearWood28** [comment]
@DorShahar 
Thank you an update regarding upcoming feature, however you didn't answer my original question relating to Javascript code.
I am still not sure where do I have a mistake here.

**Comment by DorShahar** [comment]
@BearWood28 , Please take a look in #7953
Since our developers are working on bug fixes for v3.1.0 - so it will take time to look at your code in the next few days.

You can also try to ask in the Facebook community, or investigate more [here](https://github.com/elementor/elementor/issues?q=is%3Aclose+label%3Atype%2Fdeveloper-api+popup).   

Thank you for your understanding.

**Comment by BearWood28** [comment]
@DorShahar Thank you for your reply.

No problem, I completely understand that the new version just came out, so developers are now busy fixing priority issues. 
I already asked the facebook community, but had no good feedback as this is quite technical question and requires coding skills, thats why I came here :) 

I will wait a few days and hopefully someone will be able to look in to this in their spare time.

Many thanks!

**Comment by BearWood28** [comment]
Did anyone had a chance to look at my code above yet? 
Maybe because the topic is closed so no-one seen it?
@DorShahar

**Comment by udidol** [comment]
Hi @BearWood28,
I went over your code and I'm not sure I understand what you tried to do.
There are two snippets of code that you included in your issue description.
One of them is included in the head of the page, and the other is included in the body of the page?
They both load the adsense script.
The one in the head tries to load it on button click, and the one in the body loads it always, unconditionally. This means that having the button callback doesn't prevent the AdSense script from being loaded regardless.

Anyway, I am not sure what you are trying to do. 
If you are not a developer, I would suggest consulting or hiring one, otherwise you might have issues with your code that could cause problems with your AdSense.
