### ISSUE TITLE
Elementor 3.1: Uncaught ReferenceError: wp is not defined

### ISSUE THREAD

**Issue by mcrowell** [elementor/elementor#13708]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Elementor 3.1 is causing a console error: (Uncaught ReferenceError: wp is not defined) with the plugins Autoptimize & Async Javascript.

## Steps to reproduce

Install and activate Autoptimize & Async Javascript with Elementor 3.1 and activate either Async or Defer Javascript.

You will see a console error on these 2 lines:
```
44: wp.i18n.setLocaleData( localeData, domain );
45: } )( "elementor", { "locale_data": { "messages": { "": {} } } } );</script> <script id='elementor-frontend-js-before'>var elementorFrontendConfig = {"environmentMode":{"edit":false,"wpPreview":false,"isScriptDebug":false,"isImprovedAssetsLoading":false},"i18n":[],"is_rtl":false,"breakpoints":{"xs":0,"sm":480,"md":768,"lg":1025,"xl":1440,"xxl":1600},"version":"3.1.0","is_static":false,"experimentalFeatures":[],"urls":{"assets":"https:\/\/wickydemo.com\/testing\/wp-content\/plugins\/elementor\/assets\/"},"settings":{"page":[],"editorPreferences":[]},"kit":{"lightbox_enable_counter":"yes","lightbox_enable_fullscreen":"yes","lightbox_enable_zoom":"yes","lightbox_enable_share":"yes","lightbox_title_src":"title","lightbox_description_src":"description"},"post":{"id":6609,"title":"Wicky%20Design%20%E2%80%93%20Philadelphia%20Web%20Design","excerpt":"","featuredImage":false}};</script> <script defer='defer' src='https://wickydemo.com/testing/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.1.0' id='elementor-frontend-js'></script> <script defer='defer' src='https://wickydemo.com/testing/wp-content/plugins/elementor/assets/js/preloaded-elements-handlers.min.js?ver=3.1.0' id='preloaded-elements-handlers-js'></script> </body></html><!-- Cache Enabler by KeyCDN @ 27.01.2021 09:45:27 (https html) -->
```
## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [ xI can reproduce this bug consistently using the steps above.

## Environment

[system-info-wickydemo.com-27-01-2021.txt](https://github.com/elementor/elementor/files/5881001/system-info-wickydemo.com-27-01-2021.txt)

**Comment by shilo-ey** [comment]
Thanks, we are examining this issue.

By the way, if you clear your CDN cache it resolves? 
If not - activate the Improved Asset Loading experiment resolves the issue?

Waiting for your responses

Thanks!

**Comment by mcrowell** [comment]
Thank you.
This website isn't using a CDN.
I cleared all local cache on the server.
I activated the Improved Asset Loading and the same errors appear in the console.

**Comment by astbarc** [comment]
Hi,

Same error appearing in my website when js is asyn or defer.

@shilo-ey , can I ask why are you including these translation scripts in version 3.1.0

`
<script type='text/javascript' src='https://www.cupapizarras.com/wp-includes/js/dist/i18n.min.js' id='wp-i18n-js'></script>
 <script type='text/javascript' id='elementor-frontend-js-translations'>
  ( function( domain, translations ) {
  var localeData = translations.locale_data[ domain ] \|\| translations.locale_data.messages;
  |localeData[""].domain = domain;
   wp.i18n.setLocaleData( localeData, domain );
   } )( "elementor", { "locale_data": { "messages": { "": {} } } } );
   </script>
`

**Comment by developdude** [comment]
Same here with Asset Clean Up

**Comment by gebsl** [comment]
Also experiencing this problem when using `defer` on javascript assets.

**Comment by kromeninja** [comment]
Same issue with Litespeed

**Comment by reachdigitalaus** [comment]
@shilo-ey  I am also experiencing this issue. I use CDN , have cleared all caches and disabled cdn and all plugins, console error still persists.

Error is here:

`<script id='elementor-frontend-js-translations'>
( function( domain, translations ) {
	var localeData = translations.locale_data[ domain ] || translations.locale_data.messages;
	localeData[""].domain = domain;
	wp.i18n.setLocaleData( localeData, domain );
} )( "elementor", { "locale_data": { "messages": { "": {} } } } );
</script>`

Hope this can be fixed.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.1.1

Feel free to update

Thanks!

**Comment by vovkasolovev** [comment]
Elementor 3.1.1 is installed, LiteSpeed is used, no CDN, full cache is completely cleared. Error is still present for logged in users.
`The Uncaught ReferenceError: wp is not defined error`

Part with error:
`<script type='text/javascript' id='elementor-common-js-translations'>( function( domain, translations ) {
	var localeData = translations.locale_data[ domain ] || translations.locale_data.messages;
	localeData[""].domain = domain;
	wp.i18n.setLocaleData( localeData, domain );
} )( "elementor", {"translation-revision-date":"2021-01-31 17:56:50+0000","generator":"GlotPress\/3.0.0-alpha.2","domain":"messages","locale_data":{"messages":{"":{"domain":"messages","plural-forms":"nplurals=3; plural=(n % 10 == 1 && n % 100 != 11) ? 0 : ((n % 10 >= 2 && n % 10 <= 4 && (n % 100 < 12 || n % 100 > 14)) ? 1 : 2);","lang":"ru"},"Unable to connect":["\u041e\u0448\u0438\u0431\u043a\u0430 \u0441\u043e\u0435\u0434\u0438\u043d\u0435\u043d\u0438\u044f"],"Finder":["Finder"]}},"comment":{"reference":"assets\/js\/common.js"}} );</script>`

**Comment by skydev2020** [comment]
right, even I am using 3.1.3, but still same error

**Comment by cliqer** [comment]
Still the same error on my side too.
BTW why do you load translation scripts when there is no translation enabled/needed?

**Comment by alanmcginnis** [comment]
Hi all,

I am also experiencing this issue when logged in. I can't upload images when using standard widgets. Let me know if I need to provide logs.
![1-week 2021-03-17 at 3 00 01 PM](https://user-images.githubusercontent.com/7727219/111544282-74f08880-8731-11eb-9f41-9d2324ccd011.png)

**Comment by wayheming** [comment]
same issue in 3.1.3

**Comment by alexeygoncharov** [comment]
Same issue! Elementor / Elementor Pro 3.14 https://skr.sh/s78Q2dNxykT

**Comment by skydev2020** [comment]
I was able to solve it by disabling one of the cache plugin called 'Breeze'.
But I remember previous of elementor & Elementor Pro worked well with this plugin

**Comment by Backoo** [comment]
I also have this issue.
I'm using the [LiteSpeed Cache](https://it.wordpress.org/plugins/litespeed-cache/) plugin and if I disable it the issue disappears. However this is not a good solution: cache is important!
![Screen Shot 2021-03-26 at 14 41 24](https://user-images.githubusercontent.com/570181/112640205-672db800-8e41-11eb-9871-089f719ed6c5.png)

**Comment by therealgilles** [comment]
Somehow this other script got the correct dependency:

```PHP
  public function register_preview_scripts() {
    $suffix = defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG ? '' : '.min';

    wp_enqueue_script(
      'elementor-pro-preview',
      ELEMENTOR_PRO_URL . 'assets/js/preview' . $suffix . '.js',
      [
        'wp-i18n',
        'elementor-frontend',
      ],
      ELEMENTOR_PRO_VERSION,
      true
    );
  }
```

**Comment by therealgilles** [comment]
Looks like adding 'wp-i18n' as dependency does not work because the wp-includes/js/dist/i18n.js is processed by Webpack and `window.wp` gets transformed into `this["wp"]`. Adding the 'util' handle as dependency works (or probably any that would define `window.wp`. Hence this is a combination of two issues.

**Comment by therealgilles** [comment]
Turning 'JS Combine External and Inline' on fixed the issue for me. It looks like it is able to respect the priority order between inline and external scripts when the option is on.

```
Include external JS and inline JS in combined file when JS Combine is also enabled. This option helps maintain the priorities of JS execution, which should minimize potential errors caused by JS Combine.
```

**Comment by ScorpEH** [comment]
@danilomakstds this issue is indeed fixed on desktop (thanks for this)
Only on mobile it still occours and I can't troubleshoot it since I don't see anything in console. I hope you can help.
Greetings
