### ISSUE TITLE
JS Uncaught ReferenceError: wp is not defined

### ISSUE THREAD

**Issue by porcobella** [elementor/elementor#13746]
After upgrading to Elementor version 3.1.0, I got the javascript error: 
Uncaught ReferenceError: wp is not defined

The code is found in 
![image](https://user-images.githubusercontent.com/26858900/106360197-dc887b00-631f-11eb-8a8e-a8135e92856a.png)

**Comment by Jordidriesen** [comment]
Same issue here, causes the recaptcha to not work in any form. Recatcha v2 and V3

**Comment by porcobella** [comment]
I added this code to the child theme functions.php to remove the console error:

`add_action('wp_head', function() {
	echo '<script type="text/javascript">
	if (typeof(wp) == "undefined") {
	window.wp = {
		i18n: {
			setLocaleData: (function() {
			return false;
			})}
		};
	}
	</script>';
});`

Give it a try @Jordidriesen

**Comment by paniy** [comment]
I found that I set a JS file 'i18n.min.js' attribute to 'defer'. When I cancel the 'defer' attribute, the problem is solved.

**Comment by DorShahar** [comment]
Hi,
Thank you for reporting. 
We are aware of the bug, and we fixed it in the coming `v3.1.1`. 

I'm merging this issue with #13708 for better tracking. 

Thanks.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.1.1

Feel free to update

Thanks!

**Comment by phkrief** [comment]
Hi,

I have installed the v3.1.1 and I still get this error on the page that is using Toggle items (http://www.brain-iot.eu/resources/):

(index):1414 Uncaught TypeError: Cannot read property 'setLocaleData' of undefined
    at (index):1414
(anonymous) @ (index):1414
(index):1420 Uncaught TypeError: Cannot read property 'setLocaleData' of undefined
    at (index):1420
    at (index):1421
(anonymous) @ (index):1420
(anonymous) @ (index):1421
elementor-admin-bar.min.js?ver=3.1.1:2 Uncaught ReferenceError: elementorModules is not defined
    at elementor-admin-bar.min.js?ver=3.1.1:2
    at elementor-admin-bar.min.js?ver=3.1.1:2
    at elementor-admin-bar.min.js?ver=3.1.1:2
(anonymous) @ elementor-admin-bar.min.js?ver=3.1.1:2
(anonymous) @ elementor-admin-bar.min.js?ver=3.1.1:2
(anonymous) @ elementor-admin-bar.min.js?ver=3.1.1:2
autoptimize_521585d1a3775b8e0bce9b9f71653d4c.js:2 JQMIGRATE: Migrate is installed, version 3.3.2
autoptimize_521585d1a3775b8e0bce9b9f71653d4c.js:766 Uncaught TypeError: Cannot read property 'querySelector' of null
    at cbpHorizontalSlideOutMenu._init (autoptimize_521585d1a3775b8e0bce9b9f71653d4c.js:766)
    at new cbpHorizontalSlideOutMenu (autoptimize_521585d1a3775b8e0bce9b9f71653d4c.js:758)
    at autoptimize_521585d1a3775b8e0bce9b9f71653d4c.js:840
    at autoptimize_521585d1a3775b8e0bce9b9f71653d4c.js:841
    at autoptimize_521585d1a3775b8e0bce9b9f71653d4c.js:842
_init @ autoptimize_521585d1a3775b8e0bce9b9f71653d4c.js:766
cbpHorizontalSlideOutMenu @ autoptimize_521585d1a3775b8e0bce9b9f71653d4c.js:758
(anonymous) @ autoptimize_521585d1a3775b8e0bce9b9f71653d4c.js:840
(anonymous) @ autoptimize_521585d1a3775b8e0bce9b9f71653d4c.js:841
(anonymous) @ autoptimize_521585d1a3775b8e0bce9b9f71653d4c.js:842
admin-bar.min.js?ver=5.6.1:2 Uncaught TypeError: u.hoverintent is not a function
    at HTMLDocument.<anonymous> (admin-bar.min.js?ver=5.6.1:2)
(anonymous) @ admin-bar.min.js?ver=5.6.1:2
4autoptimize_521585d1a3775b8e0bce9b9f71653d4c.js:227 YT API init check

Thx for your help

**Comment by wayheming** [comment]
same issue in 3.1.3

**Comment by danilomakstds** [comment]
I solved this issue by modifying **preloaded-elements-handlers.min.js** in _wp-content/plugins/elementor-pro/assets/js_
just replace
`e.exports = wp.i18n`
with
`var wp;if (wp) {e.exports = wp.i18n}`
