### ISSUE TITLE
Background slideshow shifted

### ISSUE THREAD

**Issue by robomechs** [elementor/elementor#13750]
vlasovlab.ru
since 3.1.0 version there is some white space on the left side of landing page (only for background **slideshow**).
After some actions in any browser (for example: extend browser window to full screen or back) it fixing by itself.
[system-info-vlasovlab.ru-30-01-2021.txt](https://github.com/elementor/elementor/files/5898488/system-info-vlasovlab.ru-30-01-2021.txt)

**Comment by robomechs** [comment]
![изображение](https://user-images.githubusercontent.com/8062959/106364702-14081f00-6342-11eb-8907-e7a952a81e50.png)
should be:
![изображение](https://user-images.githubusercontent.com/8062959/106364717-2c783980-6342-11eb-8747-2551ce8695c9.png)

**Comment by DorShahar** [comment]
Hi 
We are aware of the bug and the fix will be released in the upcoming version. 

Thanks.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.1.1

Feel free to update

Thanks!

**Comment by kostasstavridis** [comment]
I am still facing the same issue, although i have updated to version 3.1.1

**Comment by robomechs** [comment]
Good. Fixed for me.
