### ISSUE TITLE
Problem loading editor in multisite env with nested big URLs

### ISSUE THREAD

**Issue by edemir206** [elementor/elementor#13789]
## Prerequisites

- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x ] The issue still exists against the latest stable version of Elementor.

## Description

Hello Elementor gurus,

We are facing a very weird problem in after updating to **Elementor > 3.0 and higher**, when we click on "**Edit with Elementor**" or **create a new post with Elementor** the Editor freezes. 

We **use a multisite setup with nested subfolders structure (sunrise)** (mysite.com/first-level/sub-level/another-level/my-website) and after investigating a little bit I found that websites with big URL length (> 64 chars) are the cause of the issue.

I duplicated the same site for example: **mysite.com/first-level/sub-level/another-level/my-blog** to **mysite.com/my-blog** and the error doesn't happen, or **if you just rename the website the error disappear**.

After debuggin I found that the problem lies here: https://github.com/elementor/elementor/blob/2b10906817663259f8a55753c0edf23e86fb8799/core/common/modules/connect/apps/base-app.php#L230 

When calling **\Requests_IDNAEncoder::encode** you can't have a URL name that has more than 64 chars, which breaks the editor, so I don't think the "encode" method should be used for getting the admin_url address.

## Steps to reproduce

1) Create a WordPress Multisite Setup
2) Install Elementor
3) Create a very big blog name (example: example.com/look-at-how-big-this-website-name-is-it-will-break-elementor)
4) Create an Elementor page in this website, the Elementor editor will not load.

## Isolating the problem

- [ x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x ] This bug happens with a default WordPress theme active.
- [ x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
https://pastebin.com/J1XLfBgY
</details>

**Comment by edemir206** [comment]
NO ONE IS GONNA GIVE ANY ATTENTION TO THIS BIG ISSUE ?

**Comment by dd32** [comment]
Hi team,

Using `\Requests_IDNAEncoder::encode()` here seems like an odd choice, I'm not entirely sure it would have ever been correct..
Looking at the original commit, https://github.com/elementor/elementor/commit/dfa24951286c67f0d2f44c07fa6944c0dba7ba08 it seems like there is good reason for it (even though I still think it's incorrect and probably an error at some other layer of the auth flow).

Nevertheless, `Requests_IDNAEncoder::encode()` throws exceptions that aren't being caught here, and more importantly, `Requests_IDNAEncoder::encode()` only operates on the hostname, not an entire URI, and is limited to 64char components (ie. `64char.64char.org`)

**Comment by TIIUNDER** [comment]
Lol, guys. Why is this closed? What is the solution now?

**Comment by TIIUNDER** [comment]
Just fyi: This is still an issue

**Comment by dvmuccillo** [comment]
Hello, any ETA on this?
Do we have an workaround, unnoficial patch or our only solution is uninstall Elementor when we face this issue?

**Comment by TIIUNDER** [comment]
Looks like this was fixed, but `\Requests_IDNAEncoder::encode()` still used here an causing issues: `/elementor/core/utils/str.php`

**Comment by dvmuccillo** [comment]
> Looks like this was fixed, but `\Requests_IDNAEncoder::encode()` still used here an causing issues: `/elementor/core/utils/str.php`

Was testing with 3.4.0, updated to 3.4.2 and still have the issue.
Seems like they just moved the problem around. :/

**Comment by Metromas** [comment]
same issues ....

**Comment by alexstewartja** [comment]
This issue is being taken for a joke.

Here's a quick hot-patch:

```php
function elementor_idn_url_patch_it_like_its_hot() {
	$className = 'Elementor\Core\Utils\Str';
	if ( class_exists( $className ) ) {
		$classFileName = ( new \ReflectionClass( $className ) )->getFileName();
		if ( is_writable( $classFileName ) ) {
			$classFileContents   = file_get_contents( $classFileName );
			$searchContents      = '\Requests_IDNAEncoder::encode( $matches[2] )';
			$replacementContents = '$matches[2]';

			if ( strpos( $classFileContents, $searchContents ) !== false ) {
				file_put_contents( $classFileName, str_replace( $searchContents, $replacementContents, $classFileContents ) );
			}
		}
	}
}
```

**Comment by fausantosdev** [comment]
Hey my friends, the solution is:

1 - Open the file "\wp-includes\Requests\IDNAEncoder.php"

2 - Look for the code snippet "if (strlen($string) < 64)" in  function "to_ascii" and change the value 54 to a higher value, 500 for example

3 - Save

As a thank you, enter my profile and give a little star to all my projects, thank you. haha

**Comment by TIIUNDER** [comment]
This bug still exists

**Comment by medkhalilbk** [comment]
> I fix this bug by changing line 37 : `const MAX_LENGTH = 64;` by `const MAX_LENGTH = 180;`
> 
> in /wp-includes/Requests/src/IdnaEncoder.php

Thanks it works for me!

**Comment by OlaIola** [comment]
Modifying core files is the wrong approach, and as @dd32 mentioned, the usage of the core method is incorrect in this case, so, the plugin should be fixed and not the core. I just stumbled on this issue myself. We have WordPress with Elementor in a subfolder with a very long URL that has no characters to encode, but we have a fatal error and are unable to enter the admin.

**Comment by viewportdesign** [comment]
I think I know what the issue here probably is - I opened another ticket for this here: 
https://github.com/elementor/elementor/issues/29423

**Comment by viewportdesign** [comment]
> Modifying core files is the wrong approach, and as @dd32 mentioned, the usage of the core method is incorrect in this case, so, the plugin should be fixed and not the core. I just stumbled on this issue myself. We have WordPress with Elementor in a subfolder with a very long URL that has no characters to encode, but we have a fatal error and are unable to enter the admin.
-> exactly it needs to be fixed within elementor
