### ISSUE TITLE
Custom Code (Elementor Pro 3.1.0) - location/priority not updating after being initially published

### ISSUE THREAD

**Issue by euene** [elementor/elementor#13971]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The "Custom Code" function that landed in Elementor Pro 3.1.0 is a great idea, but it doesn't work correctly at the moment. 

Currently, there are 2 major issues:
- There's a serious bug with code location not updating correctly once being changed after the "Custom Code" is published. If you publish a new piece of Custom Code and choose its location to be `<head>` but after publishing you decide to change it to `"<body> - Start"` or `"<body> - End"` - the code will still stay in the `<head>` and will not be moved to the `<body>`. This error also works if you publish a code that should be located in the body but later change it to the head - it will still stay in the body.

- There is absolutely no way to print any code/scripts after the default bundled jQuery core and jQuery UI from WordPress - therefore all Custom Code JavaScript has to be written in plain/vanilla and can't take advantage of any jQuery. Custom code written in jQuery will only work for logged-in users since in that scenario jQuery is being enqueued in the `<head>`, but when logged-out - jQuery will be enqueued in the footer and the custom code will always load before jQuery and errors such as `Uncaught ReferenceError: jQuery is not defined at (index):1073` will be generated in Developer Tools console. I'm not sure what priority jQuery is enqueued by default, but we either need more than the Elementor's Custom Code select field for priority that goes to a maximum of 10 - we either need higher priority options or we need a text field rather than a select field so that we can freely enter a sufficiently large number. On a related note, there's no way to add code after any of Elementor's JavaScript files either - as any Custom Code with `"<body> - End"` and a priority of 10 will still be added before Elementor's JavaScript. There should be a way to add code after anything else enqueued by WordPress core or Elementor or any other plug-in in order to make use of functions added by these scripts, or to override these scripts.

### Issue 1 - location bug:

1. Create new Elementor Pro Custom code
- Title: Head Code 1
- Location: `<head>`
- Priority 1
- Content: `<script>console.log('hello');</script>`

2. Publish -> Include -> Entire Site - Save & Close

3. Change the Location from `<head>` to `"<body> - Start"` or `"<body> - End"` and Update.

**Result:** The `<script>console.log('hello');</script>` is still in the `<head>` - but it moves down the lowest in the `<head>` and under any other Custom Elementor `<head>` code even with priority 10.

### Issue 2 - not high enough priority to be the last code after jQuery

1. Create new Elementor Pro Custom code
- Title: jQuery Test code
- Location: `"<body> - End"`
- Priority 10
- Content: `<script>jQuery('body').addClass('test');</script>`

2. Publish -> Include -> Entire Site - Save & Close

3. Log out from WordPress and go to the homepage

**Result:** `Uncaught ReferenceError: jQuery is not defined at (index):1073`

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

WordPress 5.6.1

Only plug-ins active:
Elementor 3.1.1
Elementor Pro 3.1.0

Active theme:
Hello Elementor 2.3.1

Server:
PHP 7.4.15
Apache/2.4.46
MariaDB 10.5.8

**Comment by euene** [comment]
@shilo-ey Please take a look, thank you.

**Comment by iNewLegend** [comment]
The priority does not effect the order against the scripts, there should be 'New' location after scripts.

**Comment by shilo-ey** [comment]
Hey all,

This issue has been resolved in Elementor Pro v3.2.0

Feel free to update!

**Comment by adilmchoudhury** [comment]
Issue 2 - not high enough priority to be the last code after jQuery

This is not yet solved. Please update us on this.

**Comment by euene** [comment]
Because this issue was solved but the second problem wasn't actually resolved - I created a new issue regarding custom code not having high enough priority to be after jQuery.

This is now issue #14266
