### ISSUE TITLE
Navigator Indicators don't show up

### ISSUE THREAD

**Issue by hsoroka** [elementor/elementor#14094]
I am NEVER seeing Navigator Indicators.

I have several widgets with custom CSS code, which should be indicated by the presence of a blue vertical stripe at the right edge of these widgets' lines in the Navigator. This is NEVER happening.

I am using the Elementor Pro 3.1.2 (the problem existed on 3.1.1 as well), with Safari (MacOS) and Chrome. I have tried this with custom CSS for Elementor's Shortcode widget and Text widget, applied under the Advanced tab of the Editor. I have resized and moved the Navigator, I have changed user preferences between Light, Dark, and automatic.

I cannot imagine what I am doing wrong, but I would love for this to be my fault, and correctable, but the the best of my ability to tell, this is a bug.

I'm happy to test further, if anyone can steer me toward a specific thing to try.

**Comment by DorShahar** [comment]
Thank you for reporting.
We were able to reproduce this and we will act to fix it.

Thanks

**Comment by hsoroka** [comment]
Hi Dor_S,

I would be happy to assist in testing your fix, if you like. Otherwise, I look forward to it in the next release!

THANKS!

Howard

**Comment by alexcumbers** [comment]
Is this fixed in v3.1.3 or waiting for 3.1.4?

**Comment by hsoroka** [comment]
Not fixed yet. I'm using Elementor 3.1.3 and Pro 3.1.1.

**Comment by hsoroka** [comment]
This is still not working with Elementor 3.1.4 and Elementor Pro 3.2.1.

Dor_S, any idea when we can expect it to be fixed?

Thanks...

HS

**Comment by hsoroka** [comment]
Dor_S, this is still not working, but I can add this: Rolling back Wordpress to version 5.4.2 fixes this problem, and also fixes the pagination problem described in GitHub #12126.

Rolling back Wordpress is not a good solution, but hopefully this is helpful.

**Comment by DorShahar** [comment]
Hi 
The fix will take place in the next release. 

Thank you for your patient, and for the report on the bug.

**Comment by hsoroka** [comment]
Thanks, Dor-S.

Do you know if there will also be a fix for the Posts widget pagination bug, described in #12126, in the next release?

I have a bit more precise information for you about when both of these bugs started:

The disappearance of Navigator Indicators began with the release of Wordpress 5.6. 
The Posts widget pagination problem (#12126) was introduced by Wordpress 5.5.

Thanks!

**Comment by DorShahar** [comment]
Hey all,

This issue has been resolved in Elementor v3.2.0

Feel free to update!

@hsoroka  - as for #12126, I reopened the issue. We will investigate and fix it if needed. 

Thanks.
