### ISSUE TITLE
[BUG] - Elementor Pro - "New translations are available" will not go away no matter how many times you confirm the update

### ISSUE THREAD

**Issue by MichaelDarko** [elementor/elementor#14297]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description and Steps to reproduce

There seems to be a bug related to Elementor Pro translation updates. 

**This bug started happening on all my Elementor websites sometime after the latest Elementor updates or WordPress 5.7 update.** 
______________________

### 3. But when I reload the update page, the "New translations are available" is still there. Every single time I reload the page.
______________________

The update notice for Elementor Pro translations simply won't go away.

I've clicked on the update about 20 times, it always shows "Translation updated successfully.", but the update notice never goes away.

I checked the .po and .mo files and they are being updated every time I click on "Update translations". But there is no change to the files, Elementor Pro just rewrites the same files with the same files and the "New translations are available" notice will simply not go away.

So there is some new bug causing Elementor Pro showing "New translations are available" notice that is there nonstop no mater how many times you confirm the update.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.6.41-84.1
	PHP Version: 7.4.14
	PHP Max Input Vars: 10000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7
	Site URL: https://beta.mbdemo.cz
	Home URL: https://beta.mbdemo.cz
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Prague
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.3.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.1.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.2.0
		Author: Elementor.com


== Must-Use Plugins ==
	installatron_hide_status_test.php
		Version: 
		Author: 


== Elementor - Compatibility Tag ==
	
	Elementor Pro: compatible

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	archive : 2
		archive-posts : 3
		heading : 1
		shortcode : 1
		theme-archive-title : 2
	footer : 2
		button : 1
		facebook-page : 1
		form : 1
		heading : 6
		icon : 1
	header : 1
		button : 1
		image : 5
		nav-menu : 6
		search-form : 5
		social-icons : 5
		woocommerce-menu-cart : 2
	page : 3
		button : 17
		facebook-page : 1
		form : 1
		heading : 31
		html : 7
		icon : 6
		icon-list : 1
		image : 8
		posts : 10
		shortcode : 3
		woocommerce-products : 7
	product : 0
		button : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-content : 1
		woocommerce-product-images : 1
		woocommerce-product-meta : 1
		woocommerce-product-price : 1
		woocommerce-product-related : 1
		woocommerce-product-title : 1
	section : 4
		button : 6
		heading : 25
		html : 16
		icon : 5
		image : 26
	single : 2
		facebook-comments : 1
		heading : 3
		post-info : 3
		posts : 1
		share-buttons : 2
		shortcode : 4
		theme-post-content : 2
		theme-post-featured-image : 3
		theme-post-title : 9
	wp-page : 2
		button : 18
		form : 1
		heading : 26
		html : 15
		icon : 4
		image : 25
		slides : 1
		text-editor : 1
		woocommerce-products : 3
		wp-widget-nav_menu : 2
	product-archive : 0
		theme-archive-title : 1
		wc-archive-products : 1


== Log ==
	
Log: showing 20 of 402021-03-02 14:37:38 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Start  
2021-03-02 14:37:38 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2021-03-02 14:37:38 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Start  
2021-03-02 14:37:38 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2021-03-02 14:37:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.2',
  'to' => '3.1.1',
)]
2021-03-02 14:37:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.2',
  'to' => '3.1.1',
)]
2021-03-03 18:08:30 [info] elementor::elementor_updater Started 
2021-03-03 18:08:30 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2021-03-03 18:08:30 [notice] General Settings already exist. nothing to do. 
2021-03-03 18:08:30 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2021-03-03 18:08:30 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2021-03-03 18:08:30 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2021-03-03 18:08:30 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2021-03-03 18:08:30 [notice] Custom colors already exist. nothing to do. 
2021-03-03 18:08:30 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2021-03-03 18:08:30 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2021-03-03 18:08:30 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2021-03-03 18:08:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.1',
  'to' => '3.1.3',
)]
2021-03-14 16:50:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.3',
  'to' => '3.1.4',
)]
2021-03-19 02:14:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.1',
  'to' => '3.2.0',
)]

PHP: showing 3 of 3PHP: 2021-03-02 15:06:19 [notice X 2][/data/web/virtuals/202311/virtual/www/domains/eshop.mbdemo.cz/wp-content/plugins/elementor/includes/template-library/classes/class-import-images.php::154] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-03 16:44:07 [notice X 3][/data/web/virtuals/202311/virtual/www/domains/eshop.mbdemo.cz/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-18 17:40:32 [notice X 6][/data/web/virtuals/202311/virtual/www/domains/eshop.mbdemo.cz/wp-content/plugins/elementor-pro/modules/woocommerce/classes/products-renderer.php::160] Trying to get property 'taxonomy' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

```
</details>

**Comment by Webtica** [comment]
Having the same issue here.

**Comment by MichaelDarko** [comment]
The bug is still there after updating to Elementor Pro 3.2.

**Comment by MichaelDarko** [comment]
@Webtica What language is it in you case?

**Comment by MichaelDarko** [comment]
Tested with other plugins and translations for other plugins complete and do not reappear. Only Elementor Pro translations never go away despite being completed successfully every time.

Each time I confirm the update, these files are regenerated in the languages/plugins folder:

(Changed to txt format so I can upload to GitHub)

[elementor-pro-cs_CZ.mo.txt](https://github.com/elementor/elementor/files/6184635/elementor-pro-cs_CZ.mo.txt)
[elementor-pro-cs_CZ.po.txt](https://github.com/elementor/elementor/files/6184636/elementor-pro-cs_CZ.po.txt)

So something on Elementor's end is calling for updates and for some reason Elementor constantly indicates there is new version of these files, which there is not. Just the same files being rewritten over and over again.

Would be nice if you could fix it asap, constant update notice you can't get rid of is not great if you have clients.

**Comment by EZChris** [comment]
I to can replicate this tried rolling back removing and reinstalling 
my lanuage is english GB but have the same issue on a good proportion of my sites.

**Comment by MichaelDarko** [comment]
Ok, it's a widespread bug, just saw other people complaining about it in Facebook group. It's happening on 80% of my sites. Not all of them, but on most.

**Comment by EZChris** [comment]
Thanks MichaelDarko!

Had messaged elementor about it and got a response about trying to reinstall the plugin - had already tried this but, tried again still no resolve so thanks for the update

**Comment by Webtica** [comment]
Im still having this issue. any ideas what @shilo-ey

**Comment by MichaelDarko** [comment]
Same here. I'm constantly getting requests from my clients to fix it. Elementor support told me they're aware of the bug, but since it's on Github, it's up to the devs to notice it. So the chances this is gonna get noticed or fixed are pretty slim from my experience.

**Comment by alx314** [comment]
I was gonna write about that bug...but I see it's been done here.
Confirming as well on my side for Japanese. 
(Though I would guess it's regardless of any language ?)

**Comment by jormeer** [comment]
+1 dutch language

**Comment by alx314** [comment]
It would seem that....it is solved? Up to date now.

**Comment by MichaelDarko** [comment]
It's not solved. On some of my websites, it can randomly stop happening, but it's still happening on most of my websites. Unless Elementor does something about it, it's not going to fix itself.

**Comment by Bovelett** [comment]
+1, German.

**Comment by zeinnicholas** [comment]
+1 for pt_br

**Comment by Webtica** [comment]
Still the same issue. When will we see a fix for this? It's getting quite annoying.

**Comment by Tecology** [comment]
Same issue here across all client sites. Any chance Elementor? I really don't understand why you don't fix the most basic problems in a timely manner.

**Comment by RipGill** [comment]
Same issue here. Is there any chance that this will get fixed anytime soon? Can we get some feedback from a dev. please?

**Comment by MichaelDarko** [comment]
Elementor needs to hire some bug hunters. Programmers, who spend all their time hunting and fixing small bugs reported here. The main devs don't have time for it, nor should they. Valid bug reports should be treasured, not ignored for ages.

Now imagine most companies don't have a community that finds bugs for them for free. And they still do a better job at fixing bugs than Elementor. :-/

**Comment by Tecology** [comment]
Hi guys, thought I would provide an update here. I spun up a new WP install with just Ele and Ele Pro on it, no caching and documented it all and sent it to the support team. I also spun up new installs on Siteground, Vultr and Digital Ocean servers and the same issue occurs. Just received an email back from Elementor this morning confirming they can replicate this issue with Ele Pro on their own staging environment and their developers are now working to fix the issue and it will be addressed in the next Ele Pro update. Help this may be of some help, there was no timeframe provided but at least it is being acknowledged and there is a fix coming down the line for it.

**Comment by jormeer** [comment]
> Hey all, please try to update to the latest Elementor Pro version and let us know if the issue resolved.
> 
> Thanks

i just checked on a couple of websites. Cleared cache etc but the issue still exists. I click update translations it looks like it updates and then I refresh the page, and it shows again an update. This is for Dutch language

**Comment by EZChris** [comment]
I can confirm that this still exists also in GB all updated as you stated appears to disappear but then returns the same.

**Comment by Tecology** [comment]
It’s slightly better but by no means fixed. I changed all of my sites back to English (US) and even at that I still have a few bringing up core errors because of the same issue:

***@***.***D75CAD.97AC5470]

From: EZChris ***@***.***>
Date: Tuesday, 8 June 2021 at 8:58 pm
To: elementor/elementor ***@***.***>
Cc: Tony Baker ***@***.***>, Comment ***@***.***>
Subject: Re: [elementor/elementor] [BUG] - Elementor Pro - "New translations are available" will not go away no matter how many times you confirm the update (#14297)

I can confirm that this still exists also in GB all updated as you stated appears to disappear but then returns the same.

**Comment by shilo-ey** [comment]
Can you please share administrator credentials for one site that you have in dev environment for us to inspect?

Please share details here: cazodoji@altmails.com (temp mailbox) 

Thanks

**Comment by Webtica** [comment]
When will this be fixed? This is getting quite anoying. 
If you need any info im happy to help @shilo-ey.

**Comment by jormeer** [comment]
> Can you please share administrator credentials for one site that you have in dev environment for us to inspect?
> 
> Please share details here: [cazodoji@altmails.com](mailto:cazodoji@altmails.com) (temp mailbox)
> 
> Thanks

I did send my login info a week ago. hope this helps

**Comment by shilo-ey** [comment]
We are trying to identify the cause of this issue and will fix this soon

**Comment by EZChris** [comment]
Randomly all my warnings have gone away today?

Can anyone else say the same?

**Comment by parodev** [comment]
No, still there on my Elementor sites

**Comment by MichaelDarko** [comment]
Still there.

**Comment by RipGill** [comment]
All fine for me now.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.3.3

Feel free to update

Thanks!

**Comment by dalguji** [comment]
@shilo-ey That's a great news but the available version I can download from https://my.elementor.com/subscriptions/ is `Elementor Pro 3.3.1` at the moment. How can I get `Elementor Pro v3.3.3`? I have `Elementor Pro - Expert` license.

**Comment by AndreiGhitan** [comment]
Just go to /wp-content/languages/plugins/ and add the required translation. I added .txt ad the end to eb able to upload them here. Just remove the .txt extension and upload it as required

[elementor-pro-ca.mo.txt](https://github.com/elementor/elementor/files/13416222/elementor-pro-ca.mo.txt)
[elementor-pro-ar.mo.txt](https://github.com/elementor/elementor/files/13416223/elementor-pro-ar.mo.txt)
[elementor-pro-ar.po.txt](https://github.com/elementor/elementor/files/13416224/elementor-pro-ar.po.txt)
[elementor-pro-bg_BG.mo.txt](https://github.com/elementor/elementor/files/13416225/elementor-pro-bg_BG.mo.txt)
[elementor-pro-bg_BG.po.txt](https://github.com/elementor/elementor/files/13416226/elementor-pro-bg_BG.po.txt)
[elementor-pro-ca.po.txt](https://github.com/elementor/elementor/files/13416227/elementor-pro-ca.po.txt)
[elementor-pro-cs_CZ.mo.txt](https://github.com/elementor/elementor/files/13416229/elementor-pro-cs_CZ.mo.txt)
[elementor-pro-cs_CZ.po.txt](https://github.com/elementor/elementor/files/13416232/elementor-pro-cs_CZ.po.txt)
[elementor-pro-da_DK.mo.txt](https://github.com/elementor/elementor/files/13416234/elementor-pro-da_DK.mo.txt)
[elementor-pro-da_DK.po.txt](https://github.com/elementor/elementor/files/13416235/elementor-pro-da_DK.po.txt)
[elementor-pro-de_DE.mo.txt](https://github.com/elementor/elementor/files/13416236/elementor-pro-de_DE.mo.txt)
[elementor-pro-de_DE.po.txt](https://github.com/elementor/elementor/files/13416237/elementor-pro-de_DE.po.txt)
[elementor-pro-en_GB.mo.txt](https://github.com/elementor/elementor/files/13416238/elementor-pro-en_GB.mo.txt)
[elementor-pro-en_GB.po.txt](https://github.com/elementor/elementor/files/13416239/elementor-pro-en_GB.po.txt)
[elementor-pro-es_ES.mo.txt](https://github.com/elementor/elementor/files/13416240/elementor-pro-es_ES.mo.txt)
[elementor-pro-es_ES.po.txt](https://github.com/elementor/elementor/files/13416241/elementor-pro-es_ES.po.txt)
[elementor-pro-fa_IR.mo.txt](https://github.com/elementor/elementor/files/13416242/elementor-pro-fa_IR.mo.txt)
[elementor-pro-fa_IR.po.txt](https://github.com/elementor/elementor/files/13416244/elementor-pro-fa_IR.po.txt)
[elementor-pro-fi.mo.txt](https://github.com/elementor/elementor/files/13416246/elementor-pro-fi.mo.txt)
[elementor-pro-fi.po.txt](https://github.com/elementor/elementor/files/13416247/elementor-pro-fi.po.txt)
[elementor-pro-fr_FR.mo.txt](https://github.com/elementor/elementor/files/13416248/elementor-pro-fr_FR.mo.txt)
[elementor-pro-fr_FR.po.txt](https://github.com/elementor/elementor/files/13416249/elementor-pro-fr_FR.po.txt)
[elementor-pro-he_IL.mo.txt](https://github.com/elementor/elementor/files/13416250/elementor-pro-he_IL.mo.txt)
[elementor-pro-he_IL.po.txt](https://github.com/elementor/elementor/files/13416251/elementor-pro-he_IL.po.txt)
[elementor-pro-hu_HU.mo.txt](https://github.com/elementor/elementor/files/13416252/elementor-pro-hu_HU.mo.txt)
[elementor-pro-hu_HU.po.txt](https://github.com/elementor/elementor/files/13416253/elementor-pro-hu_HU.po.txt)
[elementor-pro-it_IT.mo.txt](https://github.com/elementor/elementor/files/13416254/elementor-pro-it_IT.mo.txt)
[elementor-pro-it_IT.po.txt](https://github.com/elementor/elementor/files/13416255/elementor-pro-it_IT.po.txt)
[elementor-pro-ja.mo.txt](https://github.com/elementor/elementor/files/13416256/elementor-pro-ja.mo.txt)
[elementor-pro-ja.po.txt](https://github.com/elementor/elementor/files/13416257/elementor-pro-ja.po.txt)
[elementor-pro-nb_NO.mo.txt](https://github.com/elementor/elementor/files/13416258/elementor-pro-nb_NO.mo.txt)
[elementor-pro-nb_NO.po.txt](https://github.com/elementor/elementor/files/13416259/elementor-pro-nb_NO.po.txt)
[elementor-pro-nl_NL.mo.txt](https://github.com/elementor/elementor/files/13416260/elementor-pro-nl_NL.mo.txt)
[elementor-pro-nl_NL.po.txt](https://github.com/elementor/elementor/files/13416261/elementor-pro-nl_NL.po.txt)
[elementor-pro-pl_PL.mo.txt](https://github.com/elementor/elementor/files/13416262/elementor-pro-pl_PL.mo.txt)
[elementor-pro-pl_PL.po.txt](https://github.com/elementor/elementor/files/13416263/elementor-pro-pl_PL.po.txt)
[elementor-pro-pt_BR.mo.txt](https://github.com/elementor/elementor/files/13416264/elementor-pro-pt_BR.mo.txt)
[elementor-pro-pt_BR.po.txt](https://github.com/elementor/elementor/files/13416265/elementor-pro-pt_BR.po.txt)
[elementor-pro-pt_PT.mo.txt](https://github.com/elementor/elementor/files/13416266/elementor-pro-pt_PT.mo.txt)
[elementor-pro-pt_PT.po.txt](https://github.com/elementor/elementor/files/13416267/elementor-pro-pt_PT.po.txt)
[elementor-pro-ro_RO.mo.txt](https://github.com/elementor/elementor/files/13416269/elementor-pro-ro_RO.mo.txt)
[elementor-pro-ro_RO.po.txt](https://github.com/elementor/elementor/files/13416270/elementor-pro-ro_RO.po.txt)
[elementor-pro-ru_RU.mo.txt](https://github.com/elementor/elementor/files/13416271/elementor-pro-ru_RU.mo.txt)
[elementor-pro-ru_RU.po.txt](https://github.com/elementor/elementor/files/13416272/elementor-pro-ru_RU.po.txt)
[elementor-pro-sk_SK.mo.txt](https://github.com/elementor/elementor/files/13416273/elementor-pro-sk_SK.mo.txt)
[elementor-pro-sk_SK.po.txt](https://github.com/elementor/elementor/files/13416274/elementor-pro-sk_SK.po.txt)
[elementor-pro-sr_RS.mo.txt](https://github.com/elementor/elementor/files/13416275/elementor-pro-sr_RS.mo.txt)
[elementor-pro-sr_RS.po.txt](https://github.com/elementor/elementor/files/13416277/elementor-pro-sr_RS.po.txt)
[elementor-pro-sv_SE.mo.txt](https://github.com/elementor/elementor/files/13416278/elementor-pro-sv_SE.mo.txt)
[elementor-pro-sv_SE.po.txt](https://github.com/elementor/elementor/files/13416279/elementor-pro-sv_SE.po.txt)
[elementor-pro-tr_TR.mo.txt](https://github.com/elementor/elementor/files/13416281/elementor-pro-tr_TR.mo.txt)
[elementor-pro-tr_TR.po.txt](https://github.com/elementor/elementor/files/13416282/elementor-pro-tr_TR.po.txt)
[elementor-pro-uk.mo.txt](https://github.com/elementor/elementor/files/13416283/elementor-pro-uk.mo.txt)
[elementor-pro-uk.po.txt](https://github.com/elementor/elementor/files/13416284/elementor-pro-uk.po.txt)
[elementor-pro-vi.mo.txt](https://github.com/elementor/elementor/files/13416285/elementor-pro-vi.mo.txt)
[elementor-pro-vi.po.txt](https://github.com/elementor/elementor/files/13416286/elementor-pro-vi.po.txt)
[elementor-pro-zh_TW.mo.txt](https://github.com/elementor/elementor/files/13416288/elementor-pro-zh_TW.mo.txt)
[elementor-pro-zh_TW.po.txt](https://github.com/elementor/elementor/files/13416289/elementor-pro-zh_TW.po.txt)

**Comment by cashewcoding** [comment]
@AndreiGhitan Would you or anyone else happen to have the latest versions of the translations? I have this error again now and it doesn't go away. Updating the translations just won't work. And the ones you posted here seem to be outdated by now. Thanks!

**Comment by natko1** [comment]
This issue is happening again @shilo-ey

**Comment by nicholaszein** [comment]
Hello @cashewcoding,

can you tell us what language appears for you?

@natko1, we are aware a few languages are failing to download, and we are already working on it. We don't have an ETA at the moment, but it should be fixed in the near future.

Currently, these are the languages that are failing to download:

- English (South Africa) (en_ZA)
- English (Canada) (en_CA)
- French (Belgium) (fr_BE)

If your language is not on this list, please let us know!

Kind regards

**Comment by mapsmarketing** [comment]
`en_AU` having issues updating as well @nicholaszein 

This is happening across 53 websites we manage.

<img width="458" alt="image" src="https://github.com/elementor/elementor/assets/79551469/e54b5e05-f076-4330-8db2-57ac3fa63f62">

**Comment by nicholaszein** [comment]
Thanks @mapsmarketing, we are aware en_AU is also not downloading. The fix is under way! 😉 

(I've updated my list on my comment above)

**Comment by mapsmarketing** [comment]
Thank you very much @nicholaszein ! Much appreciated.

**Comment by iiaammyyaall** [comment]
![Screenshot 2024-05-24 at 9 19 28 AM](https://github.com/elementor/elementor/assets/153834854/0958bf3a-bbb2-4833-88ae-4a34775c27d9)

Translation is not loading.

**Comment by nicholaszein** [comment]
@iiaammyyaall .

See my comment above...

https://github.com/elementor/elementor/issues/14297#issuecomment-2115599714

**Comment by mapsmarketing** [comment]
Hi @nicholaszein ,

Just noticed the issue has been closed, but the issue still persists, and we were wondering at which point this will be fixed?

We are running Elementor v3.21.8 and Elementor Pro v3.21.3

Thank you very much

<img width="370" alt="image" src="https://github.com/elementor/elementor/assets/79551469/1cf1bf3f-4ed2-401e-9494-814d00c3782f">

**Comment by nicholaszein** [comment]
@mapsmarketing this issue was closed when it was solved. Although the problem is similar, it is not the same issue, so this is why I haven't reopened it.

We are working on a fix, but the fix is dependent on other changes that affect other parts of our infrastructure. It's all on our side (nothing to do with the plugin). So until we can make all the changes safely, we are going to be more patient.

**Comment by mapsmarketing** [comment]
Thank you very much on the reply @nicholaszein really appreciate it

**Comment by stephroseg** [comment]
+1 for  > * English Australia (en_AU)

Is there anything I can do to mitigate ? I tried changing the language to US English, but the packs still keep trying to auto-update daily - and also is there an update on an ETA ? 

I'm still investigating this morning on one of my clients sites  - but it looks like the failed update also either conflicts with the GD plugin or causes the site to go into some sort of memory and resource chewing death spiral 


> Hello @cashewcoding,
> 
> can you tell us on what language this issue appears for you?
> 
> @natko1, we are aware a few languages are failing to download, and we are already working on it. We don't have an ETA at the moment, but it should be fixed in the near future.
> 
> Currently, these are the languages that are failing to download:
> 
> * English (South Africa) (en_ZA)
> * English (Canada) (en_CA)
> * French (Belgium) (fr_BE)
> * English Australia (en_AU)
> 
> If your language is not on this list, please let us know!
> 
> Kind regards

**Comment by nicholaszein** [comment]
@stephroseg unfortunately at this time all you can do is to ignore it.

**Comment by ghhv** [comment]
weirdly, on some AU sites it does update and others not..

**Comment by niiiiiiiiiik** [comment]
Still an issue for me all (en_AU) sites
<img width="369" alt="Screenshot 2024-06-27 at 7 57 22 AM" src="https://github.com/elementor/elementor/assets/171989169/a3d218ff-9968-4f7d-b5e2-9057de76e764">

**Comment by ghhv** [comment]
is this affecting anyone else's plugin updates? I'm seemingly randomly getting the same error (on Elementor sites) updating other plugins. Odd.

**Comment by nicholaszein** [comment]
Hello there!

- @cashewcoding
- @natko1 
- @mapsmarketing 
- @iiaammyyaall 
- @stephroseg 
- @niiiiiiiiiik 
- @ghhv 

We have some great news! Last week we made some considerable changes to our translation platform that should have fixed the issue for you. Can you please verify if that's the case?

Please, try updating the translations in your end and let me know. If you can't see them you can do the following:

1. Go to your WordPress **`Dashboard`** > **`Settings`** > **`General`** page and switch the site language to English US (en_US).
2. Save changes and go to your WordPress **`Dashboard`** > **`Updates`** page, and click on **Check again** at the top.
3. After the page refreshes, see if the Update for the English translation appears, and try to update it. It should update normally.
4. Then reproduce step 1, but this time choose your language, then follow steps 2, and 3 to update your language.
5. Please, let me know if it works.

We want to make sure it works for all of your cases. In our tests it worked flawlessly! 🎉 💪 

Thank you for being so patient as we worked through this issue! 🙏 

Kind regards

**Comment by mapsmarketing** [comment]
Thank you very much @nicholaszein 

Can confirm the language errors are fixed across all the websites we manage.

Great work mate

**Comment by nicholaszein** [comment]
Hey, everyone!

I'm passing by to thank you for reporting this (second) issue, and for being so patient while we worked on fixing it. It's been a few weeks now, and it seems everything is back working correctly.

Since we have made significant changes, I'm closing the comments on this issue. If you are still experiencing problems with translation updates for Elementor Pro, please we ask you to open a new issue and follow the instructions in the [Bug Report form](https://elemn.to/gh-new-bug-report).

Thank you all, and thanks @mapsmarketing for confirming it was fixed for you as well!

Best regards!
