### ISSUE TITLE
Normal URL queries are redirected to Elementor templates, and Elementor templates URL are publicly queryable and added to sitemaps

### ISSUE THREAD

**Issue by Nazrinn** [elementor/elementor#14578]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
This seems to be a default behavior with Elementor which bothers me a lot: template "pages" are publicly queryable. For instance, if I was to write `https://mywebsite.com/hero` it would redirect me (the user) to `https://mywebsite.com/?elementor_library=hero`, which is especially problematic as misspelling of pages such as custom posts would lead to a broken page. 

Additionally, it makes that those Elementor templates get added to XML sitemaps, which is not something I'd want crawlers to look for. Those elementor template pages are not pages I'd like to index, and they can cause crawling issues on large website (because they add a significant amount of XML entries).

## Steps to reproduce

For instance, on a real estate website where I'd have a template for listing archives (template name: `Listings`) and individual listings (template name: `Listing`), if I wrote `https://mywebsite.com/listing` instead of `https://mywebsite.com/listings` in the address bar, the website would redirect me to a page of the `Listing` template with no content, under the address `https://mywebsite.com/?elementor_library=listing`.

ALL Elementor templates will be added to XML sitemaps under the queryable url `https://mywebsite.com/?elementor_library=TEMPLATE-NAME`. You can check that using by installing The SEO Framework and look at the automatically generated sitemap. You should see Elementor templates being added at the end of the sitemap like such:

![image](https://user-images.githubusercontent.com/36900693/114951919-514d5a80-9e23-11eb-93b3-fc9b088832d0.png)

## Temporary fix
I have added this quick snippet to my `function.php` file.
```
add_action( 'template_redirect', 'redirect_elementor_template' );
function redirect_elementor_template() {
	$current_url = $_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
	$is_preview = \Elementor\Plugin::$instance->preview->is_preview() ?? false;

  	if ((strpos($current_url, 'preview=1') !== false || $is_preview !== false) == false && strpos($current_url,'?elementor_library') !== false && strpos($current_url,'?elementor_library=listing') == false) {
    	wp_redirect( get_home_url(), 301 );
    	exit;
  	}
}

This works for now, but I am aware this is likely to break in future Elementor versions.
```

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.28
	PHP Version: 8.0.3
	PHP Max Input Vars: 10000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.1
	Site URL: https://barbandcarole.ca
	Home URL: https://barbandcarole.ca
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 1024M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-CA
	Timezone: America/Toronto
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_CA
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.9.5
		Author: Elliot Condon

	Asset CleanUp: Page Speed Booster
		Version: 1.3.7.7
		Author: Gabe Livan

	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Custom Post Type UI
		Version: 1.9.0
		Author: WebDevStudios

	Duplicator
		Version: 1.4.0
		Author: Snap Creek

	Elementor
		Version: 3.1.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.3.0-dev1
		Author: Elementor.com

	Enable Media Replace
		Version: 3.5.0
		Author: ShortPixel

	Image optimization service by Optimole
		Version: 3.0.1
		Author: Optimole

	LiteSpeed Cache
		Version: 3.6.4
		Author: LiteSpeed Technologies

	Phoenix Media Rename
		Version: 3.2.1
		Author: crossi72

	Post Views Counter
		Version: 1.3.4
		Author: Digital Factory

	Simple Custom Post Order
		Version: 2.5.4
		Author: Colorlib

	Site Kit by Google
		Version: 1.30.0
		Author: Google

	SVG Support
		Version: 2.3.18
		Author: Benbodhi

	The SEO Framework
		Version: 4.1.3
		Author: The SEO Framework Team

	Wordfence Security
		Version: 7.5.2
		Author: Wordfence

	Yoast Duplicate Post
		Version: 4.1.2
		Author: Enrico Battocchi & Team Yoast


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Elementor - Compatibility Tag ==
	
	Elementor Pro: compatible

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	archive : 1
		button : 2
		heading : 2
		html : 3
		image : 1
		shortcode : 1
		text-editor : 2
	footer : 1
		form : 1
		heading : 7
		image : 4
		shortcode : 4
		social-icons : 1
		spacer : 1
		text-editor : 6
	header : 1
		nav-menu : 1
		social-icons : 1
		theme-site-logo : 1
	section : 2
		button : 2
		heading : 2
		html : 3
		image : 1
		text-editor : 2
	widget : 0
		html : 85
		shortcode : 55
	wp-page : 5
		button : 23
		counter : 2
		divider : 2
		form : 1
		global : 1
		heading : 44
		html : 60
		image : 16
		media-carousel : 1
		shortcode : 14
		social-icons : 2
		spacer : 17
		text-editor : 32
	single-post : 1
		button : 2
		heading : 6
		html : 5
		image-carousel : 1
		shortcode : 13
		text-editor : 1
		video : 1
	error-404 : 1
		button : 1
		heading : 2
		text-editor : 1


== Log ==
	
Log: showing 16 of 162021-03-01 02:29:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.1',
  'to' => '3.2.0-dev4',
)]
2021-03-02 19:05:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.0-dev4',
  'to' => '3.2.0-dev5',
)]
2021-03-02 19:14:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.1',
  'to' => '3.2.0-dev5',
)]
2021-03-04 00:14:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.0-dev5',
  'to' => '3.2.0-dev6',
)]
2021-03-08 19:27:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.0-dev6',
  'to' => '3.2.0-dev7',
)]
2021-03-08 20:05:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.0-dev5',
  'to' => '3.2.0-dev6',
)]
2021-03-10 22:44:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.0-dev7',
  'to' => '3.2.0-dev8',
)]
2021-03-16 12:27:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.0-dev6',
  'to' => '3.2.0-dev7',
)]
2021-03-16 13:53:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.0-dev7',
  'to' => '3.2.0',
)]
2021-03-17 02:35:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.0',
  'to' => '3.3.0-dev1',
)]
2021-03-22 14:35:34 [info] elementor::elementor_updater Started 
2021-03-22 14:35:34 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2021-03-22 14:35:34 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2021-03-22 14:35:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.0-dev8',
  'to' => '3.2.0-beta1',
)]
2021-03-22 14:35:34 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.0-dev8',
  'to' => '3.2.0-beta1',
)]
2021-04-13 07:49:38 [error] Save submission failed, db error: Table 'emrfro02_main.bcr_e_submissions' doesn't exist 

PHP: showing 20 of 24PHP: 2021-03-12 20:17:04 [warning X 1][/home/emrfro02/public_html\wp-content\plugins\elementor-pro\modules\assets-manager\asset-types\icons\custom-icons.php::180] unlink(briefcase.svg): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-15 04:12:19 [error X 2][/home/emrfro02/public_html\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on bool in /home/emrfro02/public_html\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php:281
Stack trace:
#0 /home/emrfro02/public_html\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/emrfro02/public_html\wp-content\plugins\elementor\core\common\modules\ajax\module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/emrfro02/public_html\wp-includes\class-wp-hook.php(292): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/emrfro02/public_html\wp-includes\class-wp-hook.php(316): WP_Hook->apply_filt [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-17 14:32:45 [error X 2][/home/emrfro02/public_html\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on null in /home/emrfro02/public_html\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php:281
Stack trace:
#0 /home/emrfro02/public_html\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(7, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/emrfro02/public_html\wp-content\plugins\elementor\core\common\modules\ajax\module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/emrfro02/public_html\wp-includes\class-wp-hook.php(292): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/emrfro02/public_html\wp-includes\class-wp-hook.php(316): WP_Hook->apply_filters [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-21 21:18:14 [notice X 162][/home/emrfro02/public_html\wp-content\plugins\elementor\includes\conditions.php::90] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-30 21:36:25 [warning X 70][/home/emrfro02/public_html\wp-content\plugins\elementor\includes\conditions.php::90] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-01 18:09:41 [warning X 1][/home/emrfro02/public_html\wp-content\plugins\elementor-pro\modules\dynamic-tags\acf\tags\acf-url.php::34] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-03 23:29:38 [warning X 1][/home/emrfro02/public_html\wp-content\plugins\elementor-pro\modules\assets-manager\asset-types\icons\custom-icons.php::243] unlink(/home/emrfro02/public_html/wp-content/uploads/2021/04/SVG.zip): Resource temporarily unavailable [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-03 23:30:50 [warning X 1][/home/emrfro02/public_html\wp-content\plugins\elementor-pro\modules\assets-manager\asset-types\icons\custom-icons.php::243] unlink(/home/emrfro02/public_html/wp-content/uploads/2021/04/Fontello.zip): Resource temporarily unavailable [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-06 01:30:20 [notice X 1][/home/emrfro02/public_html\wp-content\plugins\elementor\modules\usage\module.php::146] uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-06 12:22:40 [warning X 1][/home/emrfro02/public_html/wp-content/plugins/elementor-pro/modules/forms/actions/mailchimp.php::210] foreach() argument must be of type array|object, null given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-06 12:24:26 [warning X 1][/home/emrfro02/public_html/wp-content/plugins/elementor-pro/modules/forms/actions/mailchimp.php::189] Undefined array key "email_address" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-10 12:50:25 [warning X 4][/home/emrfro02/public_html/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::101] file_get_contents(/home/emrfro02/public_html/wp-content/uploads/2021/03/crea-logo.svg): Failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-10 12:50:25 [warning X 15][/home/emrfro02/public_html/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::101] file_get_contents(/home/emrfro02/public_html/wp-content/uploads/2021/03/BCRlogo.svg): Failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-11 15:39:57 [warning X 2][/home/emrfro02/public_html/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::101] file_get_contents(/home/emrfro02/public_html/wp-content/uploads/2021/03/the-royal_logomark-logo.svg): Failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-11 15:41:54 [warning X 1][/home/emrfro02/public_html/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::101] file_get_contents(/home/emrfro02/public_html/wp-content/uploads/2021/03/beadonorca_logotype-logo.svg): Failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-11 15:42:35 [warning X 1][/home/emrfro02/public_html/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::101] file_get_contents(/home/emrfro02/public_html/wp-content/uploads/2021/03/childrens-hospital-of-eastern-ontario_logo_monogram.svg): Failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-11 15:43:04 [warning X 1][/home/emrfro02/public_html/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::101] file_get_contents(/home/emrfro02/public_html/wp-content/uploads/2021/03/national-art-centre_logomark-logo.svg): Failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-11 15:46:19 [warning X 1][/home/emrfro02/public_html/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::101] file_get_contents(/home/emrfro02/public_html/wp-content/uploads/2021/03/innovation-logo.svg): Failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-11 16:01:33 [warning X 5][/home/emrfro02/public_html/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::101] file_get_contents(/home/emrfro02/public_html/wp-content/uploads/2021/03/the-royal_logo.svg): Failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-13 02:11:37 [warning X 1][/home/emrfro02/public_html/wp-content/plugins/elementor/includes/managers/image.php::86] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
```
</details>

**Comment by Overbord** [comment]
+1 this is really annoying.

**Comment by KingGrizzly** [comment]
+1 Just started encountering this bug on archive pages. This site has the Jet Crocoblock suite.

**Comment by KingGrizzly** [comment]
Updated: problem was mine. I needed to turn on a slug rewrite for the custom post type. Fixed the issue.

**Comment by Nazrinn** [comment]
@KingGrizzly

So is this an Elementor or a Crocoblock fix?

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.4.0

Feel free to update

Thanks!

**Comment by ghettopro** [comment]
Is it possible that this behavior does reappear?

When placing an order in WooCommerce, it redirects to the following URL:
###URL##?elementor_library=product-grid%2Forder-received%2F1575%2F&key=wc_order_O0pMfccvHM1c3

All versions (core / plugins) are up to date.

**Comment by jpederson** [comment]
Can confirm this is still happening (as to the public querying of library elements that have no place having a publicly queryable slug) in 3.6.7.

**Comment by Eugenewoz** [comment]
Anyone has fixed that issue? I have Japanese SEO hack, and being redirected with Query links to ?elementor_library= which is annoying

**Comment by Agnerk** [comment]
I solved the problem as follows: 

I created a page in the normal Wordpress editor with the slug I want and, after creating the page in the Elementor editor, I set the specific page that I created in normal Wordpress as a condition for the elementor page to appear. 

Thus, the page created in Elementor replaces the original Wordpress page, but does not replace the slug.
