### ISSUE TITLE
Text Editor widget is buggy

### ISSUE THREAD

**Issue by dylzeee** [elementor/elementor#14703]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

![image](https://user-images.githubusercontent.com/59110469/116032791-e1489b00-a692-11eb-84f5-ad170a0df720.png)

When trying to use the live text editor widget on the main page (not on the left sidebar), it doesn't immediately work. There is no cursor and you can't add any text.

I did figure out eventually that if I click in the text edit area on the left sidebar, and then immediately go back to the live on-screen editor, it does work, but there's still no cursor.

This has been reproduced multiple times on a fresh install with only elementor installed and the default theme.

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

Have reproduced this on Nginx and Litespeed web servers.

<summary>System Info</summary>

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.19.6
	MySQL version: mariadb.org binary distribution v10.5.5
	PHP Version: 7.4.14
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.1
	Site URL: http://testing.local
	Home URL: http://testing.local
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 256M
	Permalink Structure: Plain
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty-One
	Version: 1.3
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.2.1
		Author: Elementor.com

== Elementor - Compatibility Tag ==	

== Elements Usage ==

== Log ==

**Comment by d19dotca** [comment]
I can confirm this behaviour my sites too. 

The Text widget is a bit temper-mental in my experience. Works for the most part but every now and then I see some odd behaviour with it. For example, I filed a defect https://github.com/elementor/elementor/issues/14077 over a month ago reporting an inconsistency of <b> and <strong> tags depending on where the text was edited from when trying to bold text.

**Comment by dasigna** [comment]
the text editor widget is buggy ever since ...
since latest update theres no inline editing possible any more at all. each site that was updated so far,

paragraphs come and go to their liking etc. etc.

this was reported in many issues for years. i wonder if anyone has detected any change to the better ...?

**Comment by d19dotca** [comment]
> since latest update theres no inline editing possible any more at all. each site that was updated so far,

Yes I just noticed that last night too. Seems 3.2.2 broke the Text widget even further.

**Comment by alexcumbers** [comment]
Yes, I think this stopped working a few versions ago - v3.1.4 or before.
I just assumed it was no longer an option to edit in content rather than properties panel.
Also, try to place or resize an image within a text box is problematic.
The whole widget needs some refinement.

**Comment by slumbergod** [comment]
I have tried 3.2.0, 3.2.1, and 3.2.2 and I cannot edit text in the visual editor. I cannot select text, double click to select, or insert the cursor to type.
I have tried this on Waterfox Classic, Waterfox G3, and the latest Firefox under Manjaro Linux -- all with the same issue.

Rolling back to 3.1.4 fixes the problem and text editing functionality returns to normal

**Comment by alexcumbers** [comment]
Yes, this widget needs re-testing / fixes.

**Comment by d19dotca** [comment]
A user made a comment in the Pro 3.3 beta where they raised this issue (though not actually related to the 3.3 beta at all), and they mentioned this happens to them when Optimized DOM experiment is enabled. Just a heads up in case others find that disabling that experiment helps at all.

**Comment by slumbergod** [comment]
@d19dotca Thanks for the heads-up!
I disabled Optimized DOM and then upgraded to Elementor 3.2.2 and text editing worked correctly.
Then I upgraded to Elementor 3.3.3 and text editing continued to work properly.
Much appreciated!

**Comment by slumbergod** [comment]
it's great the developers are always working on improving things but I definitely prefer OPT-IN. I didn't know about this experiment yet it was enabled for all of my websites. I prefer not to be a beta tester for my websites.

**Comment by alexcumbers** [comment]
Yes, you would fix it ASAP given there is around 100 developers available.

1-2 people should be dedicated to managing the GitHub page, assigning Tags to Issues, revising the guidelines to creating issues (like provide video loom.com <http://loom.com/> link to demo an issue) and use a better service for feature requests, such as Product Board.

**Comment by phil-beachler-id** [comment]
Confirmed this issue and the "workaround" by disabling Optimize DOM feature. This is not the only time I've had these automatically "opt-in" experimental features hinder or break core Elementor functionality completely. Elementor team, let's get some visibility on this and maybe revisit the approach to rolling out these experimental features.

Thanks!

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.3.0

Feel free to update

Thanks!

**Comment by ianstudio** [comment]
Text block has always been a mess when you try to add hard returns. So fickle it is insane. A hit and miss experience. Sometimes you lose your returns sometimes not.. This is by FAR my biggest frustration with Elementor. What should be simplest has made me wanna punch the wall many times.
You add <br> ;s than switch to Visual mode.. switch back to Text mode, your <br>'s are gone and the text is all linear. All returns are lost.. a complete mess. And it's so fickle, no way to troubleshoot WTF is going on.

And when you use WPML (maybe other translation tools as well) you lose all returns no matter what and have to go back in and re-add <br> 's all overt ht a place.. I N S A N E.

Are you supposes to use a separate text block every time you want a return ??? THAD'd be surreal. Is that what people do to get around this ??!

**Comment by nadworks** [comment]
Massive issue still.
Text editor on some sites not responding at all, not accepting any changes and freezes the page.

**Comment by phkoon** [comment]
Still a mess

**Comment by saviabasil** [comment]
And today, ,the text editor is crashing my website
