### ISSUE TITLE
Form Submissions don't collect the value from radio/checkbox fields using label|value format

### ISSUE THREAD

**Issue by gerardreches** [elementor/elementor#15237]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Different types of fields from the **Form widget** allow us to introduce multiple values using a `label|value` format.

<img width="249" alt="Screen Shot 2021-06-07 at 15 06 11" src="https://user-images.githubusercontent.com/7549815/120981484-e88aba80-c7a1-11eb-88c8-3b6f2c9fc31d.png">

This isn't working with the **Submissions** feature. When using this format to separate the label and the value, the submitted values won't be saved (or at least shown) in **Submissions**.

## Steps to reproduce

1. Create a form with the Form widget and add a radio, checkbox or select field. Add multiple options, one on each line, using the `label|value` format. 
2. Activate collect submissions
3. Activate Email
4. Make the form send [all-fields] to your email when sent
3. Fill and send the form
4. Check the email received, you will find that the `value` part from `label|value` was sent.
5. Now check the Submissions and open the newly collected submission. Those values won't be there and they will show up blank as if they hadn't been filled when the form was sent.

## Form field with same text for label and value
<img width="279" alt="Screen Shot 2021-06-07 at 14 56 02" src="https://user-images.githubusercontent.com/7549815/120980117-7c5b8700-c7a0-11eb-94aa-1fa691147fb4.png">
Form field
<img width="370" alt="Screen Shot 2021-06-07 at 15 01 34" src="https://user-images.githubusercontent.com/7549815/120980888-436fe200-c7a1-11eb-81b9-83c914de54a3.png">
Received email contains the selection
<img width="391" alt="Screen Shot 2021-06-07 at 14 56 29" src="https://user-images.githubusercontent.com/7549815/120980167-8c736680-c7a0-11eb-9263-67d3404bf870.png">
Value gets collected in Submissions

## Form field with different text for label and value, using `label|value` format
<img width="285" alt="Screen Shot 2021-06-07 at 14 57 59" src="https://user-images.githubusercontent.com/7549815/120980384-c3497c80-c7a0-11eb-8b95-8a68da07092e.png">
Form field
<img width="357" alt="Screen Shot 2021-06-07 at 14 59 59" src="https://user-images.githubusercontent.com/7549815/120980681-0dcaf900-c7a1-11eb-85e6-82986812be1e.png">
Received email contains the value of the selection
<img width="377" alt="Screen Shot 2021-06-07 at 14 58 20" src="https://user-images.githubusercontent.com/7549815/120980431-cf353e80-c7a0-11eb-8d0c-c91919b6c977.png">
Value doesn't get collected in Submissions

**Comment by gerardreches** [comment]
After further testing, the values seem to be stored (they are there when I export the submissions as CSV) but **filled values of fields with `label|value` options are not shown** in the submission page.

**Comment by gerardreches** [comment]
This issue has been resolved in Elementor Pro v3.3.1

**Comment by bytes-web** [comment]
Hello,
The same issue occurs with Elementor 3.17.3 and Elementor Pro 3.17.1. The Email is correct but the Submissions in WordPress are not, they appear always unselected.

**Comment by skipbrannan** [comment]
I'm having the same issue with Elementor 3.18.3 and Elementor Pro 3.18.1.

**Comment by e-popotam** [comment]
Hi, I'm having the same issue Elementor 3.20.2 and Elementor Pro 3.20.1. 

Has anyone found a solution to correct the problem?

Thanks

**Comment by Kalsers** [comment]
I got the same problem with Elementor version 3.23.4
Forms are useless without collecting data from checkboxes.

**Comment by NateStorm** [comment]
Hi, I'm having the same problem with Elementor 3.25.0. Has anyone found a solution? Thanks

**Comment by bytes-web** [comment]
Hi! In my case, the issue was resolved after updating to the latest version. I see that version 3.25.1 has already been released. It would be interesting to know if it worked.

**Comment by NateStorm** [comment]
Thanks for the reply! I've tried updating Elementor Pro and I still have the same problem. I've also tried disabling plugins and that did not work. I contacted Elementor technical support and they gave me some things to try so I'll do that and see if that works.
