### ISSUE TITLE
Nav Menu: Submenu Indicator spacing still present when 'None' selected

### ISSUE THREAD

**Issue by simonclay** [elementor/elementor#15365]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When selecting 'None' for Submenu Indicator in the Content tab of Nav Menu, Elementor still displays the spacing to the right of the nav item where the indicator would be. 

If 'None' is selected for Submenu Indicator, the space should be removed.

`selector span.sub-arrow { display: none } solves the issue.`

**Comment by ajoah** [comment]
I confirm the issue

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.4.0

Feel free to update

Thanks!

**Comment by puregraphx** [comment]
> This issue has been resolved in Elementor Pro v3.4.0

I am already on 3.4.1. and the issue is still visible. The Sub Arrow still takes 10px of space which causes an annoying glitch (bad for Google CLS score)
Padding should be 0 when sub arrow is not displayed.

/wp-content/plugins/elementor-pro/assets/css/widget-nav-menu.min.css
`.elementor-nav-menu .sub-arrow {
    line-height: 1;
    padding: 10px 0 10px 10px;
    margin-top: -10px;
    margin-bottom: -10px;
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center;`

**Comment by Hativ** [comment]
Still an issue today.

**Comment by d3faulter** [comment]
Still experiencing this in v.3.19.3

**Comment by ronnyadsetts** [comment]
This remains a bug ~3 years since reporting in v3.21.8.

**Comment by Bozodragon** [comment]
Still having this issue in v3.24.3. No able to override behaviour with CSS
