### ISSUE TITLE
Wrong Breakpoint Being Applied to Tablet Extra & Mobile Extra Media Queries

### ISSUE THREAD

**Issue by michaelwright74** [elementor/elementor#15488]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest development version of Elementor.

## Description

Using Custom Breakpoints the wrong breakpoint size is applied to the media queries for Tablet Extra & Mobile Extra

## Steps to reproduce

Create a heading and set a different font size for each of the breakpoints then view the resulting CSS

![Capture3](https://user-images.githubusercontent.com/30985280/123445449-cb425280-d5cf-11eb-84b1-d963f6134bad.JPG)

![Capture](https://user-images.githubusercontent.com/30985280/123445520-deedb900-d5cf-11eb-8bde-29ae9acb8af8.JPG)

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [x ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
https://pastebin.com/ZNE4Pvr8


```
</details>

**Comment by michaelwright74** [comment]
Just a heads up that the issue still exists after updating to Core dev7 and Pro dev23

**Comment by michaelwright74** [comment]
Also related - if you change the default breakpoint for tablet extra & mobile extra it doesn't take effect, but if you change the breakpoint for mobile & tablet then mobile extra & tablet extra takes those values.

**Comment by DorShahar** [comment]
Hi @michaelwright74 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

Please let me know if the problem is solved, so I could close the issue. 
If not - add your system info so we could investigate it. 

Thanks.

**Comment by choijun** [comment]
Hi @michaelwright74 

I have the same problem with your case and I found the way to solve it (#15782). Hope Elementor guys will consider it.

Best Regards,

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.4.0

Feel free to update

Thanks!

**Comment by theavic** [comment]
I believe this issue still persists when you try to reduce the mobile breakpoint
