### ISSUE TITLE
conflict with wpallimport

### ISSUE THREAD

**Issue by MartinLedpaleis** [elementor/elementor#15634]
After updating to the new stable elementor the wpallimport does not import new files. When i deactivate elementor it works.
elementor Versie: 3.3.0 (early version does not give problems)
elementor pro Versie: 3.3.2
wpallimport Versie: 4.6.7

On the kinsta platform is the server

After deactivation of the elementor (and not the pro) all went fine.

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Try to deactivate the Import / Export experiment and let us know what you are getting.

In addition please attach your System info, and specify exactly what is the problem you are experiencing

**Comment by MartinLedpaleis** [comment]
server is by kinsta.. this is what they say: 
We don't provide exact server infrastructure details for security purposes. We do use Linux, Nginx, PHP, MySQL however. If there's something a bit more specific we can provide, I can let you know if it's something we can share.
We do have a few articles highlighting our server:

    https://kinsta.com/why-us/#introduction
    https://kinsta.com/knowledgebase/what-you-should-know/#platform
    https://kinsta.com/knowledgebase/shared-vps-dedicated-hosting/

The support of wpallimport says this:
I thought it might be a caching issue as well, but it's not. Unfortunately, since it's a plugin conflict (https://www.wpallimport.com/documentation/troubleshooting/plugin-theme-conflicts/), you might need to reach out to Elementor to address this (since it's another plugin causing an issue on our plugin and not the other way around).


Best Regards,
Edgar Ruiz
Soflyy

**Comment by MartinLedpaleis** [comment]
php 7.4

**Comment by shilo-ey** [comment]
Go to your WP dashboard and under Elementor > System info - copy it to here.

**Comment by MartinLedpaleis** [comment]
[system-info-ledpaleis.com-13-07-2021.txt](https://github.com/elementor/elementor/files/6809989/system-info-ledpaleis.com-13-07-2021.txt)

**Comment by shilo-ey** [comment]
Please describe what is not working.

**Comment by MartinLedpaleis** [comment]
when i want to get a file with product info to import....
it will not allow the javascript to get to the file. When you try to push on the button to get the file in the browser it will not response
![afbeelding](https://user-images.githubusercontent.com/87379013/125481591-bb66f260-09bf-4dd6-8055-df7ef18e0b78.png)

**Comment by gilesholder** [comment]
I had the same issue earlier after updating. I'm on PHP 8 though and run on Siteground.

**Comment by Programmer095** [comment]
Just a heads up, this has been fixed in the latest releases: 
![image](https://user-images.githubusercontent.com/1305010/125517310-7dd856db-f88f-4e79-9bc5-1d9e7b38cd4b.png)

**Comment by Aviad-Herman** [comment]
Hey guys,
Is anyone still having this issue after updating to the latest version of WP all export?

**Comment by MartinLedpaleis** [comment]
all issues are solved. Great reply from you. The update from wpallimport solved the issue
