### ISSUE TITLE
Woocommerce Mobile Product Grid - Displays 2 Columns When Set to 1

### ISSUE THREAD

**Issue by sstrantz** [elementor/elementor#15773]
Problem on Product Grid mobile view.
Elementor Pro version:  3.3.4

Product Grid, Mobile View, Columns set to 1

Displays 2 columns rather than 1.

 
VERSION 3.3.4 PRO DOES NOT FIX THIS ISSUE.

EDITED TO ADD:
This issue happened at last PRO upgrade.

**Comment by yeswycan** [comment]
The Elementor products grid get some serious problem
Even on the product page, if you put an Upsell widget or Similar Products widget, you've got all on 1 column (Even if you're not on mobile).
It's the same bug we've got on the Products Archives page which was solved in the last update.

**Comment by sstrantz** [comment]
I'm hoping that someone does something about it quickly.  I'm at a standstill on one site (considering restoring an old backup).  And I need to start work on a second elementor/woo site that I can't do until this is resolved.

**Comment by sstrantz** [comment]
@yeswycan 
The problem on the product grids on archive page isn't solved.  That is the problem I'm describing.

**Comment by shilo-ey** [comment]
Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by micahdoulos** [comment]
I'm having the same issue. Setting the number of columns doesn't change anything. I'm also at a standstill.

**Comment by yberman66** [comment]
Same issue - I've ha dto rollback elemntor pro top version 3.3 as the latest patch is not setting the columns correctly on the Products widget (I think 3.3.4 fixed product archive but not products)

**Comment by sanjupanikkar** [comment]
Can confirm. 'Product archives' widget is now displaying correctly but the 'products' widget is not.

**Comment by oliveandlake** [comment]
I have the same issue with the related products widget. 

https://www.loom.com/share/3a720ca04af94865a58d84c0ab8edcb5

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.3.5

Feel free to update

Thanks!

**Comment by oliveandlake** [comment]
I just upgraded to v3.3.5. Still have the same issue with related products widget. 

https://prnt.sc/1ib2dak

**Comment by yeswycan** [comment]
Hi, yes the problem is unfortunately still here :/

**Comment by elektromobil-zukunft** [comment]
Hallo zusammen.
Ich habe ein Problem mit dem Produkt.
Die Fotos sind sehr groß geworden
Version 3.3.5 hat nicht geholfen
zum Beispiel https://elektromobil-zukunft.de/modelle/elektromobile/elektromobil-blei-gel-akku/eco-engel-501/

**Comment by sstrantz** [comment]
On my old site, this fixed the original problem.  However:

I just updated pro on a new site I'm working on, and the option to set columns does not appear anymore on the elementor content.  It also doesn't work from the theme, customize.

HELLO Theme.

Very strange.  So....things don't seem to be resolved.

**Comment by chkserv** [comment]
Yep, not fixed on my sites.

**Comment by sstrantz** [comment]
I see that they closed closed this.  Does that mean that we need to open another bug report?

**Comment by micahdoulos** [comment]
This issue is not resolved. It's actually worse now. In the Product Related widget, I've got columns set to 5, and it's displaying 1 column. At least before this "fix" it was displaying 4 columns. Who's doing the testing for this on the Elementor team?

**Comment by sstrantz** [comment]
Everyone:  I have posted this:  https://github.com/elementor/elementor/issues/15857

Please add to it over there!

**Comment by sstrantz** [comment]
@shilo-ey

**Comment by kieranmccarthy** [comment]
Updated today and the same issue has come back, columns display one product per row.
Using Elementor 3.3.1 and Elementor 3.3.1 Pro 3.3.5

**Comment by ahmedzeidan** [comment]
same issue here after upgrading the Pro from 3.3.4 to 3.3.5, the related product widget is showing 1 column on both desktop and mobile. Reported the issue via the official support channel and awaiting a temporary resolution. Rolling back to 3.3.4 is not possible and would require manually deleting the existing 3.3.5 and installing a fresh copy of 3.3.4 which is an interruption to any live site.

Would appreciate a quick response to resolve this issue.

**Comment by kieranmccarthy** [comment]
@ahmedzeidan this is not the cleanest solution but it will fix the issue for you, add the following CSS where you see fit:

`@media (min-width: 1025px) { .elementor-element.elementor-products-grid ul.products.columns-2{grid-template-columns:repeat(2,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-2 ul.products{grid-template-columns:repeat(2,1fr)} .elementor-element.elementor-products-grid ul.products.columns-3{grid-template-columns:repeat(3,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-3 ul.products{grid-template-columns:repeat(3,1fr)} .elementor-element.elementor-products-grid ul.products.columns-4{grid-template-columns:repeat(4,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-4 ul.products{grid-template-columns:repeat(4,1fr)} .elementor-element.elementor-products-grid ul.products.columns-5{grid-template-columns:repeat(5,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-5 ul.products{grid-template-columns:repeat(5,1fr)} .elementor-element.elementor-products-grid ul.products.columns-6{grid-template-columns:repeat(6,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-6 ul.products{grid-template-columns:repeat(6,1fr)} .elementor-element.elementor-products-grid ul.products.columns-7{grid-template-columns:repeat(7,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-7 ul.products{grid-template-columns:repeat(7,1fr)} .elementor-element.elementor-products-grid ul.products.columns-8{grid-template-columns:repeat(8,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-8 ul.products{grid-template-columns:repeat(8,1fr)} .elementor-element.elementor-products-grid ul.products.columns-9{grid-template-columns:repeat(9,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-9 ul.products{grid-template-columns:repeat(9,1fr)} .elementor-element.elementor-products-grid ul.products.columns-10{grid-template-columns:repeat(10,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-10 ul.products{grid-template-columns:repeat(10,1fr)} .elementor-element.elementor-products-grid ul.products.columns-11{grid-template-columns:repeat(11,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-11 ul.products{grid-template-columns:repeat(11,1fr)} .elementor-element.elementor-products-grid ul.products.columns-12{grid-template-columns:repeat(12,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-12 ul.products{grid-template-columns:repeat(12,1fr)} } @media (max-width: 1024px) { .elementor-element.elementor-products-grid ul.products{grid-template-columns:repeat(3,1fr)} } @media (max-width: 767px) { .elementor-element.elementor-products-grid ul.products{grid-template-columns:repeat(2,1fr)} } @media (min-width: 1025px) { .elementor-element.elementor-products-grid.elementor-products-columns-1 ul.products{grid-template-columns:repeat(1,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-2 ul.products{grid-template-columns:repeat(2,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-3 ul.products{grid-template-columns:repeat(3,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-4 ul.products{grid-template-columns:repeat(4,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-5 ul.products{grid-template-columns:repeat(5,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-6 ul.products{grid-template-columns:repeat(6,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-7 ul.products{grid-template-columns:repeat(7,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-8 ul.products{grid-template-columns:repeat(8,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-9 ul.products{grid-template-columns:repeat(9,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-10 ul.products{grid-template-columns:repeat(10,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-11 ul.products{grid-template-columns:repeat(11,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-12 ul.products{grid-template-columns:repeat(12,1fr)} } @media (max-width: 1024px) { .elementor-element.elementor-products-grid.elementor-products-columns-tablet-1 ul.products{grid-template-columns:repeat(1,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-2 ul.products{grid-template-columns:repeat(2,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-3 ul.products{grid-template-columns:repeat(3,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-4 ul.products{grid-template-columns:repeat(4,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-5 ul.products{grid-template-columns:repeat(5,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-6 ul.products{grid-template-columns:repeat(6,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-7 ul.products{grid-template-columns:repeat(7,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-8 ul.products{grid-template-columns:repeat(8,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-9 ul.products{grid-template-columns:repeat(9,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-10 ul.products{grid-template-columns:repeat(10,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-11 ul.products{grid-template-columns:repeat(11,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-12 ul.products{grid-template-columns:repeat(12,1fr)} } @media (max-width: 767px) { .elementor-element.elementor-products-grid.elementor-products-columns-mobile-1 ul.products{grid-template-columns:repeat(1,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-2 ul.products{grid-template-columns:repeat(2,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-3 ul.products{grid-template-columns:repeat(3,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-4 ul.products{grid-template-columns:repeat(4,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-5 ul.products{grid-template-columns:repeat(5,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-6 ul.products{grid-template-columns:repeat(6,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-7 ul.products{grid-template-columns:repeat(7,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-8 ul.products{grid-template-columns:repeat(8,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-9 ul.products{grid-template-columns:repeat(9,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-10 ul.products{grid-template-columns:repeat(10,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-11 ul.products{grid-template-columns:repeat(11,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-12 ul.products{grid-template-columns:repeat(12,1fr)} }`

**Comment by estalavera** [comment]
This update completely sabotaged my website. I had to roll back Pro to version 3.3.0. Please revert this update!

**Comment by momo-fr** [comment]
Same problem for me with the Similar Products widget. Defined for two (or more) columns, only one column displayed.

**Comment by ahmedzeidan** [comment]
Thanks @kieranmccarthy

The provided CSS fixed the column issue on both desktop and mobile... it is a good temporary solution until the Elementor team updates the Pro plugin.

**Comment by okikiola12** [comment]
Elementor update of late has been fill with a lot of bug. now it is pop up nav menu, when click the menu display at the bottom of the page. and the back ground color of all my page has been change to grey.. i fact all the update that is roll out within the space of two weeks has been filled with one bug or the other. and i can count the number of time i have to reload my backup.
in fact this recent up date has been the worst so far.

**Comment by creativeart** [comment]
I hope it will be corrected very soon, it's so uggly for our clients :(

**Comment by deboragreene** [comment]
This issue appeared again with last update. When will it be resolved? 
I cannot launch my store with the giant photos of products despite proper grid settings!

**Comment by Buxoluxo** [comment]
Same problem in my website!! Solution is needed urgently!! Thanks!!

**Comment by Buxoluxo** [comment]
Thanks @kieranmccarthy

The provided CSS fixed the column issue on both desktop and mobile... it is a good temporary solution until the Elementor team updates the Pro plugin.

**Comment by SandraRe** [comment]
> @ahmedzeidan this is not the cleanest solution but it will fix the issue for you, add the following CSS where you see fit:
> 
> `@media (min-width: 1025px) { .elementor-element.elementor-products-grid ul.products.columns-2{grid-template-columns:repeat(2,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-2 ul.products{grid-template-columns:repeat(2,1fr)} .elementor-element.elementor-products-grid ul.products.columns-3{grid-template-columns:repeat(3,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-3 ul.products{grid-template-columns:repeat(3,1fr)} .elementor-element.elementor-products-grid ul.products.columns-4{grid-template-columns:repeat(4,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-4 ul.products{grid-template-columns:repeat(4,1fr)} .elementor-element.elementor-products-grid ul.products.columns-5{grid-template-columns:repeat(5,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-5 ul.products{grid-template-columns:repeat(5,1fr)} .elementor-element.elementor-products-grid ul.products.columns-6{grid-template-columns:repeat(6,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-6 ul.products{grid-template-columns:repeat(6,1fr)} .elementor-element.elementor-products-grid ul.products.columns-7{grid-template-columns:repeat(7,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-7 ul.products{grid-template-columns:repeat(7,1fr)} .elementor-element.elementor-products-grid ul.products.columns-8{grid-template-columns:repeat(8,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-8 ul.products{grid-template-columns:repeat(8,1fr)} .elementor-element.elementor-products-grid ul.products.columns-9{grid-template-columns:repeat(9,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-9 ul.products{grid-template-columns:repeat(9,1fr)} .elementor-element.elementor-products-grid ul.products.columns-10{grid-template-columns:repeat(10,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-10 ul.products{grid-template-columns:repeat(10,1fr)} .elementor-element.elementor-products-grid ul.products.columns-11{grid-template-columns:repeat(11,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-11 ul.products{grid-template-columns:repeat(11,1fr)} .elementor-element.elementor-products-grid ul.products.columns-12{grid-template-columns:repeat(12,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-12 ul.products{grid-template-columns:repeat(12,1fr)} } @media (max-width: 1024px) { .elementor-element.elementor-products-grid ul.products{grid-template-columns:repeat(3,1fr)} } @media (max-width: 767px) { .elementor-element.elementor-products-grid ul.products{grid-template-columns:repeat(2,1fr)} } @media (min-width: 1025px) { .elementor-element.elementor-products-grid.elementor-products-columns-1 ul.products{grid-template-columns:repeat(1,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-2 ul.products{grid-template-columns:repeat(2,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-3 ul.products{grid-template-columns:repeat(3,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-4 ul.products{grid-template-columns:repeat(4,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-5 ul.products{grid-template-columns:repeat(5,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-6 ul.products{grid-template-columns:repeat(6,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-7 ul.products{grid-template-columns:repeat(7,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-8 ul.products{grid-template-columns:repeat(8,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-9 ul.products{grid-template-columns:repeat(9,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-10 ul.products{grid-template-columns:repeat(10,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-11 ul.products{grid-template-columns:repeat(11,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-12 ul.products{grid-template-columns:repeat(12,1fr)} } @media (max-width: 1024px) { .elementor-element.elementor-products-grid.elementor-products-columns-tablet-1 ul.products{grid-template-columns:repeat(1,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-2 ul.products{grid-template-columns:repeat(2,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-3 ul.products{grid-template-columns:repeat(3,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-4 ul.products{grid-template-columns:repeat(4,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-5 ul.products{grid-template-columns:repeat(5,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-6 ul.products{grid-template-columns:repeat(6,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-7 ul.products{grid-template-columns:repeat(7,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-8 ul.products{grid-template-columns:repeat(8,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-9 ul.products{grid-template-columns:repeat(9,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-10 ul.products{grid-template-columns:repeat(10,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-11 ul.products{grid-template-columns:repeat(11,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-12 ul.products{grid-template-columns:repeat(12,1fr)} } @media (max-width: 767px) { .elementor-element.elementor-products-grid.elementor-products-columns-mobile-1 ul.products{grid-template-columns:repeat(1,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-2 ul.products{grid-template-columns:repeat(2,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-3 ul.products{grid-template-columns:repeat(3,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-4 ul.products{grid-template-columns:repeat(4,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-5 ul.products{grid-template-columns:repeat(5,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-6 ul.products{grid-template-columns:repeat(6,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-7 ul.products{grid-template-columns:repeat(7,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-8 ul.products{grid-template-columns:repeat(8,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-9 ul.products{grid-template-columns:repeat(9,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-10 ul.products{grid-template-columns:repeat(10,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-11 ul.products{grid-template-columns:repeat(11,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-12 ul.products{grid-template-columns:repeat(12,1fr)} }`

Cheers mate

**Comment by AkramiPro** [comment]
in RTL version columns are not effected . and there is just one column . a chose 4 columns but only 1 one column show . 
the problem is in this file : 
elementor-pro/assets/css/frontend-lite-rtl.min.css
it's broken in new pro version (3.3+)

**Comment by greenstreetdesign** [comment]
Had this problem too with 3.3.5, patched it with this custom css code for the Related Products widget: 

.elementor-widget-woocommerce-product-related ul.products {
grid-template-columns: repeat(4, 1fr);
}

if you want three columns, change the 4 to a 3, etc etc

I did a media query for mobile to display 1 column. 

Hope this saves someone out there more time than I spent hunting around for this code.

Credit, this is where I found the solution:
https://www.reddit.com/r/elementor/comments/ox841u/issue_with_product_related_widget_on_single/

**Comment by creativeart** [comment]
I still have the same problem on Elementor Pro 3.3.5 with one website. The problem with the CSS code provided is that we cannot control the number of columns on smaller breakpoint. Am I wrong ?

**Comment by AkramiPro** [comment]
please fix this problems as soon as possible.

**Comment by deardigitalisrael** [comment]
someone manged to temp fix it with CSS? 
all the codes i tried + the one mentiond above me are not working for me.
i have this problem in the products widget on the home page but only in mobile...rest is working perfect. 
also the archive products page are working good in all the versions (include mobile) and if im trying to export it or copy it into the home page its getting broken again on mobile.
any ideas? the only idea i have is to use product shortcode and to desgin it all by hand in CSS.

**Comment by Bouncern** [comment]
Solved in ElementorPro 3.3.6 ( [https://elementor.com/pro/changelog/] )

Just updated on our sites, and _Related Products, Upsells_ etc. are all working fine now

**Comment by mariyanh** [comment]
It's version 3.6.2. and there is the problem again..  it's in 3 columns only, whatever you do. No CSS fix works now..
