### ISSUE TITLE
Woocommerce Product Grid Issues Not Resolved With 3.3.5

### ISSUE THREAD

**Issue by sstrantz** [elementor/elementor#15857]
@shilo-ey 

- [x ] The issue still exists against the latest stable version of Elementor.

Reported problem on https://github.com/elementor/elementor/issues/15773#issuecomment-890991270  

3.3.5 HAS NOT RESOLVED WOOCOMMERCE ISSUES.

**Content tab of the woocommerce products grid does not have an option to specify the number of columns at page break anymore.**  Can't set it from there.  

**Appearance, customize (hello theme) doesn't allow to set for each break there either.**

Please see the additional Woocommerce issues at linked post

**Comment by chkserv** [comment]
Still have this issue on all my sites, it's not resolved.

**Comment by micahdoulos** [comment]
Product Related widget is still broken when it comes to column count. My column count is set to 5, With 3.3.5 the page is showing ONE column, not 5. At least with the previous version it showed 4 columns, not 5.

**Comment by micahdoulos** [comment]
@shilo-ey Have you tried to created a Product Related widget and adjusted the number of columns? Did it work on your end?

**Comment by sstrantz** [comment]
@shilo-ey   

Is this what you need?  Please advise if I have done this correctly.

System Info:
System Info:
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.32-35
	PHP Version: 7.4.21
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8
	Site URL: https://sues16.sg-host.com
	Home URL: https://sues16.sg-host.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Indiana/Indianapolis
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.4.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0

== Active Plugins ==
	Code Snippets
		Version: 2.14.1
		Author: Code Snippets Pro

	Elementor
		Version: 3.3.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.3.5
		Author: Elementor.com

	LitExtension Customer Password Plugin
		Version: 1.0.0
		Author: LitExtension

	LitExtension SEO Plugin
		Version: 1.0.1
		Author: LitExtension

	Rank Math SEO
		Version: 1.0.69.1
		Author: Rank Math

	SiteGround Optimizer
		Version: 5.8.3
		Author: SiteGround

	SiteGround Security
		Version: 1.1.0
		Author: SiteGround

	WooCommerce
		Version: 5.5.2
		Author: Automattic

	WooCommerce PayPal Payments
		Version: 1.4.0
		Author: WooCommerce


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	footer : 1
		icon : 1
		icon-list : 3
		image : 1
		text-editor : 2
	header : 2
		icon-list : 2
		nav-menu : 2
		search-form : 2
		text-editor : 2
		theme-site-logo : 2
		woocommerce-menu-cart : 2
	product-archive : 1
		image : 1
		wc-archive-products : 1


== Log ==
	
Log: showing 2 of 22021-07-28 12:30:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.1',
  'to' => '3.3.4',
)]
2021-08-02 08:35:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.4',
  'to' => '3.3.5',
)]

PHP: showing 2 of 2PHP: 2021-07-29 07:45:33 [error X 1][/home/customer/www/sues16.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::285] Uncaught Error: Call to a member function update_meta() on bool in /home/customer/www/sues16.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:285
Stack trace:
#0 /home/customer/www/sues16.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(166): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/sues16.sg-host.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/customer/www/sues16.sg-host.com/public_html/wp-includes/class-wp-hook.php(303): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/customer/www/sues16 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-07-29 08:17:06 [error X 5][/home/customer/www/sues16.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::285] Uncaught Error: Call to a member function update_meta() on null in /home/customer/www/sues16.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:285
Stack trace:
#0 /home/customer/www/sues16.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(166): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(10, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/sues16.sg-host.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/customer/www/sues16.sg-host.com/public_html/wp-includes/class-wp-hook.php(303): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/customer/www/sues16.s [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]


				

Steps to Reproduce:

Templates, Theme Builder, Shop Page
Archive Products

No option to edit the layout columns.

Then tried to set through the theme:
Go to Theme, Appearance, Customize, Woocommerce, Product Catalog  (Hello Theme)

Products per row
Set to 3 at Desktop
If I make a change at one view (mobile for example to 1) it changes to 1 at all views.  Can't make changes here.

So it's not an option in Elementor and not working in Theme.

**Comment by ahmedzeidan** [comment]
Hi @shilo-ey

Same issue here after upgrading the Pro from 3.3.4 to 3.3.5, the related product widget is showing 1 column on both desktop and mobile. Reported the issue via the official support channel and awaiting a temporary resolution. Rolling back to 3.3.4 is not possible and would require manually deleting the existing 3.3.5 and installing a fresh copy of 3.3.4 which is an interruption to any live site.

Would appreciate a quick response to resolve this issue.

**Comment by oliveandlake** [comment]
Same here. Related product widget showing 1 column. Happens across many websites.

**Comment by shawlworld** [comment]
I have the same issue does anybody know how to fix it?

**Comment by Vubs** [comment]
Hi guys, had the same problem, still does in fact haha ^^ -> my "product categories" widget show everything on ONE column and modifying the layout properties in the panel does nothing.
Here's two solutions to ""fix it""
The issue seems to be related to the grid layout css properties, I did go to the website and downloaded elementor pro again wich gives me the 3.3.1 version that seems to be working ?
The second way you can temporarily fix it is by adding this CSS on the widget :
```
selector ul{
    grid-template-columns: repeat(4, 1fr);
}
```
(where 4 is the number of columns you want)
This solution works for the simple display where you have your columns on a single line, I haven't tested much more than this.
Hope it can help :)

**Comment by agenciasincro** [comment]
@Vubs your solution helped me! Very thanks

**Comment by dbfischer** [comment]
Same issue. After Update to 3.3.5 Pro. One column instead of 3 for related products. Changing the numbers of colums has no effect.

**Comment by ahmedzeidan** [comment]
Add the below CSS to the singple product template page and it will fix the issue temporarily until Elementor Pro team comes up with a better fix/update:

`@media (min-width: 1025px) { .elementor-element.elementor-products-grid ul.products.columns-2{grid-template-columns:repeat(2,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-2 ul.products{grid-template-columns:repeat(2,1fr)} .elementor-element.elementor-products-grid ul.products.columns-3{grid-template-columns:repeat(3,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-3 ul.products{grid-template-columns:repeat(3,1fr)} .elementor-element.elementor-products-grid ul.products.columns-4{grid-template-columns:repeat(4,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-4 ul.products{grid-template-columns:repeat(4,1fr)} .elementor-element.elementor-products-grid ul.products.columns-5{grid-template-columns:repeat(5,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-5 ul.products{grid-template-columns:repeat(5,1fr)} .elementor-element.elementor-products-grid ul.products.columns-6{grid-template-columns:repeat(6,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-6 ul.products{grid-template-columns:repeat(6,1fr)} .elementor-element.elementor-products-grid ul.products.columns-7{grid-template-columns:repeat(7,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-7 ul.products{grid-template-columns:repeat(7,1fr)} .elementor-element.elementor-products-grid ul.products.columns-8{grid-template-columns:repeat(8,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-8 ul.products{grid-template-columns:repeat(8,1fr)} .elementor-element.elementor-products-grid ul.products.columns-9{grid-template-columns:repeat(9,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-9 ul.products{grid-template-columns:repeat(9,1fr)} .elementor-element.elementor-products-grid ul.products.columns-10{grid-template-columns:repeat(10,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-10 ul.products{grid-template-columns:repeat(10,1fr)} .elementor-element.elementor-products-grid ul.products.columns-11{grid-template-columns:repeat(11,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-11 ul.products{grid-template-columns:repeat(11,1fr)} .elementor-element.elementor-products-grid ul.products.columns-12{grid-template-columns:repeat(12,1fr)} .elementor-element.elementor-products-grid .woocommerce.columns-12 ul.products{grid-template-columns:repeat(12,1fr)} } @media (max-width: 1024px) { .elementor-element.elementor-products-grid ul.products{grid-template-columns:repeat(3,1fr)} } @media (max-width: 767px) { .elementor-element.elementor-products-grid ul.products{grid-template-columns:repeat(2,1fr)} } @media (min-width: 1025px) { .elementor-element.elementor-products-grid.elementor-products-columns-1 ul.products{grid-template-columns:repeat(1,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-2 ul.products{grid-template-columns:repeat(2,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-3 ul.products{grid-template-columns:repeat(3,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-4 ul.products{grid-template-columns:repeat(4,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-5 ul.products{grid-template-columns:repeat(5,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-6 ul.products{grid-template-columns:repeat(6,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-7 ul.products{grid-template-columns:repeat(7,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-8 ul.products{grid-template-columns:repeat(8,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-9 ul.products{grid-template-columns:repeat(9,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-10 ul.products{grid-template-columns:repeat(10,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-11 ul.products{grid-template-columns:repeat(11,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-12 ul.products{grid-template-columns:repeat(12,1fr)} } @media (max-width: 1024px) { .elementor-element.elementor-products-grid.elementor-products-columns-tablet-1 ul.products{grid-template-columns:repeat(1,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-2 ul.products{grid-template-columns:repeat(2,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-3 ul.products{grid-template-columns:repeat(3,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-4 ul.products{grid-template-columns:repeat(4,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-5 ul.products{grid-template-columns:repeat(5,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-6 ul.products{grid-template-columns:repeat(6,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-7 ul.products{grid-template-columns:repeat(7,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-8 ul.products{grid-template-columns:repeat(8,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-9 ul.products{grid-template-columns:repeat(9,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-10 ul.products{grid-template-columns:repeat(10,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-11 ul.products{grid-template-columns:repeat(11,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-tablet-12 ul.products{grid-template-columns:repeat(12,1fr)} } @media (max-width: 767px) { .elementor-element.elementor-products-grid.elementor-products-columns-mobile-1 ul.products{grid-template-columns:repeat(1,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-2 ul.products{grid-template-columns:repeat(2,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-3 ul.products{grid-template-columns:repeat(3,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-4 ul.products{grid-template-columns:repeat(4,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-5 ul.products{grid-template-columns:repeat(5,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-6 ul.products{grid-template-columns:repeat(6,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-7 ul.products{grid-template-columns:repeat(7,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-8 ul.products{grid-template-columns:repeat(8,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-9 ul.products{grid-template-columns:repeat(9,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-10 ul.products{grid-template-columns:repeat(10,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-11 ul.products{grid-template-columns:repeat(11,1fr)} .elementor-element.elementor-products-grid.elementor-products-columns-mobile-12 ul.products{grid-template-columns:repeat(12,1fr)} }`

**Comment by dbfischer** [comment]
@ahmedzeidan Thank you, this helps.

**Comment by ahmedzeidan** [comment]
> Hi guys, had the same problem, still does in fact haha ^^ -> my "product categories" widget show everything on ONE column and modifying the layout properties in the panel does nothing.
> Here's two solutions to ""fix it""
> The issue seems to be related to the grid layout css properties, I did go to the website and downloaded elementor pro again wich gives me the 3.3.1 version that seems to be working (?), so I deleted mine and replaced with this older one.
> The second way you can temporarily fix it is by adding this CSS on the widget :
> 
> ```
> selector ul{
>     grid-template-columns: repeat(4, 1fr);
> }
> ```
> 
> (where 4 is the number of columns you want)
> This solution works for the simple display where you have your columns on a single line, I haven't tested much more than this.
> Hope it can help :)

This works only for the desktop view but does not fix the column issue on responsive mode (mobile).

**Comment by Vubs** [comment]
> > Hi guys, had the same problem, still does in fact haha ^^ -> my "product categories" widget show everything on ONE column and modifying the layout properties in the panel does nothing.
> > Here's two solutions to ""fix it""
> > The issue seems to be related to the grid layout css properties, I did go to the website and downloaded elementor pro again wich gives me the 3.3.1 version that seems to be working (?), so I deleted mine and replaced with this older one.
> > The second way you can temporarily fix it is by adding this CSS on the widget :
> > ```
> > selector ul{
> >     grid-template-columns: repeat(4, 1fr);
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (where 4 is the number of columns you want)
> > This solution works for the simple display where you have your columns on a single line, I haven't tested much more than this.
> > Hope it can help :)
> 
> This works only for the desktop view but does not fix the column issue on responsive mode (mobile).

Never said that it did.

**Comment by Vubs** [comment]
Here's the official solution provided by the support :
"Hey Vincent,

Thank you for contacting us.
Kindly be advised that we are aware of the issue and we are currently working to fix it.

Here is a temporary fix that we recomend using:

/* for desktop view */
body[data-elementor-device-mode="desktop"] selector ul.products{
grid-template-columns: repeat(4, 1fr);
}
/* for tablet view */
body[data-elementor-device-mode="tablet"] selector ul.products{
grid-template-columns: repeat(3, 1fr);
}
/* for mobile view */
body[data-elementor-device-mode="mobile"] selector ul.products{
grid-template-columns: repeat(2, 1fr);
}

**Comment by Vubs** [comment]
No sorry, I just came here to check if the problem was coming from one my edit or if it was on Elementor side :)
I know it's probably not the smartest solution but until they fix it, I just downgraded the plugin, thanks a lot for your help, it should cover waaaaay more cases than my snippet of code haha 😊

**Comment by ti-mercado-industrial** [comment]
> Hi guys, had the same problem, still does in fact haha ^^ -> my "product categories" widget show everything on ONE column and modifying the layout properties in the panel does nothing.
> Here's two solutions to ""fix it""
> The issue seems to be related to the grid layout css properties, I did go to the website and downloaded elementor pro again wich gives me the 3.3.1 version that seems to be working (?), so I deleted mine and replaced with this older one.
> The second way you can temporarily fix it is by adding this CSS on the widget :
> 
> ```
> selector ul{
>     grid-template-columns: repeat(4, 1fr);
> }
> ```
> 
> (where 4 is the number of columns you want)
> This solution works for the simple display where you have your columns on a single line, I haven't tested much more than this.
> Hope it can help :)

So many thanks @Vubs and @ahmedzeidan !

**Comment by Skelitalix** [comment]
> Here's the official solution provided by the support :
> "Hey Vincent,
> 
> Thank you for contacting us.
> Kindly be advised that we are aware of the issue and we are currently working to fix it.
> 
> Here is a temporary fix that we recomend using:
> 
> /* for desktop view _/ body[data-elementor-device-mode="desktop"] selector ul.products{ grid-template-columns: repeat(4, 1fr); } /_ for tablet view _/ body[data-elementor-device-mode="tablet"] selector ul.products{ grid-template-columns: repeat(3, 1fr); } /_ for mobile view */
> body[data-elementor-device-mode="mobile"] selector ul.products{
> grid-template-columns: repeat(2, 1fr);
> }

Thanks @Vubs! This will work @ahmedzeidan but you just need to comment out properly. The below works for me:

/* for desktop view */
body[data-elementor-device-mode="desktop"] selector ul.products{
grid-template-columns: repeat(4, 1fr);
}
/* for tablet view */
body[data-elementor-device-mode="tablet"] selector ul.products{
grid-template-columns: repeat(3, 1fr);
}
/* for mobile view */
body[data-elementor-device-mode="mobile"] selector ul.products{
grid-template-columns: repeat(2, 1fr);
}

**Comment by jefferson125** [comment]
> Hi guys, had the same problem, still does in fact haha ^^ -> my "product categories" widget show everything on ONE column and modifying the layout properties in the panel does nothing.
> Here's two solutions to ""fix it""
> The issue seems to be related to the grid layout css properties, I did go to the website and downloaded elementor pro again wich gives me the 3.3.1 version that seems to be working (?), so I deleted mine and replaced with this older one.
> The second way you can temporarily fix it is by adding this CSS on the widget :
> 
> ```
> selector ul{
>     grid-template-columns: repeat(4, 1fr);
> }
> ```
> 
> (where 4 is the number of columns you want)
> This solution works for the simple display where you have your columns on a single line, I haven't tested much more than this.
> Hope it can help :)

You are YYDS, which means you are the god forever!

**Comment by AkramiPro** [comment]
same problem i have in my website. show one column except 4.
i have updated to 3.3.5 but not fixed.

**Comment by shilo-ey** [comment]
We will soon release a patch for all of the WooCommerce widgets adjustments.

Please follow this thread for updates.

Thanks!

**Comment by ahmedzeidan** [comment]
3.3.6 works well and the issue is fixed from my end... Thanks Elementor team and @shilo-ey

**Comment by DorShahar** [comment]
Hi Everyone
This issue has been resolved in Elementor Pro v3.3.5
Feel free to update
Thanks!

**Comment by sstrantz** [comment]
@shilo-ey 

I am still having an issue with the **Archive Products** widget.  There is nowhere to specify number of columns in the content tab.  Has that been moved somewhere?  Please advise.

Hello Theme still does not allow setting different number for columns at different breaks.

**Comment by yberman66** [comment]
So 3.3.6 seems better but also using hello elementor and the columns OK are now set to show 1 on mobile but none of the images are central anymore as it seems to be ignoring the css. I'm back at version 3.3.0 again - these patches seem really messed up

**Comment by AlbertLexter** [comment]
> Here's the official solution provided by the support :
> "Hey Vincent,
> 
> Thank you for contacting us.
> Kindly be advised that we are aware of the issue and we are currently working to fix it.
> 
> Here is a temporary fix that we recomend using:
> 
> /* for desktop view _/ body[data-elementor-device-mode="desktop"] selector ul.products{ grid-template-columns: repeat(4, 1fr); } /_ for tablet view _/ body[data-elementor-device-mode="tablet"] selector ul.products{ grid-template-columns: repeat(3, 1fr); } /_ for mobile view */
> body[data-elementor-device-mode="mobile"] selector ul.products{
> grid-template-columns: repeat(2, 1fr);
> }

Thanks for this, I've been looking for a fix more than week now.

**Comment by sstrantz** [comment]
Still having issues with the Product Archive widget.  Can't set columns.

Please see:  https://github.com/elementor/elementor/issues/15996
