### ISSUE TITLE
Unable to upload SVG as of 3.4.2

### ISSUE THREAD

**Issue by chrissienoodle** [elementor/elementor#16084]
Hi,

As of Elementor 3.4.2, I am unable to upload SVGs. My site uses Elementor Pro 3.3.7 and the Hello Elementor 2.4.1 theme.  The option is enabled in settings and I also have a 'upload_mimes' hook in my child theme enabling the support.

When I rollback to 3.3, I can upload SVGs.

There is a series of 500 errors in the console. One for the async upload, the rest for the image sizes.  They all indicate a WP critical error but since the site is in production and doesn't use an email, I am unable to get more debug info.

Good Luck,

**Comment by shilo-ey** [comment]
Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by hogash** [comment]
Having this issue too. 

Probably just validating `$xml` should do the trick to prevent trying to access an object as bool .

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.4.3

Feel free to update

Thanks!

**Comment by pzeylstra** [comment]
The issue is still there. Elementor 3.4.4. active, option enabled in settings.

**Comment by RicBaller** [comment]
I still have this issue. Currently the upload is enabled via the Elementor settings, but I still get the question to turn it on for one time when I open the editor. 
I've tried adding the SVG support plugin, but then I can only upload via the media page and then I get the error that the image is to large.
