### ISSUE TITLE
BUG | Elementor v3.4.3 Causes all Landing Pages to result in a 404 Error, v3.4.2 Works as Expected

### ISSUE THREAD

**Issue by cirkut** [elementor/elementor#16244]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When using Elementor 3.4.3, Landing Pages (pre-existing and new) will result in a 404 error when trying to visit the landing page. Rolling back to Elementor 3.4.2 allows the landing page to be viewed as expected.

Potential issue (and resulting merge) that caused this issue: #15943

## Steps to reproduce

1. Install Elementor 3.4.3 and Elementor Pro 3.4.1
2. Create a Landing Page and place any content on the page
3. Ensure Permalinks are set to something that includes the post name.
4. Try visiting created Landing Page to see 404 error.
5. Use Elementor > Tools to roll back Elementor to version 3.4.2
6. Visit the Landing Page to see the expected page with the content added in step 2.
7. Upgrade Elementor to 3.4.3 again.
8. Visit the Landing Page to see 404 error again.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```				
== Server Environment ==
	Operating System: Darwin
	Software: nginx/1.21.2
	MySQL version: Homebrew v10.5.9
	PHP Version: 7.4.22
	PHP Max Input Vars: 1000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8
	Site URL: https://wordpress.test
	Home URL: https://wordpress.test
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: America/Detroit
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.4.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.4.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.4.1
		Author: Elementor.com

	UpdraftPlus - Backup/Restore
		Version: 1.16.61
		Author: UpdraftPlus.Com, DavidAnderson


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	landing-page : 0
		button : 3
		heading : 12
		icon-box : 8
		image : 4
		spacer : 1
		star-rating : 1
		text-editor : 3
		video : 1


== Log ==
	
Log: showing 1 of 12021-09-03 12:13:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.1',
  'to' => '3.4.1',
)]
```
</details>

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #15943, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by cirkut** [comment]
Wanted to double check to see if anyone is going to be looking at this somewhat soon? Since Landing Pages were enabled by default, this is a pretty critical bug that causes the feature to not work at all.

**Comment by jawkhan** [comment]
Hi,

I can confirm I've come across this same issue. Putting in /e-landing-page/ into the url allows me to see the landing page.
i.e. www.example.com**/e-landing-page/**<name of landing page>

However, once the landing page is published, I am unable to edit the page unless I revert the page back to Draft. I hope this can get resolved soon.

**Comment by ThomasKur** [comment]
We have the same issue on our site also with 3.4.4, really sad the feature does no longer work on a production site...

**Comment by mountbatt** [comment]
I have the same problem since months – i happens if I use a custom permalink structure. But i cant switch to another structure, cause my "blogposts" are in /aktuelles/ directory with that structure i use since years for my website. So we need a fix for this. I only can edit with Elementor if i switch my Landing Pages back to "Draft". But the landingpages are "live" for Google Ads, so i have to pause the Ads too … thats frustrating!

![Bildschirmfoto 2021-10-04 um 11 41 58](https://user-images.githubusercontent.com/2411246/135829559-f6860e32-21a7-4188-a1d5-f36e7020bdea.png)

**Comment by cirkut** [comment]
Can we get an update on this? Still having this issue. Would like to use Landing Pages and test them even further (knowing they're still in beta), but the lack of action here and the critical breaking of Landing Pages really has turned me off from them entirely. I will likely refuse to use Landing Pages once out of beta for lack of stability.

**Comment by arinbh** [comment]
Any status? Not sure why there was no consideration that users would have custom permalinks.

**Comment by mrjackyliang** [comment]
Confirmed that this works with `v3.4.2`

**Comment by mrjackyliang** [comment]
Also tested with the latest beta `3.6.0-dev16`, does not work also.

**Comment by TorbenE84** [comment]
Problem unfortunately still exists. But is not traceable, which version triggers it. Have also v3.5.2 in use, where everything runs

**Comment by TorbenE84** [comment]
Just to check, has anyone else these problems on a multisite too?

**Comment by Cruschi** [comment]
Hi everyone,
I am experiencing the same problem in the free version, really hope for a change because. I am still using the 3.4.2 version and I would love to catch up with all the updates

**Comment by cirkut** [comment]
@KingYes @arielk Can we get some type of response on this please? Landing pages are entirely broken and unusable for months now. Still getting the same results on the latest versions. I've entirely abandoned any plans to use this functionality even though there's definitely some great use that could come from this.

**Comment by murcoder** [comment]
Selecting the last but one permalink solved it for me:
![Bildschirmfoto 2022-02-02 um 22 52 01](https://user-images.githubusercontent.com/9846632/152243561-a37bd035-eb37-49e1-8d34-37f4f444411e.png)

**Comment by mountbatt** [comment]
@murcoder I don’t think it’s the solution! You show us the way how it work in general. But we have the problem in a more complex environment (see above)

**Comment by mrjackyliang** [comment]
@murcoder It's not wise to change permalinks when you're in production. It's bad for SEO

**Comment by thatguyjonny** [comment]
Has there been any traction with this? I am having the same issue and it's really causing problems. Every landing page I try to make has /e-landing-page in the URL. Changing the permalinks structure doesn't work. And even if it did, that's terrible for SEO as said above, as well as terrible for other pages, funnels, campaigns, etc.

**Comment by Genyus** [comment]
@cirkut @arinbh @Cruschi @TorbenE84 @mountbatt @mrjackyliang @thatguyjonny I've implemented a fix for this, sharing for anyone who wants. Works with all tested permalink structures in my (WPMS) site, but YMMV.

https://gist.github.com/Genyus/f9b53cf3f10996b99e1aaf3fa94fb090

**Comment by crbon** [comment]
Issue is still present in Elementor Pro v3.6.5 / Elementor v3.6.4

**Comment by matteocuellarvega** [comment]
Still have this issue using Elementor 3.6.5 / Pro 3.7.0 on a WP multisite. Resetting permalinks to `/%postname%/` doesn't resolve the issue. Is this an issue with Elementor or could it be due to WP being a multisite installation?

**Comment by jflynn2** [comment]
Still an issue, we had rolled back to an old version that worked but after upgrading our WP plugins our landing pages have broken resulting in 404 from our PPC ads. Going to roll back to a working version again, but disappointed this is still an issue months on.

**Comment by drawcard** [comment]
I was getting excited about using landing pages in Elementor until I came across this issue, and it now seems like the feature isn't that useful until this is fixed. I hope that it will be resolved soon. @arielk @ramiy will there be any movement on this issue soon?

**Comment by elnobun** [comment]
Till date, this issue has not been fixed. Elementor is a very bad product for the community. Thank God there are many better alternatives. I am so done with this company.

**Comment by talon2king** [comment]
Hey all, if you're able to edit the code to your elementor plugins, here's what I did:
Navigate to your plugins folder, then to:
Elementor\Modules\LandingPages

in module.php go to the remove_post_type_slug method and update it as follows:

`	private function remove_post_type_slug( $post_link, $post, $leavename ) {
		// Only try to modify the permalink if the post is a Landing Page.
		if ( self::CPT !== $post->post_type || 'publish' !== $post->post_status ) {
			return $post_link;
		}

		// Any slug prefixes need to be removed from the post link.
		return get_home_url() . '/e-landing-page/' . $post->post_name . '/';
	}`

this is how I got Elementor to keep the slug. It's a band-aid and not a full fix because the purpose is to create a link with the type removed. However, it's not updating the database with this information.

Here's a screenshot of after:
<img width="456" alt="image" src="https://user-images.githubusercontent.com/16641209/183119651-756de856-dbdc-4ff7-bd33-4c7b009b10ef.png">

**Comment by Genyus** [comment]
@talon2king I [shared a solution above](#issuecomment-1059559383) that doesn't require modifying plugin files and won't revert every time you update Elementor.

**Comment by talon2king** [comment]
Oh nice! I must have overlooked that one

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Grksoft-PK** [comment]
Best way to fix the above issue is to update your permalinks and save and refresh the site page.

**Comment by lexigladedigital** [comment]
Well, this is still happening in August 2023. I had to reset permalinks and copy/paste everything over to a regular Page, then change the permalink settings back.
Messy, and basically makes Landing Pages CPT unusable for anyone using custom permalink settings.

**Comment by Genyus** [comment]
@cirkut @lexigladedigital if this is still an ongoing issue in your projects, I'd invite you to review the [workaround I posted above](https://github.com/elementor/elementor/issues/16244#issuecomment-1059559383) which has been working for us in production for the past year.

**Comment by lexigladedigital** [comment]
> @cirkut @lexigladedigital if this is still an ongoing issue in your projects, I'd invite you to review the [workaround I posted above](https://github.com/elementor/elementor/issues/16244#issuecomment-1059559383) which has been working for us in production for the past year.

Thank you, I appreciate it, and the knowledge that it works consistently in production since. I'll be sure to give it a try for future landing pages!

**Comment by elnobun** [comment]
My company became more productive and profitable when we moved away from Elementor. It's 2023, there are way more better options. Example Bricks or better still, wait for Wordpress 6.1. Elementor is a joke!

**Comment by arorabhishek** [comment]
For me, the simplest of the fix was to revert the landing page to a draft version, save it in my template, and then import the same template in a page instead!

**Comment by krishnadiamesso** [comment]
@arorabhishek Thanks for this. That is what I did.

**Comment by krishnadiamesso** [comment]
I saved my elementor landing page as a template and created a custom type by following this tutorial.
https://youtu.be/NYKhybukUEc?si=925m7GnJQeI9kS5B
Once the custom type is created i import the saved template.

**Comment by vladaman** [comment]
I am having same issue on Elementor - 3.18.3 with Polylang.

**Comment by Genyus** [comment]
@vladaman Polylang implements custom URL rewriting, which this workaround doesn't account for.

**Comment by dmanexe** [comment]
Still broken, as of 3.19.0. Landing Pages as a concept just don't work. Build the "landing" page normally as a Page and use the Elementor Canvas is my work around.

**Comment by alanstainerPMW** [comment]
We're seeing the same issue with the most recent version of Elementor and Elementor Pro. As soon as the permalinks structure is set to custom, landing pages can only be edited in draft and generate a 404 on the front end once published.

**Comment by michelepilli** [comment]
Still broken, is elementor doing anything about this??

**Comment by psirotkin** [comment]
I have the same issue. Elementor (Pro) support told me:

> This issue is actually related to an error with the 'Landing Pages' feature when permalink structures are set other than 'Plain' and 'Postname' (this issue still doesn't have an ETA but our devs are already aware of the issue). 

...and referred to the [workaround posted above](https://gist.github.com/Genyus/f9b53cf3f10996b99e1aaf3fa94fb090):

> It is just how WordPress parses URLs by default. So custom code solutions should do the trick.

I'm not sure how useful landing pages are if you either have to have a `/?p=123` URL for them, or else have to have unstructured URLs where you can't tell pages from blog posts, but that seems to be the status quo.
