### ISSUE TITLE
Nav Menu's Dropdown got messed up in the latest 3.5 Elementor Pro update.

### ISSUE THREAD

**Issue by azkalex** [elementor/elementor#16815]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The new Elementor Pro 3.5 update messed up the Nav Menu widget. For some reason, you added a CSS rule in the Dropdown items that takes the value from Main Menu's Space Between option and halves it to add left and right spacing, therefore messing up thousands of Nav Menus across the web. Why would you do that?

![image](https://user-images.githubusercontent.com/60075863/140429858-c34bb877-6190-427d-9fb8-b9d4389ca8b0.png)

![image](https://user-images.githubusercontent.com/60075863/140430246-461fd577-7e88-4dcd-97f4-a83cc4959fd5.png)

Just keep it like before, let us set the horizontal/vertical spacing however we want, that doesn't need any change.

## Steps to reproduce

Create a page, add a nav menu, set it like this:

![image](https://user-images.githubusercontent.com/60075863/140430373-71e79b7b-be5a-4631-b8ef-ca3232951dec.png)
![image](https://user-images.githubusercontent.com/60075863/140430409-ecb4ca14-430a-444d-93a0-fd5fee014898.png)

And you'll see that the 40px added in the Space Between options on Main Menu, gets halved and added for no reason to the dropdown. Why change something that works just fine?

Didn't the testing team see this issue before it got into the stable build?

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by gilesholder** [comment]
I have this issue as well

**Comment by Webtica** [comment]
Having the same issue.

**Comment by avivu** [comment]
Hello all,

This issue has been resolved in Elementor Pro v3.5.1.

Feel free to update

Thanks!

**Comment by azkalex** [comment]
Thank you!

**Comment by DesignMike** [comment]
Actually, this update completely broke the Global Widgets feature. You can save any element as a global widget, but pulling it back onto another page won't work anymore

**Comment by avivu** [comment]
> Actually, this update completely broke the Global Widgets feature. You can save any element as a global widget, but pulling it back onto another page won't work anymore

Hello @DesignMike 

There was an issue regarding the global widget that we solved.
We released a fix for that yesterday.

This issue has been resolved in Elementor v3.5.3

Feel free to update

Thanks!

**Comment by DesignMike** [comment]
Thank you for your quick reply. My admin dashboard still shows 3.5.2, which is a common problem I found with premium plugins. There's sometimes a 1-2 day delay before I get notified of a premium update.

Furthermore, the [change logs page](https://elementor.com/pro/changelog/?utm_source=wp-plugins&utm_campaign=pro-changelog&utm_medium=wp-dash) doesn't mention 3.5.3

**Comment by avivu** [comment]
Hello @DesignMike,
Sure, my pleasure.

The changelog you attached here is for the Pro version,
and the fix for the global widget is part of the core version (v3.5.3),
as you can see in [this changelog](https://wordpress.org/plugins/elementor/#developers)

Thank you!
