### ISSUE TITLE
Issue with Related Products using woopt WooCommerce Pixel Manager with the newest version of Elementor

### ISSUE THREAD

**Issue by alewolf** [elementor/elementor#16934]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description

Hi

I am the author of the [woopt WooCommerce Pixel Manager](https://wordpress.org/plugins/woocommerce-google-adwords-conversion-tracking-tag/). Some of my users are experiencing an issue when they use the Related Products Widget.

Here’s a [screenshot](https://monosnap.com/file/I9F64l7qCh1Vswv7G9PvPDYsNNFvTD) of the problem.

The WooCommerce Pixel Manager injects a `<script>` through the templating engine which an entirely valid way to do and works fine on all other themes with related products. For some reason Elementor  strips out the <script> tags (probably because it uses a filter to do that) for the related products template.

One user experiences the same bug using Elementor in combination with another [related product plugin](https://wordpress.org/plugins/wt-woocommerce-related-products/), and only after he updated Elementor to version 3.5.0. So the bug is probably not within the Elementor Related Products widget, but within Elementor itself. 

Thanks
Aleksandar

## Steps to reproduce

Install the wooptpm WooCommerce Pixel Manager and use the Elementor Related Products widget on a page. 

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Kcross8787** [comment]
Hi,

Not only is the related products widget not accepting any script inputs, it looks to only be accepting the return of a PHP formatted string variable. For example, when using any woocommerce functions like woocommerce_quantity_input( array(), $product, false ), it will be hidden. This may be caused by escaped html. This also affects the upsell widget along with the related products widget, but it does not affect the product or product archive widgets.

**Comment by juliebarcelino** [comment]
Just adding on, this issue effects Elementor Pro 3.5.0 and 3.5.1. We've had to roll back to the older version (Elementor Pro 3.4.2) while we wait for this to be resolved. Hope to see this fixed soon!

**Comment by juliebarcelino** [comment]
Just tested the new Elementor Pro 3.5.2 update and the issue still persists.

**Comment by mblodorn** [comment]
+1

**Comment by juliebarcelino** [comment]
+1 to bump this up

**Comment by Pancheau** [comment]
+1

**Comment by TheSashX** [comment]
+1

**Comment by Periago4** [comment]
Tengo el mismo problema y estoy perdiendo ventas cruzadas y dirigidas desde que una nueva empresa de marketing instaló este complemento.

**Comment by alewolf** [comment]
@Periago4: There is a workaround which i described in the following support article: https://docs.woopt.com/wgact/#/troubleshooting?id=elementor-related-products-widget

**Comment by Periago4** [comment]
Gracias Alewolf, es una opción válida, pero limita demasiado la edición estética del módulo y para mi no es una solución. Esperemos que elementor soluciones este problema rápidamente.

Un saludo!

**Comment by t-bo** [comment]
I agree the workaround is also too limited in my case in term of design editing.
Elementor need to fix this...

**Comment by juliebarcelino** [comment]
I wonder if the Elementor team will ever resolve this. It's frustrating just waiting and hearing nothing. I haven't updated Elementor for two months now while waiting for any update that would address this, and am getting worried about having it outdated for so long. I'll probably just get Elementor Free and Pro updated already and try the workaround, but I agree with all who find the temp solution too limited when it comes to design. 

Otherwise, really don't know what to do at this point...

**Comment by Biggbada** [comment]
Hi all and thanks to the author for following the job.
Clearly Elementor should cooperate and solve this issue.
Hope...

**Comment by alewolf** [comment]
Quick update. I was in contact with Elementor support three weeks ago and they promised to look into it, but have not given any ETA confirmation. I followed up today and their answer ist basically the same.

**Comment by alewolf** [comment]
@Biggbada I was thinking of offering a patched file for download. But, it is an Elementor premium add-on, so I can't do that. 

Your solution is probably the easiest one. But it is also risky. With every Elementor Pro update it will get overwritten.

**Comment by Biggbada** [comment]
@Periago4 you can you can do that now, it works:
first go to:
/elementor-pro/modules/woocommerce/widgets/product-related.php on line 236
The following line:
echo wp_kses_post( $related_products_html );

has to be replaced with this one:
echo $related_products_html;

**Comment by Biggbada** [comment]
This is a quick solution, better than nothing waiting they solve !
Thank you !

**Comment by Periago4** [comment]
Voy a hacerlo, no puedo estar esperando a que Elementor decida arreglarlo. Si hay que modificarlo cada vez que Elementor actualice, pues así lo haré mientras se soluciona.

Gracias!

**Comment by Biggbada** [comment]
@juliebarcelino in your ftp, folder /wp-content/plugins/elementor-pro/modules/woocommerce/widgets find the file product-related.php and modify line 236 as indicated !

**Comment by juliebarcelino** [comment]
> @juliebarcelino in your ftp, folder /wp-content/plugins/elementor-pro/modules/woocommerce/widgets find the file product-related.php and modify line 236 as indicated !

Woohoo, the solution works! Will keep using this solution for each new update until the Elementor team officially fixes this issue. Thank you so much!

**Comment by t-bo** [comment]
My Elementor Pro just did an auto-update, and I can't find the setting where to turn off this!
In the list of plugins, elementor auto update is not enabled.

**Comment by juliebarcelino** [comment]
@t-bo this article may help you: https://wpbuffs.com/disable-wordpress-auto-updates/

**Comment by t-bo** [comment]
> @t-bo this article may help you: https://wpbuffs.com/disable-wordpress-auto-updates/

The issue is related to plugin auto updates, not wordpress auto updates.
Elementor Pro just released 3.6.2 version that fixed the issue. But it also auto updated to this one.

**Comment by juliebarcelino** [comment]
> > @t-bo this article may help you: https://wpbuffs.com/disable-wordpress-auto-updates/
> 
> The issue is related to plugin auto updates, not wordpress auto updates. Elementor Pro just released 3.6.2 version that fixed the issue. But it also auto updated to this one.

@t-bo Got it. I had actually shared an article that came from this old thread related to auto update issue with Elementor: https://wordpress.org/support/topic/how-to-disable-auto-updates-2/. 

From my understanding, even if you have "auto update" turned off for plugins, they can still be automatically updated due to wordpress core auto updates being enabled. You will have to look at your wp-config.php file. 

This gives a little more information: https://wordpress.org/support/article/configuring-automatic-background-updates/#constant-to-disable-all-updates

In the section "Update configuration" there's a subsection that explains about plugin auto updates.

**Comment by juliebarcelino** [comment]
Just to bring back the main topic, Elementor Pro 3.6.2 has not fixed the issue for sure.

**Comment by wilsontoysec** [comment]
tengo problema con productos variables, el cliente escoge una variante pero no permite agregar al carrito es persistente en varios items

**Comment by alewolf** [comment]
@wilsontoysec ¿Está esto relacionado con el problema de este informe de error? ¿También experimentas la salida en el front-end? ¿Has probado las soluciones? (traducido con deepl.com)

**Comment by Periago4** [comment]
Por si alguien utiliza las up-sells, tambien tiene el mismo problema y puede solucionarse de la misma manera:

primero vaya a:
/elementor-pro/modules/woocommerce/widgets/product-upsell.php en la línea 210
La siguiente línea:
echo wp_kses_post ($upsells_html);

tiene que ser reemplazado por este:
echo $upsells_html;

Para que Elementor lo tenga en cuenta tambien si algun dia deciden arreglarlo.

**Comment by jmichaelward** [comment]
I encountered this today after updating the latest 3.6.5 security patch for Elementor. +1 on addressing as removing `wp_kses_post` is not a sufficient workaround.

**Comment by t-bo** [comment]
> I encountered this today after updating the latest 3.6.5 security patch for Elementor. +1 on addressing as removing `wp_kses_post` is not a sufficient workaround.

I confirm The above workaround to replace a line with Elementor Pro 3.6.5 is not enough

**Comment by Biggbada** [comment]
Who is fed up with this issue ?
I am !

**Comment by t-bo** [comment]
With latest 3.7.0 the workaround is working again.

**Comment by JesseLeeStringer** [comment]
Confirming 3.7.0 (Elementor Pro) and 3.6.5 (Elementor) - Fix is working 2022-05-16

**Comment by Biggbada** [comment]
Still having a bug...

**Comment by jordianubis** [comment]
Really irreal that the problem persists.

**Comment by andreasemprofile** [comment]
The problem persists and the fix works fine.
Come on Elementor, fix it.

**Comment by JesseLeeStringer** [comment]
The problem persists and the fix works fine.
Come on Elementor, fix it. ~ Its been almost a year already.

**Comment by contemplate** [comment]
WOW glad I found this thread.  The StoreApps Buy Now button is printing css on the page due to this bug.  ELEMENTOR Team please fix this!!

**Comment by JesseLeeStringer** [comment]
Another update, the same problem.

Fix works as intended.

**Comment by JesseLeeStringer** [comment]
Appears to be fixed *WOOT*

**Comment by alewolf** [comment]
@JesseLeeStringer It looks promising. However, the pro version 3.9.0 has not been published yet. I hope it won't take too long. 🤞

**Comment by JesseLeeStringer** [comment]
I spoke too soon.. same bloody issue

**Comment by alewolf** [comment]
I confirm that the new Elementor Pro version (3.9.0), released today, fixes the issue.

**Comment by nicholaszein** [comment]
Hello everyone!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.9.0**! 🥳 

Thank you so much for your feedback, and most importantly, thanks for being so patient! 🙏 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂

**Comment by jontro** [comment]
The same bug still exists in woocommerce/module.php at get_product_widget_content for upsells, related products and cross sells

**Comment by contemplate** [comment]
Yes I'm still experiencing this issue when using the Products module and selecting Upsells or Related.  The Upsells & Related Products modules work fine.
