### ISSUE TITLE
Form submissions no longer working

### ISSUE THREAD

**Issue by thetypist** [elementor/elementor#17195]
Elementor Pro - 3.5.2

I can see form submissions no longer. The link is no longer present under "elementor" category. I've tried to use an old link to see the submissions but the link doesn't work anymore.

**Comment by vgstef** [comment]
Same here. And in the form widget, the "Collect submission" doesn't show up in the after submit action field. Quite an urgent issue!

**Comment by thetypist** [comment]
Well, the forms are submitted properly and I'm getting email notifications but there is no record of the submissions on the database. We really need to get it fixed ASAP.

**Comment by Gabugbuster** [comment]
@thetypist  Can you check if the Safe Mode is active on your install? Since 3.5.0, the safe mode also disables the experiments. To ensure that it is not happening, go to "plugins" > "must use" on your WP dashboard.

**Comment by shilo-ey** [comment]
Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by vgstef** [comment]
> @thetypist Can you check if the Safe Mode is active on your install? Since 3.5.0, the safe mode also disables the experiments. To ensure that it is not happening, go to "plugins" > "must use" on your WP dashboard.

Yes, on my site, by deactivating the Safe Mode in the must use plugins, the problem was fixed.

**Comment by Aryehhirsc** [comment]
@shilo-ey im getting error logs on the server end as follows

[Thu Dec 16 19:18:27.208422 2021] [proxy_fcgi:error] [pid {redacted}:tid {redacted}] [client {redacted}] AH01071: Got error 'PHP message: PHP Notice: Undefined index: referrer in /home/511211.cloudwaysapps.com/{redacted}/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php on line 179', referer: https://{redacted}/

The error log is filled with this

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.5.1

Feel free to update

Thanks!

**Comment by JanWebofka** [comment]
> This issue has been resolved in Elementor v3.5.1
> 
> Feel free to update
> 
> Thanks!

I have 3.6.6. and in my log i see:

/data/a/c/ac2c7e41-7ed0-4926-a35e-ee9a45cfe267/DOMAIN.COM/web/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php on line 179

Is this problem still present for you ?

**Comment by wischn** [comment]
I am also still facing the same issue, working with Elementor 3.6.1. 
Could there please be a fix?
