### ISSUE TITLE
Inner section is not working in Elementor 3.5.1

### ISSUE THREAD

**Issue by saqib-naeem-nxb** [elementor/elementor#17249]
Hay folks. I just noticed that after uploading the Elementor 3.5.0 to 3.5.1, the Inner Section element stops working. I try to drag and drop but nothing happens

**Comment by dennylai1990** [comment]
yeah I've got the same issue

**Comment by mcrowell** [comment]
+1

**Comment by shilo-ey** [comment]
Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by tamelander** [comment]
I have this too. Rolling back to 3.5.0.

**Comment by arielk** [comment]
This issue has been resolved in Elementor v3.5.2

Feel free to update

Thanks!

**Comment by Jschmidt73** [comment]
It looks like the issue with the widgets is still persisting.  The widgets look fine when you go to Saved Templates, but when I drag a widget into the work area, it loses all it's previous configurations.

**Comment by JidWictut** [comment]
**Hello, the bug is not solved. When i drag a global widget into a new section it loses all it's design :(**

**Comment by jp-wolf** [comment]
Globales Widget funktioniert weiterhin NICHT (3.5.2)

**Comment by Jschmidt73** [comment]
@arielk, any updates on the Global Widget issue?

**Comment by arielk** [comment]
Please follow this issue: https://github.com/elementor/elementor/issues/17296
