### ISSUE TITLE
Improper WordPress root write permissions check

### ISSUE THREAD

**Issue by JoshuaGoode** [elementor/elementor#17255]
ℹ️  ***For those impacted by this, see the workaround at the end of this report.***
 
 Please note this is not host-specific -- while hosts like WordPress.com and Pressable encounter this issue, it can occur on ANY hosting environment configured in a similar way.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Elementor checks for write permissions to the core WordPress directory using ABSPATH.  That specifically isn't the issue but there are some related problems that it causes.

https://github.com/elementor/elementor/blob/7d2ab814abea1424627a5b1d5dd63dafcf785820/modules/system-info/reporters/server.php#L259

### 1) Why does Elementor check for this? It shouldn't be necessary.  

Elementor shouldn't need write access to WordPress core files.

Ideally, this would be checking to ensure `WP_CONTENT_DIR` is writeable, not the core files directory via `ABSPATH`.

Some hosts symlink and protect the core WordPress directory but leave the rest of the web root and wp-content accessible and writeable.  This is all Elementor should need.

On hosts that do symlink the root, Elementor generally _**works without issue**_ but the system report displays an error. 

`There are some writing permissions issues with the following directories/files: – WordPress root directory`

![Screen Shot on 2021-12-20 at 15:52:05](https://user-images.githubusercontent.com/4887830/146831203-b8f73990-aba9-4c70-b58a-bbf312121158.png)

### 2) The check causes the Kit Library import functions fail.

Since the Kit Library importer requires the write permissions check to pass, the kit importer will fail with `Elementor is not authorized to read or write from this file. Contact your site host.`

https://github.com/elementor/elementor/blob/7d2ab814abea1424627a5b1d5dd63dafcf785820/core/app/modules/import-export/iterator.php#L51

## Workaround

If we **_manually bypass this check, the kit importer will work without issue_** -- all pages and media are imported and the error will be dismissed.

A quick way to bypass this is to edit `wp-content/plugins/elementor/modules/system-info/reporters/server.php` and remove the `ABSPATH => 'WordPress root directory',` line from `$paths_to_check` 

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

Various hosting environments that symlink or protect the WordPress core files.

**Comment by JoshuaGoode** [comment]
Highlighting that if I eliminate the root directory check, system info returns `All right`.  The error is dismissed and the kit library importer works as expected.

**Comment by JoshuaGoode** [comment]
More on ABSPATH and WP_CONTENT_DIR in hosting environments like WordPress.com and Pressable.com

* https://pressable.com/knowledgebase/abspath-and-pressable/#understanding-abspath
* https://wordpress.com/support/incompatible-plugins/#using-abspath-read-on

**Comment by matthollis83** [comment]
I have got the same issue when trying to use the kits, just an error message Elementor is not authorised to read or write from this file. Contact your site host.

**Comment by mvtenney** [comment]
I have the same issue, and a client rollout plan hinged on having this working. I will not be giving root write permissions to the web user for security reasons.

**Comment by jrdnwntr** [comment]
I've also experienced this issue! I reached out to Elementor and they just told me to contact Wordpress support, who only took 5-6 minutes to fix the bug in Elementor's code. This is what Wordpress support said:

"Normally I would not be able to fix a bug with Elementor, but in this case, we are aware of how to edit the bug in Elementor's code, and it's a simple fix, so I will take care of that for you. I would encourage you to please report that you're experiencing the bug here: https://github.com/elementor/elementor/issues/17255. More reports will get more attention, and hopefully Elementor will fix it."

I don't know why Elementor hasn't removed this bug from their system yet, but I'm really disappointed that I'm paying for a premium subscription and my experience has been full of errors. ELEMENTOR: FIX YOUR SHIT!

**Comment by WanneCode** [comment]
i have the same problem. What can I do?

**Comment by rscafidi** [comment]
I'm also having the same issue on a self-managed linux server/fresh wordpress install.  I just paid for elementor before realizing this was an issue.  I applied the workaround that @JoshuaGoode highlighted (thanks for that!) and it worked for me, but would like if this could be patched in the release source code so i don't have to track it as a post-install configuration change.

**Comment by patrick-leb** [comment]
Thank you @gilzow !! I've been manually patching too.
Related to the same problem of lack of customization in the paths, I created this issue and PR : #18565

**Comment by Ryanhyatthailey** [comment]
I am having the same issue, worpress has said they have tried to work with elementor in patching this issue, but elementor wont fix it. and the workaround might not work with future updates if they don't foix it themselves.

**Comment by patrick-leb** [comment]
@Ryanhyatthailey There is a PR made by @gilzow, hopefully it gets accepted...

**Comment by gilzow** [comment]
Don't suppose anyone knows someone who works at Elementor who could ask them to look at the PR and accept it or use it as a basis to fix the root issue?

**Comment by gilzow** [comment]
Can someone from elementor ( @kobizz @KingYes @matipojo ?) give us an update on the status of this issue and/or the acceptance of the submitted PRs?

**Comment by happyfrank73** [comment]
This worked perfectly for me in March 2022, but on 9 June 22, I get this on both of my accounts in my FTP Error:        	

Could not open '/server.php' for writing.
Error:        	local: unable to open /server.php
Error:        	Critical file transfer error
Status:      	Disconnected from server

Did wordpress put an end to this workaround, or is something corrupted on my end?

**Comment by syhussaini** [comment]
I got the same issue reported by one of the users.
The workaround does not stand and is causing issues in importing the Kits.

Any updates on the fix?

**Comment by wiesenhauss** [comment]
This issue was reported by another user today. Any updates on a permanent fix to that?

**Comment by gilzow** [comment]
I spoke to a group of employees from Elementor while at WCEU, and asked them to push for someone to look at my pr but so far, I've heard nothing. @udidol any updates?

**Comment by udidol** [comment]
@gilzow I've reviewed your PR

**Comment by pneuschwander** [comment]
We are affected by this issue, too.

We operate Wordpress as a Docker Container using the "Static image / updates-via-redeploy" approach (https://hub.docker.com/_/wordpress)

Besides of /tmp and /run, only the /usr/src/wordpress/wp-content/uploads directory is writable at runtime.

The themes and plugins are baked into our custom docker image.

Elementor System Info reports:
```
There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
		 - .htaccess file
```

We tried to use Export / Import Kit and got the same error message.

Does Elementor require write access to any other directory or file other than / outside of `wp-content/uploads`?
(I think elementor mainly operates with/inside `wp-content/uploads/elementor`, isn't it?)

@JoshuaGoode raised the question whether it is necessary for elementor to have write access to the wp root directory. 

> Elementor shouldn't need write access to WordPress core files.
>
> Ideally, this would be checking to ensure WP_CONTENT_DIR is writeable, not the core files directory via ABSPATH.

I'd like to add here, that even write access to WP_CONTENT_DIR might not be necessary. Maybe it is enough to have write access to the uploads directory only. Or maybe even the elementor directory inside the uploads directory could be enough...

Further, I'd like to add the question, whether there is a need for elementor to have write access to the .htaccess file. This is another write permission issue that is reported for our setup and that prevents us from using Import / Export Kit.

By the way, the check for write permission warnings was introduced by PR https://github.com/elementor/elementor/pull/16720

Therefore, maybe @rotemee and/or @kobizz could add something to our discussion.

**Comment by gilzow** [comment]
> I'd like to add here, that even write access to WP_CONTENT_DIR might not be necessary. Maybe it is enough to have write access to the uploads directory only. Or maybe even the elementor directory inside the uploads directory could be enough...
> 
> Further, I'd like to add the question, whether there is a need for elementor to have write access to the .htaccess file. This is another write permission issue that is reported for our setup and that prevents us from using Import / Export Kit.

+1 on only needing write access to uploads, not all of WP_CONTENT_DIR. If Elementor needs a space to write to outside of uploads, then it should be exposed as a constant that can be changed.

**Comment by kettultim** [comment]
Just adding to this workaround for WPCOM staff: SFTP access is not necessary if you/user can access the plugin file editor. 

Visit [SITE]/wp-admin/plugin-editor.php?file=elementor%2Fmodules%2Fsystem-info%2Freporters%2Fserver.php&plugin=elementor%2Felementor.php and edit file directly in WP admin.

**Comment by allysonoakleydobbins** [comment]
Having the same issue! Wordpress has removed some code until Elementor is able to fix. Pretty frustratinG!!! I just purchased a pro plan to run across a bug (ongoing since December 2021???) not even one hour after purchase. Come on guys!

**Comment by imperfectnotions** [comment]
> Just adding to this workaround for WPCOM staff: SFTP access is not necessary if you/user can access the plugin file editor.
> 
> Visit `[SITE]/wp-admin/plugin-editor.php?file=elementor%2Fmodules%2Fsystem-info%2Freporters%2Fserver.php&plugin=elementor%2Felementor.php` and edit file directly in WP admin.

hello - complete non-prgrammer here looking to apply a kit - could you please help me out - is this an safe fix for someone who has no clue what they are doing ;) - thanks

**Comment by kettultim** [comment]
This is indeed a safe fix to make - if you screw anything up, you can simply delete and install Elementor again. Every time Elementor updates, it's going to wipe the changes you make directly to the plugin so this is only a temporary workaround.

**Comment by imperfectnotions** [comment]
thank you so much for getting back to me - now I've gotton to where you said to go in the editor but no clue what the heck I am supposed to type - je je - if it's not to much hassle give a hand - cheers

![image](https://user-images.githubusercontent.com/112255303/187227343-251f0bcf-a346-430e-986c-81c3a3901247.png)

**Comment by kettultim** [comment]
Sure! So - click anywhere within the code window, then type CTRL and F (to search the file), and then search for this: 

`ABSPATH => 'WordPress root directory',`

Delete that line and click the `Update File` button. That's it!

**Comment by imperfectnotions** [comment]
appreciate timely reply - unfortuantely I am still unable to apply a kit - SO FRIGGIN' frustrating - anyway I am going to use individual templates for now coz at  a loss - have a good one - ta

**Comment by imperfectnotions** [comment]
> Sure! So - click anywhere within the code window, then type CTRL and F (to search the file), and then search for this:
> 
> `ABSPATH => 'WordPress root directory',`
> 
> Delete that text and click the `Update File` button. That's it!

**Comment by g000m** [comment]
Just ran into that issue and this helped. Thanks.

**Comment by udidol** [comment]
Hi everyone. In the upcoming 3.8.0 version we did some serious work on the Import/Export mechanisms for kits.
As part of these efforts, we also fixed this issue with this file permissions check. So this will be resolved in the next major version of Elementor coming soon.

**Comment by udidol** [comment]
Core version 3.8.0 will be going into beta very soon

**Comment by syhussaini** [comment]
The issue was reported by another user today.
I am checking to see if we have any updates on the permanent fix for this issue.

**Comment by udidol** [comment]
The Import/Export mechanism was refactored in the upcoming Core 3.8.0 version. It will probably be released in the next month or so.

**Comment by BartEggermont** [comment]
Just ran into this error today, cannot seem to install any kits... really annoying tbh.

Have to do the whole thing manually now which sux

**Comment by udidol** [comment]
This issue has been resolved in Elementor Core v3.8.0.
There is a beta version for 3.8.0 out right now.
If you have not done so already, to get access to the beta, you can sign up as a Beta Tester in one of your staging sites. 

This is done by going to your test site's `Admin Dashboard > Elementor > Tools > Version Control` screen, enabling the beta tester setting, and saving. Within a couple of hours you should be getting an update notification for the beta version.

**Comment by patrick-leb** [comment]
@udidol this is still an issue with Elementor 3.8.1

```php
// web/app/plugins/elementor/app/modules/import-export/module.php


	private function ensure_writing_permissions() {
		$server = new Server();

		$paths_to_check = [
			Server::KEY_PATH_WP_CONTENT_DIR => $server->get_system_path( Server::KEY_PATH_WP_CONTENT_DIR ),
			Server::KEY_PATH_UPLOADS_DIR => $server->get_system_path( Server::KEY_PATH_UPLOADS_DIR ),
			Server::KEY_PATH_ELEMENTOR_UPLOADS_DIR => $server->get_system_path( Server::KEY_PATH_ELEMENTOR_UPLOADS_DIR ),
		];

		$permissions = $server->get_paths_permissions( $paths_to_check );

		// WP Content dir has to be exists and writable.
		if ( ! $permissions[ Server::KEY_PATH_WP_CONTENT_DIR ]['write'] ) {
			throw new \Error( self::NO_WRITE_PERMISSIONS_KEY . 'in - ' . Server::KEY_PATH_WP_CONTENT_DIR );
		}

		// WP Uploads dir has to be exists and writable.
		if ( ! $permissions[ Server::KEY_PATH_UPLOADS_DIR ]['write'] ) {
			throw new \Error( self::NO_WRITE_PERMISSIONS_KEY . 'in - ' . Server::KEY_PATH_UPLOADS_DIR );
		}

		// Elementor uploads dir permissions is divided to 2 cases:
		// 1. If the dir exists, it has to be writable.
		// 2. If the dir doesn't exist, the parent dir has to be writable (wp uploads dir), so we can create it.
		if ( $permissions[ Server::KEY_PATH_ELEMENTOR_UPLOADS_DIR ]['exists'] && ! $permissions[ Server::KEY_PATH_ELEMENTOR_UPLOADS_DIR ]['write'] ) {
			throw new \Error( self::NO_WRITE_PERMISSIONS_KEY . 'in - ' . Server::KEY_PATH_ELEMENTOR_UPLOADS_DIR );
		}
	}

```

We're assuming here that wp-content is writeable. It's not the case for all installations. We need to either get rid of that or have filters allowing to by-pass the check.

**Comment by udidol** [comment]
@patrick-leb Our Import process includes installing plugins, so we need the Plugins and Uploads directories

**Comment by patrick-leb** [comment]
Every single import requires plugins? That's a very aggressive behaviour. You're basically killing the library for anyone using https://github.com/roots/bedrock/ or any kind of version controlled deployment.

**Comment by mvtenney** [comment]
Can plugin installation be placed behid a flag in settings? There are a variety of reasons that plugin installation would be disabled or discouraged on an installation. Security being the most prominent.

**Comment by cuemarie** [comment]
@udidol , I'm still seeing folks run into issues importing kit libraries on the newest versions of Elementor. Now that the original problematic code is removed (the the `ABSPATH => 'WordPress root directory',` line from `$paths_to_check`), the workaround above is no longer of use. 

Reopening this for further investigation.

**Comment by cuemarie** [comment]
Since this issue has been closed without resolution, a new version of the issue has been re-opened here: https://github.com/elementor/elementor/issues/21036

**Comment by gudyo** [comment]
How could this have been closed when it is still happening? I recently (a week ago) purchased Elementor Pro and have been fighting with this ever since. It isn't mentioned on any of the Elementor support or documentation pages. I even reached out to the "support" which is supposed to be 24/7 which was entirely useless.

**Comment by mkenacnibuk** [comment]
Today - I will skip how long time I spent with Support

* bought elementor-pro 3.20.1
* install [Elementro Pro via Composer](https://elementor.com/help/installing-elementor-pro-with-composer/) - in CLI it is still asking me for uname&psswd on elementor.com while composer is trying to install it -> support center finally told me to install it manually because they can't help me ( I have wordpress on docker- with nginx, db, php, phpmyadmin, etc... ) You probably understand how satisfied I'm I bought Elementor Pro...
* **but what I can confirm - this issue is closed but I still HAD problem to [APPLY] given kit form Wp-Dashboard->Elementor->Kit Library** 
* I had to overcome it by instructions mentioned in this chat group
![image](https://github.com/elementor/elementor/assets/17276604/a29e9ea7-2e2f-4244-adab-1892be300d21)

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor v3.23.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

### 🔒 We are closing the comments in this issue.

If you are still experiencing something similar, please open a new issue.

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
