### ISSUE TITLE
Menu is not working on mobile version after updated the latest Elementor

### ISSUE THREAD

**Issue by Watashiadmin** [elementor/elementor#17324]
Menu is not working on mobile version after updated the latest Elementor, have to try/wait few times

https://user-images.githubusercontent.com/96811551/147633759-720361ec-f754-4bbf-a8d3-f4d960656339.mov

**Comment by KazOverOnGitHub** [comment]
@Watashiadmin Is your problem still there? I'm dealing with a similar bug on mobile version of my site https://gamesguru.pl/ and looking for a solution. BTW - the video you posted is broken.

**Comment by Watashiadmin** [comment]
> @Watashiadmin Is your problem still there? I'm dealing with a similar bug on mobile version of my site https://gamesguru.pl/ and looking for a solution. BTW - the video you posted is broken.

Yes. The problem is still here.

**Comment by KazOverOnGitHub** [comment]
@Watashiadmin I have fixed the issue on my website, so I will try to guide you to the solution if you are still struggling with this problem.

Are you currently using any software (maybe WordPress plugin) to optimize your website speed? Something that can limit how much code your site visitors load? In my case, it was the Rocket Loader feature in CloudFlare.

**Comment by Watashiadmin** [comment]
> @Watashiadmin I have fixed the issue on my website, so I will try to guide you to the solution if you are still struggling with this problem.
> 
> Are you currently using any software (maybe WordPress plugin) to optimize your website speed? Something that can limit how much code your site visitors load? In my case, it was the Rocket Loader feature in CloudFlare. If you are using something like this, try disabling it and see if the problem persists after a while. Also keep in mind that enabled caching can slow down changes made to your site.

Thank you for your suggestions, I've tried. But the problem is still here... sigh..
