### ISSUE TITLE
✅ 🐞 Bug report: Error with Vimeo videos in lightbox created with dynamic tags in WP 5.9

### ISSUE THREAD

**Issue by augustoms** [elementor/elementor#17619]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When using a button or image element, we can enable a lightbox in the LINK field through the dynamic tags available with Elementor Pro. By enabling this function, we can choose between displaying an image or a video. Selecting the 'Video' option, and including the URL of any Vimeo video, when the lightbox is activated the Vimeo player displays an error, informing that the video embed code is incorrect.

![CleanShot 2022-01-28 at 18 23 46](https://user-images.githubusercontent.com/3129481/151623449-cfa766fd-3d42-4c5f-a456-ac070b865d13.gif)

- This issue only occurs in WordPress version 5.9;
- This issue occurs with any other element that allows enabling a lightbox through dynamic tags in the LINK field;
- This issue does not occur with Youtube videos;
- This issue does not occur with Video elements (where it's possible to enable the lightbox when Image overlay is enabled).

### Steps to reproduce

- In a fresh wp 5.9 install, activate both elementor and elementor pro;
- In a blank page, editing with elementor, insert a button element;
- In the button LINK field, click on the 'dynamic tags' button and select "Actions > Lightbox";
- In the 'Lightbox' settings, select type 'VIDEO', and insert a Vimeo video URL (eg: https://vimeo.com/235215203);
- Publish and have a look at the page;
- Click on the button and check the error in the lightbox Vimeo embed video.

![CleanShot 2022-01-28 at 18 07 03](https://user-images.githubusercontent.com/3129481/151622309-fe7b97d4-ff1d-45ce-a912-12e5a6b622df.gif)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.6.40
	PHP Version: 7.3.13
	PHP Max Input Vars: 1000
	PHP Max Post Size: 500M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9
	Site URL: _(hidden)_
	Home URL:  _(hidden)_
	WP Multisite: No
	Max Upload Size: 500 MB
	Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Sao_Paulo
	Admin Email:  _(hidden)_
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.5.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36

== Active Plugins ==
Elementor
Version: 3.5.4
Author: Elementor.com

Elementor Pro
Version: 3.5.2
Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility Improvements: Inactive
	Import Export Template Kit: Inactive
	Additional Custom Breakpoints: Inactive
	Hide native WordPress widgets from search results: Inactive
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Landing Pages: Inactive
	Color Sampler: Inactive
	Favorite Widgets: Inactive
	Admin Top Bar: Inactive
	Form Submissions: Inactive
	Scroll Snap: Inactive


== Log ==
	


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	

				

````

</details>

**Comment by rjvas** [comment]
Just came here to corroborate this. There was a similar ticket for YouTube and privacy settings and that was even fixed ( https://github.com/elementor/elementor/issues/17749 ) but this continues to be a problem for us.

Support said it's known and a fix will be out eventually but because there's a million other things going on, no ETA.

I just wanted anyone else seeing this to not feel helpless or crazy. =)

**Comment by vincentjflorio** [comment]
I saw that this similar YouTube/privacy settings issue was resolved ( https://github.com/elementor/elementor/issues/17749 ) but wanted to corroborate this Vimeo one specifically, which also occurs for me even with the videos set to Public.

Support said it's known and will be addressed but they don't have an ETA. Didn't want anyone else to feel helpless or crazy =)

**Comment by adverman** [comment]
Same issue here! Any ETA?

**Comment by garylevansjr** [comment]
If you need a dirty temp fix, on line 113 of /wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/lightbox.php,
Change:
`'url' => $video_url,`
To:
`'url' => str_replace('#t=','?#t=',$video_url),`

Timecode is not even an option on the lightbox video tag, so I think this will work until the Elementor team releases a clean patch.

**Comment by steveni1963** [comment]
I noticed that this bug seemed to have been fixed for previous 2 updates but latest update today has caused this issue again.  The fix posted by garylevansjr restores functionality.

**Comment by rftmedia** [comment]
Just tried the above dirty patch. Still not working over here.

**Comment by ashleyjenniker** [comment]
This worked for me - https://player.vimeo.com/video/235215203?h=dce96a3d73

note the hash parameter at the end of the URL. This works for both public and private videos

**Comment by ncasedk** [comment]
> If you need a dirty temp fix, on line 113 of /wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/lightbox.php, Change: `'url' => $video_url,` To: `'url' => str_replace('#t=','?#t=',$video_url),`
> 
> Timecode is not even an option on the lightbox video tag, so I think this will work until the Elementor team releases a clean patch.
> 
> I could not find the JS hook for lightbox open, if there is one, you can remove the #t= from the URL and it works too

Thanks @garylevansjr !
Your dirty fix did the job for me. Phew!

**Comment by azanoni** [comment]
Any news about this issue?

**Comment by getcordial** [comment]
This bug is still haunting me. Wordpress Version 6.0.1, Elementor Version 3.7.0, Elementor Pro Version 3.7.3. No other plugins and hello theme. 
The temp fix from @garylevansjr sorted it out for me. Thank you so much!

**Comment by kerr-nz** [comment]
Elementor say this issue was related to Wordpress version, but it keeps coming back and has never been fixed.  Been a bug for about 9 months now, resulting in your entire site breaking wherever you have used a lightbox to show a Vimeo video.

The work-around of adding a Hast to the end of the Viemo share URL is better than editing the Elementor code, as your edits get overwritten every time Elementos do an update.

Simply add something like ?h=2342323 to the end of your Vimeo Share URL.

**Comment by azanoni** [comment]
> Elementor say this issue was related to Wordpress version, but it keeps coming back and has never been fixed. Been a bug for about 9 months now, resulting in your entire site breaking wherever you have used a lightbox to show a Vimeo video.
> 
> The work-around of adding a Hast to the end of the Viemo share URL is better than editing the Elementor code, as your edits get overwritten every time Elementos do an update.
> 
> Simply add something like ?h=2342323 to the end of your Vimeo Share URL.

Sadly we cannot edit more than 100 videos just because they dont fix this issue. This is being annoying

**Comment by anjanphukan** [comment]
Adding hash like ?h=0123456789 worked for me. But I wanted to check if there is any permanent solution from Elementor.
Thank you.

**Comment by mateitudor** [comment]
Still an error in 3.10

**Comment by getcordial** [comment]
Yes this is still an issue on my site. It has been an annoyance for over a year now 

- WP 6.1.1
- Hello Theme 
- Elementor Version 3.11.2
- Elementor Pro Version 3.11.3

Adding the ?h=0123456789 works as a temp fix
Thank you

**Comment by rouken-co** [comment]
+1

Still an issue. The ?h=0123456789 trick works well, but you shouldn't have to do that.

**Comment by mateitudor** [comment]
Lightboxes are a mess. They don't work with most things, including GravityForms. Classic Elementor.

**Comment by gervy28** [comment]
Something similar worked for me, it seems like a Vimeo sharing issue rather than an Elementor issue:
- Access the video at Vimeo
- Click Share
- Go to embed code
- copy the `src` portion of the URL that includes the `?h=XXXXXX` parameter, it will look something like this:
`<iframe src="https://player.vimeo.com/video/XXXXXXXX?h=XXXXXXXXX&title=0&byline=0&portrait=0" width="640" height="360" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen>`
- Use that as your iFrame link

**Comment by michaelhaberle** [comment]
For embedding videos, it's a bit more involved. It requires making thumbnails or grabbing the generated ones manually to avoid the placeholder thumbnail that would otherwise show. To embed:

1. Select "self hosted"

2. Use the URL in this format, making sure to update the video ID ("VIDEO_ID_HERE")
https://player.vimeo.com/video/VIDEO_ID_HERE?h=0123456789

**Comment by WebblaJordan** [comment]
Just adding to this, I had the same issue but found setting the video to "unlisted" on Vimeo settings was the only link it accepted. Hope this helps.

**Comment by bgmckenzie** [comment]
I'm glad I found this thread, tho I'm sorry it's the bug hasn't been fixed. I've found that the fake query string solution works with the url as simple as https://vimeo.com/123456789?h=1. Also, the query string is not necessary for unlisted Vimeo videos, presumably because those urls have two code numbers(. . . vimeo.com/123456789/ab12c3d4567). Ugh.

**Comment by TChord22** [comment]
Lol still seems to be an issue, the following URL worked for me https://player.vimeo.com/video/VIDEO_ID_HERE?h=0123456789
But anyone figure out how to do an auto play? LOL!

**Comment by gerardreches** [comment]
This is still an issue with the latest version of WordPress, Elementor, and Elementor Pro.

**Comment by dkndn** [comment]
+1 still the issue in dozends of installations..
Elementor 3.19.3
Elementor Pro 3.19.2

**Comment by kathleenraabe** [comment]
Still an issue in:
Elementor - 3.20.3 and Elementor Pro - 3.20.2
![screenshot](https://github.com/elementor/elementor/assets/100250512/8099515c-f6e4-4589-aa23-fca27c65504c)

**Comment by 319heads** [comment]
Over 2 years later and this is still a bug! Can we please get this prioritized?

**Comment by nicholaszein** [comment]
Hello everyone!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor v3.23.0! 🥳 

Now Vimeo videos that have privacy settings enabled should load correctly on the lightbox.

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
