### ISSUE TITLE
🐞 The menu cart widget icon crashes under certain conditions.

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#17705]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

hello @avivu , If you remember, in beta 3.6 I reported a bug that if the "Font-Awesome Inline" option is enabled, the menu cart widget icon will crash. And you did not succeed in reproducing it.

I researched this problem further and came to the conclusion that if you look at the website as an admin, it's right. But if you visit the website as a guest user, the menu cart icon is completely broken. It's like this : https://prnt.sc/26o6k1j

### Steps to reproduce

Enable the "Font-Awesome Inline" option and then view the website as a guest user. The menu icon in the menu is completely broken.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

elementor Version 3.5.5
elementor pro Version 3.6.0
wordpress Version 5.9
theme : hello elementor Version 2.5.0

**Comment by avivu** [comment]
Hi @Michaelgimii 

Thank you for your research. Appreciated!
We are aware of this issue and will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.7.2

Feel free to update

Thanks!

**Comment by malihamannanss** [comment]
I have updated to the latest version 3.7.2 but the cart icon is still not showing. This is not resolved. This works on 3.7.1 so I'm still on that version.
