### ISSUE TITLE
🐞 Bug report: Sticky Header cause website to automatically scroll down on resize

### ISSUE THREAD

**Issue by abbasdv** [elementor/elementor#17839]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Sticky Header causes website to automatically scroll down when window is being resized back and forth.

### Steps to reproduce

Install latest version of elementor & elementor pro as of today (2022-02-14).

Create a sticky header.

Go to homepage, resize the window. (Autmatically Scrolls down)

Now, remove sticky effect on header and resize again. (Works fine i.e. no autmatic scroll)

Happens in edit mode aswell.

Theme: OceanWP Child Theme

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment == 
Operating System: Linux 
Software: Apache 
MySQL version: MySQL Community Server (GPL) v5.7.37 
PHP Version: 7.4.27 
PHP Max Input Vars: 1000 
PHP Max Post Size: 30M 
GD Installed: Yes 
ZIP Installed: No 
Write Permissions: All right 
Elementor Library: Connected 

== WordPress Environment == 
Version: 5.9 Site 
URL: website 
Home URL: website 
WP Multisite: No 
Max Upload Size: 30 MB 
Memory limit: 256M 
Permalink Structure: /%postname%/ 
Language: en-US 
Timezone: 0 
Admin Email: 
Debug Mode: Inactive 

== Theme == 
Name: OceanWP Child Theme 
Version: 1.0 
Author: OceanWP 
Child Theme: Yes 
Parent Theme Name: OceanWP 
Parent Theme Version: 3.1.3 
Parent Theme Author: OceanWP 

== User == 
Role: administrator 
WP Profile lang: en_US 
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 

== Active Plugins == 
Ajax add to cart for WooCommerce 
Version: 1.2.8 
Author: QuadLayers 

Elementor 
Version: 3.5.5 
Author: Elementor.com 
Elementor Pro Version: 3.6.2 
Author: Elementor.com 

Theme Editor 
Version: 2.7 
Author: mndpsingh287 

Visibility Logic for Elementor 
Version: 2.2.8 
Author: StaxWP 

WooCommerce Version: 6.2.0 
Author: Automattic 

== Elementor Experiments == 
Optimized DOM Output: Active by default 
Improved Asset Loading: Active by default 
Improved CSS Loading: Active by default 
Inline Font Icons: Inactive by default 
Accessibility Improvements: Active by default 
Import Export Template Kit: Active by default 
Additional Custom Breakpoints: Active by default 
Hide native WordPress widgets from search results: Active by default 
Default to New Theme Builder: Active by default 
Landing Pages: Active by default 
Color Sampler: Active by default 
Favorite Widgets: Active by default 
Admin Top Bar: Active by default 
Page Transitions: Active by default 
Form Submissions: Active by default 
Scroll Snap: Active by default 

== Log == 
PHP: showing 3 of 3PHP: 2022-02-07 02:27:59 [notice X 2][/home/website/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array ( 'trace' => ' #0: Elementor\Core\Logger\Manager -> shutdown() ', )] 

PHP: 2022-02-09 12:51:49 [notice X 2][/home/website/public_html/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array ( 'trace' => ' #0: Elementor\Core\Logger\Manager -> shutdown() ', )] 

PHP: 2022-02-13 21:00:05 [error X 2][/home/website/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 8774984 bytes) [array ( 'trace' => ' #0: Elementor\Core\Logger\Manager -> shutdown() ', )] 

JS: showing 1 of 1JS: 2022-02-07 12:51:11 [error X 7][website/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:453832] Cannot read properties of null (reading \'getBoundingClientRect\') 

Log: showing 1 of 12022-02-13 16:48:15 [info] Elementor data updater process has been queued. [array ( 'plugin' => 'Elementor Pro', 'from' => '3.6.0', 'to' => '3.6.1', )] 

== Elementor - Compatibility Tag == 
Elementor Pro: Compatible 
Visibility Logic for Elementor: Compatible 

== Elementor Pro - Compatibility Tag == 
Visibility Logic for Elementor: Compatible

**Comment by Trinto610** [comment]
Yes, facing the same issue..... infact the tab widget is working anomalously when the header is positioned fixed.... when clicked on a tab item the website scrolls down by few pixels for no reason...... this isn't happening when the fixed positioning is removed.
I tried to find the solution for it in the devTools and found that some javascript code reruns when the devtools window is resized....we can see some changes happening in the header HTML section.......
One More Important thing, when the devTools window is resized, we get this error message in the console "[Violation] Forced reflow while executing JavaScript took 50ms" --> This message does not only once it keep appearing as long as the window is resized.

![Screenshot 2022-02-16 003846](https://user-images.githubusercontent.com/79373886/154131808-683be915-9a91-4a48-85c2-1574b55ea1bf.png)
@abbasdv @nicomollet @iamntz @ibndawood @rsiddall

**Comment by abbasdv** [comment]
Here is a video

https://files.katart.com/v/6dWTjL6YaaHm4MupwDzQ

This bug was seen in 2018 - https://github.com/elementor/elementor/issues/5740

**Comment by andriussok** [comment]
I had the same issue with tabs-widget and dropdown elements, which kept shifting content.
I used this workaround and it's kinda working:
set ".elementor-location-header" to fixed height in px in your CSS;
or set static header height dynamically with JS by calculating child elements height
```
<script>
// Prevent content shifts when header is sticky.
const fixsticky = event => {
  let header = document.querySelector('.elementor-location-header');
  let sections = header.querySelectorAll('.elementor-top-section');
  let height = 0;
  if (sections.length) {
    [...sections].map( section => {
      if ('none' != section.style.display && 'hidden' != section.style.visibility) {
        height += parseInt(section.offsetHeight, 10);
      }
    });
    header.style.height = height + 'px';
  }
};
window.addEventListener('load', fixsticky );
window.addEventListener('resize', fixsticky );
</script>
```

**Comment by Trinto610** [comment]
I am already using js for my header, I am using it to make the header appear when the window is scrolled up and disappear it when scrolled down.... I am hoping for elementor team to fix it from their end.....

**Comment by shilo-ey** [comment]
Hey all,

This issue will be fixed in both Elementor v3.6.0 and Elementor Pro v3.6.4

Thanks for reporting

**Comment by abbasdv** [comment]
Hi shilo-ey,

I just updated to 3.6.4 but the issue seems to remain. The sticky header causes the website to scroll down when i resize my window.

Anything I'm missing?

**Comment by janonkelbach** [comment]
> 

Same here. Updated Elementor Pro to 3.6.4 and the issue is still there.

**Comment by Trinto610** [comment]
Yes same here... issue not solved!

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.6.0

Feel free to update

Thanks!

**Comment by Csaba01** [comment]
> This issue has been resolved in Elementor v3.6.0
> 
> Feel free to update
> 
> Thanks!

Thanks!

**Comment by xxHeartFirexx** [comment]
Page jumping/skipping down on scroll stop still isn't fixed. I have disabled sticky headers to solve the issue. Many others are still complaining about the issue. I see it in the elementor pro changelog website with sticky header on the page. Any idea when it will finally be fixed?

**Comment by Csaba01** [comment]
For me, updating Elementor 3.6.0 solved the issue.

**Comment by xxHeartFirexx** [comment]
Not for me. Even alot of other people I know. It did however fix all the other sticky header issues, but the scroll skipping on stop remained. I use an image in my header, not sure if that would effect it. I have update the look of the site and don't use sticky on header now. Ill keep a check on the other people sites and see if it ever goes away. There are 2 threads still going on in the elementor pro changelog about it.

**Comment by Csaba01** [comment]
Sorry I didn't post my comment for the correct bug report. I had a problem with the toggle widget.
#17821

**Comment by 79ho3ein** [comment]
> Sorry I didn't post my comment for the correct bug report. I had a problem with the toggle widget. #17821

Other than that is there still a problem?

**Comment by xxHeartFirexx** [comment]
Only issue I still see is sticky header makes page jump down when moving up or down. Note #17767  It is still very widespread. I browsed many sites that I knew had all updates current and they all scroll jump on moble. (If they have sticky headers.) I hope this is addressed soon. I had to redesign a header and turn sticky off because of the bug. I use e3.6 and epro 3.6.4 and its still there.

**Comment by Csaba01** [comment]
Other than that is there still a problem?

I haven't experienced any other issues yet.

**Comment by Csaba01** [comment]
> Other than that is there still a problem?

I haven't experienced any other problems yet.

**Comment by abbasdv** [comment]
Not fixed. 
I literally just updated to 3.6.2 and 3.6.4 (pro) and the website still scrolls up and down when I resize the window.

**Comment by xxHeartFirexx** [comment]
> Not fixed. I literally just updated to 3.6.2 and 3.6.4 (pro) and the website still scrolls up and down when I resize the window while having sticky header.

Yep. Thats what I been saying since Feb 3.6.0 pro update. There are alot of open threads going on about it. The sticky header scroll stop page jump is the reason most of us are stuck on pro 3.5.2. This is the most aggravating bug I've seen in awhile. Just wish it would get fixed finally. Roll back or disable sticky header to keep the nauseating scroll jump from messing with site visitors. Any devs reading this, is this ever going to be fixed?

**Comment by nimaaminz** [comment]
Still Have problem  with the latest elementor 3.6.3 version !

**Comment by ludvigeriksson** [comment]
This is still occurring in Elementor 3.6.4 (+ Elementor Pro 3.6.5)

**Comment by Michaelgimii** [comment]
Pro 3.7 will be released soon, but I'm still in version 3.5.4. Just because this bug exists in version 3.6. It's been a long time. When will it really be fixed?
