### ISSUE TITLE
🐞 Bug report: Sticky Header with accordion and other widgets

### ISSUE THREAD

**Issue by zlaten9** [elementor/elementor#18069]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I got on a very annoying bug in Elementor All versions after 3.5.0 (3.5.1 etc.)
I checked several sites and several servers

When there is a sticky header then an accordion / spoiler and other widgets with elements of clicking (like SWATCHES) bounce the site down and really creates a mess

If the header is not sticky, then everything works fine ..
Attaches a video
In version 3.5.0 this does not happen

https://www.youtube.com/watch?v=ylKNiWbMhD0

### Steps to reproduce

Just make sticky header and add an accordion widget
than yo can see what happens when you click on the accordion elements

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.32
	PHP Version: 7.4.28
	PHP Max Input Vars: 1000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.1
	Site URL: 
	Home URL: 
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: he-IL
	Timezone: 3
	Admin Email: 
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.5.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.5.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.3
		Author: Elementor.com

	Header and Footer Scripts
		Version: 2.2.1
		Author: Digital Liberation

	JetElements For Elementor
		Version: 2.6.2
		Author: Crocoblock

	JetEngine
		Version: 2.10.3
		Author: Crocoblock

	Join.chat
		Version: 4.3.2
		Author: Creame

	WP Fastest Cache
		Version: 0.9.9
		Author: Emre Vona

	Yoast SEO
		Version: 18.2
		Author: Team Yoast

== Elementor Experiments ==
	פלט DOM שעבר אופטימיזציה: לא פעיל כברירת מחדל
	טעינת נכסים משופרת: לא פעיל כברירת מחדל
	Improved CSS Loading: לא פעיל כברירת מחדל
	Inline Font Icons: לא פעיל כברירת מחדל
	שיפורי נגישות: לא פעיל כברירת מחדל
	Import Export Template Kit: פעיל כברירת מחדל
	Additional Custom Breakpoints: לא פעיל כברירת מחדל
	Hide native WordPress widgets from search results: פעיל כברירת מחדל
	Default to New Theme Builder: פעיל כברירת מחדל
	Hello Theme Header & Footer: לא פעיל כברירת מחדל
	דפי נחיתה: פעיל כברירת מחדל
	דוגם צבע: פעיל כברירת מחדל
	וידג׳טים מעודפים: פעיל כברירת מחדל
	באר עליון אדמין: פעיל כברירת מחדל
	מעבר עמוד: פעיל כברירת מחדל
	לידים: פעיל כברירת מחדל
	Scroll Snap: פעיל כברירת מחדל

== יומן שינויים ==
	
Log: showing 20 of 372022-02-15 02:41:25 [info] אלמנטור פרו/Upgrades - _on_each_version Start  
2022-02-15 02:41:25 [info] אלמנטור פרו/Upgrades - _on_each_version Finished 
2022-02-15 02:41:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-02-16 13:13:34 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.5.4',
  'to' => '3.5.5',
)]
2022-02-16 13:13:34 [info] elementor::elementor_updater Started 
2022-02-16 13:13:34 [info] אלמנטור/Upgrades - _on_each_version Start  
2022-02-16 13:13:34 [info] אלמנטור/Upgrades - _on_each_version Finished 
2022-02-16 13:13:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.5.4',
  'to' => '3.5.5',
)]
2022-03-03 16:56:01 [info] elementor-pro::elementor_pro_updater Started 
2022-03-03 16:56:01 [info] אלמנטור פרו/Upgrades - _on_each_version Start  
2022-03-03 16:56:01 [info] אלמנטור פרו/Upgrades - _on_each_version Finished 
2022-03-03 16:56:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-03-03 16:56:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-03-03 16:56:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-03-03 16:56:01 [info] elementor::elementor_updater Started 
2022-03-03 16:56:01 [info] אלמנטור/Upgrades - _on_each_version Start  
2022-03-03 16:56:01 [info] אלמנטור/Upgrades - _on_each_version Finished 
2022-03-03 16:56:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-03-03 16:56:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-03-03 16:56:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]

**Comment by shilo-ey** [comment]
Hey all,

This issue will be fixed in both Elementor v3.6.0 and Elementor Pro v3.6.4

Thanks for reporting

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.6.0

Feel free to update

Thanks!

**Comment by up-creator** [comment]
Hi, this bug is not solved.
it is happening with sticky elements in columns when placed further down on a page (not header).

**Comment by nestorespinal** [comment]
The bug continues, when you have an accordion and it is opened it does not remain in the column
