### ISSUE TITLE
✔️ 🚀 Feature Request: Add CSS transform option for column and container

### ISSUE THREAD

**Issue by Tanvir-Roky** [elementor/elementor#18268]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

There is the **transform** option under advanced setting which is very useful, but only available on widgets only.  But it will be nice to have this option for column, inner section, and container(on beta) too. This will allow adding some 3D effect or some hover effects to the container. Please see this image- 
![image](https://user-images.githubusercontent.com/80110072/160200179-a6ec4d5d-ebd5-42b2-ba00-1d4c1482812f.png)

### Describe the solution you'd like

Just add the transform option like widget

### Describe alternatives you've considered

In my case, i added some custom CSS on the column.

**Comment by 79ho3ein** [comment]
+1

**Comment by 3l3mentor** [comment]
+1

**Comment by septatrix** [comment]
Especially for column this is something we could very well use. Currently made the whole content into an image on which we apply the transforms though that obviously has some drawbacks like text being inaccessible to users and search engine crawlers as well as bad responsive behaviour.

<hr>

Also the obligatory: "Please do not write '+1' but instead add a :+1: reaction unless you have something to add to the conversation like your specific use case, a plugin or workaround which enables this behaviour, or if you started work on this and would like to show your code."

**Comment by nicholaszein** [comment]
Hello everyone!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.9.0**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂

**Comment by septatrix** [comment]
I have elementor 3.10.1 though I still do not see the option for transformations on neither sections nor columns nor inner sections.

![image](https://user-images.githubusercontent.com/24257556/215278695-01325413-791e-421a-8f5e-23fbbed403a7.png)

**Comment by 79ho3ein** [comment]
Hi @septatrix 

This option has been added to the container. I recommend you to update your websites to container. Many of the exciting features of Elementor that will be released in the near future will require the container to be active. It also seems that from the next version (3.12.0) the container will be enabled by default for Elementor.

**Comment by septatrix** [comment]
> This option has been added to the container. I recommend you to update your websites to container. Many of the exciting features of Elementor that will be released in the near future will require the container to be active. It also seems that from the next version (3.12.0) the container will be enabled by default for Elementor.

How would I do that? I assume it's the flexbox container beta feature in the settings?

**Comment by nicholaszein** [comment]
Hello @septatrix,

you can enable the Flexbox Container in your WordPress Dashboard > Elementor > Settings > Features page. Check **<ins>[this article](https://elementor.com/help/elementor-experiments-2/)</ins>** to learn more about enabling experiments.

To learn more about Flexbox Containers, please check **<ins>[this article](https://elementor.com/help/container-element/)</ins>**
