### ISSUE TITLE
🐞🔥The page jump bug is still present in elementor 3.6 & elementor pro 3.6.4. Of course only in mobile!

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18313]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

As the title suggests, this bug still exists. Of course, this time the bug is not related to the accordion widget or tab, **but only occurs when the header is sticky! Also, I experience this bug only on mobile and tablet.** We need to see what other users' experiences are like. Do they experience this bug on the desktop or not. 

### Steps to reproduce

Just sticky the header on top. Then open the site with mobile and scroll. The page jumps.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by hettbeans** [comment]
Came here for the same issue. This is infuriating as almost every single one of the dozens of deployed sites I have running on Elementor uses a sticky header.

It has to do with the viewport being redrawn after the mobile browser UI elements (e.g. the URL bar) scroll out of view. This is the kind of problem I used to deal with using Jupiter and WP Bakery years ago.

**Comment by Michaelgimii** [comment]
I have this bug too

**Comment by aureliePrd** [comment]
+1 !

**Comment by 79ho3ein** [comment]
The important thing is that this bug does not occur in Safari browser. I experience this bug in Chrome Android browser. hi
@shilo-ey Please check this bug. thanks

**Comment by plxrisa** [comment]
I have the same issue.

**Comment by xxHeartFirexx** [comment]
Same here. The page jumps down just as the scroll stops on moble. Very annoying user experience. Only with sticky header. I have disabled sticky header on moble untill this finaly gets resolved. (Hopefully very very soon)

**Comment by 79ho3ein** [comment]
@xxHeartFirexx , Yes, exactly. The page jumps when scrolling stops. But I only experience this bug on tablets and mobiles. Are you dealing with it only on mobile?

**Comment by xxHeartFirexx** [comment]
So far it has been just on mobile. With sticky header on top. The bug also affected tabs and accordion widgets but I heard that much was fixed. Now it is on Sticky Headers on mobile and tablet. It is unknown to me if it affects desktop sticky headers. Same symptoms, page jump down on scroll stop causing a nauseating user experience on mobile and tablets. If there isn't a sticky header the scroll jump is not present. This has been since epro 3.6.0.

**Comment by Deadlift79** [comment]
Yes, bug still present in some environments.
You can see it here before the footer (on tablet/mobile of course):

https://elementor.com/help/flexbox-settings-overview/

**Comment by rami-elementor** [comment]
Duplicate of #17767

**Comment by xxHeartFirexx** [comment]
@rami-elementor Do you know if this bug is being worked on? The scroll stop page jump bug. Many sites using sticky headers are greatly affected by it. Many of us are stuck on pro 3.5.2 to avoid it.
