### ISSUE TITLE
🐞 Bug report: Sticky effect bug - CONTAINER

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#18357]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When the sticky effect is activated on the top for a container, when scrolling the page, the container moves unexpectedly

### Steps to reproduce

Activate the sticky top mode and scroll the page

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

/

**Comment by ConsultMePL** [comment]
Yeah, there is an issue with this. I have a sticky header with Containers enabled. So when I change a scroll direction, a page jumps equally to the height of header. I can't understand why they still haven't released a fix yet. They are aware

**Comment by rodolphebertozzo** [comment]
@shilo-ey @arielk ???

**Comment by hb81010** [comment]
+1 

For me the same problem with the "inner" containers. I have 2 inner containers and the right container, which should sticky pinned jumps around.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.7.3

Feel free to update

Thanks!

**Comment by oliveandlake** [comment]
@shilo-ey  - this didn't fix it for me. In fact, it's broken it even more. In Pro v3.7.3 the sticky effect now doesn't work when scrolling. 

The sticky element now stretches out across the screen. Reverting back to the previous version fixes it. 

I tested it on a fresh install with only Elementor, Elementor Pro and Hello theme. Everything up to date. No other plugins.

Video - https://www.loom.com/share/cb2023b7d4184f7ea0ac56d623224aa8

I can give you a login if you want?

**Comment by shilo-ey** [comment]
Thank you.

There are indeed still some glitches.
We will resolve this issue and update.

Cheers.

**Comment by briski-design** [comment]
Same issue on Elementor v3.6.7

**Comment by NAROLLES** [comment]
> Merci.
> 
> Il y a en effet encore quelques bugs. Nous allons résoudre ce problème et mettre à jour.
> 
> Acclamations.

Hello
After elementor pro 3.7.3 update
I still encounter the problem
Thanks

**Comment by gfdesign** [comment]
Similar issue by here.
When user scrolls, the sticky container spans beyond its parent container.
https://www.loom.com/share/3861843f60e949eb9cb764260ff064ba
Best regards

**Comment by mkiii333** [comment]
Fix this issue!

**Comment by ara-amir** [comment]
Same issue on Elementor v3.7.5
Until the problem is solved, i use css position: sticky;

**Comment by ShifraCohen** [comment]
Same issue on Elementor v3.7.7!
Please fix it----
(Positiion: sticky css attribute is not working for me)

**Comment by arielk** [comment]
This issue has been resolved in Elementor v3.8.0-beta-6

Feel free to update

Thanks!

**Comment by NAROLLES** [comment]
Dear @arielk 
Hello
After last update of elementor and elementor pro
overall the problems of sticky are solved but I still sometimes have an error

/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.8.0

Uncaught TypeError: this.$element.sticky is not a function
    at child.activate (frontend.min.js?ver=3.8.0:2:19466)
    at e.each.r.<computed> [as activate] (frontend-modules.min.js?ver=3.8.0:2:9876)
    at child.run (frontend.min.js?ver=3.8.0:2:19777)
    at e.each.r.<computed> [as run] (frontend-modules.min.js?ver=3.8.0:2:9876)
    at child.onInit(frontend.min.js?ver=3.8.0:2:20585)
    at e.each.r.<computed> [as onInit] (frontend-modules.min.js?ver=3.8.0:2:9876)
    at Module.trigger(frontend-modules.min.js?ver=3.8.0:2:11235)
    at e.each.r.<computed> [as trigger] (frontend-modules.min.js?ver=3.8.0:2:9876)
    at init (frontend-modules.min.js?ver=3.8.0:2:10065)
    at child.Module(frontend-modules.min.js?ver=3.8.0:2:11315)

This is fixed by refreshing the page
like here
https://www.jardinerie-animalerie-fleuriste.fr/actualites/copie-de-top-jardinerie-animalerie-fleuriste-etes-vous-prets-pour-2022/680837/
Thanks

**Comment by hein-obox** [comment]
Hi @NAROLLES, 

Thank you for your message.

Would it be possibly for to share a video to demonstrate the issue? e.g. using www.loom.com?

Kind regards,
Hein

**Comment by NAROLLES** [comment]
Hello @hein-obox 
It's hard to reproduce it
most often this happens when it is an indirect arrival on the page .... via a newsletter or a social network
the same as a symptom when the problem exists .... the sharing buttons do not work .....
If that can help you - Thanks
