### ISSUE TITLE
🐞 Bug report: Container left/right padding does not work when its width is higher than screen width.

### ISSUE THREAD

**Issue by Arian-c27** [elementor/elementor#18414]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

 Container left/right padding does not work when its width is higher than screen width.

### Steps to reproduce

I encountered this issue when I added a container to the page and set the container width to 1500px
On screens smaller than 1500px width, the container correctly maintains a 100% max width so there's no horizontal scroll, however I can't add padding to it so the content doesn't touch the edges.

I know you can add an additional container within that container but I don't think this behaviour is intended, correct me if I'm wrong

You can see the issue reproduced here:
https://www.youtube.com/watch?v=M5h-7F_W_Q4

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.47 (Win64) OpenSSL/1.1.1k PHP/7.4.19
	MySQL version: MySQL Community Server - GPL v8.0.28
	PHP Version: 7.4.19
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 2G
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: http://192.168.178.55/voxel
	Home URL: http://192.168.178.55/voxel
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: voxel@test.de
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== Elementor - Compatibility Tag ==

**Comment by scottyzen** [comment]
@perks98 Your solution worked a treat. 

Elementor seem to be way overcomplication this. I don't understand why they can't just use max-width. Leave padding for just that. There is no need to re-invent anything here. Just make the GUI and mirror the normal properties.

**Comment by perks98** [comment]
> @perks98 Your solution worked a treat.
> 
> Elementor seem to be way overcomplication this. I don't understand why they can't just use max-width. Leave padding for just that. There is no need to re-invent anything here. Just make the GUI and mirror the normal properties.

@scottyzen glad it worked.

I think they are using padding to create the content area to reduce the DOM size as with the current sections and columns (without the flexbox experiment) Elementor team used a container div within a container div plus side margins to create the content area, so it reduces the overall HTML by getting rid of that extra container to create the content area.

**Comment by Arian-c27** [comment]
Something to note: The issue happens only when the width is set to Boxed. If you set it to full width, it works correctly.

**Comment by torchsmith** [comment]
> Something to note: The issue happens only when the width is set to Boxed. If you set it to full width, it works correctly.

Only problem with that is when you need a full-width bg-image. full width w/padding will add padding to the bg image as well.

**Comment by shilo-ey** [comment]
Hey,

This issue has been resolved in Elementor v3.7.0

Feel free to update

Thanks!

**Comment by abdulsamad1999** [comment]
> Something to note: The issue happens only when the width is set to Boxed. If you set it to full width, it works correctly.

hey! but it's not working also in full width mode

**Comment by abdulsamad1999** [comment]
> Hey,
> 
> This issue has been resolved in Elementor v3.7.0
> 
> Feel free to update
> 
> Thanks!

I have upgraded the version, but the issue still persists. if you have resolved it, it would lovely if you share it with others
