### ISSUE TITLE
🐞 Bug report: Container background overlay

### ISSUE THREAD

**Issue by petrou4ine** [elementor/elementor#18433]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When i put a video on the background of a container and try to overlay it with some transparent color in the tab below I can't do it. Looks like the Z-index of video background is more than the one of background overlay.

### Steps to reproduce

Just put a link to a video on a background of a container, than try to put any background overlay.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.38 (Debian)
	MySQL version: Debian 10 v10.3.29
	PHP Version: 7.4.21
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://cityherowear.com
	Home URL: https://cityherowear.com
	WP Multisite: No
	Max Upload Size: 30 МБ
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: ru-RU
	Timezone: Europe/Moscow
	Admin Email: petrou4ine@mail.ru
	Debug Mode: Active

== Theme ==
	Name: Astra-Child ДОЧЕРНЯЯ ТЕМА!
	Version: 1.5.5.1541693858
	Author: Andrey P
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 3.6.2
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: ru_RU
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36

== Active Plugins ==
	Big File Uploads
		Version: 2.0.2
		Author: Infinite Uploads

	Easy Google Fonts
		Version: 2.0.4
		Author: Titanium Themes

	Ecwid Ecommerce Shopping Cart
		Version: 6.10.20
		Author: Ecwid Ecommerce

	Elementor
		Version: 3.6.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.4
		Author: Elementor.com

	Error Log Monitor
		Version: 1.7.2
		Author: Janis Elsts

	FileBird Lite
		Version: 4.9.8
		Author: Ninja Team

	Google Tag Manager for Wordpress
		Version: 1.14.2
		Author: Thomas Geiger

	Insert Headers and Footers
		Version: 1.6.0
		Author: WPBeginner

	iThemes Security
		Version: 8.1.0
		Author: iThemes

	Premium Addons for Elementor
		Version: 4.9.5
		Author: Leap13

	Regenerate Thumbnails
		Version: 3.1.5
		Author: Alex Mills (Viper007Bond)

	Robin image optimizer
		Version: 1.5.6
		Author: Creative Motion <info@cm-wp.com>

	SendPulse Email Marketing Newsletter
		Version: 2.1.0
		Author: SendPulse

	Simple Custom CSS
		Version: 4.0.5
		Author: John Regan

	Smart Slider 3
		Version: 3.5.1.4
		Author: Nextend

	Starter Templates
		Version: 3.1.7
		Author: Brainstorm Force

	UpdraftPlus - Backup/Restore
		Version: 1.22.11
		Author: UpdraftPlus.Com, DavidAnderson

	WPForms Lite
		Version: 1.7.3
		Author: WPForms

	WPML Multilingual CMS
		Version: 4.4.8
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.1.6
		Author: OnTheGoSystems

	WPML Translation Management
		Version: 2.10.4
		Author: OnTheGoSystems

	WPS Hide Login
		Version: 1.9.4
		Author: WPServeur, NicolasKulka, wpformation

	Yoast Duplicate Post
		Version: 4.4
		Author: Enrico Battocchi & Team Yoast

== Must-Use Plugins ==
	Plugin Organizer MU
		Version: 10.1.6
		Author: Jeff Sterup

== Эксперименты Elementor ==
	Оптимизированный вывод DOM: Неактивен по умолчанию
	Улучшенная загрузка ресурсов: Активен
	Улучшенная загрузка CSS: Неактивен по умолчанию
	Встроенные шрифтовые иконки: Неактивен по умолчанию
	Улучшения доступности: Активен
	Импорт и экспорт набора шаблонов: Активен по умолчанию
	Дополнительные настраиваемые брейкпоинты: Неактивен по умолчанию
	Скрыть родные виджеты WordPress из результатов поиска: Активен по умолчанию
	: Неактивен по умолчанию
	Флексбокс-контейнер: Активен
	Конструктор темы по умолчанию: Активен по умолчанию
	Лендинги: Активен по умолчанию
	Сэмплер цветов: Активен по умолчанию
	Избранные виджеты: Активен по умолчанию
	Админ панель: Активен по умолчанию
	Page Transitions: Активен по умолчанию
	Заявки с форм: Активен по умолчанию
	Индикатор прокрутки: Активен по умолчанию

== Журнал ==
	
Log: showing 20 of 372021-12-04 20:38:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.7',
  'to' => '3.4.8',
)]
2022-04-11 21:53:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.8',
  'to' => '3.6.2',
)]
2022-04-11 21:53:57 [info] elementor::elementor_updater Started 
2022-04-11 21:53:57 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-11 21:53:57 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-11 21:53:57 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2022-04-11 21:53:57 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2022-04-11 21:53:58 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-11 21:53:58 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-11 21:53:58 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2022-04-11 21:53:58 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2022-04-11 21:53:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.8',
  'to' => '3.6.2',
)]
2022-04-11 21:53:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.8',
  'to' => '3.6.2',
)]
2022-04-11 21:55:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.1',
  'to' => '3.6.4',
)]
2022-04-11 21:55:12 [info] elementor-pro::elementor_pro_updater Started 
2022-04-11 21:55:12 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-04-11 21:55:13 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-04-11 21:55:13 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2022-04-11 21:55:16 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2022-04-11 21:55:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.1',
  'to' => '3.6.4',
)]

PHP: showing 6 of 6PHP: 2021-07-05 02:31:55 [notice X 221][/var/www/cityherowear/data/www/cityherowear.com/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined index: referrer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-07-06 00:38:09 [error X 1][/var/www/cityherowear/data/www/cityherowear.com/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::285] Uncaught Error: Call to a member function update_meta() on bool in /var/www/cityherowear/data/www/cityherowear.com/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:285
Stack trace:
#0 /var/www/cityherowear/data/www/cityherowear.com/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(166): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/cityherowear/data/www/cityherowear.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /var/www/cityherowear/data/www/cityherowear.com/wp-includes/class-wp-hook.php(292): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /var/www/cityherowear/data/www/ci [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-04 20:49:20 [notice X 1459][/var/www/cityherowear/data/www/cityherowear.com/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::230] Undefined index: field_label [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-06 11:23:09 [notice X 23][/var/www/cityherowear/data/www/cityherowear.com/wp-content/plugins/elementor-pro/modules/forms/classes/recaptcha-v3-handler.php::137] Undefined index: recaptcha_badge [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-06 12:28:13 [notice X 3][/var/www/cityherowear/data/www/cityherowear.com/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-12 12:14:25 [notice X 2][/var/www/cityherowear/data/www/cityherowear.com/wp-content/plugins/elementor-pro/modules/forms/classes/recaptcha-v3-handler.php::119] Undefined index: score [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Совместимый
	Premium Addons for Elementor: Совместимый

== Elementor Pro - Compatibility Tag ==
	
	Premium Addons for Elementor: Совместимый

**Comment by Mediafluent** [comment]
Same issue here using the new Flexbox Containers.

**Comment by 3l3mentor** [comment]
Same issue there. The background overlay is not working properly when the background is a video.
Happen only on flexbox container (not on sections).

**Comment by mbaierl** [comment]
Yes, same issue. The :before pseudo element (for the background overlay) is below the video, which is a separate DIV element.

**Comment by mbaierl** [comment]
Can be fixed with this CSS code:

```
selector:before {
    z-index: 10;
  }
  selector>*:not(.elementor-background-video-container) {
    z-index: 20;
  }
```

**Comment by Mediafluent** [comment]
Thanks for the CSS, @mbaierl 
Moving forward again!

**Comment by graf1x** [comment]
+1 But not a video background, but a slideshow background on a Flexbox container

**Comment by shilo-ey** [comment]
Hey all,

This issue has been resolved in Elementor v3.7.0

Feel free to update

Thanks!

**Comment by pafmobile** [comment]
As of version v3.7.3 this is NOT resolved, it's a bug. Here the same solution for Elementor Background Image Overlay with Scroll effects turned on does not show (the overlay i mean):

selector:before {
    z-index: 10;
  }
  selector:hover>*:not(.elementor-motion-effects-container) {
    z-index: 20;
  }
  
It Just works with this CSS in container section .

**Comment by pafmobile** [comment]
> Hey all,
> 
> This issue has been resolved in Elementor v3.7.0
> 
> Feel free to update
> 
> Thanks!

NOT resolved, see above!

**Comment by udidol** [comment]
@pafmobile
What scenario did you encounter that is not solved in 3.7? Could you please provide detailed steps to reproduce the scenario that doesn't work for you?

**Comment by lllopo** [comment]
3.7.7 - NOT resolved. Elementor Background Image Overlay with Scroll effects turned on does not show.

**Comment by pafmobile** [comment]
> @pafmobile What scenario did you encounter that is not solved in 3.7? Could you please provide detailed steps to reproduce the scenario that doesn't work for you?

It's described above what else do you want to know?

**Comment by lllopo** [comment]
@udidol Just add a background image, a background overlay and enable some scroll effects and there you go - no overlay.

**Comment by justgkp** [comment]
https://user-images.githubusercontent.com/71189434/200512202-2ad5ae85-8fe4-49bb-a5bb-ecdd4ed02f1b.mp4

This issue has not been resolved in Elementor latest version. Please rectify it as early as possible as many customers are have been facing it and elementor team is not at all worried about this bug.

**Comment by Shehzad282** [comment]
video background with image overlay.

selector CSS_Selector {
z-index: -1;
}

e.g.

selector .elementor-background-video-container {
z-index: -1;
}

https://ayeshaharam.com

**Comment by Alta1re** [comment]
still not solved for two years now

**Comment by Robert080** [comment]
Same situation today. Tryng to set an overlay color to a pic setted as backgrpound of the container, the overlay color activate only on hover. This is unespected because the overlay color is setted only for "normal" but activate with hover.
