### ISSUE TITLE
🐞 Bug report: Elementor 3.6.8 Divider Widget breaks the container spacing

### ISSUE THREAD

**Issue by dara-mtl** [elementor/elementor#19288]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I create a 2 column layout and use a divider widget, that divider widget will automatically takes all the space in the container. It will start to act as if the container alignment was set to "space between". 
![Screenshot 2022-07-28 150704](https://user-images.githubusercontent.com/44647589/181455006-467f095a-4504-4bc3-8e50-7463e6058e54.png)

### Steps to reproduce

Create a container with 2 columns. Add any widget on the left (or right) that exceed the screen height. Add a divider widget in the opposite column, followed by any other widget. The divider widget will take all the space in that column and push the following widget at the end of the container.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.35
	PHP Version: 7.4.30
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://cambodiaadventuretours.com
	Home URL: https://cambodiaadventuretours.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: info@cambodiaadventuretours.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.6.8
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive
	Hide native WordPress widgets from search results: Inactive
	: Inactive by default
	Flexbox Container: Active
	Hello Theme Header & Footer: Inactive
	Landing Pages: Active by default
	Color Sampler: Inactive
	Favorite Widgets: Active by default
	Admin Top Bar: Inactive

== Log ==
	
PHP: showing 5 of 5PHP: 2022-07-23 11:28:21 [notice X 1][/home/cambodi4/public_html/cambodiaadventuretours.com/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-23 13:16:52 [notice X 488][/home/cambodi4/public_html/cambodiaadventuretours.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-25 15:30:01 [notice X 1][/home/cambodi4/public_html/cambodiaadventuretours.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-25 15:30:05 [notice X 1][/home/cambodi4/public_html/cambodiaadventuretours.com/wp-content/plugins/elementor/core/app/modules/import-export/import.php::110] Undefined offset: 157 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-28 00:47:46 [error X 1][/home/cambodi4/public_html/cambodiaadventuretours.com/wp-content/plugins/elementor/core/base/document.php::1703] Uncaught Error: Class 'Elementor\Core\Base\Elements_Iteration_Actions\Assets' not found in /home/cambodi4/public_html/cambodiaadventuretours.com/wp-content/plugins/elementor/core/base/document.php:1703
Stack trace:
#0 /home/cambodi4/public_html/cambodiaadventuretours.com/wp-content/plugins/elementor/core/base/document.php(1656): Elementor\Core\Base\Document->get_elements_iteration_actions()
#1 /home/cambodi4/public_html/cambodiaadventuretours.com/wp-content/plugins/elementor/core/base/document.php(1558): Elementor\Core\Base\Document->get_runtime_elements_iteration_actions()
#2 /home/cambodi4/public_html/cambodiaadventuretours.com/wp-content/plugins/elementor/core/base/document.php(1022): Elementor\Core\Base\Document->print_elements(Array)
#3 /home/cambodi4/public_html/cambodiaadventuretours.com/wp-content/plugins/elementor/includes/frontend.php(1092): Elementor\Core\Base\Document->print_elements_with_wrapper(Array)
#4 /home/cambodi4/public_html/cambodiaadventuretours.com/wp-content/plugins/elementor/includes/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2022-07-25 15:38:12 [error X 89][https://cambodiaadventuretours.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:475108] Cannot read properties of undefined (reading \'parent\') 
JS: 2022-07-26 03:17:33 [error X 3][https://cambodiaadventuretours.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view2324\") has already been destroyed and cannot be used. 
JS: 2022-07-26 03:17:33 [error X 1][https://cambodiaadventuretours.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view3339\") has already been destroyed and cannot be used. 

== Elementor - Compatibility Tag ==

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor v3.7.2

Feel free to update

Thanks!

**Comment by awebguy99** [comment]
I think the problem has come back. It's still happening for me on Elementor 3.7.8.
