### ISSUE TITLE
🐞 Bug report: Flex grow

### ISSUE THREAD

**Issue by asafmoraz** [elementor/elementor#19325]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

During one of the latest updates I'm not sure which version exactly, divider widget suddenly gets flex grow on it's css code and it looks like this on the front:

![Flex Grow](https://user-images.githubusercontent.com/59032032/182285055-bc744089-218f-4567-935b-5c5e1cb15dec.JPG)

While inspecting this element this is the css it gets from elementor, although there is no flex grow setting that was ever made:

.e-container>.elementor-widget-divider {
    width: var(--container-widget-width,100%);
    -webkit-box-flex: 1;
    -ms-flex-positive: 1;
    flex-grow: 1;
}

In order to fix this i had to do this:

.elementor-widget-divider 
{
    flex-grow:unset!important;
}

It happend to me also on a fresh website so it's definately a bug... 

### Steps to reproduce

Just add divider widget inside a container and see what happens... 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.25 (Debian)
	MySQL version: mariadb.org binary distribution v10.4.20
	PHP Version: 7.4.30
	PHP Memory Limit: 512M
	PHP Max Input Vars: 2500
	PHP Max Post Size: 10M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://magenpro.morazweb.com
	Home URL: https://magenpro.morazweb.com
	WP Multisite: No
	Max Upload Size: 10 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: he-IL
	Timezone: Asia/Jerusalem
	Admin Email: dkalaora@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.5.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

== Active Plugins ==
	Activity Log
		Version: 2.8.3
		Author: Activity Log Team

	Elementor
		Version: 3.6.8
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.3
		Author: Elementor.com

	EWWW Image Optimizer
		Version: 6.6.0
		Author: Exactly WWW

	FiboSearch - AJAX Search for WooCommerce
		Version: 1.18.1
		Author: FiboSearch Team

	GTM4WP
		Version: 1.16.1
		Author: Thomas Geiger

	JetEngine
		Version: 2.11.11
		Author: Crocoblock

	JetProductGallery For Elementor
		Version: 2.1.2
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.1.17
		Author: Crocoblock

	JetWooBuilder For Elementor
		Version: 1.12.4
		Author: Crocoblock

	Loco Translate
		Version: 2.6.2
		Author: Tim Whitlock

	One Click Accessibility
		Version: 2.0.3
		Author: One Click Accessibility

	WooCommerce
		Version: 6.7.0
		Author: Automattic

	WooCommerce PayPal Payments
		Version: 1.8.1
		Author: WooCommerce

	Woo Discount Rules
		Version: 2.4.3
		Author: Flycart

	Yaad Sarig Payment Gateway For WC
		Version: 2.1.50
		Author: YAAD-PAY & 10Bit

	Yoast SEO
		Version: 19.4
		Author: Team Yoast

== Must-Use Plugins ==
	Object Cache Pro (MU)
		Version: 1.14.5
		Author: Rhubarb Group

== הניסויים של אלמנטור ==
	פלט DOM שעבר אופטימיזציה: לא פעיל
	טעינת נכסים משופרת: לא פעיל
	טעינת CSS משופרת: לא פעיל
	Inline Font Icons: לא פעיל
	שיפורי נגישות: לא פעיל
	Import Export Template Kit: פעיל כברירת מחדל
	Additional Custom Breakpoints: לא פעיל
	Hide native WordPress widgets from search results: פעיל כברירת מחדל
	: לא פעיל כברירת מחדל
	Flexbox Container: פעיל
	Default to New Theme Builder: פעיל כברירת מחדל
	Hello Theme Header & Footer: לא פעיל כברירת מחדל
	דפי נחיתה: לא פעיל
	דוגם צבע: לא פעיל
	וידג׳טים מעודפים: פעיל כברירת מחדל
	סרגל אדמין עליון: פעיל כברירת מחדל
	מעבר עמוד: לא פעיל
	Notes: לא פעיל
	לידים: פעיל
	Scroll Snap: לא פעיל

== יומן שינויים ==
	
JS: showing 19 of 19JS: 2022-06-21 06:03:34 [error X 1][https://magenpro.morazweb.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view9498\") has already been destroyed and cannot be used. 
JS: 2022-06-21 06:17:27 [error X 1][https://magenpro.morazweb.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view24580\") has already been destroyed and cannot be used. 
JS: 2022-06-21 07:46:26 [error X 100][https://magenpro.morazweb.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:391230] Cannot read properties of undefined (reading \'parent\') 
JS: 2022-06-21 09:25:53 [error X 1][https://magenpro.morazweb.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:38470] Cannot read properties of undefined (reading \'getElementsByTagName\') 
JS: 2022-06-22 17:57:03 [error X 1][https://magenpro.morazweb.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.6.6:2:5384] Cannot read properties of null (reading \'toJSON\') 
JS: 2022-06-23 02:57:20 [error X 1][https://magenpro.morazweb.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view3928\") has already been destroyed and cannot be used. 
JS: 2022-06-23 03:47:25 [error X 1][https://magenpro.morazweb.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view6988\") has already been destroyed and cannot be used. 
JS: 2022-06-23 04:58:26 [error X 1][https://magenpro.morazweb.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view26006\") has already been destroyed and cannot be used. 
JS: 2022-06-23 18:01:44 [error X 1][https://magenpro.morazweb.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view1843\") has already been destroyed and cannot be used. 
JS: 2022-06-23 18:01:44 [error X 1][https://magenpro.morazweb.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view1851\") has already been destroyed and cannot be used. 
JS: 2022-06-24 03:58:17 [error X 1][https://magenpro.morazweb.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view30214\") has already been destroyed and cannot be used. 
JS: 2022-06-24 03:58:17 [error X 1][https://magenpro.morazweb.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view30447\") has already been destroyed and cannot be used. 
JS: 2022-06-24 03:58:18 [error X 1][https://magenpro.morazweb.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view30492\") has already been destroyed and cannot be used. 
JS: 2022-06-24 04:05:35 [error X 1][https://magenpro.morazweb.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view37265\") has already been destroyed and cannot be used. 
JS: 2022-06-24 04:16:38 [error X 1][https://magenpro.morazweb.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view80886\") has already been destroyed and cannot be used. 
JS: 2022-06-26 07:32:18 [error X 1][https://magenpro.morazweb.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view14770\") has already been destroyed and cannot be used. 
JS: 2022-06-27 03:14:16 [error X 1][https://magenpro.morazweb.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view13753\") has already been destroyed and cannot be used. 
JS: 2022-06-27 03:42:53 [error X 7][https://magenpro.morazweb.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:242773] Cannot read properties of undefined (reading \'html\') 
JS: 2022-06-27 06:58:32 [error X 1][https://magenpro.morazweb.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:158269] C.ui.sync.removeClass is not a function 

PHP: showing 8 of 8PHP: 2022-06-21 09:12:54 [notice X 12][/home/568315.cloudwaysapps.com/pkwvbkwqpy/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-21 12:35:14 [notice X 31][/home/568315.cloudwaysapps.com/pkwvbkwqpy/public_html/wp-content/plugins/elementor/core/app/modules/import-export/module.php::90] Trying to get property 'label' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-24 06:51:28 [notice X 6][/home/568315.cloudwaysapps.com/pkwvbkwqpy/public_html/wp-content/plugins/elementor/core/dynamic-tags/manager.php::73] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-26 09:21:08 [notice X 5][/home/568315.cloudwaysapps.com/pkwvbkwqpy/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/cart.php::2400] Undefined index: section_coupon_display [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-26 09:25:42 [notice X 3][/home/568315.cloudwaysapps.com/pkwvbkwqpy/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/checkout.php::4130] Undefined index: coupon_section_display [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-26 09:25:45 [notice X 2502][/home/568315.cloudwaysapps.com/pkwvbkwqpy/public_html/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1483] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-26 09:26:00 [notice X 1][/home/568315.cloudwaysapps.com/pkwvbkwqpy/public_html/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-02 06:30:30 [notice X 2][/home/568315.cloudwaysapps.com/pkwvbkwqpy/public_html/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 15 of 152022-07-04 02:07:17 [info] elementor::elementor_updater Started 
2022-07-04 02:07:17 [info] אלמנטור/Upgrades - _on_each_version Start  
2022-07-04 02:07:17 [info] אלמנטור/Upgrades - _on_each_version Finished 
2022-07-04 02:07:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-04 02:07:18 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-28 02:11:30 [info] elementor::elementor_updater Started 
2022-07-28 02:11:30 [info] אלמנטור/Upgrades - _on_each_version Start  
2022-07-28 02:11:30 [info] אלמנטור/Upgrades - _on_each_version Finished 
2022-07-28 02:11:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-07-28 02:11:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-08-02 06:20:43 [info] elementor-pro::elementor_pro_updater Started 
2022-08-02 06:20:43 [info] אלמנטור פרו/Upgrades - _on_each_version Start  
2022-08-02 06:20:43 [info] אלמנטור פרו/Upgrades - _on_each_version Finished 
2022-08-02 06:20:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-02 06:20:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]

== אלמנטור - Compatibility Tag ==
	
	Elementor Pro: תאימות לא הוגדרה
	JetProductGallery For Elementor: תאימות לא הוגדרה
	JetTabs For Elementor: תאימות לא הוגדרה
	JetWooBuilder For Elementor: תאימות לא הוגדרה

== אלמנטור פרו - Compatibility Tag ==

**Comment by studiotopo** [comment]
Please fix it.
Thank you

**Comment by shilo-ey** [comment]
Hey friends, thank you for reporting.

This issue has been resolved in Elementor v3.7.2

Feel free to update

Thanks!

**Comment by dipesh-01** [comment]
This issue is still not resolved, try to add the DIVIDER widget in a nested container, and it will grow and take the remaining space.

Tested on Elementor v3.7.3 & Elementor Pro v3.7.4
