### ISSUE TITLE
🐞 Bug report: Cant Save after pasting style to a button

### ISSUE THREAD

**Issue by masterhinz** [elementor/elementor#19392]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When i copy a button and paste the style to another button i cant save anymore. I click on save, but it does not save. 

### Steps to reproduce

When i copy a button and paste the style to another button i cant save anymore. I click on save, but it does not save. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: (Ubuntu) v5.7.37
	PHP Version: 7.4.30
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://pmr.bio
	Home URL: https://pmr.bio
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 256M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: Europe/Berlin
	Admin Email: marc@pinmy.reviews
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 3.8.1
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.167 Safari/537.36

== Active Plugins ==
	BetterLinks
		Version: 1.4.1
		Author: WPDeveloper

	BetterLinks Pro
		Version: 1.2.5
		Author: WPDeveloper

	Elementor
		Version: 3.7.0
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.1.9
		Author: WPDeveloper

	Essential Addons for Elementor - Pro
		Version: 5.1.5
		Author: WPDeveloper

	Essential Blocks
		Version: 3.5.2
		Author: WPDeveloper

	Fluent Forms
		Version: 4.3.9
		Author: Contact Form - WPManageNinja LLC

	Formidable Forms
		Version: 5.4.3
		Author: Strategy11

	Formidable Forms Pro
		Version: 5.4.2
		Author: Strategy11

	Matomo Analytics - Ethical Stats. Powerful Insights.
		Version: 4.11.0
		Author: Matomo

	Newsletter, SMTP, Email marketing and Subscribe forms by Sendinblue
		Version: 3.1.47
		Author: Sendinblue

	OTGS Installer
		Version: 3.0.3
		Author: OnTheGoSystems

	Templately
		Version: 1.3.6
		Author: Templately

	WPML Media
		Version: 2.7.0
		Author: OnTheGoSystems

	WPML Multilingual CMS
		Version: 4.5.8
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.2.1
		Author: OnTheGoSystems

== Elements Usage ==
	
	page : 3
		button : 16
		eael-adv-accordion : 1
		eael-info-box : 3
		eael-testimonial-slider : 1
		heading : 9
		image : 15
		text-editor : 7
	wp-page : 48
		button : 177
		eael-adv-accordion : 1
		eael-dual-color-header : 1
		eael-feature-list : 3
		eael-info-box : 3
		eael-testimonial-slider : 1
		heading : 11
		image : 36
		menu-anchor : 2
		spacer : 1
		text-editor : 36
		video : 2

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	
Log: showing 20 of 342022-04-27 19:39:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-06-09 23:55:11 [info] elementor::elementor_updater Started 
2022-06-09 23:55:11 [info] Elementor/Upgrades - _on_each_version Start  
2022-06-09 23:55:11 [info] Elementor/Upgrades - _on_each_version Finished 
2022-06-09 23:55:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-07-03 21:09:05 [info] elementor::elementor_updater Started 
2022-07-03 21:09:05 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-03 21:09:05 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-03 21:09:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-03 21:09:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-27 21:19:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-07-27 21:19:27 [info] elementor::elementor_updater Started 
2022-07-27 21:19:27 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-27 21:19:28 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-27 21:19:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-07-27 21:19:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-08-08 22:19:51 [info] elementor::elementor_updater Started 
2022-08-08 22:19:51 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-08 22:19:51 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-08 22:19:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]

JS: showing 4 of 4JS: 2022-04-22 12:16:25 [error X 9][https://pmr.bio/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.4:2:515479] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-05-09 12:43:14 [error X 51691][https://pmr.bio/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16820] Cannot read properties of null (reading \'clone\') 
JS: 2022-05-09 12:43:15 [error X 1329][https://pmr.bio/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:21012] Cannot read properties of null (reading \'changestop\') 
JS: 2022-08-08 20:15:41 [error X 12][https://pmr.bio/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.7.0:2:18515] Cannot delete property \'logic_type\' of # 

PHP: showing 1 of 1PHP: 2022-07-26 22:33:40 [notice X 10][/www/htdocs/w00d6f77/pmr.bio/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Essential Addons for Elementor: Incompatible
	Essential Addons for Elementor - Pro: Incompatible

**Comment by elmalak** [comment]
I can confirm having the same bug since I updated Elementor last night to version 3.7.0
I don't have Essential Addons for Elementor installed and yet I have the same issue.
I'm however, using Ultimate addons for Elementor.

**Comment by jimdmeyer21** [comment]
Same issue, cannot past a style even on text...

**Comment by imandings** [comment]
I discussed this with Elementor Support, and the verdict was that this seems to be an issue with Elementor Essentials Addons or Ultimate Addons for Elementor. When just Elementor and Elementor Pro are enabled, this works correctly.

**Comment by RonR-WebDesign** [comment]
I reverted to Elementor 3.6 and that also fixed
        it.
    
    
    On 08/09/22 9:36 PM, Andy wrote:
    
    
      
      I discussed this with Elementor Support, and the
        verdict was that this seems to be an issue with Elementor
        Essentials Addons or Ultimate Addons for Elementor. When just
        Elementor and Elementor Pro are enabled, this works correctly.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you are subscribed to this
        thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/elementor/elementor/issues/19392#issuecomment-1210150355",
"url": "https://github.com/elementor/elementor/issues/19392#issuecomment-1210150355",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by 79ho3ein** [comment]
Friends, this is not a problem of elementor. In fact, it is an incompatibility with a third-party plugin that has a display condition feature.
For example, I also experienced this problem. Finally, I found out that this bug occurs when the display condition feature is enabled in the elementor extras plugin. Therefore, this is a problem that needs to be addressed by the developers of the plugin that provides the display condition feature.
A similar example : #19420

**Comment by RonR-WebDesign** [comment]
I removed versions 3.7 and went back to 3.6 and
        the problem went away.
    What is "display condition feature"?   Can you be
        more specific?
      
    
      
    On 08/11/22 5:44 AM, HOSEIN wrote:
    
    
      
      Friends, this is not a problem of elementor. In
        fact, it is an incompatibility with a third-party plugin that
        has a display condition feature.
        For example, I also experienced this problem. Finally, I found
        out that this bug occurs when the display condition feature is
        enabled in the elementor extras plugin. Therefore, this is a
        problem that needs to be addressed by the developers of the
        plugin that provides the display condition feature.
        A similar example : #19420
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you are subscribed to this
        thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/elementor/elementor/issues/19392#issuecomment-1211939115",
"url": "https://github.com/elementor/elementor/issues/19392#issuecomment-1211939115",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by 79ho3ein** [comment]
@RonR-WebDesign 
Some plugins like elementor extras, power pack, ultimate, element pack and several others provide this feature.
like this : https://ultimateelementor.com/docs/display-conditions/

**Comment by jimdmeyer21** [comment]
I  don’t run either of those plugins and have the problem.

**Comment by MaxBoyman** [comment]
I have done all of top workarounds without a single luck.

**Comment by shilo-ey** [comment]
Thank you for raising this issue.

It is indeed caused due to a conflict with 3rd party plugins.

We recommend you to contact their support and update them about this bug.

Thanks.

**Comment by masterhinz** [comment]
Which plugin is it? 
Jimdmeyer21 commented that he doesnt use any of those plugins and does have the Bug too? 
Im not a developer... If Elementor tell me, which Plugin is responsible for that issue, im able to raise an issue... but without any help, it will be dificult for me

**Comment by elmalak** [comment]
Hello,
The issue has been fixed after updating to Elementor 3.7.1

Thank you.

**Comment by MaxBoyman** [comment]
I double checked, and problem still exsists even after updating to elementor 3.7.1
i tried to downgrade to 3.6.8 and checked in various scenarios, in some cases problem fixed and in some cases problem is still there.
so i don't know how you closed the issue while it still isn't fixed. although it's a problem with thirdparty plugins but those plugins aren't cause a problem for themselves but they are affecting elementor functionality. And as a programmer i know that there is a way to make some exceptions in code that can fix this problem even when elementor conflicts with other plugins.

**Comment by Brink67** [comment]
I am using Essential Addons for Elementor - Pro (and required to be installed along side the free 5.2.3) and had this issue so this is one of the plugins that cause the issue. I verified that disabling the conditional display functionality through the plugin's settings panel made the problem go away. 

I already reached out to WPdeveloper (the creator of Essentials Addons) letting them know of the bug and of this thread. They are pretty good folks and will likely release a fix pretty soon.

**Comment by MaxBoyman** [comment]
I opened an issue on essential addon for elementor on github and they told that they are releasing a new update which is now in dev channel soon which will fix the problem. On the other hand i have ultimate addon elementor plugin too. It has the same problem but i couldn't contact the to report the issue. Is anybody sent them a report about this problem? Cause they don't have a github public repo and their ticketing system is confusing

**Comment by jim28100** [comment]
I am experiencing the same issue with The Plus Addons plugin too.

**Comment by omgrech** [comment]
I have the same issue with Premium Addons for Elementor

**Comment by Brink67** [comment]
Crocoblock's JetEngine has a feature call Dynamic Visibility and it seems to work just fine.  So if you are inconvenienced by having to turn that off in your favorite plugin or else not use "paste style" JetEngine is an alternative that you can use.

**Comment by elmalak** [comment]
It seems Ultimate add-ons have just released an update with a fix for the above issue.
https://ultimateelementor.com/changelog/?utm_source=graupi-updater&utm_medium=changelog-link&utm_campaign=graupi-changelog

I updated and everything seems to be working fine for me.
Give it a try!

**Comment by webster-mcwebby** [comment]
For me, it is caused by Element Pack Pro. I did not find a fix. I alerted the developer but have simply deactivated it for now as we weren't really using it.

**Comment by eminozturk58** [comment]
> For me, it is caused by Element Pack Pro. I did not find a fix. I alerted the developer but have simply deactivated it for now as we weren't really using it.

We have been experiencing the same problem for the last 2-3 weeks.

**Comment by kippoulet** [comment]
We also experience this effect with this setup:
- Elementor Pro 
- Power Pack
- Elements Kit Pro
- The Plus Addons

The "solution" was as suggested above:
- disabling "Display Conditions" in Power Pack -> Extensions
- disabling "Conditional Content" in Elements Kit -> Modules
Both items have to be deactivated, otherwise the "fix" won´t work.

**Comment by jcalvopatino** [comment]
Same problem caused by The Plus Addons for Elementor. The helpdesk solved my problem with the following instructions:

_Disable the feature "Display Condition" from your admin panel The Plus Settings >> Widgets_

This solved the problem for me

**Comment by atlantsecurity** [comment]
I see the replies by Elementors staff here absolutely outrageous. You add one stupid feature on your plugin, it breaks thousands of sites, because hundreds of plugins fight with this feature - and YOU DEMAND ALL PLUGIN AUTHORS TO FIX THEIR PLUGINS????

**Comment by oliverf72** [comment]
I can confirm that it is an error related to the Display Condition function. We are using ThePlusAddons.
If I disable the function there, copy+paste style works again.

**Comment by eatplaygo** [comment]
I too have a problem with paste style and I use a bunch of plugins. The ideas of disabling plugins is not an option for me as all of them are essential in one way or another.  I agree with the post before that to expect all authors to fix their plugins because of one thing Elementor did to break them all is silly. 

All that does is make me wary of recommending Elementor to anyone. Maybe they are comfortable with their user base and can afford to turn their backs on us. It's a terrible posture for any company to have let alone one as popular as this one.

**Comment by KCGLtd** [comment]
Same issue here, have to keep reverting to a previous version to get any work done. Copy and pasting the style of anything causes you to not be able to save or do anything, so any work done and not saved is lost.  So frustrating and losing so much time redoing stuff or painstakingly styling each element one at a time. The copy and paste style functionality is a major reason we love building with Elementor. If it worked with the previous versions with the same supporting Elementor plugins it seems clear something with Elementor itself has changed which is causing the issue. Can this please be looked into?

**Comment by evankford** [comment]
Same issue here for me. Copying an element, then pasting style works at the moment, but when you go to save, it fails. 

On checking the console, it errors out first with `Cannot delete property 'ep_condition_key' of #<Object>`. Then there's no data to save, so the save function fails.

**Comment by felipepitol** [comment]
It's an error related to the Display Condition. I'm using Happy Addons Pro.
I tried to disable the display condition module and the problem was fixed.

**Comment by Brink67** [comment]
This is still going on? Some folks need to let support for their favorite plugin know that this is an issue. Don't post it here. Post it in support or forum for the plugin that you are using that causes it. There seem to be several.

**Comment by jhgeluk** [comment]
I'm also having this issue!

**Comment by eatplaygo** [comment]
This was now fixed for me in the latest Elementor Update. - Version 3.8.0

**Comment by alexemstudio** [comment]
I'm running 3.8.0 and still not fixed for me. 

As of now my install is up to date on everything and has :
Dynamic.oo
ElementsKit Lite
Premium Addons for Elementor
Ultimate Addons for Elementor

I'll do a major clean up and verify which one is the culprit but damn...

**Comment by diquispe** [comment]
Same issue with powerpapck for elementor

CONSOLE.
Document already in save progress

Disabled and deleted this plugin with updated elementor and elementor pro

**Comment by felipepitol** [comment]
> Same issue with powerpapck for elementor
> 
> CONSOLE. Document already in save progress
> 
> Disabled and deleted this plugin with updated elementor and elementor pro

If you are not using display conditions module from power pack - just disable it.

**Comment by murgatroydj** [comment]
Disables UEA display conditions and i seem to have resolved the issue as well

**Comment by jgarcianewemage** [comment]
Can confirm, the "display conditions" of several plugins are causing this issue

**Comment by guadster-git** [comment]
> Disables UEA display conditions and i seem to have resolved the issue as well

How do you disable them?

**Comment by Brink67** [comment]
It depends on the plugin. It is one of the addons for elementor. Most have a configuration menu that allow you to disable the conditional display feature of that plugin.

**Comment by guadster-git** [comment]
yeah, i am talking specificly about the UEA plugin. That doesnt seem to have a config menu.

**Comment by JustinM2M** [comment]
> yeah, i am talking specificly about the UEA plugin. That doesnt seem to have a config menu.

Wordpress Settings > UAE
Scroll to the bottom and disable the Display Conditions extension.

![Display-Conditions](https://user-images.githubusercontent.com/51822097/202199790-7e68d475-a6db-4432-ba80-f8b5ecd63b75.png)

Fixed it for me too!

**Comment by marvin0o** [comment]
Hello still not fixed?? Still can't copy paste styles. This is hurting my workflow.

**Comment by melzor** [comment]
Yep, same issue. Thank god someone pointed me to this thread. I'm using Powerpack Elementor add-ons and this is what was causing the bug. I disabled Display Conditions and I don't have this issue anymore.

**Comment by AdherenceDigital** [comment]
Same here with Ultimate Addons. Disabling Display Conditions isn't a solution as that was one of the reason I got the plugin. Sort it out Elementor!

**Comment by DaNTaF** [comment]
Same for me, after 3.8 update

**Comment by deepakagupta** [comment]
Same issue

**Comment by pinkgerbils** [comment]
> Same here with Ultimate Addons. Disabling Display Conditions isn't a solution as that was one of the reason I got the plugin. Sort it out Elementor!

You're on the wrong forum; that is an issue for Ultimate Addons.

**Comment by AdherenceDigital** [comment]
That's really helpful thanks. I hadn't thought of contacting the developers of the plugin that has the issue. I suppose everyone else here with different plugins hasn't done that either. Such a simple fix!

**Comment by pinkgerbils** [comment]
> 

Most people above have confirmed it's caused by 2 third party plugins. Either **Essential Add-ons** or **Power Pack** - they both have a similar feature and this causes a conflict. It is 100% those plugins fault and their developers responsibility to fix.

We are using Essential Addons but I refuse to upgrade so we have to disable the plugin each time we wish to do this.

**Comment by redifmail** [comment]
I am experiencing the same issue with all of my sites that use Elementor and UAE. For me, disabling 'Display Conditions' in UAE settings fixed the issue. I believe that the Elementor team will have to investigate this issue and fix any compatibility issues with other plugin features.

**Comment by AdherenceDigital** [comment]
An update from the UAE team:
 The important bit: "**The Elementor team is looking into this issue and hopefully should provide a patch for this as soon as possible**."
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/13330225/207025157-53f9af83-d481-41d4-b3c1-3839dcf87b2d.png">

**Comment by jgarcianewemage** [comment]
think elementor WONT fix it as they are going to implement their own view-condition functionality

**Comment by DaNTaF** [comment]
I have talked with Elementor's support team.
They told me that it was not Elementor's bug, and they advised me to talk with the developers of the 3rd party plugins.
Or don't use these plugins.
