### ISSUE TITLE
🐞 Bug report: Custom CSS output for Number control doesn't output if value is 0

### ISSUE THREAD

**Issue by qantumthemes** [elementor/elementor#19391]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Elementor 3.7.0 the control doesn't produce any output if the value is set to 0.
When the value is > 0 it works fine.
Was not happening in previous version of Elementor.

Code to reproduce

```
$section->add_control(
			'my-items-padding',
			[
				'label' => esc_html__( 'Padding', 'proradio-elementor' ),
				'type' => \Elementor\Controls_Manager::NUMBER,
				'min' => 0,
				'max' => 40,
				'step' => 1,
				'default' => 15,
				'selectors' => [
					'{{WRAPPER}} .my-owl-carousel-container ' => 'margin: -{{SIZE}}px !important;',
					'{{WRAPPER}} .owl-item ' => 'padding: {{SIZE}}px;',
				],
			]
		);
```

### Steps to reproduce

1. Create a new elementor widget
2. Add a control using the Number control
3. There is no CSS output if the value is set to 0
4. In backend editor it works fine, there is always CSS output
5. Save and check frontend > no output for that element if value is 0

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Darwin
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 8.0.0
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: http://proradio2.local
	Home URL: http://proradio2.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: Europe/Madrid
	Admin Email: dev-email@flywheel.local
	Debug Mode: Active

== Theme ==
	Name: ProRadio Child
	Version: 1.0.0
	Author: Pro.Radio
	Child Theme: Yes
	Parent Theme Name: ProRadio
	Parent Theme Version: 2.4.0
	Parent Theme Author: Pro.Radio - Qantum Themes SL

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

== Active Plugins ==
	Blubrry PowerPress
		Version: 9.1.2
		Author: Blubrry

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Classic Widgets
		Version: 0.3
		Author: WordPress Contributors

	Contact Form 7
		Version: 5.5.6.1
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.7.0
		Author: Elementor.com

	Icons2go
		Version: 2.0.0
		Author: Themes2Go

	One Click Demo Import
		Version: 3.1.1
		Author: OCDI

	Pro.Radio Ajax
		Version: PR.3.8.1
		Author: Pro.Radio

	Pro.Radio Business Tools
		Version: 1.1.0
		Author: Qantum Themes SL

	Pro.Radio Chartvote
		Version: PR.3.0.3
		Author: Pro.Radio

	Pro.Radio Core
		Version: PR.6.0.0
		Author: Pro.Radio

	Pro.Radio Elementor Widgets
		Version: PR.2.3.8
		Author: Pro.Radio - Qantum Themes SL

	Pro.Radio Music Player
		Version: PR.4.0.1
		Author: Pro.Radio - Qantum Themes SL

	Pro.Radio Places
		Version: PR.4.0.3
		Author: Pro.Radio

	Pro.Radio ReAktions
		Version: PR.4.3
		Author: Pro.Radio

	Pro.Radio Server Check
		Version: PR.2.1
		Author: QantumThemes

	Pro.Radio Taxonomy Background
		Version: PR.1.0.1
		Author: Pro.Radio

	Pro.Radio Video Galleries
		Version: PR.2.7
		Author: Pro.Radio

	Pro.Radio Widgets
		Version: PR.1.0.6
		Author: Pro.Radio

	ProRadio Swipebox Photo And Video
		Version: PR.5.8.3
		Author: QantumThemes

	WP Post Page Clone
		Version: 1.2
		Author: Gaurang Sondagar

== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility Improvements: Inactive
	Additional Custom Breakpoints: Inactive
	Import Export Template Kit: Inactive
	Hide native WordPress widgets from search results: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive
	Landing Pages: Inactive
	Color Sampler: Inactive
	Favorite Widgets: Inactive
	Admin Top Bar: Inactive

== Log ==
	
Log: showing 20 of 382022-04-15 11:44:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.4',
)]
2022-04-15 11:44:58 [info] elementor::elementor_updater Started 
2022-04-15 11:44:58 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-15 11:44:58 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-15 11:44:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.4',
)]
2022-04-28 11:20:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-28 11:20:58 [info] elementor::elementor_updater Started 
2022-04-28 11:20:58 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-28 11:20:58 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-28 11:20:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-06-14 15:37:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-06-14 15:37:13 [info] elementor::elementor_updater Started 
2022-06-14 15:37:13 [info] Elementor/Upgrades - _on_each_version Start  
2022-06-14 15:37:13 [info] Elementor/Upgrades - _on_each_version Finished 
2022-06-14 15:37:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-08-08 18:37:54 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.7.0',
)]
2022-08-08 18:37:54 [info] elementor::elementor_updater Started 
2022-08-08 18:37:54 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-08 18:37:54 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-08 18:37:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.7.0',
)]

JS: showing 2 of 2JS: 2022-04-15 16:19:43 [error X 2][http://proradio2.local/wp-content/plugins/proradio-business-tools/assets/js/proradio-business-tools.js?ver=0.0.1:45:26] Cannot read properties of undefined (reading \'length\') 
JS: 2022-05-25 07:39:11 [error X 2][http://proradio2.local/wp-content/plugins/proradio-business-tools/assets/js/proradio-business-tools-min.js?ver=1.0.6:1:530] Cannot read properties of undefined (reading \'bannersArray\') 

PHP: showing 3 of 3PHP: 2022-05-05 15:45:18 [warning X 1][/Users/igornardo/Desktop/Dropbox/My Mac (Igor’s MacBook Pro)/Documents/0. LAVORO/7. PRO.RADIO/2. PROJECTS/03. PRORADIO WP/5. DEV/app/public/wp-content/plugins/elementor/includes/frontend.php::281] array_merge(): Expected parameter 1 to be an array, string given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-05 15:45:22 [warning X 2][/Users/igornardo/Desktop/Dropbox/My Mac (Igor’s MacBook Pro)/Documents/0. LAVORO/7. PRO.RADIO/2. PROJECTS/03. PRORADIO WP/5. DEV/app/public/wp-content/plugins/elementor/includes/frontend.php::281] array_merge(): Expected parameter 1 to be an array, bool given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-18 17:37:53 [warning X 1][/Users/igornardo/Desktop/Dropbox/My Mac (Igor’s MacBook Pro)/Documents/0. LAVORO/7. PRO.RADIO/2. PROJECTS/03. PRORADIO WP/5. DEV/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /Users/igornardo/Desktop/Dropbox/My Mac (Igor’s MacBook Pro)/Documents/0. LAVORO/7. PRO.RADIO/2. PROJECTS/03. PRORADIO WP/5. DEV/app/public/wp-content/plugins/proradio-elementor/widgets/_helpers/get-terms-array.php:9) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Pro.Radio Elementor Widgets: Compatibility not specified

**Comment by khag7** [comment]
Issue #19386 also relates to number fields and that issue only started happening with the new version. I wonder what changed with number fields that broke two things.

**Comment by BSG-75** [comment]
I am having a similar issue across all of my sites that upgraded to Elementor 3.7.0. The issue I am experiencing is the widget spacing under column settings is getting ignored if it's set to "0". If you set it to any other number like "1" the column reflects the changes. In the editor everything looks fine, but on the front end the default 20px of bottom margin is being applied:

This is what Elementor 3.7.0 is applying to the column spacing if the value is "0":

`.elementor-widget:not(:last-child) {
    margin-bottom: 20px;
}`

Rolling back to Elementor 3.6.8 removes the issue.

**Comment by perks98** [comment]
Even with in-built Elementor controls like the z-index doesn't respond to an input of '0' since 3.7. A bigger problem than expected.


<details>
<summary>
<b>Quick video of my problem: </b>
</summary>

https://user-images.githubusercontent.com/55829113/183618569-446642dc-bb1f-45d8-9b62-c7cf52cf56e6.mp4

</details>

**Comment by mbaierl** [comment]
Issue #19393 is also related.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.7.1

Feel free to update

Thanks!

**Comment by NAROLLES** [comment]
The same problem is not solved by the latest version for those who use the flex container

**Comment by mbaierl** [comment]
The issue is not yet solved for Flexbox Containers. Still 10px padding.

**Comment by perks98** [comment]
z-index works for me in the latest update.

@mbaierl I can't seem to replicate the padding issue when set to 0px. Do you have any steps to replicate? Since 3.7 the default padding for containers is 10px and can be changed in the site settings under the layout tab.
<details>
<summary>Unsucessful video of trying to replicate padding issue in 3.7.1</summary>

https://user-images.githubusercontent.com/55829113/184861154-f3c47554-974f-4016-a416-8482127d0897.mp4


</details>

**Comment by NAROLLES** [comment]
Hello - Maybe it was necessary to inform the community of this new function (global padding configuration - layout tab) - it would have avoided many inconveniences
Thanks

**Comment by perks98** [comment]
Hi @NAROLLES,
That is true, maybe they should have made a better note in the 3.7 [changelog](https://en-gb.wordpress.org/plugins/elementor/#developers), as it only mentioned:

> Tweak: Added default padding values to Container Element
> Tweak: Added site-wide containers padding option to Site Settings

Maybe in the tweak message they could have mentioned the exact change from the default of 0px to 10px. I believe this change was done as the default padding for columns currently is 10px and nesting containers become easier to manage rather than overlap.

**Comment by mbaierl** [comment]
> @mbaierl I can't seem to replicate the padding issue when set to 0px. Do you have any steps to replicate? Since 3.7 the default padding for containers is 10px and can be changed in the site settings under the layout tab.
I was not aware of this new feature, thanks for bringing it to my attention. Works like a charm now.
