### ISSUE TITLE
🐞 Bug report: Experiment - Inline Font Icons - Form

### ISSUE THREAD

**Issue by hitsgee** [elementor/elementor#19495]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When using the experiment Inline Font Icons with a Form that uses a select field, the "chevron" icon is broken.
It displays correctly when editing in the backend but not on the frontend.

Screenshot:
![Contact-HITS-A-Creative-Design-Studio-Based-In-Andover-Hampshire](https://user-images.githubusercontent.com/40209785/184815635-95107aa5-d777-4d9e-9886-02a737d2cd45.png)

### Steps to reproduce

Create a form that uses a select field and has multiple options configured.
Enable the inline font icon experiment 
View in backend - should display the chevron in the field like normal
View in frontend - the chevron icon in the field should be broken

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Latest Elementors & WordPress

**Comment by shilo-ey** [comment]
Hey @hitsgee 

This issue has been resolved and will be released in Elementor Pro v3.7.4

I merged this issue with #18598, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by javacious** [comment]
I can say this has *not* been resolved as of Elementor Pro v3.7.7. (or maybe the bug was reintroduced)

I too had to disable the inline font experiment to keep the black boxes showing up behind the dropdown arrows.

**Comment by efintina** [comment]
This issue is still active in Elementor Pro v3.16.2

**Comment by growth-wizard-digital** [comment]
This issue is still a problem in Elementor Pro 3.18.1 - specifically on the caret icon on forms.
