### ISSUE TITLE
🐞 Bug report: Custom background position not inherited on tablet and mobile in Flipbox back

### ISSUE THREAD

**Issue by jamieburchell** [elementor/elementor#19527]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I set a custom background position for the background of the back of a Flipbox, tablet and mobile views do not inherit the position. It works in Elementor, but not on the front end. I confirmed that tablet and mobile background position was set to "default".

Not sure if the X and Y custom co-odinates fields are supposed to shown for tablet and mobile, but the values are not being inherited from the desktop setting in any case.

### Steps to reproduce

Set a custom background position on desktop, set tablet and mobile to default. Front end shows background position top, left and not what was set.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.5.16
	PHP Version: 8.0.22
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 50M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://example.com/wp
	Home URL: https://example.com
	WP Multisite: No
	Max Upload Size: 40 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-GB
	Timezone: 0
	Admin Email: me@example.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

== Active Plugins ==
	Code Snippets
		Version: 3.2.0
		Author: Code Snippets Pro

	Dynamic.ooo - Dynamic Content for Elementor
		Version: 2.7.4
		Author: Dynamic.ooo

	Elementor
		Version: 3.7.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.3
		Author: Elementor.com

	Pods - Custom Content Types and Fields
		Version: 2.9.2
		Author: Pods Framework Team

	Yoast SEO
		Version: 19.5.1
		Author: Team Yoast


== Must-Use Plugins ==
	Bedrock Autoloader
		Version: 1.0.3
		Author: Roots

	Disable status tests
		Version: 1.0.0
		Author: Roots

	Register Theme Directory
		Version: 1.0.0
		Author: Roots


== Elementor Experiments ==
	Optimised DOM Output: Inactive by default
	Improved asset loading: Inactive by default
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility improvements: Inactive by default
	Additional Custom Breakpoints: Inactive by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Landing pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default


== Log ==
	
JS: showing 20 of 25JS: 2022-08-05 09:46:35 [error X 1][https://example.com/app/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view1666\") has already been destroyed and cannot be used. 
JS: 2022-08-05 10:09:22 [error X 1][https://example.com/app/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view1706\") has already been destroyed and cannot be used. 
JS: 2022-08-05 11:31:26 [error X 1][https://example.com/app/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view458\") has already been destroyed and cannot be used. 
JS: 2022-08-05 11:31:30 [error X 1][https://example.com/app/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view2638\") has already been destroyed and cannot be used. 
JS: 2022-08-09 09:37:16 [error X 1][https://example.com/app/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view1673\") has already been destroyed and cannot be used. 
JS: 2022-08-09 09:37:16 [error X 4][https://example.com/app/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.6.8:2:4766] Cannot read properties of undefined (reading \'attributes\') 
JS: 2022-08-09 09:38:37 [error X 1][https://example.com/app/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view2050\") has already been destroyed and cannot be used. 
JS: 2022-08-09 09:59:48 [error X 2][https://example.com/app/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view135\") has already been destroyed and cannot be used. 
JS: 2022-08-09 10:16:09 [error X 1][https://example.com/app/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view56376\") has already been destroyed and cannot be used. 
JS: 2022-08-09 10:16:09 [error X 1][https://example.com/app/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view56371\") has already been destroyed and cannot be used. 
JS: 2022-08-09 10:18:41 [error X 1][https://example.com/app/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view198\") has already been destroyed and cannot be used. 
JS: 2022-08-09 10:18:46 [error X 1][https://example.com/app/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view2254\") has already been destroyed and cannot be used. 
JS: 2022-08-09 13:26:06 [error X 2][https://example.com/app/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view212\") has already been destroyed and cannot be used. 
JS: 2022-08-09 13:27:35 [error X 1][https://example.com/app/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view1685\") has already been destroyed and cannot be used. 
JS: 2022-08-09 13:27:54 [error X 1][https://example.com/app/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view8434\") has already been destroyed and cannot be used. 
JS: 2022-08-09 13:37:25 [error X 7][https://example.com/app/plugins/elementor/assets/js/editor.min.js?ver=3.6.8:3:900529] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-08-10 23:28:08 [error X 1][https://example.com/wp/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:13633] Syntax error, unrecognized expression: #elementor-control-left: auto; right: 0;-c19854 
JS: 2022-08-10 23:34:08 [error X 1][https://example.com/wp/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:13633] Syntax error, unrecognized expression: #elementor-control-left: 0%;-c1799 
JS: 2022-08-10 23:34:35 [error X 1][https://example.com/wp/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:13633] Syntax error, unrecognized expression: #elementor-control-left: auto; right: 0;-c1799 
JS: 2022-08-15 13:22:59 [error X 11][https://example.com/app/plugins/elementor/assets/js/common-modules.min.js?ver=3.7.0:2:51471] Model.isValidChild() should be implemented, please provide \'isValidChild\' functionality. 

PHP: showing 5 of 5PHP: 2022-08-09 13:25:45 [notice X 4][/var/www/vhosts/mobeus.co.uk/releases/3/web/app/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-10 23:24:56 [warning X 108][/var/www/vhosts/mobeus.co.uk/releases/2/web/app/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-15 11:59:28 [warning X 61][/var/www/vhosts/mobeus.co.uk/releases/3/web/app/plugins/elementor-pro/modules/dynamic-tags/pods/tags/pods-text.php::20] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-15 15:21:52 [error X 2][/var/www/vhosts/mobeus.co.uk/releases/3/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on null in /var/www/vhosts/mobeus.co.uk/releases/3/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /var/www/vhosts/mobeus.co.uk/releases/3/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(5, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/vhosts/mobeus.co.uk/releases/3/web/app/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /var/www/vhosts/mobeus.co.uk/releases/3/web/wp/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /var/www/vhosts/mobeus.co.uk/releases/3/web/wp/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#5 /var/www/vhosts/mobeus.co.uk/releases/3/web/wp/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#6 /var/www/vhosts/mobeus.co.uk/releases/3/web/wp/wp-admin/admin-ajax.php(187): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-17 14:54:14 [error X 2][/var/www/vhosts/mobeus.co.uk/releases/4/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on null in /var/www/vhosts/mobeus.co.uk/releases/4/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /var/www/vhosts/mobeus.co.uk/releases/4/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(5, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/vhosts/mobeus.co.uk/releases/4/web/app/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /var/www/vhosts/mobeus.co.uk/releases/4/web/wp/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /var/www/vhosts/mobeus.co.uk/releases/4/web/wp/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#5 /var/www/vhosts/mobeus.co.uk/releases/4/web/wp/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#6 /var/www/vhosts/mobeus.co.uk/releases/4/web/wp/wp-admin/admin-ajax.php(187): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 12 of 122022-08-10 22:58:08 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]
2022-08-10 23:04:02 [info] elementor::elementor_updater Started 
2022-08-10 23:04:02 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-10 23:04:02 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-10 23:04:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]
2022-08-10 23:19:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '2.7.2',
  'to' => '2.7.4',
)]
2022-08-17 14:51:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-08-17 14:52:12 [info] Update DB has been started [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-08-17 14:52:12 [info] elementor::elementor_updater Started 
2022-08-17 14:52:12 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-17 14:52:12 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-17 14:52:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]



== Elementor - Compatibility Tag ==
	
	Dynamic.ooo - Dynamic Content for Elementor: Compatibility not specified
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
```

**Comment by portrayaloflife** [comment]
Seeing this behavior in sections as well

**Comment by marian-kadanka** [comment]
Same problem here. It is happening on columns too.

We have image background overlay set on column. Image is custom positioned to some X and Y values - only for the desktop resolution. It has not position set for mobile resolution, so it has to behave like desktop if in mobile view. This is correctly happening when inside the editor.

But on the frontend side, while in mobile view, the image background, which is provided by DIV.elementor-background-overlay, suddenly gets "background-position: 0 0" CSS rule, which is not correct behaviour - because we didn't set it to 0, 0 for mobile.

This bug has been introduced between Elementor version 3.5.6 and 3.6.0. It has been partially fixed in 3.7.0 so the background image is displayed correctly inside the editor - but it's still buggy on the frontend display.

![desktop-editor-correct](https://user-images.githubusercontent.com/17478306/187430561-266ac634-9766-4d0a-be83-c30cf734b37d.png)
![mobile-editor-correct](https://user-images.githubusercontent.com/17478306/187430566-031d3b30-6ea3-4b0e-bbd7-0480570f25df.png)
![mobile-frontend-buggy](https://user-images.githubusercontent.com/17478306/187430568-f735be37-8114-40dd-81d3-710b155f092b.png)

**Comment by marian-kadanka** [comment]
Looks like it has been fixed in version 3.7.5.

**Comment by jamieburchell** [comment]
Nope. This is still not working properly in 3.7.6. The controls are shown now, but the values change to zero!

https://watch.screencastify.com/v/7JJQmkVXB9uWEEXpmijf

**Comment by avivu** [comment]
This issue has been resolved in Elementor v3.7.7

Feel free to update

Thanks!

**Comment by chasperlisimba** [comment]
@arielk This Bug should be solved in 3.7.7 but it's not working! In the editor it looks fine. But on the front-end the css is not applied and nothing is working what you edited in the backend.

**Comment by littlesantashelper** [comment]
Still have the bug in 3.7.7. All backgrounds are messed up. The bug is not solved.

**Comment by arielk** [comment]
@chasperlisimba @littlesantashelper Please try to regenerate CSS (under Elementor > Tools) and let me know if it works for you

**Comment by chasperlisimba** [comment]
@arielk No it's still not working.

**Comment by rally-lad** [comment]
Same issue here across multiple sites upgraded to Elementor 3.7.7 and Elementor PRO 3.7.7

Cache Disabled, tried re-building the CSS and tried incognito.

Currently rolled back to previous Elementor Version 3.7.3 (Pro is still at 3.7.7).

**Comment by artkrsk** [comment]
Since 3.7.7 Elementor update I'm getting this fatal error related to the responsive controls:
```
) Fatal error: Uncaught TypeError: Argument 1 passed to Elementor\Core\Files\CSS\Base::get_style_control_value() must be of the type array, null given, called in /Users/art/Local Sites/dev/app/public/wp-content/plugins/elementor/core/files/css/base.php on line 682 and defined in /Users/art/Local Sites/dev/app/public/wp-content/plugins/elementor/core/files/css/base.php on line 738
( ! ) TypeError: Argument 1 passed to Elementor\Core\Files\CSS\Base::get_style_control_value() must be of the type array, null given, called in /Users/art/Local Sites/dev/app/public/wp-content/plugins/elementor/core/files/css/base.php on line 682 in /Users/art/Local Sites/dev/app/public/wp-content/plugins/elementor/core/files/css/base.php on line 738
Call Stack
#	Time	Memory	Function	Location
1	0.0003	368848	{main}( )	.../index.php:0
2	0.0004	369128	require( '/Users/art/Local Sites/dev/app/public/wp-blog-header.php' )	.../index.php:17
3	0.1975	13205496	require_once( '/Users/art/Local Sites/dev/app/public/wp-includes/template-loader.php' )	.../wp-blog-header.php:19
4	0.2586	16084872	include( '/Users/art/Local Sites/dev/app/public/wp-content/themes/rhye/single.php' )	.../template-loader.php:106
5	0.2774	16693368	get_header( )	.../single.php:16
6	0.2774	16693744	locate_template( )	.../general-template.php:48
7	0.2775	16693840	load_template( )	.../template.php:716
8	0.2775	16694384	require_once( '/Users/art/Local Sites/dev/app/public/wp-content/themes/rhye/header.php' )	.../template.php:770
9	0.2785	16704544	wp_head( )	.../header.php:20
10	0.2785	16704544	do_action( )	.../general-template.php:3042
11	0.2785	16704920	WP_Hook->do_action( )	.../plugin.php:476
12	0.2785	16704920	WP_Hook->apply_filters( )	.../class-wp-hook.php:331
13	0.2789	16708344	wp_enqueue_scripts( )	.../class-wp-hook.php:307
14	0.2789	16708344	do_action( )	.../script-loader.php:2156
15	0.2789	16708720	WP_Hook->do_action( )	.../plugin.php:476
16	0.2789	16708720	WP_Hook->apply_filters( )	.../class-wp-hook.php:331
17	0.2850	16808768	Elementor\Frontend->enqueue_styles( )	.../class-wp-hook.php:307
18	0.2862	16918800	Elementor\Core\Files\CSS\Post->enqueue( )	.../frontend.php:639
19	0.2862	16918800	Elementor\Core\Files\CSS\Post->enqueue( )	.../post.php:201
20	0.2863	16919224	Elementor\Core\Files\CSS\Post->update( )	.../base.php:217
21	0.2863	16919224	Elementor\Core\Files\CSS\Post->update_file( )	.../base.php:130
22	0.2863	16919224	Elementor\Core\Files\CSS\Post->parse_content( )	.../base.php:180
23	0.8504	20298848	do_action( )	.../base.php:658
24	0.8504	20299224	WP_Hook->do_action( )	.../plugin.php:476
25	0.8504	20299224	WP_Hook->apply_filters( )	.../class-wp-hook.php:331
26	0.8505	20300352	Elementor\Core\Settings\Page\Manager->add_settings_css_rules( )	.../class-wp-hook.php:307
27	0.8531	20322216	Elementor\Core\Files\CSS\Post->add_controls_stack_style_rules( )	.../css-manager.php:116
28	0.8531	20322216	Elementor\Core\Files\CSS\Post->add_controls_stack_style_rules( )	.../post.php:222
29	0.8535	20323848	Elementor\Core\Files\CSS\Post->add_control_style_rules( )	.../base.php:550
30	0.8535	20324568	Elementor\Core\Files\CSS\Post->add_control_rules( )	.../base.php:681
31	0.8536	20326688	preg_replace_callback ( )	.../base.php:341
32	0.8536	20327320	Elementor\Core\Files\CSS\Post->Elementor\Core\Files\CSS\{closure:/Users/art/Local Sites/dev/app/public/wp-content/plugins/elementor/core/files/css/base.php:341-377}( )	.../base.php:341
33	0.8536	20327320	Elementor\Core\Files\CSS\Post->parse_property_placeholder( )	.../base.php:347
34	0.8536	20327352	call_user_func:{/Users/art/Local Sites/dev/app/public/wp-content/plugins/elementor/core/files/css/base.php:448} ( )	.../base.php:448
35	0.8536	20327352	Elementor\Core\Files\CSS\Post->Elementor\Core\Files\CSS\{closure:/Users/art/Local Sites/dev/app/public/wp-content/plugins/elementor/core/files/css/base.php:681-683}( )	.../base.php:448
36	0.8536	20327352	Elementor\Core\Files\CSS\Post->get_style_control_value( )
```

**Comment by portrayaloflife** [comment]
Still seeing the issue. In the editor the changes are working on smaller devices. But after publishing and viewing live, cleared cache and CSS regenerated, the bg image is still not changing for smaller devices.

**Comment by portrayaloflife** [comment]
Seeing the bug in Section bg images too, not just Flipbox

**Comment by nexgraphics** [comment]
I do not believe this was fixed, I am STILL having the exact same issue

**Comment by nicholaszein** [comment]
Hello, @nexgraphics,

the fix will be released on Elementor v3.8, when it's launched. 😉

**Comment by elosha** [comment]
@nicholaszein Ok … and when is 3.8 coming? Clients getting angry after WEEKS of this bug. And it's getting expensive for us.

Thanks, an Agency License user.

**Comment by rally-lad** [comment]
> @nicholaszein Ok … and when is 3.8 coming? Clients getting angry after WEEKS of this bug. And it's getting expensive for us.
> 
> Thanks, an Agency License user.

It was expected on the 23rd of October but with the issues of latest versions I’ll be holding off as recently it appears that as one problem is fixed it causes another one! 

I love elementor but it has been somewhat buggy of late with mid revisions causing more issues so with a major realise 3.8 looking I’ll wait before updating to see if it breaks anything else that I have to revert. 🤞fingers crossed.

**Comment by nicholaszein** [comment]
@elosha and @rally-lad,

thank you for your responses. The ETA can be seen [here](https://github.com/orgs/elementor/discussions/19854#discussion-4404476) at the end of the post:

![image](https://user-images.githubusercontent.com/113993460/198734465-2b67a8fe-539d-4c89-bff5-4b2a0f46d453.png)

#### October 30, 2022

The release was delayed so we could make sure everything raised during the beta was addressed and resolved in time - **including this issue,** not to mention to make sure the new release is as stable as possible. This is important for us, so we wanted to make sure everything was ok. And the team did a great job! I hope you will like the result.

**Comment by nicholaszein** [comment]
This issue was solved by Elementor 3.8. 🙌
