### ISSUE TITLE
🐞 Bug report: Background image custom position has no X/Y settings for tablet and mobile

### ISSUE THREAD

**Issue by verticalrailgg** [elementor/elementor#19669]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

This happens in a section's **Style** tab, using the **Background** or **Background Overlay** region.

If I set a background image, then set **Position** to _Custom_ on desktop and configure the _X and Y positions_, then when I switch to Tablet or Mobile, I can't change the _X or Y positions_... those settings don't show up even though I can select **Position: Custom** for those screen sizes.

![elementor-custom-positioning-issue](https://user-images.githubusercontent.com/7595435/187762298-5e5b746b-d50a-4e92-807d-56bf91072931.jpg)

### Steps to reproduce

Edit a page in Elementor and add a section. Click on the Style tab, expand the Background section, add a background image, then choose Custom for Position. Set X and Y positions. Now switch to tablet or mobile view. You'll see you won't be able to set a different X and Y position for tablet or mobile.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.39-42
	PHP Version: 7.4.30
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Los_Angeles
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.7.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.5
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Inactive
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 432022-08-21 01:57:08 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]
2022-08-29 14:07:36 [info] elementor::elementor_updater Started 
2022-08-29 14:07:36 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-29 14:07:36 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-29 14:07:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-29 14:07:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-31 12:10:45 [info] elementor::elementor_updater Started 
2022-08-31 12:10:45 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-31 12:10:45 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-31 12:10:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.3',
  'to' => '3.7.4',
)]
2022-08-31 12:10:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.3',
  'to' => '3.7.4',
)]
2022-08-31 12:10:49 [info] elementor-pro::elementor_pro_updater Started 
2022-08-31 12:10:49 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-31 12:10:49 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-31 12:10:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.7.4',
)]
2022-08-31 12:15:44 [info] elementor-pro::elementor_pro_updater Started 
2022-08-31 12:15:44 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-31 12:15:44 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-31 12:15:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.4',
  'to' => '3.7.5',
)]
2022-08-31 12:15:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.4',
  'to' => '3.7.5',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by UserMing24** [comment]
same issue here with the latest Elementor version

**Comment by khennicks** [comment]
I have the same issue.

**Comment by MatthewsDesign** [comment]
Same issue here. Anyone found a workaround, other than using media queries and custom css?

**Comment by khennicks** [comment]
> Same issue here. Anyone found a workaround, other than using media queries and custom css?

rollback to Elementor v3.6.8

**Comment by RemPro** [comment]
Same issue here:  diplay:block changes into display:none

**Comment by RemPro** [comment]
Problem solved with update 3.7.6 ( .... almost).

X - Position slider is still not working on tablet and Mobile in version 3.7.6

omg !

**Comment by 79ho3ein** [comment]
track this issue : #19487

**Comment by jamieburchell** [comment]
This is still not working properly in 3.7.6. The controls are shown now, but the values change to zero!

https://watch.screencastify.com/v/7JJQmkVXB9uWEEXpmijf

**Comment by avivu** [comment]
This issue has been resolved in Elementor v3.7.7

Feel free to update

Thanks!

**Comment by lalofuente** [comment]
Well, this is not solved as I have both Elementor and Elemento Pro 3.7.7 and custom positioning is still not working

**Comment by RemPro** [comment]
No problem here anymore with 3.7.7 (+PRO)

**Comment by RemPro** [comment]
I'm talking about reponsive image background positioning in a column. Others not tested yet.

**Comment by bartistiek** [comment]
The issue has not been resolved. There is a miscalculation. See screenshots
<img width="1563" alt="Schermafbeelding 2022-09-26 om 14 09 36" src="https://user-images.githubusercontent.com/48589952/192278070-05f011ef-9700-49e5-b981-3232e5a8af91.png">
<img width="1853" alt="Schermafbeelding 2022-09-26 om 14 10 11" src="https://user-images.githubusercontent.com/48589952/192278138-1d57ce0a-7807-4509-a277-e6b55fc9b653.png">

**Comment by benifunk** [comment]
The problem is still there: 3.7.8,  any news? "reponsive image background positioning"
