### ISSUE TITLE
🚀 Feature Request: Include the plus ➕ icon to Container's Editing Handles (Add Container)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19688]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

It would be great if you could add an "Add Container" option to Editing Handles. This will greatly increase the speed of work. So please keep that in mind.

### Describe the solution you'd like

![download](https://user-images.githubusercontent.com/77163248/188209445-81a15aa4-af19-4900-a246-f36550ada607.png)

**Comment by fabianenzensperger** [comment]
+1

**Comment by black-eye** [comment]
+1

**Comment by Michaelgimii** [comment]
+1

**Comment by mcrowell** [comment]
+1

**Comment by perks98** [comment]
+1

**Comment by rami-elementor** [comment]
Hi @79ho3ein 

The "**+**" handle should add a nested container or a sibling container.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.8**! 🥳 

✔️ Feel free to check it out and update your plugin to the new version!

Cheers 🥂

**Comment by fabianenzensperger** [comment]
> Hello there!
> 
> We have great news! 🙌
> 
> ### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.8**! 🥳
> ✔️ Feel free to check it out and update your plugin to the new version!
> 
> Cheers 🥂

Hey @nicholaszein, yes this is working but the "+" icon is still missing and would be nice. Any news about that?

**Comment by 79ho3ein** [comment]
I think @nicholaszein confused this request with something else.

**Comment by fabianenzensperger** [comment]
> I think @nicholaszein confused this request with something else.

No, I don't think he's wrong, actually this request is done. Just not 100%. Everything is there, except for the "Add Container option = +".

**Comment by nicholaszein** [comment]
Hello @fabianenzensperger and @79ho3ein.

Perhaps I was mistaken. I do see there is no `+` icon, but the functionality is there. Can you please explain what was the expected outcome? Was it to add a container inside the sub-container, or was it to add a sibling container?

What am I missing in this video?

https://user-images.githubusercontent.com/113993460/204651868-38a93976-abbf-4e02-93d9-fb1208a8853c.mp4

**Comment by 79ho3ein** [comment]
Hi @nicholaszein.

**What I had in mind was this :**
Each container has a +. When we click on +, a container will be added inside that container. In fact, if we click on + 3 times, three containers will be added inside the desired container. I hope the video below is a good example and of course I hope this is a reasonable request. 

https://user-images.githubusercontent.com/77163248/204658036-02b65a71-d584-44e2-8c10-d5362f53b2af.mp4

I'm not sure if that's what @fabianenzensperger is thinking too, or not.

**Comment by fabianenzensperger** [comment]
@79ho3ein 

Yes, I mean the same. It's all about the "+" icon when we hover over a 2nd level container editing element. This is not available and unfortunately very annoying because I almost never use right-click and I rarely want to duplicate the container.

Your video describes it very well, thanks!

**Comment by nicholaszein** [comment]
Thanks for the video @79ho3ein! 🙏 

So basically we are only missing the `+` icon right? Since this is already an option with the `right-click` context menu?

Is that it @fabianenzensperger ?

**Comment by fabianenzensperger** [comment]
> Thanks for the video @79ho3ein! 🙏
> 
> So basically we are only missing the `+` icon right? Since this is already an option with the `right-click` context menu?
> 
> Is that it @fabianenzensperger ?

Yes! We need the “+” icon! 👍

**Comment by nicholaszein** [comment]
Thanks for the feedback guys!

I'm reopening this Feature Request! 😉

**Comment by openskiesbeckon** [comment]
I requested something similar as this was a hugely convenient function of columns within sections. Was told no. And also, if you have several child containers and want to paste the last one, say, next to the third one, you can't copy+paste (right-click third container handle, paste). It ends up pasted INSIDE the child container (child within a child). No way to do it except to paste at the end of the child containers, then drag-slide it up where you need it. Huge step backwards from columns.

No not just a plus button, but the ability to paste containers next to each other instead of them pasting inside each other. Like we had with columns.
