### ISSUE TITLE
🐞 Bug report: Button widget > icon spacing

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19695]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

If I'm not mistaken, previously, until we selected an icon, the Icon Spacing option did not appear. But now, even if we don't select any icon for the button, the Icon Spacing option will be displayed.

![download](https://user-images.githubusercontent.com/77163248/188307970-90384ca2-22be-4a7c-b58e-02654ca79af0.png)

The problem doesn't end there, the main problem is that even if we don't choose an icon for the button, there is a default spacing for the icon. While we have not selected any icon for the button. **For better understanding, please watch the video below.**

### Steps to reproduce

https://user-images.githubusercontent.com/77163248/188308117-51222c73-7121-4a85-ad2e-407a50974fc0.mp4

As you can see in the video above, there is a default spacing for the icon. While we don't have any icons. If you set the value to 0, this space will be removed.
In general, it is better not to display the Icon Spacing option if we are not using an icon for the button. Also, the default icon spacing should be removed.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by rami-elementor** [comment]
Good catch @79ho3ein !

The **icons spacing** should be applied on the icon, not on the text wrapper.

It should also be test with and without the "Inline Font Icons" experiment.

**Comment by 79ho3ein** [comment]
@rami-elementor . This bug occurs whether "Inline Font Icons" is enabled or not.

**Comment by rami-elementor** [comment]
Fixed in Elementor 3.12.0

Ref: https://github.com/elementor/elementor/pull/9832

**Comment by 79ho3ein** [comment]
Hi @rami-elementor 

If I'm not mistaken, this bug was reverted in one of the beta versions. In version 3.12.2 I still see this bug. Have you checked it recently?

**Comment by rami-elementor** [comment]
You are correct, reopening the issue.

**Comment by 79ho3ein** [comment]
thank you @rami-elementor 🥂
