### ISSUE TITLE
🐞 Bug Report: [v3.8-Beta] Multiple compatibility bugs between widgets and the Flexbox Container (ED-8137)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#19857]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

- If we add divider widget in a row container, it will not be displayed.
- the spacer widget doesn't work perfectly in the container.
- In the row container, the Progress Tracker widget disappears.
- In a row container, add a Progress Bar widget. There is a problem.

![download](https://user-images.githubusercontent.com/88034902/191125979-786891a9-3f09-48d7-8b67-eae4dff93316.png)

- In a container with a row widget, add an Image Carousel widget. There is a problem. (also post widget , Shortcode , Read More , Menu Anchor , Sidebar , Basic Gallery & HTML widget)
- In the row container, add the accordion widget. After that, open and close the widget. The width of the widget changes as it opens and closes. This bug was already fixed and it is repeated again in the new version (also in Toggle widget).

![download (1)](https://user-images.githubusercontent.com/88034902/191127797-2f56b804-e502-4fd3-9333-fff934ece7be.png)

- The Video Playlist widget doesn't look cool in a row container.

![download (2)](https://user-images.githubusercontent.com/88034902/191128062-0a30317c-8564-44eb-838a-f0070bb673f8.png)

### Steps to reproduce

-

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by nicholaszein** [comment]
Thanks for submitting your issue here @Michaelgimii ! 🙏

**Comment by nicholaszein** [comment]
Hey @Michaelgimii,

Grat News! This bug has been fixed on v3.8-Beta 3. Can you check if everything is ok on your side?

https://github.com/orgs/elementor/discussions/19854#discussioncomment-3789526

**Comment by Michaelgimii** [comment]
Hi @nicholaszein  , For me there is no way to download beta 2 or even 3 (free version) in WordPress dashboard. Is there a direct link for it?

**Comment by Michaelgimii** [comment]
Hi @nicholaszein 
Some bugs still remain. I have mentioned them [here](https://github.com/elementor/elementor/discussions/19854#discussioncomment-3851844).

**Comment by arielk** [comment]
This issue has been resolved in Elementor v3.8.0-beta-3

Feel free to update

Thanks!
