### ISSUE TITLE
❌ 🐞 Bug Report: Elementor outputs ACF Label not value

### ISSUE THREAD

**Issue by SpinDreams** [elementor/elementor#20178]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When loading an ACF field into Elementor for example a select list of values e.g.

value1 : Value One
value2 : Value Two

elementor always returns the Label instead of the value even if value is selected in ACF.

### Steps to reproduce

Create an ACF for say posts, add a dropdown list field, add some fields values with lables like so

Value  / Label
--------------------
value1 : Value One
value2 : Value Two

Be sure to choose value as the output in ACF

Go to a post and choose a value and save, in elementor edit the post or posts template and add a heading and choose the ACF field as a dynamic title option.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.6.51
	PHP Version: 8.0.24
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	Site URL: https://ajo.house
	Home URL: https://ajo.house
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: en-GB
	Timezone: 0
	Admin Email: 
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.52

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.0.3
		Author: WP Engine

	DynamicConditions
		Version: 1.6.0
		Author: RTO GmbH

	DynamicTags
		Version: 1.2.1
		Author: RTO GmbH

	Ele Custom Skin
		Version: 3.1.7
		Author: Dudaster.com

	Ele Custom Skin Pro
		Version: 3.2.4
		Author: Dudaster.com

	Elementor
		Version: 3.7.8
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.7
		Author: Elementor.com

	Loco Translate
		Version: 2.6.3
		Author: Tim Whitlock

	OoohBoi Steroids for Elementor
		Version: 2.0.3
		Author: OoohBoi

	OWM Weather
		Version: 5.6.8
		Author: Uwe Jacobs

	Polylang
		Version: 3.2.8
		Author: WP SYNTEX

	Polylang Connect for Elementor
		Version: 2.3.2
		Author: Creame

	Randomize
		Version: 1.4.3
		Author: Javik

	Rank Math SEO
		Version: 1.0.100.1
		Author: Rank Math

	Real Estate Manager Pro
		Version: 11.2
		Author: WebCodingPlace

	REM - Map Filters and Radius Search
		Version: 3.0
		Author: WebCodingPlace

	REM - Property Listing Styles
		Version: 4.1
		Author: WebCodingPlace

	Resize Image After Upload
		Version: 1.8.6
		Author: ShortPixel

	UpdraftPlus - Backup/Restore
		Version: 1.22.23
		Author: UpdraftPlus.Com, DavidAnderson

	User Role Editor
		Version: 4.63.1
		Author: Vladimir Garagulya

	Wordfence Security
		Version: 7.7.1
		Author: Wordfence

	WP-Optimize - Clean, Compress, Cache
		Version: 3.2.9
		Author: David Anderson, Ruhani Rabin, Team Updraft

	WP Go Maps (formerly WP Google Maps)
		Version: 9.0.12
		Author: WP Go Maps

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Elementor Experiments ==
	Optimised DOM Output: Active
	Improved asset loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility improvements: Active
	Additional Custom Breakpoints: Active
	Import Export Template Kit: Active
	Hide native WordPress widgets from search results: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Active
	Landing pages: Active
	Color Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Active
	Page Transitions: Active
	Notes: Active
	Form Submissions: Active
	Scroll Snap: Active

== Log ==
	
Log: showing 12 of 122022-09-05 20:15:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.3',
  'to' => '3.7.4',
)]
2022-09-05 20:15:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.3',
  'to' => '3.7.4',
)]
2022-09-20 19:14:44 [info] elementor::elementor_updater Started 
2022-09-20 19:14:44 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-20 19:14:44 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-20 19:14:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.7',
)]
2022-09-20 19:14:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.7',
)]
2022-10-03 05:48:21 [info] elementor::elementor_updater Started 
2022-10-03 05:48:21 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-03 05:48:21 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-03 05:48:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.7.8',
)]
2022-10-03 05:48:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.7.8',
)]

PHP: showing 11 of 11PHP: 2022-09-06 11:21:21 [warning X 4643][/home/aplacein/web/dev.ajo.house/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::264] Attempt to read property "ID" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-14 14:14:14 [error X 1][/home/aplacein/web/dev.ajo.house/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /home/aplacein/web/dev.ajo.house/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /home/aplacein/web/dev.ajo.house/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/aplacein/web/dev.ajo.house/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/aplacein/web/dev.ajo.house/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/aplacein/web/dev.ajo.house/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#5 /home/aplacein/web/dev.ajo.house/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#6 /home/aplacein/web/dev.ajo.house/wp-admin/admin-ajax.php(187): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-15 07:45:50 [warning X 4][/home/aplacein/web/dev.ajo.house/wp-content/plugins/elementor-pro/modules/query-control/module.php::748] Attempt to read property "name" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-18 13:13:52 [warning X 2][/home/aplacein/web/dev.ajo.house/wp-content/plugins/elementor/core/editor/editor.php::121] Cannot modify header information - headers already sent by (output started at /home/aplacein/web/dev.ajo.house/wp-content/themes/hello-theme-child-master/rank-math.php:1) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-20 07:57:09 [warning X 44][/home/aplacein/web/dev.ajo.house/wp-content/plugins/elementor-pro/modules/theme-elements/widgets/post-info.php::829] Attempt to read property "name" on array [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-20 09:24:47 [warning X 1][/home/aplacein/web/dev.ajo.house/wp-content/plugins/elementor-pro/modules/query-control/module.php::772] Attempt to read property "hierarchical" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-20 09:43:46 [warning X 106][/home/aplacein/web/dev.ajo.house/wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-post-query.php::247] Undefined property: WP_Error::$taxonomy [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-20 11:14:05 [warning X 1][/home/aplacein/web/dev.ajo.house/wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php::50] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-21 18:06:55 [warning X 4][/home/aplacein/web/dev.ajo.house/wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-post-query.php::247] Undefined property: WP_Error::$taxonomy [array (
  'trace' => '
#0: /home/aplacein/web/dev.ajo.house/wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-post-query.php(247): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/aplacein/web/dev.ajo.house/wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-post-query.php(227): ElementorPro\Modules\QueryControl\Classes\Elementor_Post_Query -> build_terms_query()
#2: /home/aplacein/web/dev.ajo.house/wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-post-query.php(222): ElementorPro\Modules\QueryControl\Classes\Elementor_Post_Query -> build_terms_query_include()
#3: /home/aplacein/web/dev.ajo.house/wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-post-query.php(133): ElementorPro\Modules\QueryControl\Classes\Elementor_Post_Query -> set_terms_args()
#4: /home/aplacein/web/dev.ajo.house/wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-post-query.php(49): ElementorPro\Modules\QueryControl\Classes\Elementor_Post_Query -> get_query_args()
',
)]
PHP: 2022-10-22 15:40:42 [warning X 9][/home/aplacein/web/dev.ajo.house/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-29 08:09:32 [warning X 117][/home/aplacein/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 19 of 19JS: 2022-10-06 15:06:17 [error X 1][https://dev.ajo.house/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9:21077] Cannot read properties of null (reading \'getOptions\') 
JS: 2022-10-07 16:36:42 [error X 6][https://dev.ajo.house/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.7.8:2:51471] Model.isValidChild() should be implemented, please provide \'isValidChild\' functionality. 
JS: 2022-10-07 17:48:15 [error X 9][https://dev.ajo.house/wp-content/plugins/estatik/admin/assets/js/vendor/select2.min.js?ver=6.0.2:1:73361] Cannot read properties of undefined (reading \'destroy\') 
JS: 2022-10-08 06:39:14 [error X 2][https://dev.ajo.house/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:646945] this.model.isValidChild is not a function 
JS: 2022-10-08 08:04:47 [error X 3][https://dev.ajo.house/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:287003] Cannot read properties of undefined (reading \'id\') 
JS: 2022-10-08 20:11:18 [error X 17][https://dev.ajo.house/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:767848] Cannot read properties of undefined (reading \'localized\') 
JS: 2022-10-08 20:12:24 [error X 1][https://dev.ajo.house/wp-content/plugins/elementor-pro/assets/js/gallery.9c61bb9957e10e6d7bda.bundle.min.js:2:5599] Cannot read properties of undefined (reading \'setSettings\') 
JS: 2022-10-09 06:33:48 [error X 10][https://dev.ajo.house/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:692080] T.getContainer is not a function 
JS: 2022-10-11 20:53:59 [error X 4][https://dev.ajo.house/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.7.8:2:7427] Cannot read properties of null (reading \'editor\') 
JS: 2022-10-15 07:57:23 [error X 119][https://dev.ajo.house/wp-content/plugins/ele-custom-skin-pro/assets/js/ecspro.js?ver=3.2.4:172:37] Cannot set properties of undefined (setting \'spaceBetween\') 
JS: 2022-10-15 08:07:59 [error X 1][https://dev.ajo.house/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:609038] Cannot read properties of undefined (reading \'isDesignable\') 
JS: 2022-10-15 21:04:32 [error X 53][https://dev.ajo.house/wp-admin/post.php?post=4146&action=elementor#:1:1] Identifier \'$dcWidgetIdInput\' has already been declared 
JS: 2022-10-16 15:58:37 [error X 2][https://dev.ajo.house/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:652180] Cannot read properties of undefined (reading \'get\') 
JS: 2022-10-20 10:16:49 [error X 2][https://dev.ajo.house/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:117233] Cannot read properties of undefined (reading \'match\') 
JS: 2022-10-20 10:17:21 [error X 1][https://dev.ajo.house/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:586988] Cannot read properties of undefined (reading \'isEditable\') 
JS: 2022-10-22 10:27:24 [error X 85][https://dev.ajo.house/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16820] Cannot read properties of null (reading \'clone\') 
JS: 2022-10-22 10:27:25 [error X 3][https://dev.ajo.house/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:21012] Cannot read properties of null (reading \'changestop\') 
JS: 2022-10-22 14:25:09 [error X 1][https://dev.ajo.house/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.7.8:2:4807] Cannot read properties of undefined (reading \'attributes\') 
JS: 2022-10-23 20:39:58 [error X 4][https://ajo.house/wp-content/plugins/elementor-pro/assets/lib/sticky/jquery.sticky.min.js?ver=3.7.7:1:1410] Failed to execute \'getComputedStyle\' on \'Window\': parameter 1 is not of type \'Element\'. 

== Elementor - Compatibility Tag ==
	
	Ele Custom Skin: Compatible
	Ele Custom Skin Pro: Compatible
	Elementor Pro: Compatible
	OoohBoi Steroids for Elementor: Compatible
	Polylang Connect for Elementor: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Ele Custom Skin: Compatible
	Ele Custom Skin Pro: Compatible
	OoohBoi Steroids for Elementor: Compatible
	Polylang Connect for Elementor: Compatible

**Comment by nicholaszein** [comment]
Hello @SpinDreams! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by nicholaszein** [comment]
Hello @SpinDreams,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:

Using the latest version of Elementor and Elementor Pro, I was able to add several fields, and between them, a `Select` field with the **Return Format** set to `value` (see screenshots below). All fields in my test were set to return the `value`.

![image](https://user-images.githubusercontent.com/113993460/199230294-aabff6c8-2790-4005-90a7-cfcb1872fe81.png)
_ACF Field Group Settings_

![image](https://user-images.githubusercontent.com/113993460/199230444-cf469811-b545-45fe-9c73-f475380b93aa.png)
_Selected options_

Then in the Elementor Editor, I added dynamic tags to various Heading widgets, and the values always returned correctly.

![image](https://user-images.githubusercontent.com/113993460/199230807-5ec4dfd2-98d5-4a79-846c-1153b602f303.png)
_Elementor Editor_

![image](https://user-images.githubusercontent.com/113993460/199231291-5cddd1b1-fe08-4317-adc3-c5bb0e2a3932.png)
_Website Frontend_

<details>
<summary>System Info</summary>
		
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.21.4
	MySQL version: mariadb.org binary distribution v10.5.17
	PHP Version: 7.4.32
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	Site URL: localhost
	Home URL: localhost
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Sao_Paulo
	Admin Email: redacted
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.0.3
		Author: WP Engine

	Elementor
		Version: 3.8.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.0
		Author: Elementor.com


== Elements Usage ==
	
	wp-post : 0
		button : 1
		container : 1
		heading : 8
		image : 1
		image-gallery : 1


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Inactive
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Landing Pages: Inactive
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Inactive by default
	Form Submissions: Inactive
	Scroll Snap: Active by default


== Log ==
	
Log: showing 13 of 132022-11-01 07:57:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-01 07:57:03 [info] elementor-pro::elementor_pro_updater Started 
2022-11-01 07:57:03 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-01 07:57:03 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-01 07:57:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-01 07:57:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-01 07:57:03 [info] elementor::elementor_updater Started 
2022-11-01 07:57:03 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-01 07:57:03 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-01 07:57:03 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-11-01 07:57:03 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-11-01 07:57:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-01 07:57:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
</details>

### ✅ What you can do to solve your issue:

⚠️  **Backup** your website before proceeding, and if possible do it in a staging environment!

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the 3rd-party plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2. Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3. Clear all cache types, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). To check this information go to your _WordPress Dashboard > Elementor > System Info_, and check both your **Server Environment** and **WordPress Environment** tables. You can also scroll down to the end of the **System Info** page and click on the **Download System Info** button. Then submit another comment here and drop the `.txt` file inside the text box to upload your system information and share it with us.

#### 👎 If the issue persists, try contacting 💎 **Elementor Support** (for Pro Users). 
To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards

**Comment by SpinDreams** [comment]
@nicholaszein I guess you removed your last response as I don't see it here now. From the screens you sent it seems you have the same issue with Elementor only outputting the labels not the values. I created a staging site and disabled all plugins except for elementor pro and ACF (always using hello theme) and I still get the issue with outputting only the Label not the value, the only way to output the value is not to set Labels in ACF.

**Comment by SpinDreams** [comment]
Here are some screens from my test site.

![image](https://user-images.githubusercontent.com/70260163/199300350-c6d350d0-bf09-457b-b6f2-acc8eaf65f05.png)
![image](https://user-images.githubusercontent.com/70260163/199300670-9f4b037c-4274-4620-954a-809243575ea1.png)
![image](https://user-images.githubusercontent.com/70260163/199300944-241b9325-06cd-4ab3-a384-84535631f614.png)

**Comment by SpinDreams** [comment]
![image](https://user-images.githubusercontent.com/70260163/199301734-89a54880-a9fb-4eb8-b0c3-ffa43db53314.png)

**Comment by philrp** [comment]
I found this thread because I'm having the same issue.

**Comment by rami-elementor** [comment]
We confirmed this bug with select field.

**Comment by nicholaszein** [comment]
Hey @SpinDreams, you're right! I did come to the same conclusion, but I only realized it after I answered your issue. That's why I removed my answer.

We are aware of this issue and are working on a fix.

Thank you for the detailed explanation! 🙏

**Comment by soko-grafik** [comment]
Hi, i have the same problem, with the return value from ACF Select.

my quick solution for this:

chose Dynamic Option -> Post Custom Field
and enter the ACF Field Name -> Custom Key

this returns the Value.

![image](https://github.com/elementor/elementor/assets/37374428/1c58bbc0-c7c5-419d-b700-eb9ac8ad0115)

**Comment by PinkFloyd1213** [comment]
Hello, 
I have exactly the same problem, except that I don't have any ACF Select, I'll let you see the image. 
Until this bug is corrected, do you know a way to hide the error message for site visitors? 
Thanks in advance

![image](https://github.com/elementor/elementor/assets/31860086/46abb66d-a80c-4aad-ae42-a5d004358e87)

**Comment by wlmmatt** [comment]
Same again - happens with select, radio and checkbox. Ended up just making the labels generic enough to use as stand-ins but it's not very user-friendly.

**Comment by MarcoHaase** [comment]
Quick workarround:

create a ACF field checkbox with choices
`
// ...
'choices' => [
  'xxxhidden'   => 'hidden',
  // ...
],
// ...
`

add to style.css
`
// ...
.xxx-hidden {
  display: none;
}
// ...
`
add to functions.php
`
// ...
// https://www.advancedcustomfields.com/resources/acf-format_value/
function xxx_fix_elementor_acf_checkbox($value, $post_id, $field)
{
	if (array_key_exists('xxxhidden', $field['choices']) && $value != '') {
		$value = ['xxx-hidden'];
	}
	return $value;
}
add_filter('acf/format_value/type=checkbox', 'xxx_fix_elementor_acf_checkbox', 10, 3);
// ...
`

**Comment by blockmonkey** [comment]
Just ran into this issues. Any timeline for getting this fixed?

**Comment by JennyPower** [comment]
This is still an issue - same for the ACF select field

**Comment by markbulingit** [comment]
Bug still exists August 30, 2024 8:51AM

**Comment by magesticmojo** [comment]
Still having this bug in 2024 :-(
Please fix this!

**Comment by gabrielwalther** [comment]
@nicholaszein any updates on this in 2025? ;)

**Comment by gumbapt** [comment]
Still a bug with the latest versions it seems. How are people using this, it seems important to create custom layouts.

**Comment by mikethomastv** [comment]
This is still a bug as of May 5, 2025. Seems risky to use this field in any custom functions as it could change suddenly with an update. Why hasn't this been addressed in 3 years?

**Comment by INT-010** [comment]
Still having this issue with the Select type of ACF fields. Thanks to @soko-grafik for posting a work around that can successfully return the value. 

> Hi, i have the same problem, with the return value from ACF Select.
> 
> my quick solution for this:
> 
> chose Dynamic Option -> Post Custom Field and enter the ACF Field Name -> Custom Key
> 
> this returns the Value.
> 
> ![image](https://github.com/elementor/elementor/assets/37374428/1c58bbc0-c7c5-419d-b700-eb9ac8ad0115)
