### ISSUE TITLE
✔️ 🐞 Bug Report: Sticky Inner Section - Stay in column not working (ED-8545)

### ISSUE THREAD

**Issue by mcrowell** [elementor/elementor#20203]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The stay in column feature isn't working correctly when applied to an inner section. 

Watch the video below to see the bug:
https://www.youtube.com/watch?v=Vi_Z0d1lNRk

### Steps to reproduce

Apply stay in column to an inner section and scroll down the page.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.40
	PHP Version: 7.4.32
	PHP Memory Limit: 256M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	Site URL: https://wickydemo.com/testing
	Home URL: https://wickydemo.com/testing
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 128M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York	
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== Active Plugins ==
	Code Snippets Pro
		Version: 3.2.1
		Author: Code Snippets Pro

	Elementor
		Version: 3.8.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.0
		Author: Elementor.com

	motion.page
		Version: 1.6.6
		Author: motion.page

	Slider Revolution
		Version: 6.6.3
		Author: ThemePunch

	Slider Revolution Mousetrap Add-On
		Version: 3.0.6
		Author: ThemePunch

	Slider Revolution Transitionpack Add-On
		Version: 1.0.4
		Author: ThemePunch

	White Label CMS
		Version: 2.3
		Author: www.videousermanuals.com

	Wordfence Security
		Version: 7.7.1
		Author: Wordfence

	WP Revisions Control
		Version: 1.4.3
		Author: Erick Hitter

== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility Improvements: Inactive
	Additional Custom Breakpoints: Inactive
	Import Export Website Kit: Inactive
	Hide native WordPress widgets from search results: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Landing Pages: Inactive
	Color Sampler: Inactive
	Favorite Widgets: Inactive
	Admin Top Bar: Inactive
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Inactive
	Form Submissions: Inactive
	Scroll Snap: Inactive

**Comment by dburke-ux** [comment]
+1, our team had run into the same issue with Sticky Inner Sections not staying in column

**Comment by Vitaio** [comment]
+1 same problem

**Comment by amelosmanovic** [comment]
+1

**Comment by editor-acd** [comment]
Same problem.

**Comment by dezinux** [comment]
Noticed the Same issue, rolling back to Elementor 3.7.8 and Elementor Pro 3.7.7 resolves the issue.

**Comment by StenderIternum** [comment]
+1 - This happened after the fix that made "stay in column" work in container mode.

**Comment by nicholaszein** [comment]
Hey @mcrowell, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- **Isolating the Problem:** You need to ensure this only happens while using Elementor, Elementor Pro, and the Hello Elementor theme. We do not provide support for 3rd-party themes and plugins. You have some plugins that might conflict with the sticky feature (Motion.page and Revolution Slider).

👉 Please clarify the information above before we continue. Does it happen without those plugins being active?

Best regards,

Nick

**Comment by 79ho3ein** [comment]
Hi @nicholaszein , I just tested it now. And yes, this bug exists.

**system info**

[system-info-localhost-01-11-2022.txt](https://github.com/elementor/elementor/files/9909049/system-info-localhost-01-11-2022.txt)

**Comment by mcrowell** [comment]
@nicholaszein - Yes, I can confirm the bug is still there after I deactivated all other plugins.

**Comment by amelosmanovic** [comment]
Stay in column work only when I use Containers. But don't work when I use Sections and Columns

**Comment by StenderIternum** [comment]
The problem only exists on sticky inner sections, it seems

**Comment by micmiller-apptio** [comment]
I can also confirm this issue and don't have any of the plugins mentioned above installed. We are stuck on 3.7.4 since we also use responsively positioned background images on our site and had been waiting for that fix which is in 3.8.

**Comment by mateitudor** [comment]
I can also confirm this.
Layout: Main container → inside container 1 (text) + inside container (sticky item).
Can replicate it consistently if I fast scroll up or down.

**Comment by perks98** [comment]
+1 Just noticed this on a bunch of client sites. Needs a fix pushed out asap

**Comment by kskonovalov** [comment]
+1

**Comment by conorlobrien** [comment]
+1

**Comment by steve1401** [comment]
Same for us.

**Comment by awebguy99** [comment]
+1 Same for us.

Hey Elementor. Can I ask a favor? When you fix a bug in containers (E.G. stay in column), can you please also check the fix doesn't break it for the old system (Section/Columns/Inner Sections)? Thanks so much. ;)

**Comment by clmnsm** [comment]
This breaks pages for us too. Please fix.

**Comment by mcrowell** [comment]
@nicholaszein - Is there an ETA on when this bug will get fixed?

**Comment by nicholaszein** [comment]
Hello everybody!

This issue is a known bug and the team is already working on a fix. We are sorry for the inconvenience and trouble that this might have caused.

Thank you all for reporting the issue! 🙏 

 The bug should be patched in the next release scheduled to be launched in a few days.

Kind regards

**Comment by awebguy99** [comment]
Yay, good news, thanks. Looking forward to the fix.

**Comment by nicholaszein** [comment]
Hey everybody!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.8.1**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂

**Comment by mateitudor** [comment]
That's awesome! Thank you! Any news for us 3.9 beta testers?

**Comment by fwhitten** [comment]
Hi, I'm on v3.8.1 and the problem still occurs?
Fixing sticky wasn't listed in the changelog for 3.8.1?
Are other people still experiencing it?

**Comment by wirednkod** [comment]
I'm also on v3.8.1 and problem still occurs. Stay-in-column still not working. The switch seems to have no effect to the mentioned column

**Comment by micmiller-apptio** [comment]
Make sure you've updated the Pro version. The fix was in Pro v3.8.1, not the standard version. It worked correctly for me after I updated Elementor Pro.

**Comment by wirednkod** [comment]
> Make sure you've updated the Pro version. The fix was in Pro v3.8.1, not the standard version. It worked correctly for me after I updated Elementor Pro.

I am in version 3.8.1 and pro (of course)

**Comment by Irinel123** [comment]
Hello elements, I'm on 3.9 and the problem still exists.

When will we have a solution?

**Comment by mhr88** [comment]
I have updated to the newest version but problem still exists

**Comment by taropaa** [comment]
Same here, problem still exists.

**Comment by razfazz** [comment]
please fix this issue also in the new container

**Comment by idamcevski** [comment]
Interestingly enough, **if you add any URL argument, (eg. ?test=test) the bug is no longer present** and everything works as intended. I have no idea why it behaves the way does but I hope it helps in resolving the issue.

**Comment by thehuykiu** [comment]
please fix this , my elementor version :3.9 still not working

**Comment by contrastxxx** [comment]
3.11 still problem :(

**Comment by khairulimran-97** [comment]
Not working for chrome with latest version.

**Comment by VisionaryOS** [comment]
I bought PRO for this particular feature - so the fact it's not working is pretty upsetting

**Comment by markosansa** [comment]
Hello, 
March 2023 and still having issues. 
Both with the current versions Elementor 3.11.0  and Elementor Pro 3.12.0

**Comment by thiagomeedeiros** [comment]
May 2023 and the bug still persists. When I disable stay in collun, it fixes but ends up going down to the end of the page. When active, it ends up going up and down the entire site, without stopping at any container
