### ISSUE TITLE
ACF Images don't show up

### ISSUE THREAD

**Issue by MC0R3** [elementor/elementor#20264]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi there,

Since Elementor 3.8, dynamically showing images with ACF doesn't work as expected anymore. I have several websites that are impacted, and it's a rather annoying issue. Fallback images do show up as expected.

This requires ACF to be setup with an image-field in a post type (doesn't matter if it's custom or not).

### Steps to reproduce

1. Use the Image-widget
2. Use the dynamic-option and select the image-field you've set up with ACF
3. It shows fine in the editor
4. It doesn't show up frontend

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '42', Revision 'b0a7dc2da2e' v5.7.39-42
	PHP Version: 7.4.33
	PHP Memory Limit: 256M
	PHP Max Input Vars: 20000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1
	Site URL: https://wik.mcore-services.be
	Home URL: https://wik.mcore-services.be
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: nl
	Timezone: 0
	Admin Email: websites@mcore-services.be
	Debug Mode: Inactive

== Theme ==
	Name: MCore Services bv
	Version: 1.0.1
	Author: MCore Services
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: nl_NL_formal
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.0.3
		Author: WP Engine

	Branda Pro
		Version: 3.4.8
		Author: WPMU DEV

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Custom Post Type UI
		Version: 1.13.1
		Author: WebDevStudios

	Dynamic.ooo - Dynamic Content for Elementor
		Version: 2.8.0
		Author: Dynamic.ooo

	Elementor
		Version: 3.8.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.0
		Author: Elementor.com

	Happy Elementor Addons
		Version: 3.7.1
		Author: weDevs

	Happy Elementor Addons Pro
		Version: 2.6.1
		Author: weDevs

	Imagify
		Version: 2.0
		Author: WP Rocket

	WPMU DEV Dashboard
		Version: 4.11.17
		Author: WPMU DEV

== Must-Use Plugins ==
	Ensure admin user isn't deleted
		Version: 1.0
		Author: 

	WP CLI Login Command Server
		Version: 1.3
		Author: Evan Mattson

== Elements Usage ==
	
	footer : 1
		icon-list : 2
		nav-menu : 2
		theme-site-logo : 1
	header : 1
		button : 2
		nav-menu : 1
		theme-site-logo : 1
	section : 1
		dyncontel-acf : 1
		heading : 1
	wp-page : 10
		button : 6
		dce-dynamicposts-v2 : 1
		ha-step-flow : 4
		heading : 21
		html : 1
		icon-box : 3
		image : 1
		posts : 8
		text-editor : 24

== Elementor Experiments ==
	Geoptimaliseerde DOM-uitvoer: Standaard actief
	Verbeterd laden van assets: Standaard actief
	Verbeterd laden van CSS: Standaard actief
	Inline Font Icons: Standaard inactief
	Toegang verbeteringen: Standaard actief
	Extra aangepaste onderbrekingspunten: Standaard actief
	Import export template kit: Standaard actief
	Hide native WordPress widgets from search results: Standaard actief
	admin_menu_rearrangement: Standaard inactief
	Flexbox Container: Standaard inactief
	Default to New Theme Builder: Standaard actief
	Hello Theme Header & Footer: Standaard actief
	Landingspagina's: Standaard actief
	Kleur sampler: Standaard actief
	Favorite Widgets: Standaard actief
	Beheerder bovenste balk: Standaard actief
	Page Transitions: Standaard actief
	Notes: Standaard actief
	Loop: Standaard inactief
	Form Submissions: Standaard actief
	Scroll Snap: Standaard actief

== Log ==
	
PHP: showing 7 of 7PHP: 2022-10-08 12:08:26 [notice X 1][/data/sites/web/mcore-servicesbe/subsites/wik.mcore-services.be/wp-content/plugins/elementor/core/common/modules/connect/module.php::230] Trying to get property 'email' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-01 09:23:17 [notice X 3][/data/sites/web/mcore-servicesbe/subsites/wik.mcore-services.be/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-01 09:24:52 [notice X 2][/data/sites/web/mcore-servicesbe/subsites/wik.mcore-services.be/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-01 13:29:28 [notice X 3][/data/sites/web/mcore-servicesbe/subsites/wik.mcore-services.be/wp-content/plugins/elementor/includes/widgets/traits/button-trait.php::552] Undefined index: icon [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-02 10:38:16 [notice X 3][/data/sites/web/mcore-servicesbe/subsites/wik.mcore-services.be/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::40] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-02 10:40:15 [error X 1][/data/sites/web/mcore-servicesbe/subsites/wik.mcore-services.be/wp-content/plugins/elementor/core/common/modules/finder/module.php::90] Uncaught Error: Call to a member function get_category_items() on array in /data/sites/web/mcore-servicesbe/subsites/wik.mcore-services.be/wp-content/plugins/elementor/core/common/modules/finder/module.php:90
Stack trace:
#0 [internal function]: Elementor\Core\Common\Modules\Finder\Module->ajax_get_category_items()
#1 /data/sites/web/mcore-servicesbe/subsites/wik.mcore-services.be/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#2 /data/sites/web/mcore-servicesbe/subsites/wik.mcore-services.be/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#3 /data/sites/web/mcore-servicesbe/subsites/wik.mcore-services.be/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#4 /data/sites/web/mcore-servicesbe/subsites/wik.mcore-services.be/wp-includes/plugin.php(517): WP_Hook->do_action()
#5 /data/sites/web/mcore-servicesbe/subsites/wik.mcore-services.be/wp-admin/admin-ajax.php(188): do_action()
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-02 12:23:45 [warning X 4][/data/sites/web/mcore-servicesbe/subsites/wik.mcore-services.be/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /data/sites/web/mcore-servicesbe/subsites/wik.mcore-services.be/wp-content/plugins/dynamic-content-for-elementor/modules/dynamic-tags/tags/token.php:164) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 12 of 122022-11-01 08:54:26 [info] elementor::elementor_updater Started 
2022-11-01 08:54:26 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-01 08:54:27 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-01 08:54:27 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-11-01 08:54:27 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-11-01 08:54:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-11-01 08:54:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-11-01 13:08:41 [info] elementor-pro::elementor_pro_updater Started 
2022-11-01 13:08:41 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-01 13:08:41 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-01 13:08:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-01 13:08:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]

JS: showing 3 of 3JS: 2022-11-01 09:25:20 [error X 3][https://wik.mcore-services.be/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0:3:1061530] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-11-01 10:24:52 [error X 7][https://wik.mcore-services.be/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0:3:769459] Cannot read properties of undefined (reading \'localized\') 
JS: 2022-11-02 10:37:48 [error X 1][https://wik.mcore-services.be/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.8.0:2:2932] elementor_new_template_form_controls is not defined 

== Elementor - Compatibility Tag ==
	
	Dynamic.ooo - Dynamic Content for Elementor: Niet compatibel
	Elementor Pro: Niet compatibel
	Happy Elementor Addons: Niet compatibel
	Happy Elementor Addons Pro: Niet compatibel

== Elementor Pro - Compatibility Tag ==
	
	Dynamic.ooo - Dynamic Content for Elementor: Compatibel
	Happy Elementor Addons: Niet compatibel
	Happy Elementor Addons Pro: Niet compatibel

**Comment by MC0R3** [comment]
Duplicate issue with

https://github.com/elementor/elementor/issues/20235

Not sure how I missed that 😅

**Comment by nicholaszein** [comment]
Hello there @MC0R3!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.8.1**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂

**Comment by critdhenz** [comment]
@nicholaszein this is still existing in Elementor v3.11.4. The ACF fields not rendering in Pop up or Modal.
