### ISSUE TITLE
✔️ 🐞 Bug Report: Loop Grid Duplicated Featured Images When Using Ajax Pagination

### ISSUE THREAD

**Issue by nerdtech** [elementor/elementor#20729]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When using the loop grid and setting a featured image as a background in a container some images are duplicated (does not use the actual featured image of the post) when using any ajax pagination such as "load more" and "infinite scroll". It does not seem to effect numbers and forward/next.

Please see this short video below showing the issue...

https://www.loom.com/share/73f98c1d420444898f4a2914f49e7367

thanks.

### Steps to reproduce

1. Create a loop grid using a container and set the background to be a featured post image.
2. Use load more or infinite scroll pagination.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.47 (Win64) OpenSSL/1.1.1k PHP/7.4.19
	MySQL version: MySQL Community Server (GPL) v5.7.33
	PHP Version: 7.4.19
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 2G
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://elementor.dev
	Home URL: https://elementor.dev
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 256M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Admin Email: admin@admin.net
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.9.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.0
		Author: Elementor.com

	Optimize Database after Deleting Revisions
		Version: 5.0.110
		Author: CAGE Web Design | Rolf van Gelder, Eindhoven, The Netherlands

	Perfmatters
		Version: 2.0.0
		Author: forgemedia

	Unlimited Elements for Elementor (Premium)
		Version: 1.5.43
		Author: Unlimited Elements

	WP Dummy Content Generator
		Version: 2.1.2
		Author: Deepak anand

== Must-Use Plugins ==
	Perfmatters MU
		Version: 2.0.0
		Author: forgemedia

== Elementor Experiments ==
	Optimised DOM Output: Inactive
	Improved asset loading: Active by default
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive by default
	Accessibility improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive
	Landing pages: Inactive
	Colour Sampler: Active by default
	Favourite Widgets: Active by default
	Admin Top Bar: Active by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Active
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
JS: showing 4 of 4JS: 2022-12-08 09:33:29 [error X 138][https://elementor.dev/wp-admin/load-scripts.php?c=1&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:4:51824] Cannot read properties of undefined (reading \'replace\') 
JS: 2022-12-09 12:10:06 [error X 4][https://elementor.dev/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.0:3:655278] this.model.isValidChild is not a function 
JS: 2022-12-10 14:54:33 [error X 2][https://elementor.dev/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.0:3:1068229] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-12-12 14:34:02 [error X 1][https://elementor.dev/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.0:3:775220] Cannot read properties of undefined (reading \'toLowerCase\') 

PHP: showing 3 of 3PHP: 2022-12-09 11:14:43 [notice X 3][C:\laragon\www\elementor\wp-content\plugins\elementor\app\modules\import-export\module.php::563] Trying to get property 'label' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-10 11:58:43 [notice X 5][C:\laragon\www\elementor\wp-content\plugins\elementor\core\common\modules\ajax\module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-10 14:55:25 [notice X 3][C:\laragon\www\elementor\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php::167] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Unlimited Elements for Elementor (Premium): Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @nerdtech! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this issue was solved with Elementor Pro **v3.10**! 🥳 

✔️ Feel free to check it out and update your plugin to the new version!

Cheers 🥂

**Comment by paletta** [comment]
I can still reproduce this bug in v3.10...anyone else with this problem?

**Comment by paletta** [comment]
@nicholaszein I can still reproduce this bug on 3.10...the strange thing is that if I'm logged in everything works but when I'm not logged the bug is still visible (Hello theme without any plugin active except Elementor core and Pro)

**Comment by PixeljackDesign** [comment]
> 
Hi Nicholas, 

I'm experiencing the same issue as above in Elementor Pro v3.10.3, where infinite scroll doesn't load the correct image.
