### ISSUE TITLE
Posts Widget Pagination Bug in Elementor Templates

### ISSUE THREAD

**Issue by schndr-cdn** [elementor/elementor#21417]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I create a template and use the "Posts" widget in the template, the pagination features like "load more" or "infinite scroll" don't work. Example Every time I click the "Load more" button, it keeps loading the same first columns (posts).

### Steps to reproduce

1) Create a section template
2) Add Posts widget
3) Enter a value (Example 3) for Posts per Page
4) Set your pagination to "Infinite Scroll"
5) Add your template (short code) to any page
6) Test your posts

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Debian 10 v10.3.36
	PHP Version: 8.0.28
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://gaede.werbeagentur-schneider.de
	Home URL: https://gaede.werbeagentur-schneider.de
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Admin Email: info+admin@werbeagentur-schneider.de
	Debug Mode: Inactive

== Theme ==
	Name: Fahrrad Gäde
	Version: 1.0.1
	Author: Werbeagentur Schneider
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

== Active Plugins ==
	All-in-One WP Migration
		Version: 7.71
		Author: ServMask

	All-in-One WP Migration Dropbox Extension
		Version: 3.71
		Author: ServMask

	Branda
		Version: 3.4.8.1
		Author: WPMU DEV

	Elementor
		Version: 3.11.1
		Author: Elementor.com

	Elementor Blocks for Gutenberg
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.11.1
		Author: Elementor.com

	JetEngine
		Version: 3.1.1
		Author: Crocoblock

	Password Protected
		Version: 2.6.2
		Author: WPExperts

	Smart Slider 3 Pro
		Version: 3.5.1.14
		Author: Nextend

	WP Media folder
		Version: 5.5.4
		Author: Joomunited

== Eigenschaften ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	

== Elementor-Experimente ==
	Optimierte DOM Ausgabe: Standardmäßig aktiviert
	Verbessertes Laden von Assets: Aktiv
	Verbessertes Laden von CSS: Aktiv
	Inline-Schriftarten-Symbole: Aktiv
	Verbesserungen der Zugänglichkeit: Standardmäßig aktiviert
	Zusätzliche benutzerdefinierte Breakpoints: Inaktiv
	admin_menu_rearrangement: Standardmäßig deaktiviert
	Flexbox Container: Inaktiv
	Upgrade Swiper Library: Standardmäßig deaktiviert
	Default to New Theme Builder: Standardmäßig aktiviert
	Hello Theme Header & Footer: Standardmäßig aktiviert
	Editor V2: Standardmäßig deaktiviert
	Startseiten: Inaktiv
	Nested Elements: Standardmäßig deaktiviert
	Lazy Load Background Images: Standardmäßig deaktiviert
	Save as Default: Standardmäßig aktiviert
	Page Transitions: Inaktiv
	Notes: Inaktiv
	Loop: Standardmäßig aktiviert
	Form Submissions: Inaktiv
	Scroll Snap: Inaktiv
	Mega Menu: Standardmäßig deaktiviert

== Protokoll ==
	
Log: showing 20 of 342022-12-20 09:38:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.9.1',
)]
2023-01-20 09:06:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.1',
  'to' => '3.10.1',
)]
2023-01-20 09:06:18 [info] elementor::elementor_updater Started 
2023-01-20 09:06:18 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-20 09:06:18 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-20 09:06:18 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.1',
  'to' => '3.10.2',
)]
2023-01-20 09:06:19 [info] elementor-pro::elementor_pro_updater Started 
2023-01-20 09:06:19 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-01-20 09:06:19 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-01-20 09:06:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.1',
  'to' => '3.10.2',
)]
2023-02-20 09:59:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.1',
  'to' => '3.11.1',
)]
2023-02-20 09:59:02 [info] elementor::elementor_updater Started 
2023-02-20 09:59:02 [info] Elementor/Upgrades - _on_each_version Start  
2023-02-20 09:59:02 [info] Elementor/Upgrades - _on_each_version Finished 
2023-02-20 09:59:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.1',
  'to' => '3.11.1',
)]
2023-02-20 09:59:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.2',
  'to' => '3.11.1',
)]
2023-02-20 09:59:02 [info] elementor-pro::elementor_pro_updater Started 
2023-02-20 09:59:02 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-02-20 09:59:02 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-02-20 09:59:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.2',
  'to' => '3.11.1',
)]

JS: showing 5 of 5JS: 2022-12-05 10:30:38 [error X 1][https://gaede.werbeagentur-schneider.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.2:3:873489] elementorFrontend is not defined 
JS: 2022-12-19 15:32:47 [error X 9][https://gaede.werbeagentur-schneider.de/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:4:51824] Cannot read properties of undefined (reading \'replace\') 
JS: 2023-01-20 09:03:54 [error X 1][https://gaede.werbeagentur-schneider.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.1:3:781513] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2023-02-02 10:33:29 [error X 5][https://gaede.werbeagentur-schneider.de/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:4:51824] Cannot read properties of undefined (reading 'replace') 
JS: 2023-02-21 15:23:39 [error X 1][https://gaede.werbeagentur-schneider.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.1:3:408058] Cannot read properties of null (reading 'history') 

PHP: showing 4 of 4PHP: 2022-12-20 09:14:20 [error X 5][/var/www/vhosts/werbeagentur-schneider.de/gaede.werbeagentur-schneider.de/wp-content/plugins/elementor-pro/plugin.php::350] Uncaught TypeError: Cannot access offset of type string on string in /var/www/vhosts/werbeagentur-schneider.de/gaede.werbeagentur-schneider.de/wp-content/plugins/elementor-pro/plugin.php:350
Stack trace:
#0 /var/www/vhosts/werbeagentur-schneider.de/gaede.werbeagentur-schneider.de/wp-includes/class-wp-hook.php(310): ElementorPro\Plugin->get_responsive_stylesheet_templates('/var/www/vhosts...')
#1 /var/www/vhosts/werbeagentur-schneider.de/gaede.werbeagentur-schneider.de/wp-includes/plugin.php(256): WP_Hook->apply_filters(NULL, Array)
#2 /var/www/vhosts/werbeagentur-schneider.de/gaede.werbeagentur-schneider.de/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(357): apply_filters_ref_array('elementor/core/...', Array)
#3 /var/www/vhosts/werbeagentur-schneider.de/gaede.werbeagentur-schneider.de/wp-content/plugins/elementor/core/breakpoints/manager.php(533): Elementor\Modules\DevTools\Deprecation->apply_deprecated_filter('elementor/core/...', Array, '3.2.0', 'elementor/core/...')
#4 /var/www/vhosts/werbeagentur-schneider.de/gaede.werbeagentur-schneider.de/wp-content/plugins/elementor/core/breakpoints/manager.php(420): Elementor\Core\Breakpoints\Manager::get_stylesheet_templates()
#5 /var/www/vhosts/werbeagentur-schneider.de/gaede.werbeagentur-schneider.de/wp-content/plugins/elementor/core/kits/documents/tabs/settings-layout.php(292): Elementor\Core\Breakpoints\Manager::compile_stylesheet_templates()
#6 /var/www/vhosts/werbeagentur-schneider.de/gaede.werbeagentur-schneider.de/wp-content/plugins/elementor/core/kits/documents/kit.php(98): Elementor\Core\Kits\Documents\Tabs\Settings_Layout->on_save(Array)
#7 /var/www/vhosts/werbeagentur-schneider.de/gaede.werbeagentur-schneider.de/wp-content/plugins/elementor/core/documents-manager.php(527): Elementor\Core\Kits\Documents\Kit->save(Array)
#8 [internal function]: Elementor\Core\Documents_Manager->ajax_save(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#9 /var/www/vhosts/werbeagentur-schneider.de/gaede.werbeagentur-schneider.de/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#10 /var/www/vhosts/werbeagentur-schneider.de/gaede.werbeagentur-schneider.de/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#11 /var/www/vhosts/werbeagentur-schneider.de/gaede.werbeagentur-schneider.de/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#12 /var/www/vhosts/werbeagentur-schneider.de/gaede.werbeagentur-schneider.de/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#13 /var/www/vhosts/werbeagentur-schneider.de/gaede.werbeagentur-schneider.de/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#14 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-20 09:31:00 [warning X 4][/var/www/vhosts/werbeagentur-schneider.de/gaede.werbeagentur-schneider.de/wp-content/plugins/elementor/app/modules/import-export/module.php::628] Attempt to read property "label" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-20 09:31:01 [warning X 3][/var/www/vhosts/werbeagentur-schneider.de/gaede.werbeagentur-schneider.de/wp-content/plugins/elementor/core/common/modules/ajax/module.php::172] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-21 16:25:34 [warning X 1][/var/www/vhosts/werbeagentur-schneider.de/gaede.werbeagentur-schneider.de/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::168] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Kompatibel

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @schndr-cdn! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by vladninja** [comment]
I have the same issue. Other of pagination types also not working.
The number of the pages in pagination looks OK, but there is 301 redirect when I try to change a page by the Number pagination.
Only 1 possible solution is enter 999 on "item per page" option, but if you have a lot of the data there is a huge problem

**Comment by octavian-one** [comment]
Probably related to https://github.com/elementor/elementor/issues/12126

**Comment by SeanHut42** [comment]
Having the same issue, we have had to turn off the pagination for related posts, which could be better for the client.

**Comment by Everard1** [comment]
Hi, this appears to be fixed now in the latest version of Elementor Pro.  I was using the loop grid widget and had the issue of pagination not working, just updated and now all good.  Saved me a lot of troubleshooting, haha.

**Comment by caspervoogt** [comment]
Using WordPress 6.3 and Elementor Pro 3.15.1 and I ran into this just now. Fixed it with https://stackoverflow.com/questions/63552653/fix-pagination-after-wordpress-5-5-update

**Comment by xianglinkong** [comment]
Using WordPress 6.3 and Elementor Pro 3.15.1，having the same issue, the pagination of post widget does not work, every time we click on page number or next page, it just redirect to first page again.

**Comment by caspervoogt** [comment]
Using a Posts widget on an archive can cause this. See https://github.com/elementor/elementor/issues/7613 . I fixed my issue by switching from a Posts widget to an Archive Posts widget

**Comment by Stml-St** [comment]
I think I have the same Problem. I use just the default posts-widget set to "full-content" with the pagination as "Load More" Button. When I click "Load More" in frontend, it just loads the same 8 Posts under the 8 posts that are already there? Is there any fix? Do I have to use Archive Page to use this setting? What is going wrong here?

**Comment by sf-steve** [comment]
Still present, for us it appears when we have loop grids within tabs and use load more pagination.

For now we have a fix in our codebase as follows:

```
/***
     * Fix bug with elementor loop grid within tabs, that breaks pagination via load more (click) or page refresh
     * The bug causes requests to /page-url/{pagination_no}/ to 301 back to /page-url/
     * Why exactly this fixes it is unknown, but taken from here:
     * https://stackoverflow.com/questions/63552653/fix-pagination-after-wordpress-5-5-update
     *Open Github on the issue here:
     * https://github.com/elementor/elementor/issues/21417
     */
    private function filter404PreHandler(){

        add_filter( 'pre_handle_404', function($preempt, $wp_query)
        {
            if (isset($wp_query->query['page']) && $wp_query->query['page']) {
                return true;
            }

            return $preempt;
        }, 10, 2 );
    }
```

**Comment by caspervoogt** [comment]
I am running into this again, on a Page with a Posts widget. None of the pagination options work, and when using number navigation the number links use a URL format like /my-page-slug/3/, which redirects to my home page. My August 9th 2023 solution above no longer works for me. I also tried a JS solution that replaces navigation link URLs e.g. /my-page-slug/3/ with /my-page-slug/page/3/ but that also doesn't solve it.

**Comment by trinermedia** [comment]
I have also come across this phenomenon. What irritated me was that it didn't apply to all my websites. I discovered the following connection: If you place a global widget **after** the loop grid widget or posts widget on a page that is **not** the homepage, the pagination no longer works correctly. See screen recording: [https://drive.google.com/file/d/1FAVfJP1S26FCtdWik_YXcBTh3Bbgqh_9/view?usp=sharing](https://drive.google.com/file/d/1FAVfJP1S26FCtdWik_YXcBTh3Bbgqh_9/view?usp=sharing)

I hope this helps for further debugging.

**Comment by dericlima** [comment]
I ran into this issue today and spend some time to find out this is happening for YEARS. It is very frustrating, I tried using the Archive Posts widget and nothing works. The only way I made the pagination work again was to add a JS script in the header of the page and change the pagination type to Numbers.

`<script>

jQuery(document).ready(function(){ 
    
    jQuery('a.page-numbers').each(function(index) { 
    
    var oldUrl = jQuery(this).attr('href'); 
  // alert("test: "+oldUrl);
   var patt = /\/[0-9]\//;
   var result = oldUrl.match(patt);
   var result2 = '/page' +result;
   
   url = oldUrl.replace(result, result2);


    jQuery(this).attr('href', url); }); 
    
});

</script>`

Using this script with the 'Load more' pagination doesn't work

**Comment by gwillings** [comment]
Using the "load on click" pagination there is a bug in URL calculation, which as far as I can tell is within the following:

`wp-content/plugins/elementor-pro/modules/posts/widgets/posts-base.php`

I found the following code:

```
if ( $i > 1 ) {
	if ( '' === get_option( 'permalink_structure' ) || in_array( $post->post_status, [ 'draft', 'pending' ] ) ) {
		$url = add_query_arg( $this->get_wp_pagination_query_var(), $i, $url );
	} elseif ( get_option( 'show_on_front' ) === 'page' && (int) get_option( 'page_on_front' ) === $post->ID ) {
		$url = trailingslashit( $url ) . user_trailingslashit( "$wp_rewrite->pagination_base/" . $i, 'single_paged' );
	} else {
		$url = trailingslashit( $url ) . user_trailingslashit( $i, 'single_paged' );
	}
}
```

I replaced this code with:

```
if ( $i > 1 ) {
	if ( '' === get_option( 'permalink_structure' ) || in_array( $post->post_status, [ 'draft', 'pending' ] ) ) {
		$url = add_query_arg( $this->get_wp_pagination_query_var(), $i, $url );
	} else {
		$url = trailingslashit( $url ) . user_trailingslashit( "$wp_rewrite->pagination_base/" . $i, 'single_paged' );
	}
}
```

This only seems to fix pagination using the "load more" button. 
Obviously, this will break again when we update the Elementor Pro plugin. I have not fully explored the consequences of this code change, nor fixing other pagination methods. Let me know if you'd be interested.

I also posted this here: https://github.com/elementor/elementor/issues/24973

**Comment by KingGrizzly** [comment]
Any news on this and https://github.com/elementor/elementor/issues/24973? We are seeing the load more pagination option loading in duplicates even though we have checked the option to avoid duplicates. Query is set to random and a term. There is no archive slug conflict (page slug is different than the ACF CPT slug).

**Comment by jamesturnernz** [comment]
Hi @KingYes and Team, I have a client using Elementor and have this specific issue.  It has been open for over 2 years.  Any chance it could be reviewed please?  I think it's a popular feature from what I can tell from trying to find work arounds.

Kind regards.
