### ISSUE TITLE
Motion effects, like the sticky header, are not working on the latest Google Chrome version (111.0.5563.65 Official Build 64-bit).

### ISSUE THREAD

**Issue by Colminas** [elementor/elementor#21629]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

This problem is not only occurring on the latest version of Google Chrome, but it also works only on Version 110 and below.

### Steps to reproduce

This problem is not only occurring on the latest version of Google Chrome, but it also works only on Version 110 and below.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-visaandcitizen.wpengine.com-12-03-2023.txt](https://github.com/elementor/elementor/files/10949730/system-info-visaandcitizen.wpengine.com-12-03-2023.txt)

**Comment by dlackovic2** [comment]
Already submitted multiple times.
Have you checked pinned issue? Have you searched for issue before posting? 
Please have a look at #21612 
Elementor team is working on a fix. We just need to wait a little bit more :)
As a temporary fix you can try the following:

              I concur with @KonstantinosPantalos. If you add "widescreen" as a custom breakpoint, it does fix the problem temporarily unit the folks at Elementor fix the issue. Go to Site Settings > Layout > Breakpoints, click the + sign under "Active Breakpoints" to fix the issue on Chrome.

_Originally posted by @erok415 in https://github.com/elementor/elementor/issues/21612#issuecomment-1465033672_

**Comment by avivu** [comment]
I merged this issue with #21612, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by gervy28** [comment]
I'd like to request that you reopen this, as the resolution in #21612 has not solved the problem.

**Comment by berkmh** [comment]
> I'd like to request that you reopen this, as the resolution in #21612 has not solved the problem.

+ 1 - update did not fix it for me either.

**Comment by Florian-GM** [comment]
Same issus here. Sticky not working any more.

**Comment by erok415** [comment]
Hi there,

I can confirm that updating to the latest Elementor and Elementor Pro, sticky effects will work as you expect them to work. I've tested this with Chrome (Version 111.0.5563.64 (Official Build) (x86_64)) and Safari (Version 16.2 (18614.3.7.1.5)) on a MacBook Pro. You can view our agency website here to see the sticky header working properly. 

https://mollyduggan.com

**Comment by berkmh** [comment]
hey guys i figured it out at least in my case. Im using perfmatters to remove unused CSS. Apparently before the chrome update perf was removing this file: /wp-content/plugins/elementor-pro/assets/css/widget-nav-menu.min.css  i excluded the file and now its working fine.

**Comment by gervy28** [comment]
Thanks @berkmh and I apologize to the community, I should have spent more time debugging. The I was having is around Perfmatters as well. The solution for me was to Clear Used CSS in Perfmatters > Assets, then Regenerate CSS & Data in Elementor > Tools > General, then to purge my cache.
