### ISSUE TITLE
If we move the mouse out of the top of mega menu content, the mega menu does not hide.

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#22076]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi team!

If the megamenu content is displayed and we move the mouse over it and then move the mouse away from the top of the megamenu content, the megamenu will not be hidden. **Watch the video below.**

https://user-images.githubusercontent.com/88034902/232461944-61ccb417-2f48-4ce8-9c6c-0a4c3a1bbce5.mp4

As you can see in the video above, the megamenu doesn't close when the mouse moves off the top of the megamenu content. This is a situation that often happens and many users will face it.

### Steps to reproduce

1- Add the Megamenu widget and enable dropdown content for one of the items.
2- Create mega menu content according to your taste.
3- As in the video above, hover mouse over an item that has a mega menu enabled to display the mega menu.
4- After the megamenu is displayed, move the mouse over the megamenu content.
5- Finally, remove the mouse from the top of the Megamenu content to hide the Megamenu.

**But Megamanu does not hide!**

To better understand this problem, we will see another Megamenu that does not have this problem.

https://user-images.githubusercontent.com/88034902/232464269-afe481cb-2891-4700-869c-3b2e7f8266c2.mp4

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

It cannot be useful

**Comment by BENWECHSLER** [comment]
I have the same issue. Am using Elementor Pro version 3.12.3.

**Comment by Michaelgimii** [comment]
This problem is solved in the new version.

elementor : 3.12.2
e pro : 3.12.3
hello elementor : 2.7.1

**Comment by Michaelgimii** [comment]
You should not use the hover type on touch screens. Click is the best option.

**Comment by macazaga** [comment]
> This problem is solved in the new version.
> 
> elementor : 3.12.2 e pro : 3.12.3 hello elementor : 2.7.1

Looks like it's not solved?

https://covectrstg.wpengine.com/

**Comment by 79ho3ein** [comment]
Friends, this bug has been fixed in version 3.14. (Randomly, of course, because it was not mentioned in the beta version).
Is anyone facing this bug on version 3.14?

**Comment by 79ho3ein** [comment]
Hi @macazaga,

From what I see on your website, your megamenu width appears to be "full width" and in fact the width of your current menus is controlled in inner containers. Because of this, the megamenu does not hide when you move the mouse away from the left and right side of the menu. Because the width of your megamenu is "full width". Actually, there is a full width container, but we don't see it because it has no color. **In my opinion, this is the big weakness of Megamanu widget, which does not have two important feature.**

1- Ability to control the width of mega menu for each item independently.

2- Ability to set custom width of content container(Currently, the width of the content can only be controlled in two ways: full width and fit to content).

**Comment by macazaga** [comment]
Hi @79ho3ein Thanks for your comment. So what do you suggest to make it work properly?

**Comment by macazaga** [comment]
@79ho3ein Appreciate your help!, I will try that :)

**Comment by jlemonz** [comment]
Please get this fixed.
