### ISSUE TITLE
✅ 🧩 🐞 Bug Report: Mini cart template appears as empty after updating to WooCommerce v7.8.0 - [ED-11063]

### ISSUE THREAD

**Issue by SimoPepin** [elementor/elementor#22789]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

the Elementor mini cart widget appear empty without any content. While in the editing mode, the widget displays the content correctly, but once the website is published and viewed online, the cart widget appears as a blank, white box.
The bug can be frustrating for users as they are unable to view the contents of their cart when browsing the website. This can potentially lead to a loss of sales and a poor user experience.

### Steps to reproduce

1. Edit mini cart widget in the header template works fine, all added products are visibible
2. Once you publish the page template and open the website 
3. add a product to the cart
4. click on the mini cart widget icon
5. slide coming from right is completely blank without content

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.39-42
	PHP Version: 7.4.33
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://eccellenzediluigi.eu
	Home URL: https://eccellenzediluigi.eu
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: it-IT
	Timezone: Europe/Rome
	Admin Email: [REDACTED]
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor - child
	Version: 1.0
	Author: Administrator
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.7.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: it_IT
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

== Active Plugins ==
	Childify Me
		Version: 1.2.3
		Author: Rocco Aliberti

	CookieYes | GDPR Cookie Consent
		Version: 3.0.9
		Author: CookieYes

	Elementor
		Version: 3.13.4
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.13.0
		Author: Elementor.com

	Google Listings and Ads
		Version: 2.4.10
		Author: WooCommerce

	Login/Signup Popup
		Version: 2.3
		Author: XootiX

	Product Slider and Carousel with Category for WooCommerce
		Version: 2.8
		Author: WP OnlineSupport, Essential Plugin

	ShopLentor – WooCommerce Builder for Elementor & Gutenberg
		Version: 2.6.3
		Author: HasThemes

	SiteGround Central
		Version: 3.0.1
		Author: SiteGround

	SiteGround Optimizer
		Version: 7.3.3
		Author: SiteGround

	SiteGround Security
		Version: 1.4.5
		Author: SiteGround

	WooCommerce
		Version: 7.8.0
		Author: Automattic

	WooCommerce Checkout Manager
		Version: 7.1.5
		Author: QuadLayers

	WooCommerce Payments
		Version: 6.0.0
		Author: Automattic

	WooCommerce PayPal Payments
		Version: 2.1.0
		Author: WooCommerce

	Yoast SEO
		Version: 20.9
		Author: Team Yoast


== Utilizzo degli elementi ==
	
	container : 1
		container : 5
		icon-list : 4
	footer : 3
		container : 18
		html : 1
		icon-list : 17
		image : 6
		image-carousel : 1
		text-editor : 7
		theme-site-logo : 1
	header : 9
		button : 7
		container : 21
		heading : 53
		html : 1
		image : 1
		nav-menu : 4
		search-form : 4
		theme-site-logo : 3
		woocommerce-menu-cart : 4
	page : 4
		button : 2
		container : 4
		form : 1
		heading : 1
		image : 1
		text-editor : 2
	popup : 20
		button : 2
		container : 5
		heading : 2
		text-editor : 1
	product : 1
		container : 24
		divider : 2
		heading : 4
		icon-list : 4
		image : 1
		media-carousel : 1
		nav-menu : 1
		search-form : 1
		theme-site-logo : 1
		woocommerce-menu-cart : 1
		woocommerce-product-add-to-cart : 2
		woocommerce-product-content : 1
		woocommerce-product-images : 2
		woocommerce-product-price : 2
		woocommerce-product-short-description : 2
		woocommerce-product-title : 3
	wp-page : 16
		button : 7
		container : 284
		divider : 5
		form : 3
		heading : 89
		html : 7
		icon-list : 57
		image : 3
		nested-tabs : 8
		text-editor : 27
		woocommerce-cart : 1
		woocommerce-checkout-page : 1
		woocommerce-products : 69
		woolentor-universal-product : 4
	search-results : 2
		container : 3
		heading : 2
		theme-archive-title : 1
		woocommerce-products : 1
	product-archive : 1
		container : 3
		theme-archive-title : 1
		woocommerce-products : 1


== Impostazioni ==
	
	cpt_support: post, page, e-landing-page, product
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Caratteristiche ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrazioni ==
	
	recaptcha_v3: Attiva
	woocommerce: Attiva


== Esperimenti Elementor ==
	Uscita DOM ottimizzata: Attivo per impostazione predefinita
	Caricamento delle risorse migliorato: Attivo per impostazione predefinita
	Caricamento CSS migliorato: Attivo per impostazione predefinita
	Icone dei font in linea: Attivo per impostazione predefinita
	Miglioramenti dell'accessibilità: Attivo per impostazione predefinita
	Punti di interruzione aggiuntivi: Attivo per impostazione predefinita
	admin_menu_rearrangement: Inattivo per impostazione predefinita
	Contenitore Flexbox: Attiva
	Upgrade Swiper Library: Attivo per impostazione predefinita
	Grid Container: Attiva
	Predefinito per Nuovo generatore di temi: Attivo per impostazione predefinita
	Header e Footer del tema Hello: Attivo per impostazione predefinita
	Editor Top Bar: Inattivo per impostazione predefinita
	Landing Page: Attivo per impostazione predefinita
	Nested Elements: Attiva
	Lazy Load Background Images: Inattivo per impostazione predefinita
	Transizioni pagine: Attivo per impostazione predefinita
	Notes: Attivo per impostazione predefinita
	Ciclico: Attiva
	Invii forms: Attivo per impostazione predefinita
	Snap scroll: Attivo per impostazione predefinita
	Menu: Inattivo per impostazione predefinita


== Registro ==
	
Log: showing 20 of 332023-05-29 00:16:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.3',
  'to' => '3.14.0-dev1',
)]
2023-06-06 11:03:59 [info] elementor::elementor_updater Started 
2023-06-06 11:03:59 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-06 11:03:59 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-06 11:03:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.3',
  'to' => '3.14.0-dev2',
)]
2023-06-08 19:30:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0-dev2',
  'to' => '3.14.0-dev3',
)]
2023-06-08 19:30:41 [info] elementor::elementor_updater Started 
2023-06-08 19:30:41 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-08 19:30:42 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-08 19:30:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0-dev2',
  'to' => '3.14.0-dev3',
)]
2023-06-13 00:20:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0-dev3',
  'to' => '3.14.0-dev4',
)]
2023-06-13 00:20:40 [info] elementor::elementor_updater Started 
2023-06-13 00:20:40 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-13 00:20:41 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-13 00:20:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0-dev3',
  'to' => '3.14.0-dev4',
)]
2023-06-14 12:09:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0-dev4',
  'to' => '3.14.0-dev5',
)]
2023-06-14 12:09:56 [info] elementor::elementor_updater Started 
2023-06-14 12:09:56 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-14 12:09:57 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-14 12:09:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0-dev4',
  'to' => '3.14.0-dev5',
)]

PHP: showing 7 of 7PHP: 2023-05-23 09:59:38 [notice X 1][/home/customer/www/eccellenzediluigi.eu/public_html/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-23 10:03:13 [notice X 1][/home/customer/www/eccellenzediluigi.eu/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::171] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-27 03:07:21 [error X 8][/home/customer/www/eccellenzediluigi.eu/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/products.php::336] Uncaught Error: Call to undefined function ElementorPro\Modules\Woocommerce\Widgets\wc_print_notices() in /home/customer/www/eccellenzediluigi.eu/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/products.php:336
Stack trace:
#0 /home/customer/www/eccellenzediluigi.eu/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2268): ElementorPro\Modules\Woocommerce\Widgets\Products->render()
#1 /home/customer/www/eccellenzediluigi.eu/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack->render_by_mode()
#2 /home/customer/www/eccellenzediluigi.eu/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base->render_content()
#3 /home/customer/www/eccellenzediluigi.eu/public_html/wp-content/plugins/elementor/includes/base/element-base.php(449): Elementor\Widget_Base->print_content()
#4 /home/customer/www/eccellenzediluigi.eu/public_html/wp-content/plugins/elementor/includes/base/element-ba [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-27 08:57:39 [notice X 3790][/home/customer/www/eccellenzediluigi.eu/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::381] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-30 10:52:46 [notice X 7][/home/customer/www/eccellenzediluigi.eu/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-30 10:52:46 [notice X 7][/home/customer/www/eccellenzediluigi.eu/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /home/customer/www/eccellenzediluigi.eu/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/customer/www/eccellenzediluigi.eu/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/customer/www/eccellenzediluigi.eu/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/customer/www/eccellenzediluigi.eu/public_html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-06-09 10:34:25 [notice X 1][/home/customer/www/eccellenzediluigi.eu/public_html/wp-content/plugins/elementor-pro/modules/forms/actions/mailchimp.php::345] Undefined index: email_address [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2023-05-30 14:59:03 [error X 3][https://eccellenzediluigi.eu/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.14.0-dev1:3:107472] Routes: `panel/editor/settings` not found. 
JS: 2023-06-06 11:21:29 [error X 1][https://eccellenzediluigi.eu/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.0-dev2:3:309454] Cannot read properties of undefined (reading 'id') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibilità non specificata
	ShopLentor – WooCommerce Builder for Elementor & Gutenberg: Compatibilità non specificata

== Elementor Pro - Compatibility Tag ==
	

				

````

</details>

**Comment by 319heads** [comment]
I can confirm this issue, experiencing the exact same problem here. I did a fresh install and was able to replicate. 

2 temporary solutions are to either rollback Woocommerce from 7.8.0 to 7.7.2 or switch from Hello theme to Storefront theme.

The issue looks to be with the Woocomemrce 7.8.0 update, the empty/blank mini-cart issue looks to occur when you use any other theme besides Storefront, not just Hello.

**Comment by waazaa** [comment]
sam here

**Comment by ChrisASearles** [comment]
Just for anyone else that comes across this, I confirmed with Elementor support that they are aware of the issue and it's due to a WooCommerce change in 7.8.0. Rolling WooCommerce back to 7.7.2 is a temporary fix that worked for me.

**Comment by splaquet** [comment]
i've found that the contents of the mini-cart display for me in Chrome, but not in Safari.

Safari:
<img width="1095" alt="image" src="https://github.com/elementor/elementor/assets/6146508/cd458182-b650-48c1-8aaf-4e1aabab8e90">

Chrome:
<img width="1066" alt="image" src="https://github.com/elementor/elementor/assets/6146508/405bfcf2-d6f0-45aa-b149-b36482336589">

**Comment by lankathilina** [comment]
There was some discussion on [woocommerce/woocommerce/issues/38736](https://github.com/woocommerce/woocommerce/issues/38736) and had some details for a temp fix. 

I used the below code to enqueue wc-cart-fragments, and it worked on Woo 7.8.0

`function enqueue_wc_cart_fragments() { wp_enqueue_script( 'wc-cart-fragments' ); }
add_action( 'wp_enqueue_scripts', 'enqueue_wc_cart_fragments' );`

**Comment by nicholaszein** [comment]
Hello everyone! 

Thank you for submitting your issue, and for the feedback! 🙏 

We are aware of this issue and our team is already working on a fix. We are planning on releasing this fix together with Elementor Pro v3.14.0 next week.

Meanwhile, a workaround is to either Rollback your WooCommerce version to 7.7.2, or to use the following code snippet that can be added to your `functions.php` child theme file, or use the [Code Snippets](https://wordpress.org/plugins/code-snippets/) plugin:

```php

add_action( 'wp_enqueue_scripts', 'custom_enqueue_wc_cart_fragments' );
function custom_enqueue_wc_cart_fragments() {
    wp_enqueue_script( 'wc-cart-fragments' );
}

```

Best regards

**Comment by waazaa** [comment]
> Hello everyone!
> 
> Thank you for submitting your issue, and for the feedback! 🙏
> 
> We are aware of this issue and our team is already working on a fix. We are planning on releasing this fix together with Elementor Pro v3.14.0 next week.
> 
> Meanwhile, a workaround is to either Rollback your WooCommerce version to 7.7.2, or to use the following code snippet that can be added to your `functions.php` child theme file, or use the [Code Snippets](https://wordpress.org/plugins/code-snippets/) plugin:
> 
> ```
> add_action( 'wp_enqueue_scripts', 'custom_enqueue_wc_cart_fragments' );
> function custom_enqueue_wc_cart_fragments() {
>     wp_enqueue_script( 'wc-cart-fragments' );
> }
> ```
> 
> Best regards

thanks, you are the best mate!

**Comment by mrickan** [comment]
I am having the same issue. I implemented the code snippet suggested by nicholaszein and it seems to solve the empty/blank mini cart problem.
BUT I still have the issue that when customers click on "Go to checkout" in the mini cart, they are sent to the home page and not to the checkout. 
I'd really prefer not to roll back my woo version and I can't wait until next week for the update.

Does anyone have a code snippet for this issue?

I'd really appreciate it!
Thanks!

**Comment by hekreates** [comment]
I'm going a bit crazy with this issue, I've tried rollbacks to Woocommerce version 7.7.2, also Wordpress version 6.2.1., even added the PHP code mentioned here and nothing changes. (The page now is with 7.8.0 + wordpress 6.2.2 + the PHP code added here) 

If you add a product to the cart, the page stays as it is. If you refresh after you have done so, the added products appear and you can go to the cart to checkout. 

If I deactivate the plugin that has the ajax cart, and then try to click on add to cart, it directly causes a critical error on the site. 

Is there something I am missing? https://hekreations.com/en

**Comment by Jameshallsm** [comment]
> Hello everyone!
> 
> Thank you for submitting your issue, and for the feedback! 🙏
> 
> We are aware of this issue and our team is already working on a fix. We are planning on releasing this fix together with Elementor Pro v3.14.0 next week.
> 
> Meanwhile, a workaround is to either Rollback your WooCommerce version to 7.7.2, or to use the following code snippet that can be added to your `functions.php` child theme file, or use the [Code Snippets](https://wordpress.org/plugins/code-snippets/) plugin:
> 
> ```
> add_action( 'wp_enqueue_scripts', 'custom_enqueue_wc_cart_fragments' );
> function custom_enqueue_wc_cart_fragments() {
>     wp_enqueue_script( 'wc-cart-fragments' );
> }
> ```
> 
> Best regards

It looks like this has NOT been updated on version 3.13.4 like the above comment advises. Can someone please confirm if this is the case, and if so, when may this fix be applied? Cheers

**Comment by SrGexj** [comment]
> 
Not working for me.

**Comment by eyad-alkhalidy** [comment]
I've just updated Elementor Pro to the most recent version, v3.14.0, and it works for me. The issue is fixed.

**Comment by jgigon** [comment]
> I've just updated Elementor Pro to the most recent version, v3.14.0, and it works for me. The issue is fixed.

me too !

**Comment by vandevo** [comment]
Hello, I just updated today the new version 3.14.0 - 2023-06-19, this issue is still not fixed. I am creating a support ticket now. Anyone has the same issue?

**Comment by Jameshallsm** [comment]
> Hello, I just updated today the new version 3.14.0 - 2023-06-19, this issue is still not fixed. I am creating a support ticket now. Anyone has the same issue?

Try updating Elementor Pro. The fix is applied to that plugin. :)

**Comment by vandevo** [comment]
> > Hello, I just updated today the new version 3.14.0 - 2023-06-19, this issue is still not fixed. I am creating a support ticket now. Anyone has the same issue?
> 
> Try updating Elementor Pro. The fix is applied to that plugin. :)

I already updated to Elementor Pro the new one, but it hasn't been fixed. I cached my site and stuff. The cart ajax is still shown empty. :(

**Comment by vandevo** [comment]
> Hello, I'm having the same issue. If cart is empty, product page reload, after that, I can add as many products I want and Ajax works properly. The other issue is, as people mentioned earlier, that the template not appear when you delete a product. It shows an empty one. I tried all what is posted here, but I keep with this trouble...

Have you managed to fix it with the new update? Mine still shows blank, strange.

**Comment by SrGexj** [comment]
> 

Nah it's not working. Keep showing blank for mee too.

**Comment by vandevo** [comment]
> > 
> 
> Nah it's not working. Keep showing blank for mee too.

Did you check in system info that it's the Elementor Pro 3.14.0 version?

**Comment by vandevo** [comment]
> > 
> 
> Yeah!

What's your site? Send me the link I will take a look.

**Comment by SrGexj** [comment]
> > > 
> > 
> > 
> > Yeah!
> 
> What's your site? Send me the link I will take a look.

https://vianoleo.bittacora.dev/

**Comment by eyad-alkhalidy** [comment]
Make sure to purge all cache,

> > > > 
> > > 
> > > 
> > > Yeah!
> > 
> > 
> > What's your site? Send me the link I will take a look.
> 
> https://vianoleo.bittacora.dev/tienda

I tried to add an item to the cart on your website, and it seems to be working. The cart shows the items now. It's not blank.

**Comment by SrGexj** [comment]
> 

When you delete it, template not shows anymore until you reload.

**Comment by eyad-alkhalidy** [comment]
Make sure to purge all cache, and to **Regenerate Files and Data** and **Sync Library** from Elementor Tools.

**Comment by eyad-alkhalidy** [comment]
> > 
> 
> When you delete it, template not shows anymore until you reload.

Your mini cart is working just fine for me without reloading. Which template are you talking about here?

**Comment by eyad-alkhalidy** [comment]
> 



> > > > 
> > > 
> > > 
> > > When you delete it, template not shows anymore until you reload.
> > 
> > 
> > Your mini cart is working just fine for me without reloading. Which template are you talking about here?
> 
> About empty cart template, before you add nothing. https://postimg.cc/cvjDFv2Z

I see what you mean now. When you remove the last item from the cart, the cart becomes blank instead of showing that cart/bag icon with the "cart is empty" message and the "go to shop" button underneath. You need to reload the page in order to see these. 
![Screenshot 2023-06-19 150526](https://github.com/elementor/elementor/assets/41296016/22e1b534-eb33-440b-b1d4-d3e79e447211)

Unfortunately, I have no idea about this issue.

**Comment by SrGexj** [comment]
> 

Yeah, that's my problem. Thanks for helping me too, it's ok. I'll be searching a trying something and if something become useful I'll post it. Have a nice day

**Comment by eyad-alkhalidy** [comment]
> is it just me having the issue that when clicking on "checkout" button in the minicart you don't get to the checkout? It just sends me to home page.

@mrickan 
I don't have this issue. The checkout button in the mini cart sends me to the checkout page. Tested it on my website and just now on @SrGexj's website.

**Comment by mrickan** [comment]
In contact with the support now about the checkout button issue. Hopefully they can help.
