### ISSUE TITLE
✅ 🐞 3.22.0 has removed Source Sans Pro as a font

### ISSUE THREAD

**Issue by Jowl90** [elementor/elementor#27701]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

After upgrading to Elementor 3.22.0, I noticed that Source Sans Pro font has been removed. 
Any hardcoded fonts within the webpage now have defaulted back to the theme's default (in this case Time New Roman)

### Steps to reproduce

1. Be on version 3.21.8 of Elementor
2. Go to Wordpress > Pages > Edit with Elementor
3. Go to a Text box > Set font to Source Sans Pro
4. Upgrade to Elementor 3.22.0
5. Return to page and notice that the Font field is empty. and the Live page will default to Times New Roman

### Expected behavior

Any old functionality to not be deprecated, including fonts. 
OR hardcoded fonts be updated/replaced with a similar font, such as Source Sans 3

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
Server info:		Apache/2.4.59 (Debian)
WooCommerce version:		8.9.3
PHP version:		8.1.28
Elementor Pro	 	by Elementor.com – 3.22.0
Elementor	 	by Elementor.com – 3.21.8
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by wpturnedup** [comment]
I can confirm this as well.

**Comment by toltechinternet** [comment]
I'm having this issue at the moment, however, with the recent update it has brought the Source Sans Pro font back but for some strange reason, it hasn't brought the font-weight variants from 700 - 900.

Anyone else having this issue?

**Comment by wpturnedup** [comment]
> fixed in #27715

Do you mean "will be fixed"? Because it's not fixed as of 3.22.2.

**Comment by m1ga** [comment]
no, as you can see in the PR it was merged to the main branch, not the bugfix 3.22.2 branch. So it will be in the next version. Try the beta release and check it there.

**Comment by toltechinternet** [comment]
Yep, I had a problem with Source Sans Pro. I had to change my fonts to Source Sans 3.

The Source Sans Pro completely lost the font weights on my design and it wouldn't recognise the font weights between 100-400 and 600-900.

I don't think this has been fixed yet.

**Comment by wpturnedup** [comment]
> no, as you can see in the PR it was merged to the main branch, not the bugfix 3.22.2 branch. So it will be in the next version. Try the beta release and check it there.

Confirmed - Fixed in 3.23.0 beta 1

**Comment by ghhv** [comment]
Annoying 🤬 and every page/post/component failed to use the revised global font settings and was using the global fallback.. Every little thing was requiring a manual reset.. so yes I restored to previous versions and OK...

**Comment by davelavoie** [comment]
It's still doesn't fix the issue. The page needs to be resaved in order to fix it. I've got a lot of pages using Source Sans Pro, I can't possibly update manually all of them...

Also, Source Sans Pro is not exactly the same as Source Sans 3, it's particularly the case when you're using text stroke:

With Source Sans Pro:
![image](https://github.com/elementor/elementor/assets/3408028/686a7b8c-17eb-46cf-8f4e-d936ed252e4f)

With Source Sans 3:

![image](https://github.com/elementor/elementor/assets/3408028/5a520af5-f0b5-400a-9afb-4c9d44a8fb35)

Now I would need to upload a separate Source Sans Pro font in order to prevent this issue. Can we still allow Source Sans Pro to be used directly instead of switching to Source Sans 3?

In the mean time, I'll need to revert back to a previous version of Elementor :-(

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor v3.23.0! 🥳 

The **Source Sans Pro** font is now back in the list of fonts.
A word of advice, Google has deprecated this font family. We suggest trying to switch to a similar font to avoid it breaking your styles in the future.

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
