### ISSUE TITLE
✅ 🔗 WordPress Menu appears without styles after updating to version 3.24.0 (Duplicate)

### ISSUE THREAD

**Issue by mocana** [elementor/elementor#28671]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

After updating live websites and a test development site to ELE 3.24 (pro latest update too), my website layouts completely fell apart. Even after reseting the Elementor Cache (Elementor Tools), the sites still appear broken.
![screen 2024-09-11 at 7 33 11 AM](https://github.com/user-attachments/assets/5f40d840-9450-4dae-ac56-c59b646d91ba)
![screen 2024-09-11 at 7 33 06 AM](https://github.com/user-attachments/assets/36d9c534-6d31-4080-883a-3fce7fd1f871)

### Steps to reproduce

Update Elementor and Elementor Pro

### Expected behavior

Expected current website layouts to look the same without visual changes

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Darwin
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 8.0.30
	PHP Memory Limit: 512M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	Site URL: http://npc-hello-container.local
	Home URL: http://npc-hello-container.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 256M
	Max Memory limit: 512M
	Permalink Structure: /blog/%category%/%postname%/
	Language: en_US
	Timezone: America/Denver
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.1.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

== Active Plugins ==
	Admin Columns Pro
		Version: 6.4.11
		Author: AdminColumns.com

	Advanced Custom Fields PRO
		Version: 6.3.6
		Author: WP Engine

	All-in-One WP Migration
		Version: 7.86
		Author: ServMask

	CookieYes | GDPR Cookie Consent
		Version: 3.2.6
		Author: CookieYes

	Dashboard Welcome for Elementor
		Version: 1.0.8
		Author: IdeaBox Creations

	Elementor
		Version: 3.23.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.23.2
		Author: Elementor.com

	Gravity Forms
		Version: 2.8.17
		Author: Gravity Forms

	Imagify
		Version: 2.2.2
		Author: Imagify – Optimize Images & Convert WebP & Avif

	My Templates Thumbnails for Elementor
		Version: 1.0.0
		Author: Abangani Media

	One Click Accessibility
		Version: 2.1.0
		Author: One Click Accessibility

	Post Types Order
		Version: 2.2.6
		Author: Nsp Code

	Rank Math SEO
		Version: 1.0.227.1
		Author: Rank Math

	WooCommerce
		Version: 9.2.3
		Author: Automattic

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast


== Elements Usage ==
	
	archive : 2
		container : 2
		divider : 1
		heading : 1
		loop-grid : 1
		text-editor : 1
	container : 6
		button : 3
		container : 10
		copyright : 1
		heading : 3
		icon : 3
		icon-box : 1
		icon-list : 1
		image : 2
		nav-menu : 1
		npc-siteby : 1
		spacer : 1
		template : 1
		text-editor : 1
		woocommerce-menu-cart : 1
	page : 8
		ColorSwatch : 1
		ELETemplateGallery : 1
		accordion : 1
		button : 22
		call-to-action : 1
		container : 211
		countdown : 1
		counter : 1
		flip-box : 1
		gallery : 2
		heading : 172
		html : 3
		icon : 4
		icon-box : 6
		icon-list : 6
		image : 30
		image-box : 11
		image-carousel : 2
		login : 1
		nested-accordion : 1
		price-list : 1
		price-table : 1
		progress : 1
		progress-tracker : 2
		spacer : 9
		table-of-contents : 1
		tabs : 1
		testimonial : 1
		text-editor : 42
		toggle : 1
	popup : 1
		container : 1
		html : 1
		shortcode : 1
	product : 1
		container : 6
		divider : 1
		heading : 3
		woocommerce-product-add-to-cart : 1
		woocommerce-product-data-tabs : 1
		woocommerce-product-images : 1
		woocommerce-product-meta : 1
		woocommerce-product-price : 1
		woocommerce-product-rating : 1
		woocommerce-product-related : 1
		woocommerce-product-short-description : 1
		woocommerce-product-stock : 1
		woocommerce-product-upsell : 1
	section : 2
		button : 1
		container : 5
		heading : 3
		price-list : 1
		text-editor : 1
	wp-post : 1
		container : 10
		heading : 2
		image : 2
		loop-grid : 1
		template : 4
		text-editor : 1
	wp-page : 17
		QuickMenuNav : 2
		button : 16
		container : 65
		divider : 5
		dualheadline : 1
		heading : 74
		icon-box : 3
		icon-list : 6
		image : 12
		image-box : 14
		imageseparator : 1
		loop-carousel : 1
		loop-grid : 4
		press-widget : 1
		shortcode : 1
		sitemap : 1
		template : 5
		text-editor : 57
		woocommerce-cart : 1
		woocommerce-checkout-page : 1
		woocommerce-my-account : 1
	single-post : 5
		button : 1
		container : 19
		divider : 2
		heading : 8
		icon-box : 3
		image : 2
		loop-carousel : 1
		loop-grid : 1
		post-info : 1
		share-buttons : 1
		text-editor : 3
		theme-post-content : 2
		theme-post-title : 1
	single-page : 1
		container : 2
		template : 1
		theme-post-content : 1
	search-results : 1
		container : 2
		divider : 1
		loop-grid : 1
		theme-archive-title : 1
	loop-item : 8
		button : 5
		container : 13
		heading : 10
		icon-box : 1
		image : 5
		post-info : 1
		postexcerptnpc : 2
		text-editor : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-price : 1
	error-404 : 1
		container : 3
		heading : 2


== Settings ==
	
	cpt_support: post, page, ajax
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap
	disabled_elements: AjaxLoader, antispam, stripe-button, paypal-button, code-highlight, lottie, facebook-button, facebook-comments, facebook-embed, reviews, animated-headline, hotspot, dyncontel-readmore, dce-dynamicposts-v2, dyncontel-acf-relation, dyncontel-acfgallery, text-path, wp-widget-woocommerce_rating_filter, wp-widget-woocommerce_recent_reviews, wp-widget-woocommerce_top_rated_products, wp-widget-woocommerce_recently_viewed_products, wp-widget-woocommerce_products, wp-widget-woocommerce_product_tag_cloud, wp-widget-woocommerce_product_search, wp-widget-woocommerce_product_categories, wp-widget-woocommerce_price_filter, wp-widget-woocommerce_layered_nav_filters, wp-widget-woocommerce_layered_nav, wp-widget-gform_widget, wp-widget-block, wp-widget-woocommerce_widget_cart, wp-widget-custom_html, wp-widget-tag_cloud, wp-widget-rss, wp-widget-recent-comments, wp-widget-recent-posts, wp-widget-categories, wp-widget-text, wp-widget-search, wp-widget-meta, wp-widget-media_video, wp-widget-media_gallery, wp-widget-media_image, wp-widget-media_audio, wp-widget-archives, wp-widget-calendar, wp-widget-pages, rating, sidebar, audio, alert, facebook-page, woocommerce-purchase-summary, woocommerce-breadcrumb, post-comments, author-box, testimonial-carousel, media-carousel, slides, portfolio, theme-post-featured-image, theme-post-excerpt, theme-page-title, theme-site-title, inner-section, form, blockquote, theme-site-logo


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active by default
	Flexbox Container: Active
	Grid Container: Inactive
	Upgrade Swiper Library: Active
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Inactive
	Header & Footer: Inactive
	Elementor Home Screen: Active by default
	Editor Top Bar: Inactive
	Build with AI: Inactive
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Inactive
	Element Caching: Active
	Link In Bio: Inactive by default
	Floating Buttons: Inactive by default
	Elementor Editor Events: Inactive by default
	Display Conditions: Active
	Form Submissions: Active
	Menu: Active
	Taxonomy Filter: Active
	Search: Inactive by default


== Log ==
	
Log: showing 20 of 322024-09-06 20:43:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '3.0.10',
  'to' => '3.0.15',
)]
2024-09-06 20:43:30 [info] elementor::elementor_updater Started 
2024-09-06 20:43:30 [info] Elementor/Upgrades - _on_each_version Start  
2024-09-06 20:43:30 [info] Elementor/Upgrades - _on_each_version Finished 
2024-09-06 20:43:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.3',
  'to' => '3.23.4',
)]
2024-09-06 20:46:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]
2024-09-06 20:46:24 [info] elementor-pro::elementor_pro_updater Started 
2024-09-06 20:46:24 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-09-06 20:46:24 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-09-06 20:46:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]
2024-09-11 07:31:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.4',
  'to' => '3.24.0',
)]
2024-09-11 07:31:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.3',
  'to' => '3.24.0',
)]
2024-09-11 07:31:05 [info] elementor::elementor_updater Started 
2024-09-11 07:31:05 [info] Elementor/Upgrades - _on_each_version Start  
2024-09-11 07:31:05 [info] Elementor/Upgrades - _on_each_version Finished 
2024-09-11 07:31:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.4',
  'to' => '3.24.0',
)]
2024-09-11 07:31:05 [info] elementor-pro::elementor_pro_updater Started 
2024-09-11 07:31:05 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-09-11 07:31:05 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-09-11 07:31:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.3',
  'to' => '3.24.0',
)]

PHP: showing 5 of 5PHP: 2024-09-06 20:51:02 [warning X 9][../wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php::50] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-09-06 21:53:05 [warning X 48][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-09-06 21:53:22 [warning X 4][../wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-09-06 22:14:53 [warning X 6][../wp-content/plugins/elementor/includes/template-library/sources/local.php::669] Attempt to read property "display_name" on bool [array (
  'trace' => '
#0: ../wp-content/plugins/elementor/includes/template-library/sources/local.php(669): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ../wp-content/plugins/elementor/includes/template-library/sources/local.php(472): Elementor\TemplateLibrary\Source_Local -> get_item()
#2: ../wp-content/plugins/elementor/includes/template-library/manager.php(201): Elementor\TemplateLibrary\Source_Local -> get_items()
#3: ../wp-content/plugins/elementor/includes/template-library/manager.php(233): Elementor\TemplateLibrary\Manager -> get_templates()
#4: ../wp-content/plugins/elementor/includes/template-library/data/endpoints/templates.php(51): Elementor\TemplateLibrary\Manager -> get_library_data()
',
)]
PHP: 2024-09-06 23:03:09 [warning X 8][../wp-content/plugins/elementor/includes/template-library/sources/local.php::669] Attempt to read property "display_name" on bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2024-09-07 03:43:00 [error X 2][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.4:3:832463] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2024-09-07 04:00:02 [error X 4][../wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,utils,wp-hooks&ver=6.6.1:2:28760] Cannot read properties of undefined (reading 'value') 
JS: 2024-09-07 04:15:20 [error X 47][../wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.23.4:3:16087] Cannot read properties of undefined (reading 'global') 
JS: 2024-09-07 04:41:42 [error X 2][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.4:3:588967] Failed to read a named property 'elementorFrontend' from 'Window': Blocked a frame with origin ".." from accessing a cross-origin frame. 
JS: 2024-09-07 05:18:11 [error X 40][../wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.23.3:2:21897] this.$element.sticky is not a function 



== Elementor - Compatibility Tag ==
	
	Dashboard Welcome for Elementor: Compatibility not specified
	Elementor Pro: Incompatible
	My Templates Thumbnails for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by Fyang0219** [comment]
getting a similiar behaviour with broken UI after updating 3.24.
I've got error in console and system info

`Uncaught TypeError: elementorFrontend.waypoint is not a function`

system info:

`JS: 2024-09-10 16:41:24 [error X 139][https://vsconsultinggroup.ca/_static/??-eJydUttOwzAM/SGyiElje0F8CnITk6ZL4mAnVNvXE4qAIbV07CWSnXOxjj1mZSgVTEXnUJ1PogcsGcxRR7I1oOgxO6aeNoPcjVn5ZEK1rT2I7ukN2U9sNcgm+jQDAtv6qgO++F+yfG5E3VUfrBYD6YerEhVvcEai9BibEYTgIZ01iGCZfNv4yMmf+VqCNIfjad0CQytTIf4gOYE8PbfwxDCFUNg7h3PxXCtAnzneomCiqGn8a1OFf3l8F8pUKRQX9j8SGYoR2eDlQqi2RteIyL+KPy5pXumFJ5jVxO0oFJSWeVeLp7RwtMNrRT7p6rUhxlVQpCrrKMvgHHThC/kUH+/32932sH/YHd4B5UhY1Q==:1635:39] elementorFrontend.waypoint is not a function. (In 'elementorFrontend.waypoint($scope.find('.cms-lazy'), function() { // remove css class $(this).removeClass('lazy-loading').addClass('cms-lazy-loaded'); // add style var duration = $(this).data('duration'); if(typeof duration != 'undefined'){ $(this).css({'animation-duration': duration+'ms'}); } }, { //offset: 'top-in-view' })', 'elementorFrontend.waypoint' is undefined) 
JS: 2024-09-11 17:52:55 [error X 1176][https://vsconsultinggroup.ca/_static/??-eJydUttOwzAM/SGyiElje0F8CnITk6ZL4mAnVNvXE4qAIbV07CWSnXOxjj1mZSgVTEXnUJ1PogcsGcxRR7I1oOgxO6aeNoPcjVn5ZEK1rT2I7ukN2U9sNcgm+jQDAtv6qgO++F+yfG5E3VUfrBYD6YerEhVvcEai9BibEYTgIZ01iGCZfNv4yMmf+VqCNIfjad0CQytTIf4gOYE8PbfwxDCFUNg7h3PxXCtAnzneomCiqGn8a1OFf3l8F8pUKRQX9j8SGYoR2eDlQqi2RteIyL+KPy5pXumFJ5jVxO0oFJSWeVeLp7RwtMNrRT7p6rUhxlVQpCrrKMvgHHThC/kUH+/32932sH/YHd4B5UhY1Q==:1635:31] elementorFrontend.waypoint is not a function `

**Comment by neatdisorder** [comment]
Hi! I'm experiencing a similar issue but just on the theme builder, on pages which are made entirely of custom widgets using corrrectly "get_style_depends()" as per the new documentation: https://developers.elementor.com/elementor-3-24-developers-update/

On the console I have the following error:

Uncaught TypeError: e.O is not a function

Happening at frontend.min.js, which seems to have been affected as well.

**Comment by mocana** [comment]
Interesting. I'm having this issue on sites that are not using any custom widget's or 3rd-party add-ons though.

**Comment by nicholaszein** [comment]
Hi @mocana!

Thank you for submitting your issue! 🙏 

There are multiple reports similar to yours, and all of them have something in common: Server Cache. In your System Info I see you shared a copy of your staging site. Please, if you have server cache on your production site, you need to purge and clear all. If you make use of performance optimization plugins, clear and purge their cache as well. The same if you make use of a CDN.

The way Elementor loads styles has changed, and it's empirical to purge and clear all levels of cache. It's also important to make sure your add-ons are compatible with the new version. They may break your website's layout if they aren't compatible.

Please, if you haven't already, try again and let me know.

Kind regards

**Comment by nicholaszein** [comment]
Hi @Fyang0219, 

your issue is caused by an incompatible addon. If you have addons installed, make sure they are compatible with Elementor version 3.24.0.

**Comment by nicholaszein** [comment]
Hello, @neatdisorder!

The error in the console you're reporting is caused by the Site Settings Style Guide, and does not affect the functionality or performance of Elementor. You can ignore it for now. We are aware of this error, and we will be working on a fix soon.

You can follow this issue for more info: #24492

**Comment by mocana** [comment]
@nicholaszein thank you for your reply and clarity. Yes I did send my staging server because I wanted to test the update locally and try to troubleshoot. What's odd is there is no server caching on that site and I have tools like WP Rocket deactivated.

I do have custom widget's i've created but none require any external stylesheets or javascript—would that mean that I still need to declare dependencies even if they don't use any third party libraries?

**Comment by mocana** [comment]
**Update** - I think I may have found my issue for my theme builds. I use a tool that gathers all the posts of content to build out a "status" menu, kind of like a sitemap. ELE 3.24 added a new post type called `e-floating-buttons` which is empty until you create one and I think that was throwing off my loops and crashing them.

**Comment by nicholaszein** [comment]
Hi @mocana!

If your widget has styles, it would be wise (and beneficial) to follow the instructions in [this article](https://developers.elementor.com/elementor-3-24-developers-update/). If not, you don't need to do anything.

As for not having cache, that's really odd. Could you try something? After updating, go to your header template, edit something and then save it. Let me know if this fixes the issue with the menu for you.

About the floating buttons, try flushing your permalinks:
> Go to your WordPress **`Dashboard`** > **`Settings`** > **`Permalinks`** and click on **`Save Changes`** twice without changing any settings. This should flush the permalinks and fix that issue with the Loop Grid.

Let me know about the menu! 🙏

**Comment by mocana** [comment]
@nicholaszein thank you for these tips! 

Yeah the menu updates didi work well. I think the issues are resolved on my end and were indeed due to having a new post type that hadn't had any posts yet (the floating buttons) and that's what was crashing my theme.

Thank you for the link again to your article, I'll continue to read and make sure there isn't anything else I can work on for updates to my custom widgets/controls.

**Comment by mcrowell** [comment]
Do you happen to have a Lottie widget on the page? I'm finding out that the Lottie widget in 3.24 is breaking my pages.

**Comment by mapsmarketing** [comment]
> Hi! I'm experiencing a similar issue but just on the Theme Builder, on pages which are made entirely of custom widgets using corrrectly "get_style_depends()" as per the new documentation: https://developers.elementor.com/elementor-3-24-developers-update/
> 
> On the console I have the following error:
> 
> Uncaught TypeError: e.O is not a function
> 
> Happening at frontend.min.js, which seems to have been affected as well.
> 
> I have tried clearing all caches, without success. I've also regenerated files and css and synced library, but it didn't work either.

@nicholaszein 

I get the same error as above for a few websites which uses Motion Effects on containers. If I go into Elementor > Tools and run "Regenerate CSS & Data" and "Sync Library" the issue vanishes for one load of the page. If I reload the same page again, the error above persists. This only happens when you are logged in as well while the pages are loading normally when viewed from Incognito (Chrome) or when editing the page with Elementor.

Thankfully I only had updated 3 websites to the latest Elementor as the issues were consistent for all 3 websites.

**Comment by quintonv** [comment]
Roll back your elementor version to before 3.24.0, it solves it for now. Hopefully the developers will acknowledge this bug and fix it soon. There's a few other issues that are similar from what I've seen.

Multiple of my sites are showing the same behavior as your screenshot. Headers are just suddenly broken

**Comment by carlos-blazquez-global** [comment]
Hi.

As I commented in this thread:

https://wordpress.org/support/topic/header-problem-53/#post-18012360

I think the problem is the “search form” widget, replaced without contiunity solution by a plain “search” widget. So wherever you have an Elementor “search form” widget you will have a problem.

Hope this helps.

**Comment by pumadog** [comment]
Same here on several sites. Had to roll back to 3.23.

**Comment by incircolo** [comment]
I have the same issues (and no, it's not cache related). 
I have fix it adding a colour declaration in styles (where there is no colour declaration, the issue appear) for text and background colour in dropdown styles (with default one it works before the upgrade).

**Comment by nicholaszein** [comment]
Hey everyone!

We have great news! 💪  

### 📢 We're happy to announce that we just released a new patch for Elementor Core that solves this issue! 🥳 

Make sure to update Elementor Core and Pro to their latest versions. At the moment of writing that would be: **Elementor Core v3.24.2 Pro v3.24.1.** 

If you experience any issues or have feedback, please reach out, your input is crucial to us improving.

We deeply appreciate your support and feedback. Your trust is important to us, and we’re committed to learning from this experience to ensure every next release is a better one. 

🙏 Thank You

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)
>
> _Follow our Status page to be among the first to know about any incident:_
> [Elementor Status](https://elemn.to/status)

Cheers 🥂

**Comment by Julie900** [comment]
However, this did not solve my issue which is the opposite of the above.  My header is not displaying on any of the pages on the back end of my site, and the product photos are not displaying on the individual product pages on the back end.  The front end looks fine in both cases. https://redbridgequilts.com

**Comment by nicholaszein** [comment]
Hi @Julie900!

Thank you for your feedback!

I took a look at your website, and it seems indeed that everything is running as expected in the frontend. However, I did notice that you make use of several Elementor Addons, such as **Essential Addons**, **Vamtam Elementor** (Theme addon), and **Woolentor**. Before updating, did you check if these plugins were compatible with the latest version of Elementor? Maybe they aren't compatible yet, and this is why you're experiencing these problems. 

Another alternative is the possibility of WP Rocket caching your WP Admin pages. In the WP Rocket settings did you enable the option to cache pages for logged-in users? If you did, it might also be the root of your issue.

In both cases a good way to troubleshoot this is to try to temporarily deactivate these plugins, then purging the WP Rocket cache and deactivating it. 

If after following these steps and also clearing your browser cache, you're still experiencing this issue, then, please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Kind regards

**Comment by Julie900** [comment]
Hello,

I followed your instructions, and it appears the problem might be with the
theme plugin, Vantam Elementor Integration (Debebe).  If I deactivate that
plugin, then all looks good on the back end.

The last theme update was on 26/8/24 to v. 6.3.  I'm not sure I understand
why on the plugins page the Vantam Debebe plugin says v. 1.0.16.  I updated
Elementor and Elementor Pro to v. 3.24 on 10/9/24.  I am on my site every
day checking for updates, etc., but I didn't notice the issue until
12/9/24.  I know everything was okay before then.  There had been an issue
with the new feature "Quick View".  It was not displaying correctly on the
mobile version.  Support from Has Themes intervened on 12/9/24 to fix that
issue, and it was right after that that I noticed this current problem.  I
am not saying that Has Themes had anything to do with it though.

I would appreciate  any suggestions on how to resolve this issue.

Thank you very much.

Kind regards,
Julie

**Comment by brightlybiz** [comment]
Thanks, Nicholas. I will try this tomorrow and let you know the results

**Comment by nicholaszein** [comment]
@Julie900 thats a progress. You now narrowed down to the root cause of your issue.

I would suggest you reach out to your theme support and let them know what is happening. It most likely is a conflict with the new version of Elementor. They will have to patch the problem. In this case it would be prudent to rollback Elementor to the previous stable version (3.23.X, where X is the latest patch number) until they fix the issue (do this only after you have talked to them). You can follow the instructions in this article: https://elementor.com/help/rolling-back-to-a-previous-version-of-elementor/

I am closing this issue as it's clear its not an Elementor bug. But I'll leave comments open for a while.

Best regards

**Comment by Julie900** [comment]
Thank you very much for your help, Nicholas. I will do as you suggest. Kind regards,JulieOn 14 Sep 2024, at 03:20, Nicholas Zein ***@***.***> wrote:﻿
@Julie900 thats a progress. You now narrowed down to the root cause of your issue.
I would suggest you reach out to your theme support and let them know what is happening. It most likely is a conflict with the new version of Elementor. They will have to patch the problem. In this case it would be prudent to rollback Elementor to the previous stable version (3.23.X, where X is the latest patch number) until they fix the issue (do this only after you have talked to them). You can follow the instructions in this article: https://elementor.com/help/rolling-back-to-a-previous-version-of-elementor/
I am closing this issue as it's clear its not an Elementor bug. But I'll leave comments open for a while.
Best regards
