### ISSUE TITLE
Pagination dots in Loop Carousel have wrong position with active Optimized Control Loading

### ISSUE THREAD

**Issue by pumadog** [elementor/elementor#28811]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I can't set my pagination icons of the loop carousel to custom position left if Optimized Control Loading is active. The editor shows the wanted position, but the frontend shows them always in the center. Deactivating Optimized Control Loading fixes the issue.

### Steps to reproduce

1. Set up loop carousel
2. Set pagination dots to custom position left/middle/right
3. Toggle Optimized Control Loading experiment on/off

### Expected behavior

Render pagination icons in frontend as in the editor.
<img width="1463" alt="Bildschirmfoto 2024-09-24 um 17 31 46" src="https://github.com/user-attachments/assets/494bdae8-14f2-44c5-b380-aaec4901571b">
<img width="1466" alt="Bildschirmfoto 2024-09-24 um 17 32 23" src="https://github.com/user-attachments/assets/c5233cc9-1f90-41ae-b5c7-463d746355a3">
<img width="1472" alt="Bildschirmfoto 2024-09-24 um 17 34 38" src="https://github.com/user-attachments/assets/b1918669-8120-453b-92e0-c5d3de12eca7">

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.11.7-MariaDB-log
	PHP Version: 8.2.23
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	WP Multisite: Yes
	Max Upload Size: 1 MB
	Memory limit: 64M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%postname%/
	Language: de_DE
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.1.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de-DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15

== Network Plugins ==
	Advanced Custom Fields
		Version: 6.3.6
		Author: WP Engine

	Elementor
		Version: 3.24.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.24.2
		Author: Elementor.com

	NS Cloner - Site Copier
		Version: 4.4.7.2
		Author: Never Settle

	Premium Addons for Elementor
		Version: 4.10.52
		Author: Leap13

	WP-Sweep
		Version: 1.1.8
		Author: Lester 'GaMerZ' Chan


== Elemente Verwendung ==
	
	archive : 1
		container : 4
		loop-grid : 1
		taxonomy-filter : 1
		theme-archive-title : 1
	container : 3
		button : 2
		container : 11
		gallery : 1
		heading : 4
		image : 1
		loop-grid : 2
		nav-menu : 1
		search : 1
	footer : 1
		container : 6
		heading : 3
		nav-menu : 1
		text-editor : 3
	header : 2
		container : 20
		heading : 8
		html : 1
		icon : 1
		icon-box : 1
		image : 2
		nav-menu : 9
		nested-accordion : 1
		off-canvas : 1
		search : 3
	wp-page : 5
		button : 4
		container : 60
		gallery : 1
		heading : 15
		image : 6
		loop-carousel : 1
		loop-grid : 5
		nested-accordion : 3
		taxonomy-filter : 2
		text-editor : 23
		theme-post-title : 2
		video : 2
	single-post : 2
		button : 2
		container : 14
		theme-post-content : 2
		theme-post-title : 2
	single-page : 4
		container : 9
		theme-post-content : 4
		theme-post-title : 2
	search-results : 1
		container : 4
		loop-grid : 1
		taxonomy-filter : 1
		theme-archive-title : 1
	loop-item : 8
		container : 14
		post-info : 1
		theme-post-excerpt : 3
		theme-post-featured-image : 2
		theme-post-title : 8


== Einstellungen ==
	
	cpt_support: post, page
	allow_tracking: yes
	unfiltered_files_upload: 1


== Eigenschaften ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	


== Elementor-Experimente ==
	Verbessertes Laden von CSS: Standardmäßig deaktiviert
	Inline-Schriftarten-Symbole: Aktiv
	Additional Custom Breakpoints: Standardmäßig aktiviert
	Flexbox Container: Standardmäßig aktiviert
	Grid Container: Standardmäßig aktiviert
	Upgrade Swiper Library: Standardmäßig aktiviert
	Nested Elements Performance: Standardmäßig aktiviert
	Optimized Control Loading: Inaktiv
	Optimized Markup: Standardmäßig deaktiviert
	Conditionally load Swiper CSS files: Standardmäßig deaktiviert
	Plugin Onboarding: Standardmäßig aktiviert
	Default to New Theme Builder: Standardmäßig aktiviert
	Header und Footer: Standardmäßig aktiviert
	Elementor Home Screen: Standardmäßig aktiviert
	Build with AI: Standardmäßig aktiviert
	Startseiten: Standardmäßig deaktiviert
	Launchpad Checklist: Standardmäßig deaktiviert
	Nested Elements: Aktiv
	Editor Top Bar: Standardmäßig aktiviert
	Seiten Panel: Standardmäßig deaktiviert
	Element Caching: Standardmäßig aktiviert
	Link In Bio: Standardmäßig aktiviert
	Floating Buttons: Standardmäßig aktiviert
	Elementor Editor Events: Standardmäßig deaktiviert
	Atomic Widgets: Standardmäßig deaktiviert
	Bedingungen anzeigen: Standardmäßig aktiviert
	Form Submissions: Standardmäßig aktiviert
	Menü: Aktiv


== Protokoll ==
	
Log: showing 20 of 202024-08-21 15:37:54 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.1',
  'to' => '3.23.3',
)]
2024-08-21 15:37:55 [info] elementor-pro::elementor_pro_updater Started 
2024-08-21 15:37:55 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-08-21 15:37:55 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-08-21 15:37:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.1',
  'to' => '3.23.3',
)]
2024-09-19 17:37:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.4',
  'to' => '3.24.3',
)]
2024-09-19 17:37:37 [info] elementor-pro::elementor_pro_updater Started 
2024-09-19 17:37:37 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-09-19 17:37:37 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-09-19 17:37:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.3',
  'to' => '3.24.2',
)]
2024-09-19 17:37:37 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.3',
  'to' => '3.24.2',
)]
2024-09-19 17:37:37 [info] elementor::elementor_updater Started 
2024-09-19 17:37:37 [info] Elementor/Upgrades - _on_each_version Start  
2024-09-19 17:37:37 [info] Elementor/Upgrades - _on_each_version Finished 
2024-09-19 17:37:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.4',
  'to' => '3.24.3',
)]
2024-09-24 16:29:35 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.3',
  'to' => '3.24.4',
)]
2024-09-24 16:29:35 [info] elementor::elementor_updater Started 
2024-09-24 16:29:35 [info] Elementor/Upgrades - _on_each_version Start  
2024-09-24 16:29:36 [info] Elementor/Upgrades - _on_each_version Finished 
2024-09-24 16:29:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.3',
  'to' => '3.24.4',
)]

PHP: showing 6 of 6PHP: 2024-08-21 16:35:32 [warning X 39][/homepages/43/d267719704/htdocs/test/berufskolleg/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-22 17:18:03 [warning X 174][/homepages/43/d267719704/htdocs/test/berufskolleg/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /homepages/43/d267719704/htdocs/test/berufskolleg/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /homepages/43/d267719704/htdocs/test/berufskolleg/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /homepages/43/d267719704/htdocs/test/berufskolleg/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /homepages/43/d267719704/htdocs/test/berufskolleg/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-08-26 16:03:48 [notice X 110][/homepages/43/d267719704/htdocs/test/berufskolleg/wp-content/plugins/elementor/includes/base/controls-stack.php::229] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-27 13:05:27 [warning X 38][/homepages/43/d267719704/htdocs/test/berufskolleg/wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-manager.php::150] Undefined array key "logicalJoin" [array (
  'trace' => '
#0: /homepages/43/d267719704/htdocs/test/berufskolleg/wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-manager.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /homepages/43/d267719704/htdocs/test/berufskolleg/wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-query-builder.php(33): ElementorPro\Modules\LoopFilter\Query\Taxonomy_Manager -> get_hierarchy_of_selected_terms()
#2: /homepages/43/d267719704/htdocs/test/berufskolleg/wp-content/plugins/elementor-pro/modules/loop-filter/module.php(124): ElementorPro\Modules\LoopFilter\Query\Taxonomy_Query_Builder -> get_merged_queries()
#3: /homepages/43/d267719704/htdocs/test/berufskolleg/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\LoopFilter\Module -> filter_loop_query()
#4: /homepages/43/d267719704/htdocs/test/berufskolleg/wp-includes/plugin.php(205): WP_Hook -> apply_filters()
',
)]
PHP: 2024-09-03 12:20:09 [warning X 2][/homepages/43/d267719704/htdocs/test/berufskolleg/wp-content/plugins/elementor/includes/elements/container.php::1835] Undefined array key "size" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-09-03 14:41:03 [warning X 1][/homepages/43/d267719704/htdocs/test/berufskolleg/wp-content/plugins/elementor/core/logger/items/js.php::17] Undefined array key "url" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 8 of 8JS: 2024-08-22 10:42:34 [error X 8][https://test.k-konzept.de/berufskolleg/design-a/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.4:3:1265356] null is not an object (evaluating '$.getBoundingClientRect') 
JS: 2024-08-23 13:11:03 [error X 1][https://test.k-konzept.de/berufskolleg/design-a/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.4:3:54582] undefined is not an object (evaluating 'V.activate') 
JS: 2024-08-26 11:18:20 [error X 1][https://test.k-konzept.de/berufskolleg/design-a/wp-content/plugins/elementor-pro/assets/js/gallery.8ca9a354ce039d1ba641.bundle.min.js:2:5673] undefined is not an object (evaluating 'this.gallery.setSettings') 
JS: 2024-08-28 06:47:12 [error X 3][https://test.k-konzept.de/berufskolleg/design-a/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:20082] View (cid: "view68") has already been destroyed and cannot be used. 
JS: 2024-08-28 12:10:40 [error X 1][https://test.k-konzept.de/berufskolleg/design-a/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:20082] View (cid: "view46131") has already been destroyed and cannot be used. 
JS: 2024-08-28 12:11:36 [error X 5][https://test.k-konzept.de/berufskolleg/design-a/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.4:3:663450] undefined is not an object (evaluating 'this.view.container.isDesignable') 
JS: 2024-09-03 11:38:58 [error X 388][https://test.k-konzept.de/berufskolleg/design-a/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:17922] null is not an object (evaluating 'this.getColorRepresentation().toLowerCase') 
JS: 2024-09-03 13:22:07 [error X 1][https://test.k-konzept.de/berufskolleg/design-a/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:20082] View (cid: "view6112") has already been destroyed and cannot be used. 



== Elementor - Compatibility Tag ==
	


== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by steveindzine** [comment]
I just came here to report the same issue. My clients site uses them all over the place and it looks very odd! This is the site: https://newburyracecourse.co.uk/racing/

**Comment by thomas-doppeln** [comment]
I am facing the same issue on a lot of our clients sites.
Setting the custom css of the loop carousel to this fixes it temporarily:
`selector .swiper-pagination-bullets {
left: calc(var(--dots-horizontal-position) + var(--dots-horizontal-offset))!important;
}`

**Comment by jamieburchell** [comment]
Same issue here. Dots now appear aligned to the left instead of centre like they were before. There is a new toggle for custom position of the dots and enabling this and setting the dots to centred doesn't work on the front end either. @nicholaszein

**Comment by pumadog** [comment]
> I am facing the same issue on a lot of our clients sites. Setting the custom css of the loop carousel to this fixes it temporarily: `selector .swiper-pagination-bullets { left: calc(var(--dots-horizontal-position) + var(--dots-horizontal-offset))!important; }`

Hmm, the code does nothing here. https://test.k-konzept.de/berufskolleg/design-a2/

**Comment by jamieburchell** [comment]
> Hmm, the code does nothing here. https://test.k-konzept.de/berufskolleg/design-a2/

It's giving you a horizontal scrollbar. Try the `transform: none !important;`. You may need to adjust bottom/top though.

**Comment by pumadog** [comment]
> Edit: Your dots already appear centralised to me without the `transform` rule.

The dots were supposed to be left, centralised was the error.

But it seems to be fixed with the latest update. I removed the code. Can anyone confirm?

**Comment by dev12-byte** [comment]
+1
That is definitely a bug with the loop carousel element. I am using a few of these across my site and all of them suddenly broke after an update. The biggest issue is that the custom position values you can set have NO effect at all. I can't even move the dots using custom positioning because the slider has no effect. 

This needs to be fixed ASAP.

**Comment by pumadog** [comment]
Did you install the latest updates? Seems to be fixed for me with Ele 3.24.6/pro 3.24.4.

**Comment by dev12-byte** [comment]
Sadly not, I am on the latest versions but I can still not change the positioning of the pagination and navigation arrows. Interestingly I can move them in one direction (Either horizontal or vertical).

**Comment by thomas-doppeln** [comment]
I updated, but the issue still persists for my site.

**Comment by marowi85** [comment]
Same on my sites. Looks still broken after the update to 3.24.6

**Comment by webagens** [comment]
Same issue on my website

**Comment by webagens** [comment]
> Setting the custom css of the loop carousel to this fixes it temporarily: `selector .swiper-pagination-bullets { left: calc(var(--dots-horizontal-position) + var(--dots-horizontal-offset))!important; }`

Same issue on my website: looking good in the preview, but not on the published page. This code solves it temporarily.

**Comment by dev12-byte** [comment]
@nicholaszein:
To put my last comment into perspective: https://github.com/elementor/elementor/issues/29092#issuecomment-2444660161

For the last few releases now the pagination and navigation of loop carousel is completely broken. 

In my case the default position is wrong (similar to the images above) and at the same time the custom position parameters (x,y position) is not working. You can set the position using the slider but nothing happens with the element. 

Take a look at the current state of my carousels:
![image](https://github.com/user-attachments/assets/c40ee6cc-9c56-4727-95de-f66165947e77)

And I cannot change the positions of them if I wanted to, as any changes made in the settings are not reflected. I even created a new carousel from scratch - same thing. 

Please look into this.

All the best
David

**Comment by pumadog** [comment]
It was fixed somehow (with the posted code?) on the project above, but is still dysfunctional for new projects. Bugfix please!

**Comment by flogeh** [comment]
It is still not working. I just installed the newest version of Elementor (PRO)  3.34.0 and I have the same issue. The dots are plazed left and event too much left.

**Comment by ErisLoona** [comment]
I wanted to move the pagination dots to the side, but they were always centered. Additionally, they did not respect the "Space between dots" setting. Using Elementor 4.0.9, Elementor Pro 4.0.4.  

I've solved it by adding the following Custom CSS to the carousel:  
```css
selector .swiper-pagination-bullets {
    width: fit-content;
}

selector .swiper-pagination-bullet {
    margin: 0 3px; /* I wanted 6px between the dots, change as needed */
}
```
