### ISSUE TITLE
⛔ Hiding widgets on mobile using responsive settings is not working anymore

### ISSUE THREAD

**Issue by Irinel123** [elementor/elementor#29148]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Hi,

I am experiencing major problem on websites updated from 3.25+
All the items that have display none on mobile now don’t have and are displayed ( only on mobile all items are displayed )

I did rollback to 3.24.8 here everything looks fine.

When we get good update ?

### Steps to reproduce

Only 3.25+ 
1. If we have Ex header elements desktop/tablet/mobile on mobile we will see them all even if before the update they were hidden
2. All the sections / widgets that were hidden on mobile are not hidden anymore

### Expected behavior

Everything that is already display none should remain display none and visibility should remain checked

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.38 (Debian)
	MySQL version: MySQL Community Server (GPL) v5.7.29
	PHP Version: 7.4.16
	PHP Memory Limit: 1524M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	Site URL: https://dev1-www.ongage.com
	Home URL: https://dev1-www.ongage.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 1524M
	Max Memory limit: 1524M
	Permalink Structure: /blog/%postname%/
	Language: en_US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child Ongage
	Version: 2.3.1.1615792406
	Author: Elementor Team - Ongage
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.1.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Post Queries
		Version: 1.1.3
		Author: Shabti Kaplan

	Akismet Anti-spam: Spam Protection
		Version: 5.3.3
		Author: Automattic - Anti-spam Team

	Algori PDF Viewer Lite
		Version: 1.0.7
		Author: Kevin Bazira

	Custom Post Type UI
		Version: 1.17.1
		Author: WebDevStudios

	Disable Emojis (GDPR friendly)
		Version: 1.7.6
		Author: Ryan Hellyer

	Disable Feeds
		Version: 1.4.4
		Author: Samir Shah, BBpress support by Matthew Sigley

	Ele Custom Skin
		Version: 3.1.9
		Author: Dudaster.com

	Elementor
		Version: 3.25.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.25.0
		Author: Elementor.com

	Forminator
		Version: 1.36.3
		Author: WPMU DEV

	GraphComment
		Version: 4.0.3
		Author: GraphComment <contact@graphcomment.com>

	Import / Export Customizer Settings
		Version: 1.1.0
		Author: Brainstorm Force

	Ongage Connect
		Version: 
		Author: 

	Optimization Extras
		Version: 1.21.1
		Author: 

	PowerPack Lite for Elementor
		Version: 2.8.0
		Author: PowerPack Addons Team - IdeaBox Creations

	Redirection
		Version: 5.5.0
		Author: John Godley

	Search Regex
		Version: 3.1.0
		Author: John Godley

	Secure Custom Fields
		Version: 6.3.10.2
		Author: WordPress.org

	Simple Image Sizes
		Version: 3.2.2
		Author: Rahe

	Smart Slider 3 Pro
		Version: 3.5.1.24
		Author: Nextend

	User Profile Picture
		Version: 2.6.3
		Author: Cozmoslabs

	WebP Express
		Version: 0.25.9
		Author: Bjørn Rosell

	WordPress Importer
		Version: 0.8.3
		Author: wordpressdotorg

	Worth The Read
		Version: 1.14.2
		Author: Well Done Marketing

	WP-Sweep
		Version: 1.1.8
		Author: Lester 'GaMerZ' Chan

	WP Mail SMTP
		Version: 4.1.1
		Author: WP Mail SMTP

	WP Migrate Lite
		Version: 2.6.11
		Author: WP Engine

	WP Plugin Manager
		Version: 1.2.6
		Author: HasThemes

	WP Rocket
		Version: 3.9.4
		Author: WP Media

	WP Rollback
		Version: 2.0.7
		Author: WP Rollback

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 23.7
		Author: Team Yoast


== Must-Use Plugins ==
	htpm-mu-plugin.php
		Version: 1.0.8
		Author: 


== Elements Usage ==
	
	archive : 14
		archive-posts : 1
		button : 16
		container : 11
		divider : 7
		heading : 62
		html : 11
		image : 17
		loop-grid : 1
		nav-menu : 2
		ongage_connect_newsletter_form : 4
		posts : 33
		search-form : 8
		spacer : 1
		text-editor : 16
	header : 5
		button : 6
		html : 1
		icon : 6
		image : 6
		nav-menu : 2
		text-editor : 2
	loop : 12
		heading : 2
	page : 78
		button : 43
		call-to-action : 4
		counter : 5
		divider : 8
		flip-box : 3
		gallery : 1
		heading : 444
		html : 32
		icon : 111
		image : 470
		image-carousel : 7
		ongage_connect_newsletter_form : 1
		posts : 1
		pp-icon-list : 41
		share-buttons : 2
		sidebar : 1
		spacer : 8
		tabs : 1
		text-editor : 343
		toggle : 2
	section : 105
		button : 6
		container : 2
		heading : 44
		html : 5
		icon : 12
		icon-list : 6
		image : 52
		image-carousel : 1
		ongage-button : 1
		ongage_connect_newsletter_form : 1
		pp-icon-list : 12
		share-buttons : 2
		text-editor : 35
	widget : 0
		accordion : 1
		nav-menu : 1
		share-buttons : 1
		shortcode : 1
		text-editor : 1
	wp-page : 68
		button : 142
		container : 1022
		divider : 6
		heading : 1013
		html : 31
		icon : 136
		icon-list : 6
		image : 913
		image-carousel : 9
		loop-grid : 1
		menu-anchor : 1
		ongage_connect_Kids2_form : 1
		ongage_connect_Kids_form : 1
		ongage_connect_contact_form : 4
		ongage_connect_newsletter_form : 2
		posts : 3
		pp-icon-list : 46
		share-buttons : 4
		shortcode : 1
		sidebar : 1
		slides : 1
		spacer : 6
		text-editor : 549
		toggle : 11
	single-post : 3
		author-box : 4
		button : 12
		heading : 24
		html : 9
		icon-list : 1
		image : 10
		menu-anchor : 1
		ongage_connect_newsletter_form : 1
		ongage_connect_newsletter_single_post : 1
		post-comments : 1
		post-info : 1
		posts : 2
		search-form : 1
		share-buttons : 4
		shortcode : 3
		text-editor : 11
		theme-post-content : 2
	loop-item : 1
		button : 1
		container : 4
		divider : 1
		heading : 1
		image : 1
		text-editor : 1
		theme-post-title : 1


== Settings ==
	
	cpt_support: post, page, glossary
	allow_tracking: yes
	unfiltered_files_upload: 1
	load_fa4_shim: yes


== Features ==
	Custom Fonts: 4
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Active
	Additional Custom Breakpoints: Inactive
	Container: Active
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active by default
	Optimized Markup: Active
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	CSS Smooth Scroll: Active by default
	Default to New Theme Builder: Active by default
	Header &amp; Footer: Inactive by default
	Elementor Home Screen: Active by default
	Landing Pages: Inactive
	Nested Elements: Inactive
	Editor Top Bar: Active by default
	Pages Panel: Inactive by default
	Element Caching: Inactive by default
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Launchpad Checklist: Inactive by default
	Menu: Inactive by default


== Log ==
	
Log: showing 20 of 422024-10-10 09:32:03 [info] elementor-pro::elementor_pro_updater Started 
2024-10-10 09:32:03 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-10-10 09:32:03 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-10-10 09:32:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.3',
  'to' => '3.24.4',
)]
2024-10-17 05:39:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.6',
  'to' => '3.24.7',
)]
2024-10-17 05:39:03 [info] elementor::elementor_updater Started 
2024-10-17 05:39:03 [info] Elementor/Upgrades - _on_each_version Start  
2024-10-17 05:39:06 [info] Elementor/Upgrades - _on_each_version Finished 
2024-10-17 05:39:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.6',
  'to' => '3.24.7',
)]
2024-10-31 12:41:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.7',
  'to' => '3.25.3',
)]
2024-10-31 12:41:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.0',
)]
2024-10-31 12:41:11 [info] elementor::elementor_updater Started 
2024-10-31 12:41:11 [info] Elementor/Upgrades - _on_each_version Start  
2024-10-31 12:41:12 [info] elementor-pro::elementor_pro_updater Started 
2024-10-31 12:41:12 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-10-31 12:41:12 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-10-31 12:41:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.0',
)]
2024-10-31 12:41:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.0',
)]
2024-10-31 12:41:18 [info] Elementor/Upgrades - _on_each_version Finished 
2024-10-31 12:41:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.7',
  'to' => '3.25.3',
)]

JS: showing 1 of 1JS: 2024-09-27 05:29:25 [error X 1][../wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.24.3:2:20010] Cannot read properties of undefined (reading &#039;top&#039;) 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	PowerPack Lite for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by jdpoccorie** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by portrayaloflife** [comment]
Experienced this as well, my header hidden on mobile was now visible on mobile and had to reset it.

**Comment by ad2003** [comment]
I see also a few different bugs in the latest release - they removed smooth scrolling while the css way doensn't work on all browsers and also some problems with disappearing Icons which worked completely fine before, transitions are broken, etc.. Needed to import backup.

**Comment by pgrafix** [comment]
We, too, have been experiencing a lot of issues as well. Notably, missing css and js files (e.g. load more). Rolling back both Elementor and Elementor Pro to the last of 3.24 series seems to resolve the issues.

**Comment by nicholaszein** [comment]
Hello @Irinel123, @portrayaloflife, @ad2003, and @pgrafix!

Thank you for sharing your feedback! 🙏 

In version **3.4.0**, released way back in August 2021, we released the new **Additional Custom Breakpoints** feature, aimed to allow users to use additional breakpoints on their websites. This was a long requested feature, and welcomed by the users.

At the time, [we explained](https://developers.elementor.com/additional-custom-breakpoints-technical-details-and-gotchas/) that we were deprecating the `.elementor-hidden-phone` class used to hide elements in mobile devices and replace it with the more appropriate `.elementor-hidden-mobile` class.

We recommended to everyone using those classes to replace them with the new ones, including addons and 3rd-party plugins.

We also set a [deprecation notice](https://developers.elementor.com/docs/deprecations/) that this class would be removed within the next 8 minor versions of Elementor.

Since then, we released 26 minor versions, and we finally removed this class.

We are getting a lot of complaints about this issue, despite those warnings. But upon investigation, most of the users affected by this change are those employing any sort of CSS optimization, including using any level of cache.

It's important that users applying cache to their sites, to purge, clear, and flush all levels of cache after updating, including the new Element Caching, which can be done by going to Elementor > Tools > General and clicking on "Regenerate CSS & Data".

Once you've done this, your elements and widgets using the old class can be updated to use the new class.

Therefore this is not a bug, this is a conflict caused by cache. Once the users who reported this problem to Elementor Support performed the cache cleanup, they were able to see the problem being fixed.

Please, clear your cache. If you are still having problems after doing that (including clearing the mobile browser cache, which is very persistent due to mobile data usage), then reach out to Elementor Support and they will be able to assist you better.

For now, we are closing this issue.

Kind regards

**Comment by portrayaloflife** [comment]
@nicholaszein Clearing the cache doesn't resolve the issue for us. Nowhere in all of those notes does it say anything remotely close to "anyone currently using a mobile breakpoint will need to reset all their mobile breakpoints again manually after activation"....

Respectfully, this seems like another situation of needing a clearer way of letting active elementor users know when an experiment is going to be merged, and how it is going to negatively impact our current sites.  

With the update, why can't the mobile options be auto-updated in all of the container/element settings without us having to update them all manually? couldn't there of been a script for the class change and it remain in the on position it was previously? We now have to comb through every site we've built and reselect the mobile responsiveness option to hide where we had previously hidden elements. 

There's got to of been a better option than this. Really frustrating for us.

**Comment by portrayaloflife** [comment]
@nicholaszein Just for clarity should the cache clear have auto-updated all the mobile responsive settings or is it indeed something we need to reselect manually?

**Comment by portrayaloflife** [comment]
@nicholaszein Pinging this

**Comment by incircolo** [comment]
This is not a cache related problem. With nocache environment all "hidden" on mobile setting on widget are lost. 
It's a really nightmare to fix it now... all content have to be modified.

**Comment by incircolo** [comment]
> @nicholaszein Just for clarity should the cache clear have auto-updated all the mobile responsive settings or is it indeed something we need to reselect manually?

Please let us know if we have to modify 1000+ contents in our sites manually (and remember which widgets have hidden mobile feature enabled).

**Comment by nicholaszein** [comment]
Hi @incircolo and @portrayaloflife!

We've updated the [blog post in the Developers Center](https://developers.elementor.com/elementor-3-25-developers-update/) to address this issue. You'll find [solutions](https://developers.elementor.com/elementor-3-25-developers-update/#:~:text=for%20existing%20websites.-,Developer%20Advisory,-We%20encourage%20Elementor) for this problem.

This contradicts my initial statement related to caching. After further investigation we concluded this is not the case. I apologize for the confusion.

Please refer to the article to learn how to handle possible issues with the classes.

Kind regards

**Comment by incircolo** [comment]
Thank you for your clarification. Now it's more clear how to proceed to fix the issues.

**Comment by portrayaloflife** [comment]
I'm confused here still, will we need to manually still update all the mobile responsive settings that become unchecked when we update? 

Or is it saying even unchecked it has the old class so adding that display none CSS site wide will keep everything as it was? Or if we do the search and replace will it auto check the new correct responsive setting?

**Comment by incircolo** [comment]
Yes you can fix with a custom CSS or replacing classes using phpmyadmin or other software which edit the database... but you need to do it carefully.
If you replace classes in the database Elementor will get it correctly in the Responsive widget section... otherwise this will remain unchecked if you simply add a custom CSS.

**Comment by portrayaloflife** [comment]
Would a better solution be just adding the new mobile class and keeping the phone class so they both do the same thing and  activate the responsive setting tab.  And then in the next version removing the phone tab, leaving behind the new mobile tab that keeps all the settings checked and then no manual updating is needed. Like a hand off.

**Comment by incircolo** [comment]
Yes. Absolutely better... to have it checked automatically.

**Comment by nicholaszein** [comment]
@portrayaloflife!

This was actually what we had since version 3.4. All we did in this version was to remove the old class from our stylesheet. So applying it manually as suggested in the article should solve this problem. 

However, due to a limitation, we cannot replace the classes on the widget level. The only way to do that is to go to each widget, turn it off and turn it on again.

This only happens on elements created before 3.4 though, which at this time are really an extremely small fraction of the userbase.

Nonetheless, we are discussing this internally.

**Comment by incircolo** [comment]
> @portrayaloflife!
> 

> However, due to a limitation, we cannot replace the classes on the widget level. The only way to do that is to go to each widget, turn it off and turn it on again.

Where is it stored? In the database? which table?

**Comment by incircolo** [comment]
Ok i have tested it.
If i add the CSS custom code all is fixed, and if i edit and update content, the responsive mobile feature is unchecked, but if i publish the page the custom CSS code always get it fixed.
So exactly where i have to check for "serch and replace" final solution? where is the old class stored exactly?

**Comment by portrayaloflife** [comment]
> This only happens on elements created before 3.4 though, which at this time are really an extremely small fraction of the userbase.

Ahh that makes sense why we weren't seeing the issue on newer sites with containers. Really appreciate y'll looking into this. One of the problems we hit is a lot of our sites are combinations of new containers etc and old sections. We're in a niche and have a lot of tool setups so we always clone sites and then build new projects on top of them to save time. So there sites with say all containers but a header might still be a section, or a single page template or page header etc might still be a section.

**Comment by incircolo** [comment]
Ah... you are right... these sites of mine don't use containers, but still structure with sections.

**Comment by incircolo** [comment]
Ok. So can i search and replace this class here?

**Comment by mirawebtr** [comment]
The following CSS code will suffice

```
@media (max-width: 767px) {
    .elementor-hidden-phone {
        display: none;
    }
}
```
