### ISSUE TITLE
✅ 🐞 Font styles are not regenerated after site migration when Load Google Fonts Locally is enabled

### ISSUE THREAD

**Issue by netnothing** [elementor/elementor#30600]
### Prerequisites

- [x] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [x] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

With the new Load Google Fonts locally option - if either of the following occurs, Elementor doesn't seem to be re-downloading the fonts again:

1. A site is duplicated and re-installed on another domain.  This causes the fonts to reference the old site.
2. If the elementor folder in /wp-content/uploads is removed, Elementor will recreate the folder, but won't re-download the Google fonts.

This post: https://github.com/orgs/elementor/discussions/30415#discussioncomment-12524242
Seems to indicate that changing the Google Fonts Load option should clear the locally stored fonts and they should be re-downloaded.  I'm not seeing this re-download happen.

### Steps to reproduce

1. Have a current updated site and is working normally.  The site should be using the new Load Google Fonts locally option as active/default.
2. Remove the /wp-content/uploads/elementor folder.
3. Load the front page of the site. 
4. The front page and all other pages will load very slowly.  
5. Elementor will re-create the /wp-content/uploads/elementor folder and the sub folders, however, the google-fonts/fonts folder will remain empty, while the css folders are created with files.
6. Even toggling the Google Fonts Load option to something else, saving and setting back - this doesn't cause the fonts to re-download.

### Expected behavior

1. If the /wp-content/uploads/elementor folder is removed, Elementor should recreate and re-download all Google fonts used on the site.

### Isolating the problem

- [x] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [x] This bug happens with the Hello Elementor theme active.
- [x] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

```txt

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v8.0.39-30
	PHP Version: 8.2.28
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.7.2
	Site URL: https://development.site
	Home URL: https://development.site
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.3.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.28.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.28.0
		Author: Elementor.com


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	Container: Active
	Optimized Markup: Inactive by default
	Load Google Fonts locally: Active by default
	Default to New Theme Builder: Active by default
	Header & Footer: Inactive by default
	Nested Elements: Active
	Editor Top Bar: Active
	Pages Panel: Inactive by default
	Element Caching: Inactive by default
	Elementor Home Screen: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Global Classes: Inactive by default
	Launchpad Checklist: Inactive by default
	Cloud Library: Inactive by default
	Menu: Active


== Log ==
	
Log: showing 20 of 382025-03-14 11:37:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.27.6',
  'to' => '3.27.7',
)]
2025-03-14 11:37:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.27.6',
  'to' => '3.27.7',
)]
2025-03-14 11:37:44 [info] elementor::elementor_updater Started 
2025-03-14 11:37:44 [info] Elementor/Upgrades - _on_each_version Start  
2025-03-14 11:37:44 [info] Elementor/Upgrades - _on_each_version Finished 
2025-03-14 11:37:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.27.6',
  'to' => '3.27.7',
)]
2025-03-14 11:37:46 [info] elementor-pro::elementor_pro_updater Started 
2025-03-14 11:37:46 [info] Elementor Pro/Upgrades - _on_each_version Start  
2025-03-14 11:37:46 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2025-03-14 11:37:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.27.6',
  'to' => '3.27.7',
)]
2025-03-19 21:13:12 [info] elementor-pro::elementor_pro_updater Started 
2025-03-19 21:13:12 [info] Elementor Pro/Upgrades - _on_each_version Start  
2025-03-19 21:13:12 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2025-03-19 21:13:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.27.7',
  'to' => '3.28.0',
)]
2025-03-19 21:13:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.27.7',
  'to' => '3.28.0',
)]
2025-03-19 21:13:12 [info] elementor::elementor_updater Started 
2025-03-19 21:13:12 [info] Elementor/Upgrades - _on_each_version Start  
2025-03-19 21:13:12 [info] Elementor/Upgrades - _on_each_version Finished 
2025-03-19 21:13:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.27.7',
  'to' => '3.28.0',
)]
2025-03-19 21:13:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.27.7',
  'to' => '3.28.0',
)]

PHP: showing 4 of 4PHP: 2025-02-13 11:05:56 [warning X 12][/home/customer/www/development.site/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /home/customer/www/development.site/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/customer/www/development.site/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/customer/www/development.site/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/customer/www/development.site/public_html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2025-02-13 11:05:57 [notice X 23][/home/customer/www/development.site/public_html/wp-content/plugins/elementor-pro/modules/screenshots/module.php::33] Function utf8_decode() is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2025-02-13 11:06:00 [notice X 9][/home/customer/www/development.site/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::229] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2025-03-12 14:00:05 [warning X 16][/home/customer/www/development.site/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /home/customer/www/development.site/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/customer/www/development.site/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/customer/www/development.site/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/customer/www/development.site/public_html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

```
</details>

### Agreement

- [x] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by netnothing** [comment]
To followup - no combo of turning features on and off seem to make Elementor re-download the fonts locally.  Turning off Load Google Fonts locally makes the site load quickly again, simply because it isn't trying to render non-existent fonts.  But turning that option back on, the site loads slowly.

**Comment by netnothing** [comment]
Just did another test and it is even weirder.

1. Installed a fresh Wordpress install
2. Deleted all plugins
3. Installed Hello Elementor theme
4. Installed Elementor

Immediately the site is slow.  The folder /wp-content/uploads/elementor was created but again no fonts are being downloaded.

Turning off Load Google Fonts locally causing the site to work as it should.

**Comment by nicholaszein** [comment]
Hello @netnothing!

Thank you for reaching out! 🙏

We are currently investigating this issue, and we will update you here once we have more information.

Meanwhile, can you clarify if you have performed the Site Migration procedure once you restored a copy of the existing site on a new installation outlined in the Help Center article below?

https://elementor.com/help/site-migration

Kind regards

**Comment by netnothing** [comment]
> Hello [@netnothing](https://github.com/netnothing)!
> 
> Thank you for reaching out! 🙏
> 
> We are currently investigating this issue, and we will update you here once we have more information.
> 
> Meanwhile, can you clarify if you have performed the Site Migration procedure once you restored a copy of the existing site on a new installation outlined in the Help Center article below?
> 
> https://elementor.com/help/site-migration
> 
> Kind regards

Nicholas,

Yes I performed all of those steps.

As for my latest test with the fresh install - I went to bed last night without success in getting the font to download.  I woke up this morning, loaded the page and it downloaded the fonts?!

What is the timeframe and trigger for this to happen?

**Comment by netnothing** [comment]
> Hi [@netnothing](https://github.com/netnothing)!
> 
> Thank you for the feedback! 🙏
> 
> What you are describing sounds like cache related, or simply a temporary glitch. You do need to Clear Files & Data after changing the URLs. This button should also trigger the re-download of the fonts.
> 
> I'm glad it's working for you now. We will continue to investigate this, and if necessary we will release a patch.
> 
> Regards

Nicholas,

Doing another migration test using the Duplicator plugin (https://wordpress.org/plugins/duplicator/)

I can confirm after restoring a site onto a new domain:

1. Elementor does NOT automatically clear the fonts and css from the old domain.  This causes console errors:

Access to font at 'https://oldsite.com/wp-content/uploads/elementor/google-fonts/fonts/lato-s6u9w4bmutphh50xswipgq.woff2' from origin 'https://newsite.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

2. Pressing the Clear Files & Data button does NOT clear the fonts or anything in the folders:  /wp-content/uploads/elementor/google-fonts - this includes CSS and font files.

3. However, changing the option Google Fonts Load to something else DOES cause everything in the /wp-content/uploads/elementor/google-fonts folder to be cleared (CSS and font files).  They are also successfully being rebuilt today.

So I still have no idea what happened yesterday where the Google Fonts Load wasn't clearing and rebuilding the fonts, but it looks like things are working today.  Does Elementor rely on the 3rd party service to download those fonts or something that would have caused the issue yesterday?

**Comment by netnothing** [comment]
Also, while using the Google Fonts Load option to clear the fonts is nice - it's obscure.  I only knew about it based on that other comment on the release notes (https://github.com/orgs/elementor/discussions/30415#discussioncomment-12516984).

I understand that thread where they don't want the Clear Files & Data to also clear the fonts - but that button isn't clearing anything in the google-fonts folder causing some of these issues.

Maybe now that this is default active - Elementor can add another button to Clear Google Font Files & Data?

**Comment by nicholaszein** [comment]
@netnothing,

Yes, that's correct, like background images, the path to the downloaded Google Fonts is stored on a stylesheet.

In glad it's working for you, but I thank you for sharing your experience. We will likely release a patch for when the site is migrated. And we will need to revisit the Clear Files & Data trigger not clearing the Google Fonts.

Regards

**Comment by mikedoyledesign** [comment]
I'd like to echo a similar experience doing a migration just now.
The site migrated really well with Updraft as per usual, except I noticed all fonts were fallback. 

Inspector in browser showed the script was trying to find the 3 fonts from the previous domain and not the new domain.

Search & Replace found no instances of the previous domain.

I turned off Google fonts loading locally and the fonts worked as intended. Switching back on caused the same issue.

Cleared Caches, Files, Browser Caches and mashed Permalinks a few times. Nothing.

Saw in the uploads/elementor/fonts folder that the correct fonts actually did get migrated over - but the site was trying to find the old URL path.

Deleted the font folder and tried to sort of change and save global fonts in Site Settings. The existing two fonts (Montserrat/Spectral) just wouldn't show up in /elementor/fonts folder not matter what variation of resaving I did - BUT - I accidently selected Montserrat Alternate font (which I've never used) - and saved, and those fonts went into the folder.

Anyway, will reassess in a few hours and likely just keep the feature off until more feedback. Hope this helps a bit.

**Comment by netnothing** [comment]
@mikedoyledesign Pretty much my exact situation yesterday.

Have you tried keeping Load Google Fonts locally ON and changing the setting for Google Fonts Load?

With the setting for Google Fonts Load, for me it was set to Default.  Any change and save will (should) clear the entire google-fonts folder.  So you can change to say Swap, save, and then change back - that should cause 2 clears and 2 re-downloads of the fonts used.

Yesterday that wasn't doing anything for me  - but for some reason today it's working like that.

**Comment by mikedoyledesign** [comment]
Yes! Switching from SWAP to DEFAULT cleared the Montserrat Alternates and visiting the site again loaded the correct two (Montserrat/Spectral). Getting no more console errors.  

Looks like that might be an indicator of an extra step required in this specific migration situation? Carry on!

**Comment by netnothing** [comment]
@mikedoyledesign Glad it worked!  Someone from Elementor mentioned in another thread that using the Clear Files & Data button wasn't going to clear the fonts because that may cause some people to have to download a lot of fonts again.  My guess is this decision also means they don't clear the old CSS files with the old domain paths.  Can't imagine a lot of the migration plugins want to be changing files, so either this will be a standard step - or Elementor gives us a second button to Clear Google Font Files & Data.

**Comment by nicholaszein** [comment]
We are working on a fix for site migrations. As for the Clear Files & Data, we are still discussing if it should include Downloaded Google Font Assets or not. 

The only step required for migrating sites is to run the Replace URL tool. That should be what will update all URLs in documents and assets edited with Elementor.

**Comment by netnothing** [comment]
@nicholaszein Thanks for the update.

I did a migration test just now and wanted to let you know that using the Replace URL tool does **NOT** update the paths in the CSS files in /wp-content/uploads/elementor/google-fonts/css.

Still the only thing that will clear those CSS files and fonts is using the Google Fonts Load option to toggle it to something else and back again.

**Comment by MariuszMilka** [comment]
Same here. I was working on a staging site with fresh wordpress and elementor pro. Loading google fonts locally was enabled by default. Today I migrated the site to a live one and no google fonts. The only thing that worked was switching off loading google fonts locally. It looks like they are downloaded and saved first time they are used and after migration they are not there or they are, bo some path does not update.

**Comment by nicholaszein** [comment]
The patch should fix this behavior, and once you update the URL it should also update the paths of downloaded Google Fonts.

Switching the option for the Google Fonts Load Method should update the paths for the Google Fonts loaded locally for now.

**Comment by netnothing** [comment]
@nicholaszein Thanks for the update!

I can confirm that when migrating a site using Elementor 3.28.1 initially the font paths are still incorrect.  However, after you use the tool: Replace URL - this will successfully clear all the font CSS and font files from the google-fonts folder.  Upon the next page load, Elementor will properly recreate the files.

Thank you and team for all the help!

**Comment by portrayaloflife** [comment]
Just flagging here that we're seeing this even when switching a dev site to a new domain at launch for custom fonts not loading. Our current fix is reuploading the custom fonts.

**Comment by nicholaszein** [comment]
This issue was solved with the release of Elementor v3.28.1.

The Google Fonts are now cleared once you **`Clear Files and Data`**, and re-downloaded when the page is visited.

----

If you are still experiencing this issue after updating to 3.28.1 or greater, it's important to ensure your Site Address URL and WordPress Address URL both contain the https protocol in the WordPress **`Dashboard`**, that you have performed the [Site Migration procedure](https://elementor.com/help/site-migration/), and that you are logged in through a secure connection (https).

Also make sure you don't have rewrite rules affecting your site. Perform a flush by going to your WordPress Dashboard > Settings > Permalinks, changing the base permalink to plain, saving, and then changing it back to the previous value. 

If you don't meet these requirements, WordPress will continue to save the non-secure http link to the files, causing mixed content when visiting the page.

Elementor uses standard WordPress checks, procedures, and sanitization to fetch the URL of your site, and save it in the font file stylesheets of their respective fonts. If you are logged-in using http instead of https, Elementor (through WordPress) will not write the link with the https protocol.

Ultimately, since it would fall into your hosting provider to force secure connections all the time (for example, using the HSTS protocol). Some hosting providers have this option in their Control Panel, but it may be disabled. Good hosting providers will have this always enabled by default.

Always ensure you are logging in through a secure connection! 

----

The issue reported here was already solved, and is now working as expected. I just tested it on both a live server, as well as on a local installation and can confirm migrating through both back and forward regenerates the Google Font styles accordingly.

For this reason, I'm closing this issue as solved.

If you are still experiencing this issue after updating, and also after following the Site Migration procedure and troubleshooting steps suggested above, feel free to open a [new 🐞 Bug Report](https://elemn.to/gh-new-bug-report) with detailed information so we can discuss your specific case further.
