### ISSUE TITLE
[Feature Request] Hide Hidden Responsive Elements on Edit Screen

### ISSUE THREAD

**Issue by TomRaraAvis** [elementor/elementor#4775]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

**Problem**:
Even though I have certain elements hidden on desktop, they still show on the edit screen. It drives me crazy and makes it very difficult to continue designing the rest of the page while there is an element showing that isn't supposed to be showing. Elementor is supposed to be visual editor — a WYSIWYG (what you see is what you get). So, it just doesn't make any sense to me why a hidden element is still visible in the edit screen. Please see example screenshot below:

<a href="https://ibb.co/da46aJ"><img src="https://preview.ibb.co/irQZUd/responsive_hidden.png" alt="responsive_hidden" border="0"></a>
I have 2 navigation menus — 1 menu for mobile and 1 for desktop/tablet. The blue menu is supposed to be only visible on mobile, but it still shows on edit screen.

**Possible Solution**:
Please add the option to also hide hidden elements from the edit screen.

<a href="https://ibb.co/hbqONy"><img src="https://preview.ibb.co/bCmxhy/responsive_hidden_suggest.png" alt="responsive_hidden_suggest" border="0"></a>
You could add this option to turn on or off under the eye icon where the preview settings are.

**Comment by black-eye** [comment]
+1
Good idea. And even when this option is not checked, the hidden element should be visibly marked (e.g. with colored point, badge or semitransparency).

**Comment by IamSiddharth** [comment]
+1

**Comment by bentalgad** [comment]
+1

**Comment by StreetDog1971** [comment]
+1

**Comment by MPHood** [comment]
+1

**Comment by Turanligil** [comment]
+1 yes that drives me crazy too :) .... a REAL WYSIWYG Editor should show mobile items when desktop is selected ...

**Comment by bentalgad** [comment]
+1 it's really weird to try to design something with a page builder and think how it would look in real live site (like when your coding).

**Comment by daniilicic** [comment]
Agree! This is a crucial feature for designing complex layouts where you have several elements shown differently on every device type. Once you open the editor you have an enormous number of elements that look very similar and it's very hard to tell which exactly you should edit.

Is there any plans to implement this?

**Comment by ChristineFerguson** [comment]
Yes, this feature seems essential! It is very difficult to design and edit elements for a device type when you're working around elements that should be hidden.

**Comment by ommr101** [comment]
+1

**Comment by ashleyyounguk** [comment]
+1 totally agree, it makes it really difficult to design a header or a page when you can see all elements for all devices.

**Comment by papplebee** [comment]
+1

**Comment by pecktron2000** [comment]
+1 Please implement this feature. It is essential.

**Comment by kodezen** [comment]
+1 This is a crucial feature. Stumbled across this thread after getting frustrated with the messy and confusing edit view after I implemented some mobile only elements (desktop/tablet hidden)

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.8

Feel free to update

Thanks!

**Comment by webndesign** [comment]
> This issue has been resolved in Elementor v2.8
> 
> Feel free to update
> 
> Thanks!

Hi there, 
Sorry, but how is this feature resolved? Could you please explain where I can see it? I'm using Elementor v 2.98 and still getting hidden sections when on editing mode!
I'm not talking about when viewing the 'eye' icon to view the site, but when on the edit screen itself. 

Thank you for clarifying, it will be really helpful for me.

**Comment by leolll** [comment]
This is still a problem.  It makes the editing mode preview virtually useless and you have to constantly collapse the editing panel to get an idea of what the site looks like.

**Comment by marekmaurizio** [comment]
Terrible solution, just add a damn class to hide them for good.

**Comment by com-xuonghuynh** [comment]
No it's not resolve, problem still there

**Comment by senginee** [comment]
Same here... problem still there

**Comment by Lemente** [comment]
> 
> 
> > This issue has been resolved in Elementor v2.8
> > Feel free to update
> > Thanks!
> 
> Hi there,
> Sorry, but how is this feature resolved? Could you please explain where I can see it? I'm using Elementor v 2.98 and still getting hidden sections when on editing mode!
> I'm not talking about when viewing the 'eye' icon to view the site, but when on the edit screen itself. I don't mean the 'muted' version as the folks at Elementor mention in above thread either.
> 
> Thank you for clarifying, it will be really helpful for me.

From #9672

> Better Responsive Visibility Indication (#8020, #4775)
> 
> Better Responsive Visibility Indication
> 
> One of the feedback we commonly get is “Why is my HIDDEN element still visible in the editor preview?! 😡”
> We feel your anger… From now on, you can cross off that question.
> When hiding an element, and switching to the view it’s hidden on, you will see that this element is “muted”.

Basically, what they added is the "greyed out" functionnality. Which means it is still very much visible, and still not hidden at all.

This is what my website currently looks like in elementor : ![d5501e48fd8247fb9a326942cd8845fb](https://user-images.githubusercontent.com/27686967/90241501-75d3db80-de2b-11ea-910c-0dbdcaf14655.png)

**Comment by WhereverPanda** [comment]
I would also like to understand how this is considered to be 'resolved'...

When using a visual editor, you want to see the page as it will appear to the end user. Elementor is brilliant with this... until it comes to responsive design, or adding a piece of script in an HTML element.

Please allow us this feature - to be able to see the site as it will appear, in the editor, without having to hit 'Preview' or hide/show sections via the navigator.

If it's accessibility you are worried about, you really shouldn't be, because any element can be accessed via the navigator at all times, visible or not visible.

This is the only flaw in an otherwise brilliant product.

Thank you!

**Comment by mapsmarketing** [comment]
A year later and still not an answer on this one. 

Can elements which are meant to be visible on specific devices be visible on those devices only? I don't need to look at a mobile element on desktop or tablet, etc.

**Comment by JHethDev** [comment]
Not sure if this will help anyone but I was recently forced to work with Elementor and ran into this apparently resolved problem.

I used a Chrome extension that adds CSS to a page ([user javascript and css](https://chrome.google.com/webstore/detail/user-javascript-and-css/nbhcbdghjpllgmfilhnhkllmkecfmpld?hl=en)), used the target classes Elementor uses to make gray lines, added display none and poof the sections are gone instead of still taking up space. And they show up on the screen sizes where they exist still, what a concept.

Here's the code if anyone else wants to do the same:

```css
.e-preview--show-hidden-elements[data-elementor-device-mode=desktop] .elementor-edit-area-active .elementor-hidden-desktop, .e-preview--show-hidden-elements[data-elementor-device-mode=laptop] .elementor-edit-area-active .elementor-hidden-laptop, .e-preview--show-hidden-elements[data-elementor-device-mode=mobile] .elementor-edit-area-active .elementor-hidden-mobile, .e-preview--show-hidden-elements[data-elementor-device-mode=mobile_extra] .elementor-edit-area-active .elementor-hidden-mobile_extra, .e-preview--show-hidden-elements[data-elementor-device-mode=tablet] .elementor-edit-area-active .elementor-hidden-tablet, .e-preview--show-hidden-elements[data-elementor-device-mode=tablet_extra] .elementor-edit-area-active .elementor-hidden-tablet_extra, .e-preview--show-hidden-elements[data-elementor-device-mode=widescreen] .elementor-edit-area-active .elementor-hidden-widescreen {
  display: none
}
```

To the Elementor folks who think the gray lines solution is good, it's not, those elements still take up space in the layout and caused me to really wreck the desktop layout trying to fix something that wasn't an issue.

**Comment by JudithK87** [comment]
It is actually possible to switch this off. 
Open a page to edit with elementor, click on the hamburger menu and select USER PREFERENCES Then under "responsive preview" toggle "Hidden Elements" to OFF and Voila!

All the mobile elements no longer show on desktop and vice-versa. Additionally, it also hides HTML elements which have nothing in it [scripts etc] (you actually have to use the navigator (CTRL+I) to find them on your page as they are virtually impossible to find back!

![Screenshot 2021-11-14 at 18 48 40](https://user-images.githubusercontent.com/79253900/141692368-2f5ec524-fbff-43f2-a927-4d3bf04d12b0.png)

OR you can also do it by element: use CTRL+I to open the navigator. Find the item you want to hide (for example the section which contains the mobile version of your menu) and then click on the eye option which will remove the visibility of the item for you. This fix is more an "on-the-go" fix as it stays hidden when you switch to mobile view. Not useful when you have many such elements but if it's only one on a page, this trick could be useful. 

Hope I helped someone with this!

**Comment by barrrricade** [comment]
Wow, @JudithK87 
MVP

**Comment by jdboyce** [comment]
[JudithK87](https://github.com/JudithK87) you have saved me from a lifetime of madness, so many of my designs were wrecked because it kept auto-adjusting the column percentages because of "hidden" columns. I signed in just to say thank you, BLESS YOU!!!

**Comment by webndesign** [comment]
Oh my…I never discovered that!!!!!
What? Since when is it available as an option??
Gosh, so many frustrating moments of checking my 2nd screen (right click - inspect element, to see the mobile version), then checking my actual mobile phone to see if what I saw under ‘inspect elements’ was actually what my mobile showed…!

Thank you!!
