### ISSUE TITLE
Center Images Vertically in Image Carousel

### ISSUE THREAD

**Issue by sp1287** [elementor/elementor#6963]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
As it stands now, images of different dimensions (i.e. heights) float to the top. I see this has been suggested before, but I have even tried to remedy this with custom CSS to no avail.

Please add functionality to vertically center images in an Image Carousel.

## Steps to reproduce

1. Add images of varying dimensions to Image Carousel
2. Watch images float to the top, looking bad

I had tried to fix this issue with the custom CSS below in Elementor Pro, but to no avail. Is there an error in my code? I tried to use exactly as prescribed for previous solutions to an image gallery, for example.

```css
.carousel .carousel-inner .item .carousel-image {
    vertical-align: middle;
}
```

Thank you!

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by andrijanasv** [comment]
Another vote for this feature - thanks! 
(Not sure if Vertical & Horizontal Alignment improvements in v2.5.0 are addressing this :)

**Comment by marclucraft** [comment]
Another vote for this feature! 👍 

@sp1287 @andrijanasv - for now you can use flex to align the images to the center, like this:

`.slick-track {
	display:flex;
	align-items:center;
}`

**Comment by andrijanasv** [comment]
@marclucraft thank you so much!

**Comment by drewclifton** [comment]
Also run right into this issue when adding brand logos to an image carousel. Thanks for your review and addressing this one. :)

**Comment by neyz** [comment]
> Another vote for this feature! 👍
> 
> @sp1287 @andrijanasv - for now you can use flex to align the images to the center, like this:
> 
> `.slick-track { display:flex; align-items:center; }`

Thanks for the workaround @marclucraft but could you please tell me where do we actually use that command ?

I also tried to update the php file from the last commit but i don't see a difference.

As you perhaps can tell i'm quite new with all this !

Thanks !

**Comment by marclucraft** [comment]
@neyz Sorry for the delay.

The simplest way would be to copy and paste the above CSS to here:  "Customise > Additional CSS".
That will then work across your whole website.

Hope that makes sense.

**Comment by easygav** [comment]
> Another vote for this feature! 👍
> 
> @sp1287 @andrijanasv - for now you can use flex to align the images to the center, like this:
> 
> `.slick-track { display:flex; align-items:center; }`

Thank you for this! Works like a charm for now - native alignment options in the carousel makes alot of sense though as no-one would ever want images/ logos to be anything other than centred. 

Thanks again, and thanks Elementor Developers ;-)

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.6.0

Feel free to update

Thanks!

**Comment by uliwest** [comment]
I tested the image carousel in the newest version of elementor, both regular Version 2.7.5 and pro Version 2.7.3, and the issue has not been resolved unfortunately. When using images of different aspect ratios, the long ones stick to the top and are not vertically centered. 

.slick-track { display:flex; align-items:center; } does not work in my case either.

In the documentation https://docs.elementor.com/article/52-image-carousel
it says that there is the following option: Vertical Align: Vertically align the image to the top, middle, or bottom. However that option doesn't show in my elementor menu, and elementor support confirmed that "Currently, this is not a native feature from Elementor and it has no option to vertically align images with the Image Carousel Widget."

Do you have any ideas for new custom css code to add that would resolve the issue?

this is the site, you can see the effect best on the last image of the carousel:
https://essbarer-naturpark.de/sortenportrait-template/

**Comment by joshua-martius** [comment]
I am on Elementor Version 3.11.3 and I am still having this problem. Is it back or am I missing a checkbox here?

**Comment by marcinkrzesinski** [comment]
Elementor PRO version 3.13.1 still problem exist.

**Comment by ev88** [comment]
The previously suggested CSS didn't work for me.  This did:

```
.elementor-image-carousel { 
    display: flex; 
    align-items: center;
    }
```

**Comment by nadworks** [comment]
Wow, why is this still not possible without custom CSS?

**Comment by L0garithmic** [comment]
2025. Why is this still not possible without custom css...
