### ISSUE TITLE
frontend-modules.js is referenceing a js.map file causing 404

### ISSUE THREAD

**Issue by jennafarr** [elementor/elementor#7082]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

websites running the latest version of Elementor Pro or Elementor are causing 404 errors as the frontend-modules.js file is referencing frontend-modules.js.map on the last line. When we remove that the 404 is gone.

## Steps to reproduce

Check console for errors in Safari with Elementor installed and activated

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

**Comment by RayAtCyberdine** [comment]
I can confirm, this issue still exists today. March 5th, 2019 - running the latest Elementor 2.5.1 and Pro Version 2.4.6 - with Astra Theme Version: 1.6.9 & Astra Pro Version 1.6.14. 

It's specifically with Safari I receive these two 404 errors on console.

http://example.com/wp-content/plugins/elementor/assets/js/frontend-modules.js.map
http://example.com/wp-content/plugins/elementor/assets/lib/swiper/swiper.min.js.map

Any help would be appreciated.

**Comment by pgrafix** [comment]
I too am having the same issue. Specifically in Safari as well. I have to wonder if this is related to another issue I am having: icon list elements are no longer loading the icons.

**Comment by pgrafix** [comment]
Icon issue for me is resolved and not due to Elementor or Astra (CDN issue).

References to .map JS files are still being seen in the console but do not seem to be affecting the site in any way I can discern.

**Comment by mellymine** [comment]
This error is also happening for me. I'm getting all of these as "Failed to load resource: the server responded with a status of 404 (Not Found)" and I'm using Safari and Chrome:

/wp-content/plugins/elementor/assets/js/common-modules.js.map
/wp-content/plugins/elementor/assets/js/editor-modules.js.map
/wp-content/plugins/elementor/assets/lib/swiper/swiper.min.js.map
/wp-content/plugins/elementor/assets/js/frontend-modules.js.map

I'm brand new to Elementor and so far, things aren't going well. I've encountered errors like this, and I just spent over an hour trying to figure out why my SVG logo was only 48px wide despite the settings I gave it. Finally found a custom solution to that elsewhere, it's another bug. I'm getting worried these problems right out of the gate mean that Elementor might be a waste of my time, despite how excited I was to try it when I first found out about it. Hope they are just a fluke and will get cleared up soon!

**Comment by seanconklin** [comment]
I'm also reproducing this issue in Safari v12.0.3 browser (latest for macOS High Sierra at least) with the latest WP software, using the default WooCommerce Storefront theme.

It's complaining about 404s with:
- `/wp-content/plugins/elementor/assets/js/frontend-modules.js.map`
- `/wp-content/plugins/elementor/assets/lib/swiper/swiper.min.js.map`
- `/wp-content/plugins/elementor/assets/js/common-modules.js.map`

**Comment by kamalahmed** [comment]
![Screen Shot 2019-03-20 at 9 27 19 PM](https://user-images.githubusercontent.com/6803549/54697268-76dddc00-4b57-11e9-9e12-35772b22f266.jpg)
**I am facing the same problem.**

**Comment by thomasmalley** [comment]
I am facing the same problems too.  (Safari Version 12.0.3 running on MacOS Mojave 10.14.3)
![Bildschirmfoto 2019-03-21 um 12 14 17](https://user-images.githubusercontent.com/13106168/54748858-27d58c80-4bd3-11e9-936d-a96d07be74c5.png)

* `/wp-content/plugins/elementor/assets/js/frontend-modules.js.map`
* `/wp-content/plugins/elementor/assets/lib/swiper/swiper.min.js.map`

**Comment by badcat** [comment]
Same here.  [Again](https://github.com/elementor/elementor/issues/5151). I'd reported this _last July_.
Why not just include the .map assets?

**Comment by berkmh** [comment]
same issue here.

**Comment by pixelxcode** [comment]
same issue. Has this been fixed yet?

**Comment by Tsluiz** [comment]
same issue here. Has it been fixed? ( I found the errors since I am having a strange 301 redirect on my product archive)

**Comment by badcat** [comment]
Why close this?  Has it been resolved?

**Comment by badcat** [comment]
Huzzah!  I see it has been marked as fixed in the Changelog.  Congrats! and thank you.

**Comment by eugenevdm** [comment]
For those who are interested, it's:

2.5.12 – 2019-04-08
...
Fix: Removed source map reference from minified versions of JS files (#7082)
...

**Comment by burblestudio** [comment]
@KingYes Unfortunately, it does not look like this issue is fully resolved. I'm still seeing the 404 .js.map errors noted above in 2.5.13

![Screen Shot 2019-04-12 at 6 35 09 AM](https://user-images.githubusercontent.com/32874432/56034695-ad89bb00-5ced-11e9-9379-f30e0fd97628.jpg)

This is in Firefox and Chrome. Have not tested in all browsers.

**Comment by CelesteGodwin** [comment]
I am seeing this error too. The common-modules.js.map is giving a 404 error message.

**Comment by clarkngo** [comment]
Mine as well.
![image](https://user-images.githubusercontent.com/30854108/56181170-37bd7200-5fc1-11e9-96ea-9057c1ab964d.png)

**Comment by giladrom** [comment]
Same here. Using the latest versions of both Elementor and Elementor Pro.

**Comment by PauloBoaventura** [comment]
Here too, although not using ELEMENTOR. Only a basic and initial installation ...

**Comment by eugenevdm** [comment]
@PauloBoaventura this is an Elementor issue tracker for issues that's Elementor related. Furthermore what Basic and Initial installation are you referring to?

**Comment by legion-support** [comment]
Same issue, so sad.  Elementor Pro, up to date.

**Source-Map-Error: Error: request failed with status 404**
**Ressources-Address: /assets/lib/pickr/pickr.min.js?ver=1.4.7**
**Source-Map-Address: pickr.min.js.map**

No Solutions ?

**Comment by kirchnerto** [comment]
Same here as @legion-support :/

**Comment by hungryjos** [comment]
Same issue.

**Comment by AxelDeneu** [comment]
Regenerating CSS and synchronizing libraries solved the problem for me.
Go to Elementor > Tools > General to do this :)

**Comment by projectpi-ca** [comment]
Same issue with Elementor v2.9.2 & Elementor Pro v2.8.4

**Comment by mattymouse** [comment]
I'm having the same problem with v.2.9.2 & Pro v.2.8.4 as well.

**Comment by ClaireDMT** [comment]
Same issue with Elementor Version 2.9.3

**Comment by joshchretien** [comment]
Has this been fixed? Its been over a year....

**Comment by anythingituk** [comment]
Same issue here. Uploaded the swiper.min.js.map (from link provided in thread #5151) to wp-content/plugins/elementor/assets/lib/swiper/ BUT still get the "DevTools failed to parse the SourceMap .."

The downloaded file does not look minified though.

**Comment by anythingituk** [comment]
Another update.  Possible 'fix'

Editing the file **swiper.min.js**  in folder _wp-content/plugins/elementor/assets/lib/swiper_ and remove this: `//# sourceMappingURL=swiper.min.js.map` has removed the parsing error from the DevTools log for me

**Comment by vilm725** [comment]
Hi everyone 👋🏼 I've a "possible fix" : copy the `swiper.min.js` of the December 19, 2018 (Swiper 4.4.6) and past in `swiper.min.js`.

For me, it's work ! It's not a perfect solution but it's work. You can check the console in this vps : https://3v12gablsu.preview.infomaniak.website

**Comment by danielmacuare** [comment]
> Same issue, so sad. Elementor Pro, up to date.
> 
> **Source-Map-Error: Error: request failed with status 404**
> **Ressources-Address: /assets/lib/pickr/pickr.min.js?ver=1.4.7**
> **Source-Map-Address: pickr.min.js.map**
> 
> No Solutions ?

I tried the following and worked for me. It removed the error.
1 - Download the file from [HERE](https://github.com/Simonwep/pickr/blob/master/dist/pickr.min.js.map)
2 - Put it on `wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js.map`
3 - Fix the permissions with chwon and chmod 664 to match the same permissions than `pickr.min.js`

**Comment by SaifAlSubhi** [comment]
this issue is still present in v3.5.3

Error 404
assets/css/frontend.css.map
assets/css/common.css.map
...
...

**Comment by Coralie-BDY** [comment]
Hi, I've the same issue now with latest version of elementor. How can i issue that?
![Capture d’écran 2022-07-19 à 15 02 42 2](https://user-images.githubusercontent.com/58588163/179769983-66cdb2d8-c3b4-40b2-bc39-25493a1c2d90.jpg)

**Comment by bsd-group** [comment]
hi
With many who reported the same issue, I wonder why does this issue not have still solution from the developer

**Comment by ahmedhaffez** [comment]
error present tell today with latest version

**Comment by HamzaMohammadKhan** [comment]
Same checking of a user still appearing 
![image](https://github.com/elementor/elementor/assets/36361756/bc578a90-ee7d-4643-a1cd-e4e01d2a596a)

**Comment by dcivera** [comment]
It still seem like this is an issue. And while it doesn't seem to affect the site's operation, it seems like a big oversight. My logs are full of 404 errors that just shouldn't be there. And it seems to be getting worse. I have issues with 

* frontend.css.map 
* text-editor.2f2f7e0ea1e16387a004.bundle.js.map
* elementor-admin-bar.js.map
* elements-handlers.js.map
* frontend.js.map
* common-modules.js.map
* notes-app-initiator.js.map
* web-cli.js.map
* theme-light.css.map
* frontend-modules.js.map
* webpack-pro.runtime.js.map
* app-loader.js.map
* common.js.map
* dev-tools.js.map

Isn't there any solution?

**Comment by Asinox** [comment]
Still this is happening on Safari!!!

**Comment by badcat** [comment]
::Checks watch:: - yup more than 5 years later...
Disable source map generation is maybe what we're asking for?

**Comment by BluFurr** [comment]
I'm on Elementor 3.26.3 and Elementor Pro 3.26.2 and get the 404 error on Safari  -  I can't seem to fix it, what is the best solution people have found? Non of the .map files are available on the links in the above messages. 
Thank you!
