### ISSUE TITLE
How can I deactivated the new cookie from elementor?

### ISSUE THREAD

**Issue by elementlex** [elementor/elementor#7151]
Hello!
This is from Elementor Technical Support:
<Thank you for the clearing it up. I'm not sure that there would be a mechanism to remove that, Cookies and LocalStorage / SessionStorage are not the same thing, LocalStorage isn't sending data to a server it only works on your browsers, therefore, it's not infringing on any GDPR regulations, Elementor doesn't collect any information from your site.
In any case, on this channel, we really don't know if it can be removed or not if you'd like to consult directly with our developers you can do so on our Github issues page below, they will be able to provide a concrete answer:
https://github.com/elementor/elementor/issues
Sorry for the inconvenience. >

My question:
The point is that after the Elementor update to version 2.4.6 and after the Elementor Pro update to 2.4.4 a "cookie" from elementor appears. This cookie can be found in the Safari-Browser-Inspector, or Firefox-Browser_Inspector under: Local storage and session storage

Local Storage: elementor | { "__Expiration": {}, "page views" 1, "sessions" 1}
Session Storage: elementor | { "__Expiration": {}, "active session": true}

How can I deactivated the new cookie from elementor?

I hope someone can help me.
Best Regards

**Comment by shilo-ey** [comment]
Hi @elementlex 

This is not a cookie, but local storage that is located on the visitors' local computer.
The local storage is used for the popups to enable the Advanced targeting.

If you don't want to use local storage please remove the popups from your page.

Thanks.

**Comment by elementlex** [comment]
Hi shilo-ey!
Please excuse me, but the "cookie" will appear on all websites that I have created with Elementor. I do not use Elementor popups!
Could you please help me. I fight here in the EU with the law "DSGVO".
One example:
----
elementor
cuxclean.de
HTML
Session
Zuerst gefundene URL: https://cuxclean.de/
Cookie Zweck-Beschreibung: Nicht klassifiziert
Initiator: Skript-Tag, seite quellzeilennummer 819
Quelle: https://cuxclean.de/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=2.4.6
----

Best Regards

**Comment by shilo-ey** [comment]
Hi @elementlex 

I'm sorry for the misunderstanding, I accidentally misled you in the previous comment.

Currently, the only way to disable the local storage for users is to deactivate Elementor Pro.

We will try adding an option to block local storage soon.

Thanks.

**Comment by elementlex** [comment]
Hi shilo-ey!
Thank you very much for your answer! I will wait...

Kind regards

**Comment by AeonFr** [comment]
I was very careful not to leak any cookie since this was a requirement from the client. Today I found out my site is technically violating the cookie law ([since localStorage is considered a cookie](https://softwareengineering.stackexchange.com/a/290571/250675)) and it's because of a function I don't even use...

Just think you should be more careful before leaking something like this into thousands of sites, since you are compromising us.

Please fix this ASAP!

**Comment by AeonFr** [comment]
I was able to disable this for my site by calling this script in the footer of my theme, before calling `wp_footer()`.


``` html
<script>
        // Solves issue https://github.com/elementor/elementor/issues/7151
        // localStorage.clear() or .removeItem()
        // woudn't work.
        // I'm guessing Elementor usses assignment like this: localStorage.elementor = ''
        // Also there's some script that registers the localStorage and sessionStorage items
        // again after certain navigation actions. There's also a fallback to indexedDB in place.
        // This piece of code is ugly but it solved the problem.
        delete window.localStorage;
        delete window.sessionStorage;
        delete window.indexedDB;
</script>
```

**Comment by elementlex** [comment]
Great, a light on the horizon!  Can you please tell me exactly where to place the script?
![F8937D0E-5E78-44BC-8678-ED9BCD969F2E](https://user-images.githubusercontent.com/47846417/62427442-342a3400-b6f3-11e9-9358-8dc812264880.jpeg)

**Comment by AeonFr** [comment]
You would call it immediately before the line that says

```
<?php wp_footer(); ?>
```

Between line 47 and 48

**Comment by elementlex** [comment]
Thanks a lot, I will try

**Comment by AeonFr** [comment]
Also please notice this script disables the global access to the
localStorage and sessionStorage interfaces, which means it could
potentially break other plug-ins that also want to register this type of
"cookies" on your site. That's why I dont consider it a "clean" solution.

**Comment by elementlex** [comment]
Hello, first of all many thanks!!!
Since I have realized many projects with elementor pro, I will not use the script here in the EU. We have to name all cookies here in the EU (GDPR). I have done that everywhere now. I refer to the statement of elementor (https://docs.elementor.com/article/485-popup-faqs)
<img width="712" alt="elementor popup" src="https://user-images.githubusercontent.com/47846417/62527276-1bc53100-b83b-11e9-9532-aa6a210b1882.png">
<img width="657" alt="elementor cookiebot" src="https://user-images.githubusercontent.com/47846417/62527300-27185c80-b83b-11e9-89e6-2d6a7a103612.png">


I hope that's good.

**Comment by AeonFr** [comment]
I'm no expert but I think it's enough. In my case, I didn't considered necessary to keep the cookie since my site doesn't use any cookie at all, so I prefer not to show any kind of pop-up.

Specially considering the cookie that elementor registers is to provide a functionaliry that is not even used on my site.

But as far as my understanding of GDPR, as long as you ask for consent (and don't register any cookies before having consent), it should be fine. Since this kind of cookies in particular are stored on the user device only, you should make sure the user accepts the cookie message before the data of those cookies is submitted back to elementor.

Im not sure how that would work since I don't use that elementor function and dont know how it works, but an audit using the chrome developers tool "network" tab might show it.

If the user decides not to accept the cookies, you should consider whether you want to block access to the site completely, or offer the service nevertheless. In the second case scenario, you should find a way to avoid elementor from reaching the server with that data.

But this law applies mostly to online tracking. Since this Elementor function probably only stores anonymous data and generic user interaction (I hope it works that way, Ive never used it really so I dont know), it would qualify as "anonymous" data in which case the law is less strict.

Im not legal expert but I think what you did qualifies as a good way to handle the collection of anonymous data.

Hope it helps.

**Comment by mgustavs** [comment]
Is that future near yet?  :)

**Comment by mgustavs** [comment]
Thank you @AeonFr for this dirty snippet!!

(A follow up on other plugins - I used Head and Footer Scripts Inserter to place it at the beginning of the footer and so far so good!)

This all, however, raises a question to Elementor - @shilo-ey: I love your stuff (the reason I have paid for Pro), but I am puzzled on one thing here - 
how can I as a regular 'code-dummy' (the reason I am buying Elementor Pro) comply with ePrivacy/GDPR in case of a web visitor, given the choice to opt-out he deserves, denies any localStorage/sessionStorage on his machine?...

As far as it goes with Elementor Pro GDPR cookie pop-up - it only informs but does not actively block cookies and sessions prior consent (or I miss where these settings are?...)

And if I put it together it looks like - One pays Elementor for extra functionality (other than popups) and in reverse that runs him/her into "cookie trouble" without a solution to it. Only another paid cookie on top solves it... Hereto I add my vote - would be lovely (and reasonable I think) to see a cookie consent pop-up from Elementor, which not only looks nice, but also solves the internal storage issue by actively blocking it and other cookies prior consent.

Thank you for reading and consideration!

**Comment by sachaandre** [comment]
Hey, we are near december and more than 9 months have passed since you promised an option to disable local storage.

Is there some news ? Because "deactivating Elementor Pro" is not an option for me now...

**Comment by elementlex** [comment]
Hello, I'm still waiting for that too!  Can I somehow help make something happen?

**Comment by olligit-design** [comment]
Hello,

is there any chance for a solution?

Perhaps the ability to deselect individual options, especially for the popup?

Thanks in advance

Olli

**Comment by Joe-Benson** [comment]
Same from my side. This is really a mess. I will not pay that much money for Elementor Pro when Elementor is not possible to remove this cookie that is not neccessary and just causes trouble with Cookiebot and other DSGVO tools. If it is neccessary for pop ups to work, these needs to be optional. 
Does not make sense to clean websites from cookies and to have Elementor always placing a cookie altough no pop up is in use.

**Comment by ianstudio** [comment]
This thread was started a year ago.. Could the Elementor team please rise up to the occasion, and maybe communicate about this at least, maybe make a video on their Youtube channel about it. Adding insult to injury this is an issue that plagues only the pro version it seems, maybe pro users deserve little more than others ?

**Comment by docfour** [comment]
Dear Elementor Team,
just a little bit of clarification. According to the [ article 5 (3) of eprivacy directive 2002/58/EC](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32002L0058) access to storage of the browser is only allowed if the user consented (GDPR article 6 (1) lit. a) or if the access is strictly necessary in order to provide or operate the service.

In both cases this means that European users of elementor pro should provide their users with detailed information about what data is stored in local storage according to article 13 GDPR. 

You statement to storage of information in local storage was 

- first that it is necessary for popups and then 

- that it is necessary for elementor pro.

I am running two sites, one with popups the other without popups. Bothe store data in local storage. 
Could you please provide us with more detailed technical information on

- why it is strictly necessary for the functionality of elementor pro to store information in  local storage and what information is stored there in detail
- what information according to popups is stored in local storage

I kindly suggest to disable storage of information in local storage if no popup feature is used. If however this storage is strictly technically necessary for the functionality of elementor pro, then please provide us with more detailed information so that European users can fullfill the legal obligations and correctly inform their website visitors.

Thanks and best regards,
Andreas

**Comment by black-eye** [comment]
I've just run across this problem. This is really inconvenient.

@shilo-ey wrote more than a year ago:
> Currently, the only way to disable the local storage for users is to deactivate Elementor Pro.

Really? I never use a popups on 90% of my sites, and if I don't want to have have your cookies on my site, I should deactivate the PRO version?  PRO version I'm paying a licence for every year since 2017. 

> We will try adding an option to block local storage soon.

When this soon comes in your terms?

Elementor team doesn't miss a chance to claim that, their builder is not bloated and no additional code is aded unless the feature is used. But reality is this. All your users in EU are basicaly (and unknowingly) breaking the law using your product.

**Comment by ianstudio** [comment]
Does the Elementor team even care to answer? This is surreal.

**Comment by isotropicdesign** [comment]
Quick question as we are doing a piece on this local storage issue. 

For you EU guys, is this localstorage absolutely non compliant (so by using E Pro, you site could never be compliant unless this is fixed), or can you make the site compliant with the regulations by simply disclosing this to your visitors? 

Should be the case if this local storage is _strictly necessary_, right? But due to that code snippet, you can obviously disable this and E Pro still works -- therefore it's not strictly necessary -- so you'd need to allow a user to opt out, which cannot be done. 

Thoughts?

**Comment by albertvisuals** [comment]
Elementor 3.0 is released and this issue is still here. That cannot be true...
Could be so easily fixed to just be able to disable the pop-up capability in the Elementor admin area.

**Comment by fdgithubby** [comment]
Working as privacy officer and having a website built with elementor drives me nuts, so please come up with a solution for this long running issue

**Comment by steevnDE** [comment]
Is there any news yet?

**Comment by elementlex** [comment]
Please take the script of Francisco Cano!
This is currently a possibility.

**Comment by mkattner** [comment]
When can we expect a solution?

**Comment by black-eye** [comment]
> When can we expect a solution?

Well 2 years ago @shilo-ey said they would be adding this option soon. So probably in a year or five. We all will be using a different page builder by then probably... :-( So sad I have to say that...

**Comment by albertvisuals** [comment]
I have moved to OxygenBuilder and am really happy with it!

**Comment by stefanullinger** [comment]
Hi, I think another easy way to prevent Elementor from writing into the local and session storage would be to override the getter and setter methods of `elementorFrontend.storage` with some empty functions.

```
<script>
  (function() {
    jQuery( window ).on( 'elementor/frontend/init', function() {
      // Wait for elementor to be initialized. 
      // Then override elementorFrontend.storage.get and elementorFrontend.storage.set with empty functions,
      // to block Elementor from writing or reading anything there.
      if (elementorFrontend && !elementorFrontend.isEditMode() && !elementorFrontend.isWPPreviewMode()) {
        elementorFrontend.storage.get = function() {}
        elementorFrontend.storage.set = function() {}
      }
    });
  })();
</script>
```

Since [Elementor Pro 3.1 introduced 'Custom Code'](https://elementor.com/blog/introducing-pro-3-1/), you could easily add the code above there.

<img width="1431" alt="disable-elementor-frontend-storage" src="https://user-images.githubusercontent.com/2063870/108623192-ecd2d800-743d-11eb-8264-e653443e9fd3.png">

**Comment by dasigna** [comment]
... this ist just another VERY annoying thing with elementor!

two years ago (!) it was mentioned to "_try to_ implement it soon" ... 'soon' again in the terms of elementor.

whats annoying about this?
the thing is that there are still many remaining and (mostly 'little') things to solve, but they keep on releasing 'important features' before doing so.

why bothering about a 'cookie' that even isnt one?
we're very careful to deliver cookie-free websites to clients. so theres a client that inspects the website and discovers this local storage thing. bad vibes.
and now i have to tweak something because of a function that is not even used? i have a feeling, that this is more than poor software design ...
sheer lazyness where it is not appropriate at all in times of gdpr compliance and all that what comes along with it.

cant comprehend at all why this takes place even where popups are not even used.
cant comprehend why this cant be deactivated. that complicated?

there would be an easy solution anyway - if elementor might finally apply the global ability to activate/deactivate used (or not) widgets and functions!
nearly every simple plugin author (for elementor extensions e.g.) is able to make this happen - elementor itself again is unable to deliver such a basic ability.

at the end we have to deal with unneccesary problems and angry clients. is elementor bothered? i fear the answer ist 'no'.

just simple poor for a 'top notch', 'premium' and whatever piece of software. shame on elementor.

**Comment by stefanullinger** [comment]
Hi @dasigna, I totally agree with you! I am also very frustrated about Elementor not fixing these very fundamental things. I understand that things have different priorities, but after working on 3-4 different websites, I found about 10 issues that are very fundamental. I will get rid of Elementor as soon as possible. I tried Oxygen now, but they have similar fundamental issues. Some of them are also open for years now and no one cares about them. I think it is time to build my very own editor now that get's these fundamental things right from the beginning.

**Comment by RalphGL** [comment]
> We will try adding an option to block local storage soon.

I am Elementor PRO Customer in 2nd year now, creating sites for medium sized and large companies in Germany. Without a solution of this problem there will be no future with elementor for me and my customers. What exactly was the meaning of "soon" in  the comment of shilo-ey in February 2019?

**Comment by geonom** [comment]
> 
> 
> Hi @elementlex
> 
> I'm sorry for the misunderstanding, I accidentally misled you in the previous comment.
> 
> Currently, the only way to disable the local storage for users is to deactivate Elementor Pro.
> 
> We will try adding an option to block local storage soon.
> 
> Thanks.

Seriously, the "solution" you still offer is to disable Elementor Pro... will do and may cancel my subscription - just got an official letter from German authorities due to this cookie not being compliant with German GDPR regulations. You are losing customers this way by not solving a two year old issue.

Not happy.

**Comment by docfour** [comment]
Hi @geonom 
I know it is annoying not getting a solution but I would be interested in the content of the letter from the German authorities as I am a data protection consultant and think that it is so possible to describe the cookie as technically necessary. 

Am 22. April 2021 22:51:22 MESZ schrieb geonom ***@***.***>:
>> 
>> 
>> Hi @elementlex
>> 
>> I'm sorry for the misunderstanding, I accidentally misled you in the
>previous comment.
>> 
>> Currently, the only way to disable the local storage for users is to
>deactivate Elementor Pro.
>> 
>> We will try adding an option to block local storage soon.
>> 
>> Thanks.
>
>Seriously, the "solution" you still offer is to disable Elementor
>Pro... will do and may cancel my subscription - just got an official
>letter from German authorities due to this cookie not being compliant
>with German GDPR regulations. You are losing customers this way by not
>solving a two year old issue.
>
>Not happy.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/elementor/elementor/issues/7151#issuecomment-825176822

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by geonom** [comment]
Just a heads up, I got a notice by Elementor support, this is their answer:

"I wanted to let you know, that I have just checked this case with our superiors and unfortunately, this is still on the table. All the feature requests are prioritized and some of them are pending until the other ones will be well tested and released. I can't tell you any ETA on this certain issue, but I want to ensure you that we do understand the importance of this feature."

And all this two years after the issue was raised to their attention. Speaks volumes by itself - this is not customer support but customer torture while putting paying customers in Europe needlessly in legal perril.

**Comment by geonom** [comment]
> <script>
>   (function() {
>     jQuery( window ).on( 'elementor/frontend/init', function() {
>       // Wait for elementor to be initialized. 
>       // Then override elementorFrontend.storage.get and elementorFrontend.storage.set with empty functions,
>       // to block Elementor from writing or reading anything there.
>       if (elementorFrontend && !elementorFrontend.isEditMode() && !elementorFrontend.isWPPreviewMode()) {
>         elementorFrontend.storage.get = function() {}
>         elementorFrontend.storage.set = function() {}
>       }
>     });
>   })();
> </script>

Is this still working for someone? Because it does not work for my Elementor Pro page with the latest Elementor Pro version.

**Comment by stefanullinger** [comment]
Hey @geonom, I just tried again with a fresh site and the latest Elementor version. I think I forgot to wait for jQuery to be ready. ... That's also the next thing they did not get right: They have implemented custom code, but you can not set some dependencies. 🙈

Here is some new code that waits for jQuery to be ready.

```
<script>
  (function() {
    function init($) {
      jQuery( window ).on( 'elementor/frontend/init', function() {
        // Wait for elementor to be initialized. 
        // Then override elementorFrontend.storage.get and elementorFrontend.storage.set with empty functions,
        // to block Elementor from writing or reading anything there.
        if (elementorFrontend && !elementorFrontend.isEditMode() && !elementorFrontend.isWPPreviewMode()) {
          elementorFrontend.storage.get = function() {}
          elementorFrontend.storage.set = function() {}
        }
      });
    }
    
    var waitForJQuery = setInterval(function () {
      if (typeof jQuery != 'undefined') {
        init(jQuery);
        clearInterval(waitForJQuery);
      }
    }, 10);
  })();
</script>
```

**Comment by dasigna** [comment]
--- whilst updating a site currently, tested this a second ago - and even the former code still seems to work perfectly :)

**Comment by stefanullinger** [comment]
Yes, I think @geonom is right – it does not seem to be working anymore. Seems like the way elementor components are loaded might have changed?!

**Comment by stefanullinger** [comment]
Hey @geonom and @dasigna, so let's remove everything that Elementor might have stored during initialization then:

```
<script>
  (function() {
    function init($) {
      jQuery( window ).on( 'elementor/frontend/init', function() {
        // Wait for elementor to be initialized. 
        // Then override elementorFrontend.storage.get and elementorFrontend.storage.set with empty functions,
        // to block Elementor from writing or reading anything there.
        if (elementorFrontend && !elementorFrontend.isEditMode() && !elementorFrontend.isWPPreviewMode()) {
          elementorFrontend.storage.get = function() {}
          elementorFrontend.storage.set = function() {}
          
          if (window.sessionStorage) {
            window.sessionStorage.removeItem('elementor');
          }
          
          if (window.localStorage) {
            window.localStorage.removeItem('elementor');
          }
        }
      });
    }
    
    var waitForJQuery = setInterval(function () {
      if (typeof jQuery != 'undefined') {
        init(jQuery);
        clearInterval(waitForJQuery);
      }
    }, 10);
  })();
</script>
```

**Comment by geonom** [comment]
Thanks a lot, that [last script version ](https://github.com/elementor/elementor/issues/7151#issuecomment-833793008 )seemed to work!

Lets hope it does not break with elementor updates ;)

**Comment by dasigna** [comment]
yep. works again:)

big thanks to @stefanullinger for looking behind this!!

sad anyway this still has to be tweaked.
wondering about the fact that obviously someone at elementor has tweaked this behaviour without solving the issue ...

speaks volumes - doesnt it?

**Comment by Stufuyi** [comment]
Hey everyone - I am glad I found this thread. I just recently started using Elemtor and created my site with it. Now I stand before the same problem as everyone here and try to remove the local storage usage on my website due to GDPR compliance. 
I tried implementing @stefanullinger 's script via the custom code feature in Elementor as you can see at the screenshot. But it is giving me some warnings and unfortunately did not work. Elementor is still loading stuff in the local storage. Thank you first of all for even providing such a script, but if possible could you maybe have a look what I am doing wrong? Since it seemed to work for @dasigna and @geonom .

Thanks already!
![elementor_Script_Localstorage](https://user-images.githubusercontent.com/84711321/119331500-b482a600-bc87-11eb-8ea7-7ea18a0fe27f.JPG)

**Comment by Stufuyi** [comment]
> 
> 
> Hey everyone - I am glad I found this thread. I just recently started using Elemtor and created my site with it. Now I stand before the same problem as everyone here and try to remove the local storage usage on my website due to GDPR compliance.
> I tried implementing @stefanullinger 's script via the custom code feature in Elementor as you can see at the screenshot. But it is giving me some warnings and unfortunately did not work. Elementor is still loading stuff in the local storage. Thank you first of all for even providing such a script, but if possible could you maybe have a look what I am doing wrong? Since it seemed to work for @dasigna and @geonom .
> 
> Thanks already!
> ![elementor_Script_Localstorage](https://user-images.githubusercontent.com/84711321/119331500-b482a600-bc87-11eb-8ea7-7ea18a0fe27f.JPG)

Nevermind - still works perfectly - thank you very much @stefanullinger !!!!

**Comment by elementlex** [comment]
![A672C252-2D3A-408C-B8C6-1996F915F029](https://user-images.githubusercontent.com/47846417/119340255-966e7300-bc92-11eb-939a-852fc7e68bb6.jpeg)

**Comment by mgustavs** [comment]
Hey @elementlex, the code in the pic looks different from what @stefanullinger was suggesting. Is that what you use? Is it working?

**Comment by mgustavs** [comment]
Hey @elementlex, noticed you use the very first "dirty" snippet by @AeonFr instead of @stefanullinger's solution. What's your reason behind it? Thanks

**Comment by elementlex** [comment]
Thanks again to @AeonFr for providing this script! This works all the time, even after the previous updates from elementor. I use this on myself and on all customer websites.  Welcome GDPR!

**Comment by mgustavs** [comment]
@elementlex and you have not encountered any weird behaviors from other plugins or while visiting the site?

**Comment by trinermedia** [comment]
> Hey @geonom and @dasigna, so let's remove everything that Elementor might have stored during initialization then:
> 
> ```
> <script>
>   (function() {
>     function init($) {
>       jQuery( window ).on( 'elementor/frontend/init', function() {
>         // Wait for elementor to be initialized. 
>         // Then override elementorFrontend.storage.get and elementorFrontend.storage.set with empty functions,
>         // to block Elementor from writing or reading anything there.
>         if (elementorFrontend && !elementorFrontend.isEditMode() && !elementorFrontend.isWPPreviewMode()) {
>           elementorFrontend.storage.get = function() {}
>           elementorFrontend.storage.set = function() {}
>           
>           if (window.sessionStorage) {
>             window.sessionStorage.removeItem('elementor');
>           }
>           
>           if (window.localStorage) {
>             window.localStorage.removeItem('elementor');
>           }
>         }
>       });
>     }
>     
>     var waitForJQuery = setInterval(function () {
>       if (typeof jQuery != 'undefined') {
>         init(jQuery);
>         clearInterval(waitForJQuery);
>       }
>     }, 10);
>   })();
> </script>
> ```

Unfortunately, this no longer seems to work. The entries in Local Storage and Session Storage are not removed.

@shilo-ey Although I consider the information that is stored here to be non-personal, I would welcome the option to disable the creation of this information (also for [the reasons mentioned by docfour](https://github.com/elementor/elementor/issues/7151#issuecomment-593982153)).

**Comment by dasigna** [comment]
yes, unfortunately completely right.

something must have been changed within the latest updates that causes the code to not work anymore.

thats sad.
and to be honest - i am really pissed off facing that case again, as we dont want to have stored ANYthing we dont want to natively regarding GDPR and such. elementor has to adress this asap.

**Comment by stefanullinger** [comment]
Hi @trinermedia & @dasigna,

there is a new checkbox in the custom codes that ensures, that jQuery is loaded: "Always load jQuery".
If you enabled this checkbox, then we do not need to test for jQuery to be loaded.

I am using the following code now, which seems to work:

```
<script>
  (function() {
    function init($) {
      jQuery( window ).on( 'elementor/frontend/init', function() {
        // Wait for elementor to be initialized. 
        // Then override elementorFrontend.storage.get and elementorFrontend.storage.set with empty functions,
        // to block Elementor from writing or reading anything there.
        if (elementorFrontend && !elementorFrontend.isEditMode() && !elementorFrontend.isWPPreviewMode()) {
          elementorFrontend.storage.get = function() {}
          elementorFrontend.storage.set = function() {}
          
          if (window.sessionStorage) {
            window.sessionStorage.removeItem('elementor');
          }
          
          if (window.localStorage) {
            window.localStorage.removeItem('elementor');
          }
        }
      });
    }
		
    init(jQuery);
  })();
</script>
```

**Comment by trinermedia** [comment]
@stefanullinger Thank you for looking into this once again! I can confirm, this last version of your code in combination with the mentioned checkbox works. 
Still, I hope this is the last time you've had to update your workaround, because Elementor has finally implemented a native solution.

**Comment by Grendelkeep** [comment]
Hi mates,

I have since 2 years the same damn problem. I use the pro version and I am based in EU. My site has only one Cookie and that is ELEMENTOR lol....

Can some one create some custom code for that specific problem? I would pay for this. Elementor support is close to zero here :(

**Comment by elementlex** [comment]
I am using the code with success in creating law compliant websites for businesses in the EU.
You don't have to pay anything!  The solution and the code is available.  Many thanks again to [@AeonFr] for providing this script!

**Comment by Grendelkeep** [comment]
> I am using the code with success in creating law compliant websites for businesses in the EU.
> You don't have to pay anything! The solution and the code is available. Many thanks again to [@AeonFr] for providing this script!

I use the latest Elementar version and with Firefox Console it shows still one Elementar Cookie. Have the Snipped added in Footer Section (Before).

**Comment by elementlex** [comment]
<img width="993" alt="screen_2022-06-24" src="https://user-images.githubusercontent.com/47846417/175475852-b9ba9620-d83c-4602-be69-681447cbe227.png">
<img width="493" alt="screen2_2022-06-2" src="https://user-images.githubusercontent.com/47846417/175475950-f548bd9b-7ff7-4c19-98d6-23d959575212.png">

To avoid using a heavyweight child theme, you can use WPBeginner’s Insert Headers and Footers plugin. Then paste the script as shown.

**Comment by JGrossholtz** [comment]
A website without the need for any cookie consent is a great way to differentiate from the rest of the web. Please implement this feature event if it disable some other features (tell us so if you need to.)

**Comment by fido-hh** [comment]
No news yet?
The suggested workarounds doesn't fix the problem. 

- When stored and deleted afterwards, it is still a violation of the GDPR, since those popups clearly serve marketing purposes.
- There seems to be no way to implement this into a cookie banner.

Please provide a solid solution, otherwise i have to move back to the free version for all my customers websites.

**Comment by ofmarconi** [comment]
### **Please provide a solid solution**

**Comment by TiDiCom** [comment]
Wow that's really annoying that Elementor is not taking privacy laws for EU countries seriously. I am also in the opinion that the user needs to give active consent before storing anything locally on their devices...

A simple Elementor checkbox to disable this shouldn't be too complicated to add as a feature...

(German Elementor Pro Customer)

**Comment by mlazzje** [comment]
Same here, the only cookie on my Website is because of Elementor pro...

**Comment by ofmarconi** [comment]
looks amazing!

**Comment by t0b1hh** [comment]
thanks @sngm  for the vanilla version. works fine for me :)

**Comment by t0b1hh** [comment]
thanks @sngm for the vanilla version.  Seems to work fine, if added as early as possible in the code ( e.g. `<head>` section). 

When just appended to the footer it could happen, that the elementor storage method runs before we unset that stuff, resulting in existing localstorage data for some milliseconds, that will get removed again as soon as our event handler got triggered.

**Comment by davidpfahler** [comment]
Hi all, I am an attorney-at-law in Germany and advise clients on data protection and privacy laws. Unfortunately, not only is this a show stopper for all enterprises wanting to use elementor pro and be in compliance with EU and national law, but also are all the solutions proposed above not correct (legally speaking). As the JavaScript code between the `<script>` tags only executes locally AFTER the localStorage or sessionStorage items have already been set. Even if these values are only set for a split second, the violation of the law has already been committed. Hence, **please notify the C-suite that this is a show stopper for EU customers.**

**Comment by elementlex** [comment]
Thank you for your approach to the solution. As a lawyer, you certainly focus more on specific legal disputes. Nowadays you can use Elementor Pro without a script, GDPR compliant.

**Comment by fido-hh** [comment]
> Thank you for your approach to the solution. As a lawyer, you certainly focus more on specific legal disputes. Nowadays you can use Elementor Pro without a script, GDPR compliant.

No, you can't. 
I am a web developer with 20 years of experience and a certified DSB (Datenschutzbeauftragter), and I can tell you that you can't use Elementor Pro in germany.
This is not because of the GDPR, but the TTDSG in Germany:

> § 25 Schutz der Privatsphäre bei Endeinrichtungen
(1) Die Speicherung von Informationen in der Endeinrichtung des Endnutzers oder der Zugriff auf Informationen,  die  bereits  in  der  Endeinrichtung  gespeichert sind, sind nur zulässig, wenn der Endnutzer auf der Grundlage von klaren und umfassenden Informationen eingewilligt hat. Die Information des Endnutzers und die Einwilligung haben gemäß der Verordnung (EU) 2016/679 zu erfolgen.
(2) Die Einwilligung nach Absatz 1 ist nicht erforderlich,
wenn die Speicherung von Informationen in der Endeinrichtung des Endnutzers oder der Zugriff auf bereits in der Endeinrichtung des Endnutzers gespeicherte Informationen unbedingt erforderlich ist, damit der Anbieter eines Telemediendienstes einen vom Nutzer ausdrücklich gewünschten Telemediendienst zur Verfügung stellen kann.

Since the localStorage-Entry clearly serves Marketing-Purposes (Popup), this is a violation of TTDSG $25 Abs.1

**Comment by elementlex** [comment]
Whether 20 or 100, it works! Before you articulate something, it makes sense to get better and more comprehensive information. Since I am in contact with the LfD in Germany, I think that your statement is not true...

**Comment by elementlex** [comment]
In 2023 you can use Elementor pro without localStorage.

**Comment by geonom** [comment]
How so? For all the installations old and new of Elementor Pro, the cookie is still set? Can it finally be deactivated?

**Comment by ofmarconi** [comment]
Guys, has it been detected which Hook is? If we write an MU, it will be executed right after the CORE, and then we could unlist this Hook.

**Comment by tsteur** [comment]
If you don't like to remove this localStorage/cookie for everyone, could you at least provide an option to disable it since it's clearly not ok for many people?

**Comment by tsteur** [comment]
Hi everyone,

below worked for me to prevent the setting of the value in the first place as deleting after it's been set would have still been problematic for us. 

In below example we're still setting the storage if someone is logged in as our end-users don't log in and I wasn't sure if the editor could break by completely removing it for logged in users.

```php

function prevent_elementor_storage() {
    if (is_user_logged_in()) {
        return;
    }
    echo '<script type="text/javascript">
const originalSetItem = Storage.prototype.setItem;

Storage.prototype.setItem = function(key, value) {
  if (key === "elementor") {
    // Prevent setting the specific key elementor for privacy compliance
    return;
  }

  originalSetItem.call(this, key, value);
};
</script>';
}
add_action( 'wp_head', 'prevent_elementor_storage', 0 );
```

**Comment by geonom** [comment]
> Hi everyone,
> 
> below worked for me to prevent the setting of the value in the first place as deleting after it's been set would have still been problematic for us.
> 
> In below example we're still setting the storage if someone is logged in as our end-users don't log in and I wasn't sure if the editor could break by completely removing it for logged in users.
> 
> ```
> function prevent_elementor_storage() {
>     if (is_user_logged_in()) {
>         return;
>     }
>     echo '<script type="text/javascript">
> const originalSetItem = Storage.prototype.setItem;
> 
> Storage.prototype.setItem = function(key, value) {
>   if (key === "elementor") {
>     // Prevent setting the specific key elementor for privacy compliance
>     return;
>   }
> 
>   originalSetItem.call(this, key, value);
> };
> </script>';
> }
> add_action( 'wp_head', 'prevent_elementor_storage', 0 );
> ```

![grafik](https://github.com/elementor/elementor/assets/1165081/e6c563b0-3b93-46b6-b59e-0ecc88182ea9)

Sadly that does not seem to work in our case. See the attached screenshot of the page with your script in private browser mode.

Thanks for your efforts and those of the others, as Elementor keeps ignoring its customers.

**Comment by geonom** [comment]
@arielk You wrote in 2019 you wanted to deal with this issue...

Any progress or plans apart from ignoring the legal issues for your European customers?

**Comment by geonom** [comment]
> Hi everyone,
> 
> below worked for me to prevent the setting of the value in the first place as deleting after it's been set would have still been problematic for us.
> 
> In below example we're still setting the storage if someone is logged in as our end-users don't log in and I wasn't sure if the editor could break by completely removing it for logged in users.
> 
> ```
> function prevent_elementor_storage() {
>     if (is_user_logged_in()) {
>         return;
>     }
>     echo '<script type="text/javascript">
> const originalSetItem = Storage.prototype.setItem;
> 
> Storage.prototype.setItem = function(key, value) {
>   if (key === "elementor") {
>     // Prevent setting the specific key elementor for privacy compliance
>     return;
>   }
> 
>   originalSetItem.call(this, key, value);
> };
> </script>';
> }
> add_action( 'wp_head', 'prevent_elementor_storage', 0 );
> ```

This is a theme script rather than an Elementor Custom Script, do I understand that correctly? So I would apply it in the footer of a child theme?

**Comment by tsteur** [comment]
> This is a theme script rather than an Elementor Custom Script, do I understand that correctly? So I would apply it in the footer of a child theme?

Indeed, we put this into the "functions.php" of our custom child theme.

**Comment by AidanAJoyce** [comment]
<!DOCTYPE html>
<body style="font-family: Arial, sans-serif; background-color: #f4f4f9; margin: 0; padding: 20px;">

<div style="background-color: #ffffff; border-radius: 8px; padding: 20px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); max-width: 600px; margin: auto;">
    <h2 style="color: #333; font-size: 24px;">2019 - 2024 The Elementor Cookie Saga</h2>
    <p style="color: #555; line-height: 1.6; margin-bottom: 12px;">Scrolling from 2019 to 2024 demonstrates that Elementor neither take GDPR or their paying customers seriously</p> <p>@tsteur, I have a few questions regarding the use of custom could you have kindly provided here for Elementor users:</p>
    <ul style="color: #555; line-height: 1.6; padding-left: 20px;">
        <li>Can the provided code be loaded using Elementor Pro 'Custom Code' feature?</li>
        <li>Is it possible to use this without creating a child theme, perhaps through the Code Snippets plugin?</li>
        <li>Do you know if this will affect popups, as many sites use off-canvas menus created with popups, not just for marketing purposes?</li>
        <li>Most importantly, is there a chance you could you provide more detailed steps on how and where this code should be loaded in a standard WordPress setup with Elementor and the Hello Theme?</li>
    </ul>
    <p style="color: #555; line-height: 1.6; margin-bottom: 12px;">Many thanks for your efforts and to all the great contributors here who are trying to address this Elementor issue.</p>
    <div style="text-align: right; margin-top: 24px; font-style: italic;">- Aidan</div>
</div>

</body>
</html>

**Comment by tsteur** [comment]
@AidanAJoyce Unfortunately, I don't have the answers for this. I haven't tried the "Custom Code" feature for example. And I've only tried it using a child theme since we had one anyway. We didn't use the popups that require a pageview count so things worked for us just the same. You would maybe need to test this.

As for creating a child theme: There is for example https://wordpress.com/support/themes/child-themes/  that explains this maybe. I then copied above code into `functions.php`. Hopefully this helps

**Comment by werk21** [comment]
Anything news here? Elementor (Pro?) sets cookies regardless of whether pop-ups are used. So there isn't even a meaningful purpose in a declaration of consent. Can this at least be converted so that a cookie is used when at least one popup is created? This is really nonsensical and violates the GDPR and the TTDSG, which requires consent BEFORE any storage in the browser.
Thank you, Kelly.

**Comment by louiswol94** [comment]
Hi everyone,

We just merged a fix for this in Elementor Pro which closed this issue. It should be available in v3.25. If you do not have any popups these Local Storage and Session Storage will not be added.

Kind regards

**Comment by t0b1hh** [comment]
Took only 6 years 😂

Thanks anyway!

**Comment by black-eye** [comment]
Well, in fact it's actually still not resolved - the solution was just merged into the dev version, which is not even in beta, so we cannot test it yet. But yes, let's appreciate it was finally taken care of and let's hope it will work.
