### ISSUE TITLE
"Disable Page Scrolling" for Popups always scrolls to top of page

### ISSUE THREAD

**Issue by booth1** [elementor/elementor#7361]
Hi all, I have created a page which uses Popups to display our Team when a link is clicked. The problem I have is that when "Disable Page Scrolling" is on for the popup, if you open a Popup then close it the page has always scrolled back to the top of the page no matter where you were before. It does this on mobile and Desktop, and it does this whether you scroll the Popup or not.

Latest Wordpress, Latest Elementor free and Pro, latest Astra Pro theme. 

Appreciate any help

**Comment by shilo-ey** [comment]
Hi, 

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* **Prerequisites.**
* Steps to replicate.
* Isolating the problem.
* System info.

We simply couldn't reproduce this issue.

thanks.

**Comment by booth1** [comment]
My apologies for jumping in. I continued bug testing and when I got around to the theme discovered it is an issue with Astra theme as others are not reproducing the issue. I will continue to troubleshoot and see if I can isolate it to a part of Astra and then go to their support forums. I hope this helps someone else with Astra themes though.

Thanks for your time

**Comment by chetanbgreen** [comment]
Hi booth1

**Comment by FlorianW7** [comment]
@booth1 did you manage to solve that problem? I have the exact same behaviour, but I'm using a different theme (jupiterx).

**Comment by rukianthony** [comment]
I'm also having the same problem but for a different theme (Ocean WP)

**Comment by Willtpf123** [comment]
Did anyone have any luck with this? Having the same issue with Astra theme. @booth1 did you get any further with your investigation.

**Comment by robertp2013-06-24** [comment]
I am using Elementor's Hello theme with the Elementor plugin and I can confirm this same problem is happening to me as well.

**Comment by draganche77** [comment]
Same problem. Please fix this! Thanks.

**Comment by lukealexander93** [comment]
Same problem happening for me and I am using Generate Press theme. Has this been resolved yet for anyone?

**Comment by ob2a** [comment]
I found the solution. It is the problem if you have add a "simple" overflow hidden to the body. So add !important only to the body (not to html tag), it solves the problem : body {overflow-x: hidden !important;} 
;)

**Comment by Brrl** [comment]
@ob2a This did not fix the issue for me. Elementor is adding an overflow:hidden to the body when "Disable Page Scrolling" is set, this is causing it to scroll to the top, my guess is some javascript is going to have to be added to the pages to get this temporary fixed till Elementor adds this fix to their popups

**Comment by arvin-top** [comment]
hi guys 
I designed the home page of my site with elementor, and when I scroll down, the scroll comes up. Where does this problem come from?

**Comment by EmerKelly** [comment]
I had this same issue with Elementor's Hello Child theme. 

For me, it turns out it was my own error. I had set the popup to trigger by selector and added a custom link to the navigation, using the selector as the CSS class. I added a # in the link field, as that's what I usually do when I want a blank link. It's the # that caused the issue for me though. When I removed it and simply left the URL field entirely blank, it worked perfectly.

Hopefully, this is helpful to somebody.

**Comment by designdust** [comment]
I'm using neve theme with Elementor, had the same issue. Solved it by Disabling Page Scrolling like what he said.

> Hi booth1,
> I am wordpress developer, you can be used an elementor WordPress plugin so, you can go an elementor popup template after go to advance setting then press on "Disable Page Scrolling
> " checkbox.

**Comment by Ssendam0101** [comment]
This bug is still an issue and also listed as recently as 2 months by others on the elementor forums. I also verified that if you try to make a popup with another plugin such as jetpopup, it has the same issue so this seems to be related to Elementor's core code.

**Comment by IlPizza79** [comment]
Yes, same issue here :-(

**Comment by leonberry** [comment]
Apparently this problem was fixed in a recent build. Not for me, after disabling plugins and working through, I found Steroids for Elementor to be the problem. In particular Poopart. Disabling did the trick.

**Comment by telip007** [comment]
Why is this issue closed? Myself and many others (see issue comments) are still having this issue. @shilo-ey could have a look at this?

**Comment by Mr-Choy** [comment]
hope this can help, it work on my theme.
[https://github.com/Mr-Choy/Elementor-popup-page-scroll-issue-fix](https://github.com/Mr-Choy/Elementor-popup-page-scroll-issue-fix)

**Comment by nevertoday** [comment]
> Had the same problem. I was able to solve it by rendering it on all pages in the popup conditions.

how to fix?

**Comment by Pikamander2** [comment]
Here's the best workaround we've come up with so far:

```
jQuery(document).on('elementor/popup/hide', () =>
{
	let page_scroll_position = document.documentElement.scrollTop;
	setTimeout(function(){document.documentElement.scrollTop = page_scroll_position}, 500);
});
```

However, the timing is a bit awkward and could break at any point.

It's ridiculous that Elementor hasn't fixed this problem after four years.

**Comment by undfine** [comment]
Agreed! 

I personally like @Mr-Choy's solution (modified below). It would great if Elementor simply added a class to the body when a popup is opened. Then we could handle use css to handle the scroll and/or animations. Example:
`
// when popup open  
jQuery( document ).on( 'elementor/popup/show', () => {
  jQuery("html,body").addClass("popup-open");  
});      

// when popup close
jQuery(document).on( 'elementor/popup/hide', () => {
  jQuery("html,body").removeClass("popup-open");
});`

**Comment by lea-pw** [comment]
@Mr-Choy's solution did not work for me, but the approach took me to this solution:

JS:
    document.addEventListener('DOMContentLoaded', function() {
        var html = document.documentElement;
        var body = document.body;
        var popup = document.querySelector('.elementor-popup-modal');

        function addCantScroll() {
            html.classList.add('cantScroll');
            body.classList.add('cantScroll');
        }

        function removeCantScroll() {
            html.classList.remove('cantScroll');
            body.classList.remove('cantScroll');
        }

        if (popup) {
            popup.addEventListener('popupOpen', addCantScroll);
            popup.addEventListener('popupClose', removeCantScroll);
        }
    });

CSS:
html.cantScroll,
body.cantScroll{
  overflow: hidden !important;
}

**Comment by phaelpfer** [comment]
> @Mr-Choy's solution did not work for me, but the approach took me to this solution:
> 
> JS: document.addEventListener('DOMContentLoaded', function() { var html = document.documentElement; var body = document.body; var popup = document.querySelector('.elementor-popup-modal');
> 
> ```
>     function addCantScroll() {
>         html.classList.add('cantScroll');
>         body.classList.add('cantScroll');
>     }
> 
>     function removeCantScroll() {
>         html.classList.remove('cantScroll');
>         body.classList.remove('cantScroll');
>     }
> 
>     if (popup) {
>         popup.addEventListener('popupOpen', addCantScroll);
>         popup.addEventListener('popupClose', removeCantScroll);
>     }
> });
> ```
> 
> CSS: html.cantScroll, body.cantScroll{ overflow: hidden !important; }

You solved? Where u put this code?

**Comment by sam-imprint** [comment]
Fixed this issue with our mobile menu by disabling **Accessible Navigation** in **Popup Settings** > **Advanced**.

Need to look into whether disabling this affects assistive technology on mobile or not.

**Comment by lea-pw** [comment]
@phaelpfer You can put the JS for example in Dashboard > Elementor > Custom Code (location head and for entire site when your navigation is visible on all pages) and the CSS in customizer (Dashboard > Design > Customizer > Custom CSS). Be aware to put a script-tag around and add the nowprocket parameter if you use WPRocket plugin (see screenshot).
<img width="1272" alt="Bildschirmfoto 2023-10-04 um 08 45 29" src="https://github.com/elementor/elementor/assets/75479174/42007ea8-bd5d-4a08-a5e5-cec2001b17d7">

Does this help?

**Comment by AlexTrask91** [comment]
Same problem I tried all the solutions on the page, nothing worked, 4 years old bug, and still unsolved, but after all I am not surprised, there are many others present for years, and still not solved even unofficially.
Good job Elementor, keep up the good work I really need more motivation to drop you for good.

**Comment by AlexTrask91** [comment]
Verify that you have not inserted any css:
html{ overflow-x: hidden}
to me that was causing it

**Comment by jp-infinite-digital-solutions** [comment]
> hope this can help, it work on my theme. https://github.com/Mr-Choy/Elementor-popup-page-scroll-issue-fix

**Worked great** for me. Though, worth mentioning, had to **disable "Disable Page Scrolling"** for it to work. 
If tested and ends being a requirement for it work properly, might be a good idea mentioning it on the README.md file @Mr-Choy 
Thanks!  :+1: :smile:

**Comment by ctl6998** [comment]
> I found the solution. It is the problem if you have add a "simple" overflow hidden to the body. So add !important only to the body (not to html tag), it solves the problem : body {overflow-x: hidden !important;} ;)

This did work for me, I encountered the same problem for a site that was build 2 years ago lol

**Comment by Jeroomvdb** [comment]
Solutions that did it for me: Popup settings > Advanced > Accessible navigation > No

Hope this helps someone.

**Comment by EquilibriumTechx** [comment]
> hope this can help, it work on my theme. https://github.com/Mr-Choy/Elementor-popup-page-scroll-issue-fix

THIS IS the best fixed so far.

**Comment by Sheikh-Abir-Ali** [comment]
**This Solution Works for me in Elementor Pro**

Just disable the _Accessible Navigation_ from the Popup Setting Advanced Section.

![solution](https://github.com/user-attachments/assets/54ec6719-6b60-4147-a477-9d669f50b1be)

**Comment by kremenovic** [comment]
> **This Solution Works for me in Elementor Pro**
> 
> Just disable the _Accessible Navigation_ from the Popup Setting Advanced Section.
> 
> ![solution](https://private-user-images.githubusercontent.com/115291629/359819645-54ec6719-6b60-4147-a477-9d669f50b1be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NjUxNDgsIm5iZiI6MTczMDQ2NDg0OCwicGF0aCI6Ii8xMTUyOTE2MjkvMzU5ODE5NjQ1LTU0ZWM2NzE5LTZiNjAtNDE0Ny1hNDc3LTlkNjY5ZjUwYjFiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQxMjQwNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmQ3ZjI4NjFjN2VlOTIxNjQxMWI2YmMzZDk1ODljNDEyMWJkNDgxMmJmMGI0OGVhN2ZjMDc5MjRmM2MzMGYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MHAFJLP-6WC4md5PdMqSCpxMwlaEWzluHqHsjYf9twY)

Thanks a lot!

**Comment by SiteBoltsAdmin** [comment]
This bug appears to be related to #21409 , although frustratingly that one has been closed and locked.

@nicholaszein - Any way that one or both of these issues could be reopened? They're still an issue in 2025.

**Comment by nicholaszein** [comment]
@SiteBoltsAdmin .

Neither of these issues are related. There is already an issue related to the problem you are reporting, and it's open.

Elementor 6 years ago was extremely different than Elementor is today. The same for the time of the publishing of the other issue you indicated.
