### ISSUE TITLE
Repalce URL Tool Does not replace page background images and custom fonts.

### ISSUE THREAD

**Issue by erfan-ilyas** [elementor/elementor#7376]
## Prerequisites
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

When changing domain the Elementor "Replace URL" Tool does work for everything else, Except 
body background image URL:

I have to manually select the background images again when moving from staging to live site.

## Steps to reproduce

Set up a staging site. Open Elementor and apply background image:

![image](https://user-images.githubusercontent.com/1281946/54014565-fc987980-419e-11e9-9c3e-4e73dc6feff8.png)

Save and once done.

Move to the production or different domain/subdomain.
To update the URL's go to the backend:
Elementor -> Repalce URL TOOL.

![image](https://user-images.githubusercontent.com/1281946/54014645-35d0e980-419f-11e9-95e0-e6c9a740cd93.png)

Replace the URL's it will replace all other URL's except that background image URL.

I guess the Replace URL tools does not also replace the Elementor Custom Fonts as well!

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
Hi @erfan-ilyas 

Please regenerate your CSS files by clicking on Elementor > Tools > General tab > Regenerate CSS
![image](https://user-images.githubusercontent.com/45009641/54083034-2d0b1f80-4327-11e9-84ae-3f62d02e9b4b.png)


This should resolve your issue.

Thanks.

**Comment by erfan-ilyas** [comment]
I tried your suggestion but it's not working.

I did regenerated the CSS files and it did regenerated the CSS as the timestamp changed. This also confirms that this is not a cache issue,

Before Screenshot:

![image](https://user-images.githubusercontent.com/1281946/54474900-ab2a6300-480c-11e9-89aa-6f626e5bbea4.png)

After Screenshot:

![image](https://user-images.githubusercontent.com/1281946/54474904-b67d8e80-480c-11e9-9e34-57903a71ff20.png)


I can confirm this same issue applies to the custom fonts.

Replace URL tool do not work on the background images.
Repalce URL tool do not work on the custom fonts.

Regenerate CSS do nothing on the above issues as well.

Please investigate this issue.

Thanks.

**Comment by shilo-ey** [comment]
Thanks for clarifying.

We will look into it and update this thread soon.

Thanks!

**Comment by tristanleboss** [comment]
Adding a message on this page explaining that the CSS cache may need to be flushed after changing the site URL could be a good idea :D

**Comment by erfan-ilyas** [comment]
There is no need to flush the css cache as the url of the CSS gets updated
thus server will always fetch new CSS.

Please review the attached screenshots.

**Comment by tristanleboss** [comment]
Are you 100% sure? If the URL changer doesn't remove the cached CSS files from `/wp-content/uploads/elementor/css`, it may still contain old incorrect URLs (for background image, for example) even if the url to this CSS file change.

**Comment by erfan-ilyas** [comment]
Yes I am 100% sure, Don't worry about it I know this stuff.

I am not using any cache plugin anyway.

Apache/Nginx does cache static resources and that why application developer updates the URL so that any CDN network picks up the new file from the harddisk.

Again this is not a cache issue.

**Comment by Tsluiz** [comment]
As I experience the same issues I am very interested to know if there is a fix for this.

**Comment by tylerhahn** [comment]
I am also experiencing the same issues here.

- No server or client-side caching
- Regenerate CSS does not work on background image urls

**Comment by silviafiat** [comment]
Hello,
I am experiencing a similar issue. We have a background image set on a popup form. This seems to be stored in DB table wp_postmeta with meta_key '_elementor_page_settings'. Using the Elementor Replace URL tool does not replace the value for this key (at least from what I can tell from the code, only meta_values for  "_elementor_data" meta_key are updated). 

Manually updating the value is not a solution because it will cause the popup form issues (we have s staging env with hostname of more characters than the production server hostname). 
I can see that the meta_value hold information about the string size for the "background_image" url:
s:16:"background_image";a:2:{s:3:"url";s:66:"https://devx-www.xyxyxy.com/wp-content/uploads/2020/03/xxxxx.jpg". As such, replacing the url with a url that has fewer character will break the form (the background image is not shown)

Any idea if this is known issue?

**Comment by tristanleboss** [comment]
@silviafiat When you see such pattern [letter]:[numbers]:[data], it means the data has been "serialized" using PHP `serialize` function. `a` means array, `s` string, `i` integer, etc...

You can use the PHP `unserialize` function to get back the PHP variable, change it and reserialize it.

**Comment by achyuthajoy** [comment]
I also encountered problems with custom fonts and background images during domain change. However, Regenerating CSS from Tools -> General fixed the problem. For background-images, sometimes I had to run the tool a couple of times.

Other than that didn't come across any problems yet.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.3.0

Feel free to update

Thanks!

**Comment by LoganStrike** [comment]
I'm still having this same issue as of Elementor 3.3.6. A section has a background image, and the image URL still shows the staging site URL. I tried using the Replace URL tool and it affected 0 rows. Regenerating Files & Data does not fix the issue either. Cache was cleared on the web hosting level, and browser cache was cleared as well. The problem remains.

**Comment by spencer-j** [comment]
Why is this closed?
Still doesn't work for the URLs on the background images. 
Elementor Pro - 3.5.1 and Elementor - 3.4.8

**Comment by euberdeveloper** [comment]
Yes, exactly, with Elementor 3.4.7 same problem here...

**Comment by holografikvoid** [comment]
Same issue here. Elementor 3.6.5. No cache problems; clients receiving updated CSS immediately (checked by switching between inline/external styles). Replace URL outputs "affected 0 rows". Regeneration of files does not usefully change anything.

**Comment by Sedrs** [comment]
Same issue here. I have tried many URL update plugins + default Elementor Tool. Never had this issue with Divi before.

**Comment by lifeact** [comment]
I have same problem.

This is very upsetting - the elementor team introduces useless things and cannot solve banal errors for years. That's what happens when it's not a competent technical specialist who manages, but marketers for whom the main profit is

**Comment by tamal-sen** [comment]
This issue still exists in the latest Elementor v3.7.7 and Elementor Pro v3.7.5
Tried "Regenerate files & Data", Search Replace Tool, but nothing works on the background images.

**Comment by techstroke** [comment]
This issue still exists, I was changing domain and the background images are still from the old site, as these are small sites I can manually go and change each image by hand but it should have been automated by now :(

**Comment by romeltech** [comment]
Fixed! For anyone still facing the issue, make sure to update `wp-content/uploads/elementor/css` a correct permission `755` or `777` then run the `Regenerate Files` again.
