### ISSUE TITLE
Stretch section not working since 2.5.0 in edit mode

### ISSUE THREAD

**Issue by swiderski** [elementor/elementor#7430]
Hey guys-)

I have templates that were created in one of older Elementor versions(around 2.3.0).

It uses stretch section option on many sections. 

Now with 2.5.0 - 2.5.5 it works fine on the front end(stretches), but in edit mode, it doesn't stretch section at all.
In 2.4.7 it works fine in the front end and the edit mode.

In frontend.js line 1660 I have added console log:
```
if ('stretch_section' === propertyName) {
			console.log(this.getElementSettings('stretch_section'));
```
And it returns _undefined_ on each change of the stretch section option, instead of _empty value_ or **section-stretched**.

I attach template on which it happens.
[elementor-12225-2019-03-12.zip](https://github.com/elementor/elementor/files/2956489/elementor-12225-2019-03-12.zip)

If you need any more details - let me know.

Hope for the fix.

With kind regards.

**Comment by shilo-ey** [comment]
Hi @swiderski 

Please make sure your Elementor is updated,
Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists.

[Here's a screen recording from your theme.](https://www.useloom.com/share/5064ffc566ab4e1492ffdf98d72616b2)

If the issue didn't resolved please contact our support.

thanks.

**Comment by swiderski** [comment]
I was afraid I will get this standard procedure ;-)

Tested on default WordPress theme, without any plugin. 

Like you can see I did pretty in-depth debugging, but I don't understand your JavaScript model that well to find out why **stretch_section** setting is not sent properly in case of old templates.

With kind regards.

**Comment by swiderski** [comment]
This is not a support question, but a bug report. Please re-read it slowly.
Things are not working since new 2.5.0

Please reopen this.

**Comment by swiderski** [comment]
I have put in on a fresh installation, theme twenty seventeen, only elementor active and template previously attached.
![screenshot-devgc kinsta com-2019 03 12-12-50-54](https://user-images.githubusercontent.com/1381850/54197968-99bc2080-44c5-11e9-8df4-d064b5b89268.png)

I kindly ask to recheck it. If you want I can prepare login data to my test installation.

With kind regards.

**Comment by shilo-ey** [comment]
Thanks for clarifying.
Next time please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report was missing key information: 

* Prerequisites.
* Isolating the problem.
* System info.

Without it we simply can't help.

After you have clarified it and now we can reproduce it we can see that this issue occurs on TwentySeventeen theme.

We will check to see if there's something we can do.

Thanks.

**Comment by swiderski** [comment]
Thanks for the update.

You are right, I didn't report it the best way possible. I will do better next time :-)

It was my day off, but instead of taking care of my business I have spent 3 hours looking for the source of the issue, and after I have found what is going on I wanted to report ASAP to have some time of this day saved :-)

Best to fins issue before any customer will notice, you know :-)

Good luck with this!

**Comment by graham00** [comment]
I've had the same issue across multiple sites. I followed all the steps (disabling all plugins, trying multiple default themes + OceanWP, debugging, etc) and submitted a case to support.

# Steps to reproduce this:

1. In the editor, add a new 2-column section
2. set "Stretch Section" to yes for the new section
3. Add a 2-column inner section to either column of the new stretched section.
4. Click Update, then ctrl-F5 to reload the editor.

The section will no longer be stretched. The live view is stretched, but not the editor view.

Incidentally, I've tested this behavior in both chrome and firefox. And like I said, I fully disabled everything and have tried many themes.

I'd like it if someone at elementor could take a few seconds to test this and confirm here that it's a bug they see on their end as well, so we at least know to not waste any more of our time trying random things on our end. Meanwhile, I suppose I'll roll the elementor version back.

**Comment by shilo-ey** [comment]
Hi @graham00 

Thanks for the steps to reproduce.

We are working on a solution for this issue.

As soon as we will release a patch - we will update this thread

**Comment by shilo-ey** [comment]
This issue has been fixed in 2.5.6

Feel free to update!

**Comment by crispee2000** [comment]
I updated and my editor view still does not show the stretch.  It looks boxed like it did before i updated.  I've tried unchecking and checking the option with no effect.

**Comment by shilo-ey** [comment]
@crispee2000 try clearing your cache.

If the regular troubleshooting doesn't work - please open a new issue, described as possible, just as @swiderski made eventually to help us isolate the problem.

**Comment by crispee2000** [comment]
Ok.  Cleared cache with Chrome advanced tools.  Restarted browser.  Still not working.

Will test some more before creating new issue.

**Comment by crispee2000** [comment]
For me it seems fine on new pages -- but doesn't affect ones that weren't working before.

**Comment by crispee2000** [comment]
@graham00  -  no CDN so it is strange.  Gonna keep trying things to see if it will work out.
