### ISSUE TITLE
Elementor Gallery Columns in Desktop and Responsive

### ISSUE THREAD

**Issue by cecofuli** [elementor/elementor#7631]
Hello Elementor Staff,

I would like to ask you if you are able to add this small, but very important feature:

**(*) add the possibility to change the columns number layout in Desktop, Tablet and Mobile.**

Right now I have 5 galleries in my desktop version (in the same page),  with more than 100 picture.
In Desktop mode everything is ok (8 columns for each gallery). But in mobile, Elementor creates only one, looooong column. I would like to set, in mobile, 3 columns and tablet 5. How can be possible? 

Thank you

Fra from Italy

**Comment by Webtica** [comment]
+1

**Comment by jim-ancon** [comment]
I second this as well. Most important is being bale to change the number of columns in mobile view.

**Comment by cecofuli** [comment]
Why no official answer to this very basic option?  :/

**Comment by eubanksto** [comment]
Still no word on this. So weird. It's so basic to just add the responsive icons to columns yet it collapses down to 1 column no matter what. I'm using dynamic content so adding columns manually and images to each column isn't an option. I am a UX Director at an agency and build a lot of websites. This lack of feature is a road block for me on almost every website.

**Comment by cecofuli** [comment]
Yes, 
and, no answer in 4 months... I think is that to change the columns layout  on different devices is  "base of the base" for every  page builder in the 2019... I'm a little bit shocked...

**Comment by normundslauva** [comment]
+1

**Comment by blazer380** [comment]
+100000000000

**Comment by AlessandroBerrone** [comment]
I agree, it is fundamental. Such a road block like the others above said.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.7

Feel free to update

Thanks!

**Comment by Helene7** [comment]
> This issue has been resolved in Elementor Pro v2.7
> 
> Feel free to update
> 
> Thanks!

I have the same issue now in 2020. Where can I edit gallery into two columns on mobile?

**Comment by Th3BiSh0p** [comment]
Still an issue.
We should be able to change the image size and the column count depending on the device.

**Comment by Alsaarom** [comment]
Hello, I think it's not an issue, it's just that Elementor considers this option pro feature, cause pro gallery allows to control the responsive columns. If it's for the money it's sad because I think is a fundamental option and basic gallery element is completely useless if you are a minimally meticulous person.

**Comment by tessaatmosoerodjo** [comment]
I had six images in the basic gallery. On tablet I had two rows with 3 images. But on mobile it was one row with six. I wanted on mobile to have two rows. So I went into the backend(code). Went to website file-> wp-content -> plugins -> elementor -> assets -> css -> frontend.min.css. Search for @media (max-width:479px) the max-width is 100%. Change it to 50%

@media (max-width:479px){.elementor-image-gallery .gallery.gallery-columns-2 .gallery-item,.elementor-image-gallery .gallery.gallery-columns-3 .gallery-item,.elementor-image-gallery .gallery.gallery-columns-4 .gallery-item,.elementor-image-gallery .gallery.gallery-columns-5 .gallery-item,.elementor-image-gallery .gallery.gallery-columns-6 .gallery-item,.elementor-image-gallery .gallery.gallery-columns-7 .gallery-item,.elementor-image-gallery .gallery.gallery-columns-8 .gallery-item,.elementor-image-gallery .gallery.gallery-columns-9 .gallery-item,.elementor-image-gallery .gallery.gallery-columns-10 .gallery-item{max-width:50%}}

It worked for me.

**Comment by Th3BiSh0p** [comment]
> Hello, I think it's not an issue, it's just that Elementor considers this option pro feature, cause pro gallery allows to control the responsive columns. If it's for the money it's sad because I think is a fundamental option and basic gallery element is completely useless if you are a minimally meticulous person.

I'm an elementor pro user. It's an issue on pro version too. Everyday I'm amazed how deep you can modify some elements and how some dead stupid elements can't be modified at all...
I guess with the new premium plans, things will change. Spoiler alert : of course not.

**Comment by emre-edu-tech** [comment]
It is completely and issue for the Elementor Free users but of course it is a marketing strategy. On the other hand in Elementor Pro, this widget has the same problem that is why they call it Basic Gallery but if you want a simple stack of images to show the user it is way better than the Pro Gallery. You can solve this responsiveness issue with Flexbox and Media Queries. Normally, Elementor uses Flexbox with its widgets to provide responsiveness but not for this widget.

If you want to make 5-column for the default and then after 1024px width you can decrease it to 4-column by using this code below: 

`.container-class {
	display: flex;
	align-items: center;
	flex-wrap: wrap;
}
.container-class .item {
	flex: 1 1 20%;
	max-width: 20%;
}
@media screen and (max-width: 1023px) {
	.container-class .item {
		flex: 1 1 25%;
		max-width: 25%;
	}
}`

**Comment by coachben** [comment]
/*Target media gallery on mobile for the elementor basic gallery widget
First: Please add a custom css id for the gallery widget class in advanced settings e.g. glosec-gallery
Next: add the below code in the custom css code in css panel under Additional CSS 

*/

`@media screen and (max-width: 640px) {
	.glosec-gallery{
	   line-height:0;
   -webkit-column-count:2; /* split it into 2 columns */
   -webkit-column-gap:5px; /* give it a 5px gap between columns */
   -moz-column-count:5;
   -moz-column-gap:5px;
   column-count:2;
   column-gap:5px;
}

}
`

**Comment by phkoon** [comment]
Any updates to this yet?

**Comment by phkoon** [comment]
Any updates to this yet? It's marked as closed, but the issue still persists.

**Comment by banch3v** [comment]
I guess, that is causa perduta. They won't fix it.
