### ISSUE TITLE
"Avoid Duplicates" not working

### ISSUE THREAD

**Issue by srcek** [elementor/elementor#7635]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce

"Avoid Duplicates" under Query options for Posts is no longer working properly after I updated to version 2.5.1 of Elementor Pro. I reverted back to 2.4.8 where query filtering works as expected. 

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by shilo-ey** [comment]
Hi @srcek 

This issue has been fixed in Elementor Pro v2.5.2

Feel free to update!

**Comment by deeftah** [comment]
Seems not to work on the Sitemap widget as well (latest version).
Don't get the option to select 'avoid duplicates'
![Screenshot](https://user-images.githubusercontent.com/6375550/74532104-9da2bf00-4f2e-11ea-96ec-4874589f4be7.png)

**Comment by eduardspocket** [comment]
Hi, I still encounter this issue. Exactly as it was described initially.

**Comment by ellainegab** [comment]
Still encountering this one as well.

**Comment by ellainegab** [comment]
Is there an update on this?

**Comment by jessyrob** [comment]
Is there an update on this?

**Comment by bentographics** [comment]
+1
