### ISSUE TITLE
ACF URL fields not functioning in Elementor (Undefined Index error)

### ISSUE THREAD

**Issue by burblestudio** [elementor/elementor#7646]
## Prerequisites
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

I have a series of posts setup with an ACF custom field to attach a file that can be downloaded by the end user. The posts display on the front end of the site as an elementor image widget. (See linked image for reference).

Since installing yesterdays update (pro 2.5.9) and even after installing today's update (2.5.10) I am receiving a PHP error that there is an undefined index related to the ACF URL fields in Elementor Pro. 

Prior to the recent updates this was working fine. 

I have replicated this on two servers.

### **HERE IS THE ERROR MESSAGE:**
**

> Notice: Undefined index: save_format in /home/~~~/public_html/~~~/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-url.php on line 64

**

![Error-ACF-Elementor-URL-Field](https://user-images.githubusercontent.com/32874432/55105555-cc0b7780-509a-11e9-9b0f-b01b625a3370.jpg)
![ACF Download File Field Settings](https://user-images.githubusercontent.com/32874432/55105559-cdd53b00-509a-11e9-9f91-5b9c3bbc86c0.jpg)
![Screen Shot 2019-03-27 at 2 19 18 PM](https://user-images.githubusercontent.com/32874432/55105786-6075da00-509b-11e9-82e9-0273db1fdd98.jpg)

## Steps to reproduce

1. Create an ACF File field and assign it to a post type
2. Create new entry in the post. Upload a file to the ACF file field, and then add a preview image of the uploaded file to the featured image. Give the post a title that describes the file.
3. Create a new single page template in Elementor Pro for the post type used in steps 1 and 2. 
4.Add an IMAGE to the Elementor template. 
5. Assign the CHOOSE IMAGE field to DYNAMIC > FEATURED IMAGE
6. Assign the CAPTION field to CUSTOM and select DYNAMIC > POST TITLE 
7. Assign the link field to CUSTOM URL with link field of DYNAMIC > ACF URL FIELD, then associate the ACF field you created in step 1 under the wrench icon. 
8. Preview a post with DEBUG TRUE set and you will see the PHP error. 

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro). 
_*N/A - ACF is required for ACF functionality to be tested. But the bug can be replicated with just ACF, Elementor and Elementor Pro on 2016 theme._
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.6.42-84.2
	PHP Version: 7.1.27
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Astra
	Version: 1.7.2
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.7.13
		Author: Elliot Condon

	Custom Post Type UI
		Version: 1.6.1
		Author: WebDevStudios

	Elementor
		Version: 2.5.10
		Author: Elementor.com

	Elementor Pro
		Version: 2.5.2
		Author: Elementor.com

	ManageWP - Worker
		Version: 4.7.7
		Author: GoDaddy

== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 
		Author: GoDaddy

== Log ==

2019-03-27 14:51:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.9',
  'to' => '2.5.10',
)]
2019-03-27 18:39:09 [info] elementor-pro::elementor_pro_updater Started 
2019-03-27 18:39:09 [info] Elementor Pro/Upgrades - _v_2_5_0_form Start  
2019-03-27 18:39:10 [info] Elementor Pro/Upgrades - _v_2_5_0_form Finished 
2019-03-27 18:39:10 [info] Elementor Pro/Upgrades - _v_2_5_0_woocommerce_menu_cart Start  
2019-03-27 18:39:10 [info] Elementor Pro/Upgrades - _v_2_5_0_woocommerce_menu_cart Finished 
2019-03-27 18:39:10 [info] Elementor Pro/Upgrades - _v_2_5_0_posts Start  
2019-03-27 18:39:10 [info] Elementor Pro/Upgrades - _v_2_5_0_posts Finished 
2019-03-27 18:39:10 [info] Elementor Pro/Upgrades - _v_2_5_0_portfolio Start  
2019-03-27 18:39:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.8',
  'to' => '2.5.2',
)]
2019-03-27 18:39:10 [info] Elementor Pro/Upgrades - _v_2_5_0_portfolio Finished 
2019-03-27 18:39:10 [info] Elementor Pro/Upgrades - _v_2_5_0_products Start  
2019-03-27 18:39:10 [info] Elementor Pro/Upgrades - _v_2_5_0_products Finished 
2019-03-27 18:39:10 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Start  
2019-03-27 18:39:11 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Finished 
2019-03-27 18:39:11 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Start  
2019-03-27 18:39:11 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Finished 
2019-03-27 18:39:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.8',
  'to' => '2.5.2',
)]

				
</details>

**Comment by thimfy** [comment]
Do not purchase elementor or any item from creator of it, no support nothing just kind of shit only.

**Comment by shilo-ey** [comment]
Hi @burblestudio 

Thanks for your feedback.

Try to set your file return value to File Array, this should solve the issue.

Thanks.

**Comment by LinearDynamics** [comment]
Also seeing this issue. 'Notice: Undefined index: save_format in /var/www/website/wordpress/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-url.php on line 64
crdl_image_url'
We're making a post loop using Anywhere Elementor & ACF. The purpose is to have a CPT(Field Types=Title, Image(PDF)) which has heading, PDF(for download).
User uploads PDF via WP media uploader.

If I change the field's return format to image array, I get Notice: Undefined offset: 0 in /var/www/website/wordpress/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-url.php on line 52 

![image](https://user-images.githubusercontent.com/32169863/61067606-f7aa3780-a3d5-11e9-9815-4121bbfdc937.png)

**Comment by burblestudio** [comment]
Hi @shilo-ey  

Sorry i didn't get a notification for your reply for some reason, but this didn't resolve the issue. Switching the return to File Array just displays a different error from Undefined Index to Undefined Offset:

Notice: Undefined offset: 0 in /home/bp11/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-url.php on line 52

**Comment by shirokoweb** [comment]
I can confirm issue still exists and @shilo-ey suggestion doesn't solve anything :

1. It throws another error [...]/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-url.php on line 52
2. We want to use "File URL" as returned value not array...

**Comment by emeraldsama** [comment]
I'm also still experiencing this bug as well. We're using ACF for editors add a media file URL in ACF and have those paired to buttons in elementor. 

Notice: Undefined index: save_format in [...]/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-url.php on line 64

**Comment by jasonhoi** [comment]
Me too, just updated ACF to v5.8.7, Elementor v2.7.5, just try to create a new page with ACF file field (output file url) link to Elementor button link field, It throws another error [...]/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-url.php on line 52

**Comment by jasonhoi** [comment]
Before Elementor fix this bug, I am gonna use ACF file field return value as "File URL" and temporary override Elementor plugin file before line 64 with: 
return wp_kses_post( $value );
![fix](https://user-images.githubusercontent.com/1080171/69476989-b0b85e00-0e1b-11ea-869a-42eeafc05bec.JPG)

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.8.1

Feel free to update

Thanks!

**Comment by emeraldsama** [comment]
After updating to 2.8.1, I now get the following error with the same ACF basic URL field setup:

NOTICE: UNDEFINED INDEX: RETURN_FORMAT IN /APP/PUBLIC/WP-CONTENT/PLUGINS/ELEMENTOR-PRO/MODULES/DYNAMIC-TAGS/ACF/TAGS/ACF-URL.PHP ON LINE 56

It seems I am able to work around it by using the ACF Relational Link field type, with Link URL selected.

**Comment by burblestudio** [comment]
@shilo-ey This isn't resolved, unfortunately. Still getting errors even with 2.8.1 and all updates installed. 

I'm getting the same error as @emeraldsama noted above. 

**Notice: Undefined index: return_format in .../wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-url.php on line 56**

**Comment by Axel186** [comment]
Same here, Elementor PRO `v2.8.2`.
ACF version: `5.7.8`

Looks like Elementor can't get the value of ACF URL. Maybe some logic was changed and this is a side effect. (`$field['value']` is empty).

**Comment by vitaminn** [comment]
still not working.

**Comment by tdpt** [comment]
Hello!

Same problem. Using one ACF file field, and it is just returning the ID beside I select to return URL or Array.

**Comment by KillaSZ** [comment]
Same issue here!

Elementor PRO v3.0.8
ACF v5.9.3

It can't get the value for the ACF Link and URL fields.

**Comment by askwpgirl** [comment]
( ! ) Notice: Undefined offset: 0 in /.../public/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-url.php on line 34

I can get the value of the ACF fields, but the undefined offset has still not been resolved, so if debug is true, you'll see this on all pages trying to retrieve ACF URL field.

**Comment by digitalformula** [comment]
+1 on this never getting resolved.  There's something not working properly with ACF URL fields in Elementor.  In my templates I can't even select a ACF URL type field from the list, when trying to display the field's value in a template.

**Comment by seolinkworld** [comment]
Well, there are also many solutions are available like [Elementor Alternatives](https://seolinkworld.com/elementor-alternatives/) 
and [Best Elementor Themes and Templates](https://seolinkworld.com/best-elementor-themes-and-templates/)
