### ISSUE TITLE
Show Name of the Image / Background Image

### ISSUE THREAD

**Issue by black-eye** [elementor/elementor#7937]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When you edit already inserted image, you can't see it's name, neither in the attributes, nor when the media folder popup is opened. Sometimes, when you have several similar images (e.g. for the background) you are unable to realize, which image is used.

**Describe the solution you'd like**
Add the image name somewhere in the settings panel (e.g. over the thumbnail), or mark it in the media selector popup (same way as it's done in native editor or post thumbnail selector).

**Describe alternatives you've considered**
Now I have to go throuh the media folder and compare images to find out which one is used. Not very user friendly.

**Comment by cpanfilio** [comment]
sometimes we have an image in the media library with the same name but slightly different crop. can there be a way to also indicate which specific image was used?

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.6.0

Feel free to update

Thanks!

**Comment by zevrix** [comment]
Unless I'm missing something, this issue is NOT resolved (_Elementor Pro 3.3.1_).

In the **Edit Image** panel, the name of the selected image is NOT listed. 

I have to click the image preview, which opens the **Insert Media** window, where the image will be selected. Only then I can see the image name. It's a lot of extra steps!

So can you please reopen this issue:

**Show the selected image name in the Edit Image panel.**
