### ISSUE TITLE
Background videos, self-hosted (non-YouTube), start time and end time not working

### ISSUE THREAD

**Issue by Nifty-250** [elementor/elementor#7941]
Hello Elementor,
I am new to Elementor, and when following along with the Tutorial by Noaa about how to create Background Videos, I found that the feature: Start Time, End Time - only works on YouTube hosted videos and not Self Hosted videos.
I double checked this on each setting twice, and it consistently works on YouTube hosted, and consistently doesn't on Self Hosted.
Any chance someone could look into it...?
Thanks,
Nifty

**Comment by shilo-ey** [comment]
Hi @Nifty-250 

Thanks for reporting.

We will look into solving this issue and will update this thread.

Thanks!

**Comment by cenemil** [comment]
I also had this issue with self-hosted videos but I found a workaround by appending "#t=[start time],[end time]" to the video url

example: https://www.videourl.com/sample.mp4#t=5,30

Hope it will be fixed soon.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.6.0

Feel free to update

Thanks!

**Comment by loobj126** [comment]
Hi all ,

I am using elementor v2.9.3 . the issue still occurring. 
kindly advise

**Comment by tanejakaran** [comment]
Still having same issue in v2.9.3

Case 1: Self-hosted video does not play for the first 10-20sec depends upon videolength. Then starts. 
Case 2: Set autoplay - same issue like case 1
Case 3: Set Autoplay + mute - then it works properly. 

How to fix case 1 and case 2?
