### ISSUE TITLE
Images of the slider widget not loading when hidden with display:none and shown with jQuery .show()

### ISSUE THREAD

**Issue by FredericReiter** [elementor/elementor#7949]
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

After hiding the slider widget and making it show with javascript the element will show but the first image won't load until the slider navigation has been used.

Please see it in action here: https://lovelyfigures.de/test

## Steps to reproduce

1. Create a new site with elementor pro enabled
2. Place a slider widget somewhere, give it an id, put custom css "display:none" to it
3. Add javascript action that displays the element like jQuery .show()
4. Trigger it and observe

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

https://pastebin.com/CTxdfuCK

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.7

Feel free to update

Thanks!

**Comment by EvelynWaugh** [comment]
this bug not resolved, I have Elementor Pro 2.9.3 and any animation freezes after display:none and jquery .show();

**Comment by AntonyOnScript** [comment]
still not working, elementor is a joke

**Comment by leccyril** [comment]
hello 2023 bug still present exemple with image gallery
