### ISSUE TITLE
Media carousel doesn't open video

### ISSUE THREAD

**Issue by thehervy** [elementor/elementor#8047]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When I add in "Media carousel" item - Video, add link to vimeo or youtube, it is not working. On frontend it is clickable, but it points to the image used, not to the video.

## Steps to reproduce

1. Add **Media carousel**
1. Add items - images (not needed)
1. Add item - switch it to video type, add link to video (youtube or vimeo)
1. Save and test it
1. Images are fine, but the video is **not** opening lightbox or link to the video. Instead it opens link to the selected image.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.5.33
	PHP Version: 7.3.1
	PHP Max Input Vars: 10000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: http://www.hervy.cz/wf6
	Home URL: http://www.hervy.cz/wf6
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 128M
	Permalink Structure: /blog/%postname%/
	Language: en-US
	Timezone: Europe/Prague
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 1.2.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.5.14
		Author: Elementor.com

	Elementor Pro
		Version: 2.5.7
		Author: Elementor.com


== Log ==
	: 
Log: showing 20 of 252019-04-04 15:25:09 [info] Elementor Pro/Upgrades - _v_2_5_4_posts callback needs to run more 1 times 
2019-04-04 15:25:09 [info] Elementor Pro/Upgrades - _v_2_5_4_portfolio Start  
2019-04-04 15:25:17 [info] Elementor Pro/Upgrades - _v_2_5_4_portfolio callback needs to run more 1 times 
2019-04-04 15:25:17 [info] Elementor Pro/Upgrades - _v_2_5_4_products Start  
2019-04-04 15:25:19 [info] Elementor Pro/Upgrades - _v_2_5_4_products Finished 
2019-04-04 15:25:19 [info] Elementor Pro/Upgrades - _v_2_5_4_form Start  
2019-04-04 15:25:22 [info] Elementor Pro/Upgrades - _v_2_5_4_form Finished 
2019-04-04 15:25:22 [info] Elementor Pro/Upgrades - _v_2_5_4_posts Start (2 of 2, 100%) 
2019-04-04 15:25:27 [info] Elementor Pro/Upgrades - _v_2_5_4_posts Finished 
2019-04-04 15:25:27 [info] elementor-pro::elementor_pro_updater Started 
2019-04-04 15:25:27 [info] Elementor Pro/Upgrades - _v_2_5_4_portfolio Start (2 of 2, 100%) 
2019-04-04 15:25:37 [info] Elementor Pro/Upgrades - _v_2_5_4_portfolio Finished 
2019-04-04 15:25:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.3',
  'to' => '2.5.4',
)]
2019-04-09 17:59:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.11',
  'to' => '2.5.12',
)]
2019-04-09 18:01:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.4',
  'to' => '2.5.5',
)]
2019-04-14 15:58:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.12',
  'to' => '2.5.13',
)]
2019-04-17 10:38:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.13',
  'to' => '2.5.14',
)]
2019-04-30 15:45:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.5',
  'to' => '2.5.6',
)]
2019-05-06 09:46:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.6',
  'to' => '2.5.7',
)]
2019-05-06 09:46:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.6',
  'to' => '2.5.7',
)]

JS: showing 14 of 14JS: 2019-04-17 11:52:08 [error X 1][http://www.hervy.cz/wf6/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.14:2:83475] Cannot set property \'controls\' of undefined 
JS: 2019-04-18 14:11:01 [error X 1][http://www.hervy.cz/wf6/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view479\") has already been destroyed and cannot be used. 
JS: 2019-04-18 14:43:42 [error X 2][http://www.hervy.cz/wf6/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view503\") has already been destroyed and cannot be used. 
JS: 2019-04-18 19:12:06 [error X 41][http://www.hervy.cz/wf6/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.14:2:28351] Cannot read property \'get\' of undefined 
JS: 2019-04-19 15:12:21 [error X 1][http://www.hervy.cz/wf6/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view30043\") has already been destroyed and cannot be used. 
JS: 2019-04-19 15:12:21 [error X 1][http://www.hervy.cz/wf6/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view30225\") has already been destroyed and cannot be used. 
JS: 2019-04-19 18:02:53 [error X 2][http://www.hervy.cz/wf6/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view498\") has already been destroyed and cannot be used. 
JS: 2019-04-20 10:15:13 [error X 1][http://www.hervy.cz/wf6/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.14:2:215671] Cannot read property \'on\' of null 
JS: 2019-04-20 10:15:33 [error X 10][http://www.hervy.cz/wf6/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.14:2:215844] tinymce is not defined 
JS: 2019-04-20 12:44:20 [error X 2][http://www.hervy.cz/wf6/wp-content/plugins/elementor/assets/lib/slick/slick.min.js?ver=1.8.1:1:19335] Cannot read property \'add\' of null 
JS: 2019-04-22 18:23:16 [error X 1][http://www.hervy.cz/wf6/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=2.5.14:2:8029] Cannot read property \'attributes\' of undefined 
JS: 2019-04-23 20:47:26 [error X 2][http://www.hervy.cz/wf6/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.14:2:84262] Blocked a frame with origin \"http://www.hervy.cz\" from accessing a cross-origin frame. 
JS: 2019-04-25 00:23:14 [error X 2][http://www.hervy.cz/wf6/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view473\") has already been destroyed and cannot be used. 
JS: 2019-05-05 21:23:23 [error X 1][http://www.hervy.cz/wf6/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view481\") has already been destroyed and cannot be used. 

PHP: showing 4 of 4PHP: 2019-04-18 15:25:53 [notice X 4][/data/web/virtuals/23769/virtual/www/wf6/wp-content/plugins/elementor/includes/managers/image.php::33] Undefined index: id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-04-18 16:07:12 [notice X 1][/data/web/virtuals/23769/virtual/www/wf6/wp-content/plugins/elementor/includes/template-library/sources/local.php::676] ob_end_clean(): failed to delete buffer. No buffer to delete [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-04-19 15:04:54 [notice X 1][/data/web/virtuals/23769/virtual/www/wf6/wp-content/plugins/elementor-pro/modules/posts/widgets/posts.php::31] Undefined index: posts_post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-04-22 16:56:43 [notice X 2][/data/web/virtuals/23769/virtual/www/wf6/wp-content/plugins/elementor-pro/modules/query-control/module.php::280] Undefined index: object_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]


				
```
</details>

**Comment by shilo-ey** [comment]
Hi @thehervy 
Thanks for reporting.

This is a known issue, and it will be resolved in v2.6.0

See here: #7908 

Thanks

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.6.0

Feel free to update

Thanks!

**Comment by thehervy** [comment]
Thank you, BUT.. the issue is still there :( I have now 2.6.1 and when I add another item, set it to video, add link, add thumbnail, it will still open only image and the video will not start playing (on live web)...

**Comment by KingGrizzly** [comment]
+1, This issue persists. Media carousel Vimeo pop-up loads an image.

**Comment by nathansvl** [comment]
+1, it's a real problem for those like me who has a video portfolio :/

**Comment by JoniWeiss** [comment]
This issue is definitely not resolved! Please fix!!

**Comment by raposx** [comment]
This issue persists for me as well on latest version of Elementor and Elementor Pro

**Comment by shilo-ey** [comment]
Hi,

The fix that was released on v2.6 relates to this issue in the case only the image opened in Media Carousel widget. 

Please keep in mind that due to [Google autoplay policy](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes) the websites that will play autoplay websites are only the ones with high media engagement score.

The initial click on the image opens the video lightbox with an autoplay attribute which might not work immediately in some cases when the Media Engagment score is relatively low. 

Thanks.

**Comment by umarglobal** [comment]
Running v2.6.5 and this is still not resolved. Any ideas when this will be fixed

**Comment by cetebuk** [comment]
Running v2.7.3. Windows 7 Pro (64-bit) 
Issue happens with Chrome v77.0.3865.90 (64-bit) 
But works with FF v69.0.1 (64-bit)

**Comment by akalid1000** [comment]
Elementor v2.7.3
Issue happens on Chrome, but works properly on IE

**Comment by umarglobal** [comment]
How is this ticket closed when the issue still persists *baffled*

Using Elementer 2.7.4 with (Pro v 2.72)

**Comment by useahawk** [comment]
Elementor v2.7.4 Elementor Pro v2.7.2
Still no video :(
C'mon guys..

**Comment by blaisck** [comment]
+1 
Elementor 2.7.5
Elementor Pro 2.7.3

**Comment by SoundYeti** [comment]
I'm having the same Issue - Won't load the videos, Just sits on the lightbox "and spinning wheel of death" 

IS this Issue Closed?

**Comment by DynamoProd** [comment]
The problem seems to come from the "Viewer" parameter of Elementor, you have to activate it to display the videos instead of loading the image, the problem for example in my case is that I do not want to use the viewer of Elementor so the "Gallery Media" widget does not work.

**Comment by DynamoProd** [comment]
(You still can use .elementor-lightbox {display: none !important;} anyway)

**Comment by shelbysoto** [comment]
Still no video :(
With latest version. Nothing. No answers either.

**Comment by NTuneMusic** [comment]
Nope. Not working as it should if you're going to include it in Elementor as a widget. Fix it or remove it until it works like it's supposed to.

**Comment by umarglobal** [comment]
Maybe because the ticket is closed which is why there is no response? Developers probably think this is resolved. I have created another bug report pointing to this one suggesting that it is not fixed. Hopefully it will flag up to developers

https://github.com/elementor/elementor/issues/10167

**Comment by Applepiee** [comment]
Anyone knows how to fix this?

**Comment by Meganitrospeed** [comment]
When is this getting solved?

**Comment by Applepiee** [comment]
Mine was fixed by disabling minify plugins. (in my case it was Autoptimize causing the problem)

**Comment by pavs94** [comment]
The problem still exists for me too. Only images show but on click the video does not load. Surprising it works fine on the editor, but not on the actual page for me.

**Comment by johnholliday** [comment]
Not fixed - only images - video does not load.  Elementor v2.9.14.  Elementor Pro v1.10.3

What are the best alternatives until this problem is addressed?

**Comment by DannyCarter2020** [comment]
I have the very latest version of elementor and elementor pro as i unpdated them at the time of typing this message and all i get is just images the video does not load if anyone has an alternative to fix this problem I would be very grateful

**Comment by ErnestPH** [comment]
Indeed this is still an issue... Can we open this ticket again. Thanks!

**Comment by cristianstortoni** [comment]
I have the same issue! how did you solve?

**Comment by ErnestPH** [comment]
> The issue! Is still remains how did you solve?

It's actually a plugin conflict :) You have to test all the plugins. Try to deactivate it one by one...

**Comment by cristianstortoni** [comment]
I know I found the plugin that generates the error but I can't delete it because it is the plugin that manages all the post types of my theme, I wrote both to elementor's assistance and to my theme's assistance and both do not they told me how to resolve by blaming each other.

**Comment by arturikoX** [comment]
Hi,
I'm trying to see videos too on versions :
Elementor Pro - 3.0.8
Elementor - 3.0.14

( Self hosted videos, it opens the image only )

Any assistance will be appreciated,

Thanks

**Comment by juniormcmillan** [comment]
The same issue as the above poster here..  Did you not include the external link support for that widget?

**Comment by GIVENALITY** [comment]
Same issue as above. Did anyone find a solution?

**Comment by MadeByKarl** [comment]
Same problem.

**Comment by camachok** [comment]
Had the same issue. I was using a Media Library plugin that saves images to Google Drive instead my web server. I had to add the image to regular Media Library upload storage in order for the lightbox to work.

**Comment by XDesignsit** [comment]
Seems like this is still a problem.  I'm trying to use YouTube links (any) and none of them will play.  Tried on a couple different Elementor sites on different servers, plugins and NONE of them will play.

**Comment by ivanverona1** [comment]
I'm trying too and is not working. Only in editor mode i can see the thumbnails and play the video in the lightbox but after saved the project and testing it on live preview is completley stop to work.

**Comment by LorenzWieseke** [comment]
Still not fixed after more than 2 years!
I found a solution where you can build your own slider using video elements.

https://youtu.be/r6aZ246cwcw

**Comment by Ameer-Hamza11** [comment]
> Running v2.6.5 and this is still not resolved. Any ideas when this will be fixed

**Comment by Ameer-Hamza11** [comment]
Elementor Pro media carousel working fine on mobile but not working on desktop videos of carousel not opening on desktop, please anyone can help  this is a site link https://maximilianfend.com/ please see this and help

**Comment by hax1** [comment]
issue still seems to persist in latest elementor & pro versions. vimeo videos not opening in lightbox but linking to the images.

**Comment by silvernblackgtp** [comment]
Hey all, I found that my issue was due to WP Featherlight plugin, I disabled the plugin and now the videos work without the image popping up over it. Hope that helps for ya'll...

**Comment by paimvictor** [comment]
This error still occurrs
Elementor - 3.22.2

**Comment by rdushaev** [comment]
I solved the problem by replacing the transition effect. With the Cube effect, some videos did not open for me.

**Comment by Prillou** [comment]
its 2024 and I am encountering the same issue ! Please help

**Comment by jonathangormsen1** [comment]
Still in 2026 not working

**Comment by Prillou** [comment]
oh what a surprise (ironic) !

**Comment by DannyCarter2020** [comment]
I'm suprised this thread is still running all these years I've shifted from
Wordpress and elenentor to Wix and shifted from Wix to manus AI to build
web applications  - these developers of elementor are hopeless
