### ISSUE TITLE
DynamicTags in section cause error in following elements

### ISSUE THREAD

**Issue by crazypsycho** [elementor/elementor#8074]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

If you create an element with dynamic content in a column of a section, all following elements with dynamic content are opacitied, after you reload editor.
It throws also an javascript-error:
ViewDestroyedError: View (cid: "view476") has already been destroyed and cannot be used.

## Steps to reproduce

Create a inner section. Add a text-widget in one column with dynamic content.
Add another text-widget with dynamic content under the section.
Save & Reload (F5).
Second text-widget is now not fully rendered and has opacity.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/7.0.13
	MySQL version: MariaDB Server v5.6.32-79.0
	PHP Version: 7.0.13
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2
	Site URL: https://
	Home URL: https://
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Debug Mode: Active

== Theme ==
	Name: Twenty Nineteen
	Version: 1.4
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.7.12
		Author: Elliot Condon

	Elementor
		Version: 2.5.15
		Author: Elementor.com

	Elementor Pro
		Version: 2.5.8
		Author: Elementor.com


== Log ==
	: 
Log: showing 20 of 262019-05-09 08:56:37 [info] Elementor Pro/Upgrades - _v_2_5_0_woocommerce_menu_cart Finished 
2019-05-09 08:56:37 [info] Elementor Pro/Upgrades - _v_2_5_0_posts Start  
2019-05-09 08:56:37 [info] Elementor Pro/Upgrades - _v_2_5_0_posts Finished 
2019-05-09 08:56:37 [info] Elementor Pro/Upgrades - _v_2_5_0_portfolio Start  
2019-05-09 08:56:37 [info] Elementor Pro/Upgrades - _v_2_5_0_portfolio Finished 
2019-05-09 08:56:37 [info] Elementor Pro/Upgrades - _v_2_5_0_products Start  
2019-05-09 08:56:37 [info] Elementor Pro/Upgrades - _v_2_5_0_products Finished 
2019-05-09 08:56:37 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Start  
2019-05-09 08:56:37 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Finished 
2019-05-09 08:56:37 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Start  
2019-05-09 08:56:37 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Finished 
2019-05-09 08:56:37 [info] Elementor Pro/Upgrades - _v_2_5_4_posts Start  
2019-05-09 08:56:37 [info] Elementor Pro/Upgrades - _v_2_5_4_posts Finished 
2019-05-09 08:56:38 [info] Elementor Pro/Upgrades - _v_2_5_4_portfolio Start  
2019-05-09 08:56:38 [info] Elementor Pro/Upgrades - _v_2_5_4_portfolio Finished 
2019-05-09 08:56:38 [info] Elementor Pro/Upgrades - _v_2_5_4_products Start  
2019-05-09 08:56:38 [info] Elementor Pro/Upgrades - _v_2_5_4_products Finished 
2019-05-09 08:56:38 [info] Elementor Pro/Upgrades - _v_2_5_4_form Start  
2019-05-09 08:56:38 [info] Elementor Pro/Upgrades - _v_2_5_4_form Finished 
2019-05-09 08:56:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.3.1',
  'to' => '2.5.8',
)]
```
</details>

**Comment by horizzons** [comment]
Hello there.

Can somebody clarify me please if this issue was already solved?

Because I had exactly the same problem described here with the latest version of Elementor and Elementor Pro (2.9.4).

I can't use ACF or JetEngine color picker fields to change section background color dynamic tags without appearing the ViewDestroyedError: View (cid: "view476") has already been destroyed and cannot be used.

Seriously? Since May, 2019 this issue still open and not solved?

**Comment by 1000camels** [comment]
Do you ever resolve this?

**Comment by tollube** [comment]
Same issue here. Basically makes the dynamic features useless...
It's quite frustrating seeing new features beeing released every week or two but old known bugs still exist for years.

**Comment by Sitecentrale** [comment]
I have the same thing, using your own Hello theme, trying to edit header in the Theme Builder. I'm using ACF to display/hide a slider element, so *BUMP* I guess :)

**Comment by AzTeK23** [comment]
I am having the same problem on elementor pro 3.2.2, problem that goes away with the use of a third party plugin complementary to Elementor

**Comment by Aviad-Herman** [comment]
Problem seems to be fixed on latest versions of Elementor.
If you still have this problem please try to isolate the problem by deactivating all experiments (elementor --> settings --> experiments) and deactivating all plugins.

If the problem still occurs please send some screenshots or even a video.
We need to understand the exact steps to reproduce this on our end.
I was not able to reproduce the bugs using the instructions in this thread.

Thanks,

**Comment by mbenba01** [comment]
> Problem seems to be fixed on latest versions of Elementor. If you still have this problem please try to isolate the problem by deactivating all experiments (elementor --> settings --> experiments) and deactivating all plugins.
> 
> If the problem still occurs please send some screenshots or even a video. We need to understand the exact steps to reproduce this on our end. I was not able to reproduce the bugs using the instructions in this thread.
> 
> Thanks,

Hi Aviad-Herman,

I am still experiencing the exact same problem now. 
I have a custom taxonomy "Collection" for the Product post type (woocommerce) with an ACF image field
The Custom taxonomy was created as a must use plugin.
I created a product archive template using theme builder to display products of a given Collections taxonomy
The template includes a hero section with the title of the Collection (cusotm taxonomy) and a short description
I want to add a dynamic image background on the hero section which would display the collection image.
The problem is that the image does not seem to be recognised or displayed.
Screenshot:
https://prnt.sc/1yr51vb

Thanks!

**Comment by ofmarconi** [comment]
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/6594795/172269323-2eaa568e-c635-4d47-9c4c-421a9c6d0dd6.png">

I'm facing a similar problem, any ideas on how to debug?
