### ISSUE TITLE
Popup menu problems (close and reopen)

### ISSUE THREAD

**Issue by Luxamman** [elementor/elementor#8189]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
We are creating a new site and we want to use the popup for the mobile menu, like in your video. But there are some problems with working with popups. 

1: Like in #7664 & #8125 the menu is not closing on a click on a menu-button inside the popup, when using anchor links on the same page. This is solved via code, but this is of course not a clean and for everyone usable solution. Should it be like in "Triggers" - Close on click on Element id/class...?

2: The popup is only opening one time, after that, the button/icon is useless. Also a major problem on single pages or when working with anchors. I think there was an issue about this and "this is the normal behavior", but for a menu it is definitely not. I tryed via link within the icon and via "Open By Selector" in the popup.

We have the problem (2) also on other sites. Deactivated other Elementor elements a.s.o.

## Steps to reproduce
Just use a icon to trigger a custom popup menu and put a button in it with a anchor for the page your opening the popup menu. 

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: (Debian) v5.7.26
	PHP Version: 7.3.5
	PHP Max Input Vars: 1000
	PHP Max Post Size: 30M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.1
	WP Multisite: No
	Max Upload Size: 30 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: Europe/Vienna
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.0.5
	Author: Elementor Team
	Child Theme: No

== Active Plugins ==
	All-in-One WP Migration
		Version: 6.96
		Author: ServMask

	Duplicator
		Version: 1.3.14
		Author: Snap Creek

	Elementor
		Version: 2.5.15
		Author: Elementor.com

	Elementor Extras
		Version: 2.0.17
		Author: Namogo

	Elementor Pro
		Version: 2.5.8
		Author: Elementor.com

	Essential Addons for Elementor - Pro
		Version: 2.15.0
		Author: WPDeveloper

	HTTP Headers
		Version: 1.12.2
		Author: Dimitar Ivanov

	JetElements For Elementor
		Version: 1.15.12
		Author: Zemez

	Pods - Custom Content Types and Fields
		Version: 2.7.12
		Author: Pods Framework Team

	Shortcoder
		Version: 4.4
		Author: Aakash Chakravarthy

	WP Media folder
		Version: 4.7.12
		Author: Joomunited

	WPML CMS Nav
		Version: 1.5.1
		Author: OnTheGoSystems

	WPML Media
		Version: 2.5.2
		Author: OnTheGoSystems

	WPML Multilingual CMS
		Version: 4.2.6
		Author: OnTheGoSystems

	WPML Sticky Links
		Version: 1.5.0
		Author: OnTheGoSystems

	WPML String Translation
		Version: 2.10.4
		Author: OnTheGoSystems

	WPML Translation Management
		Version: 2.8.5
		Author: OnTheGoSystems

	Yoast SEO
		Version: 11.2.1
		Author: Team Yoast

	Yoast SEO Multilingual
		Version: 1.0.0
		Author: OnTheGoSystems

</details>

**Comment by shilo-ey** [comment]
Hi @Luxamman 

Thanks for your feedback.

As for your first topic - as mentioned earlier, we are considering a broader solution. for the meanwhile, we provided the code mentioned in those threads.

As for your second issue - can you please elaborate? we can't reproduce this issue on our side.

1. Created a popup (with no conditions)
2. Added a button in the page I want it to be added
3. Link > Dynamic > Popup > Open popup > Selected my recent popup
![image](https://user-images.githubusercontent.com/45009641/58261543-2a926080-7d81-11e9-9910-49b4de094c6e.png)
4. Preview -> Click on the button and closed it - still works.
https://www.loom.com/share/d4546dc536624d53be72e2076ec7d33a

Please make sure there's no limit for the number of times the popup can be triggered or a rule for what happens after you close the popup.

Thanks

**Comment by Luxamman** [comment]
Thanks! 
Yes that is what I have done. 
My popup only has one condition: shown on every site. No trigger, no advanced rules. With "Disable Page Scrolling" and "Avoid Multiple Popups".

And there seems to be the problem: When I deactivate "Avoid Multiple Popups" it's reopening. With active "Avoid Multiple Popups", you can close it and it won't open again.

Should "Avoid Multiple Popups" just avoid that two ore more popups can be opened on a site? 
Hope this helps to refine the popups.
Thanks!

**Comment by shilo-ey** [comment]
Thanks, we will look into it.

**Comment by Jehu** [comment]
> My popup only has one condition: shown on every site. No trigger, no advanced rules. With "Disable Page Scrolling" and "Avoid Multiple Popups".
> 
> And there seems to be the problem: When I deactivate "Avoid Multiple Popups" it's reopening. With active "Avoid Multiple Popups", you can close it and it won't open again.
> 
> Should "Avoid Multiple Popups" just avoid that two ore more popups can be opened on a site?
> Hope this helps to refine the popups.

Same issue here when "Avoid Multiple Popups" is activated! Thanks @Luxamman for pointing this out.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.6.0

Feel free to update

Thanks!

**Comment by aminesayagh** [comment]
I already have version 2.7 of elementor pro but the problem is not resolved

**Comment by Michalkessel** [comment]
same here, still not working with the latest version of Elementor. 'avoid multiple popups' is disabled.

**Comment by Twolar** [comment]
Currently on the latest version of Elementor (v3.0.10) and Elementor Pro (v3.0.5).

'Avoid Multiple Popups' does not seem to be functioning correctly for me.

I am looking to create multiple popups on the same page (from the header), but when one is shown hide the other.

e.g. click a navigation element that triggers the 'restaurant menu pop up' (this shows food category options), from which if you click one of the food categories options (lets say 'pizza') it will trigger another popup ( 'pizza popup') that shows you all of the pizza options available. But when this 'pizza pop up' shows it hides the previous "restaurant menu pop up".

Currently, for both popups I have 'Avoid Multiple Popups' checked, but when one shows it just shows ontop of the other and no hiding of the previous pop up occurs.

When ideally if one is currently toggled and then another is toggled, I want to hide the original pop up and vice versa.

**Comment by xyberscript** [comment]
Currently on the latest version of Elementor (v3.0.11) and Elementor Pro (v3.0.5).

I have same issue

**Comment by saranghills** [comment]
Not sure whether this is a new issue or related to the above. I am also using pop-up for menu. There is an item on the menu that opens a new pop-up. When I close the second pop-up, the first one also is getting closed. Like avoiding opening multiple pop-ups is there a way to avoid closing multiple pop-ups?

**Comment by khelochagabia** [comment]
> Not sure whether this is a new issue or related to the above. I am also using pop-up for menu. There is an item on the menu that opens a new pop-up. When I close the second pop-up, the first one also is getting closed. Like avoiding opening multiple pop-ups is there a way to avoid closing multiple pop-ups?

Yes there is, You can go to the advance settings of the popup and enable the prevent closing on overlay and esc key

**Comment by Twolar** [comment]
> Currently on the latest version of Elementor (v3.0.11) and Elementor Pro (v3.0.5).
> 
> I have same issue

Hey Khel,

This is the response I got from the elementor team, hopefully it helps you in some way!

```
The "Avoid multiple popups" option doesn't prevent to have multiple popups opened, it prevents to display a second popup if another one has been displayed already, to prevent spamming the visitor with too many popups; so this feature will not work for what you need.

You will need to add some custom code to the first popup top to achieve the wanted functionality.

You can add an HTML Widget to the first popup with the code below:
<script>
jQuery(function($){
$(document).on('click','.elementor-location-popup a', function(event){
elementorProFrontend.modules.popup.closePopup( {}, event);
});
});
</script>

Source: https://elementorcodes.com/elementor-close-popup-on-click-link/

This code will close the popup when any link on it is clicked. If you wanted to be more specific, like closing the popup only when a button is clicked, you can change the ".elementor-location-popup a" selector in the code.

Please note that custom code is outside our support scope. This information is provided as a reference only.
```

**Comment by saranghills** [comment]
> > Not sure whether this is a new issue or related to the above. I am also using pop-up for menu. There is an item on the menu that opens a new pop-up. When I close the second pop-up, the first one also is getting closed. Like avoiding opening multiple pop-ups is there a way to avoid closing multiple pop-ups?
> 
> Yes there is, You can go to the advance settings of the popup and enable the prevent closing on overlay and esc key

Wow! Now, this fixed it.  I feel so dumb for missing that! :D Thank you so much!

**Comment by Xanou96** [comment]
> Currently on the latest version of Elementor (v3.0.10) and Elementor Pro (v3.0.5).
> 
> 'Avoid Multiple Popups' does not seem to be functioning correctly for me.
> 
> I am looking to create multiple popups on the same page (from the header), but when one is shown hide the other.
> 
> e.g. click a navigation element that triggers the 'restaurant menu pop up' (this shows food category options), from which if you click one of the food categories options (lets say 'pizza') it will trigger another popup ( 'pizza popup') that shows you all of the pizza options available. But when this 'pizza pop up' shows it hides the previous "restaurant menu pop up".
> 
> Currently, for both popups I have 'Avoid Multiple Popups' checked, but when one shows it just shows ontop of the other and no hiding of the previous pop up occurs.
> 
> When ideally if one is currently toggled and then another is toggled, I want to hide the original pop up and vice versa.

Hello, did you find a solution to this? Is it fixed or any work around?

**Comment by lensbreak** [comment]
Why is this issue closed if it is still buggy and not resolved in 2024? Is this again a classic Elementor example of not solving a bug for 5 years?! Look at the date of OP.

**Comment by Rvnd0m** [comment]
One more person with the same problem here. 5 years to NOT fix it, Elementor? Really? If it were a free plugin it would be ok, but with an expensive builder like this one, this is not serious. Time to start looking for other building tools, because Elementor is bug after bug, and they don't even solve it when useres spot them.

**Comment by mcimam** [comment]
One more person with same problem here. Howeve, i notice that somehow pop up link is reset even after selecting and pop up still functioning just can only click once. Reselect popup again will fix it.

![image](https://github.com/elementor/elementor/assets/22250002/4a92dfad-ff83-48bf-810f-9e077add97a7)

**Comment by artechio** [comment]
The issue still exists against the latest stable version of Elementor.

**Comment by rrdirnens** [comment]
Same issue. Please address this, Elementor team.

**Comment by sdgamage** [comment]
@rrdirnens  
> Same issue. Please address this, Elementor team.

Did you try disabling the option below in Popup settings? As it states, it will prevent opening another popup if the user has already seen one on the same page.

This worked for me.

![image](https://github.com/user-attachments/assets/789e6e75-97e7-4005-b273-657329d8d6ca)

**Comment by blaaskaakje** [comment]
Same here, same issue. It’s not fixed and I don’t get how this is closed.
