### ISSUE TITLE
Full Width Slider's Navigation Causes Horizontal Scrollbar After Update to 2.6.x

### ISSUE THREAD

**Issue by black-eye** [elementor/elementor#8527]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Another bug after update to 2.6 - when using full width slides, updated arrows are causing extended width and thus horizontal scrollbar appearance.

This is how it was before:

![obrazek](https://user-images.githubusercontent.com/5634870/61005700-f7278780-a368-11e9-84cb-53c258012ecb.png)

And this is, how it is after the update:

![obrazek](https://user-images.githubusercontent.com/5634870/61005768-19b9a080-a369-11e9-8c01-4daa413909d6.png)

![obrazek](https://user-images.githubusercontent.com/5634870/61005790-250ccc00-a369-11e9-9aea-5a80389f4029.png)

I would have provided you with a live example, but I'll have to roll back. Sorry, too many bugs again... :-(

## Steps to reproduce

1. Update to 2.6
2. Make a full width section
3. Place a Slides widget there
4. Check the horizontal scrollbar

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.6.40
	MySQL version: MariaDB Server v5.5.59-MariaDB-38.11
	PHP Version: 7.1.0
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.2
	Site URL: https://behaviolabs.com/dev
	Home URL: https://behaviolabs.com/dev
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: cs-CZ
	Timezone: Europe/Prague
	Debug Mode: Inactive

== Theme ==
	Name: Behavio WPBF
	Version: 1.0.0
	Author: Petr Jandák
	Child Theme: Yes
	Parent Theme Name: Page Builder Framework
	Parent Theme Version: 2.0.7
	Parent Theme Author: David Vongries

== User ==
	Role: administrator
	WP Profile lang: cs_CZ
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0

== Active Plugins ==
	Activity Log
		Version: 2.5.2
		Author: Activity Log Team

	Admin Menu Editor
		Version: 1.9
		Author: Janis Elsts

	All-in-One WP Migration
		Version: 6.77
		Author: ServMask

	Central Color Palette
		Version: 1.13.10
		Author: Daniel Schneider

	Classic Editor
		Version: 1.5
		Author: WordPress Contributors

	Clean Image Filenames
		Version: 1.2.1
		Author: Upperdog

	Cookie Notice
		Version: 1.2.46
		Author: dFactory

	Disable Comments
		Version: 1.9.0
		Author: Samir Shah

	Duplicate Post
		Version: 3.2.3
		Author: Enrico Battocchi

	Elementor
		Version: 2.6.1
		Author: Elementor.com

	Elementor Extras
		Version: 2.1.4
		Author: Namogo

	Elementor Pro
		Version: 2.5.12
		Author: Elementor.com

	Enable Media Replace
		Version: 3.3.1
		Author: ShortPixel

	Intuitive Custom Post Order
		Version: 3.1.2
		Author: hijiri

	iThemes Security
		Version: 7.4.0
		Author: iThemes

	Nested Pages
		Version: 3.0.11
		Author: Kyle Phillips

	Page Builder Framework Premium Addon
		Version: 2.0.5
		Author: David Vongries

	Piotnet Addons For Elementor Pro
		Version: 4.8.29
		Author: Luong Huu Phuoc (Louis Hufer)

	ShortPixel Image Optimizer
		Version: 4.14.2
		Author: ShortPixel

	Simple 301 Redirects
		Version: 1.07
		Author: Scott Nellé

	SVG Support
		Version: 2.3.15
		Author: Benbodhi

	The SEO Framework
		Version: 3.2.4
		Author: Sybre Waaijer

	TinyMCE Advanced
		Version: 5.2.1
		Author: Andrew Ozz

	WP Media folder
		Version: 4.8.5
		Author: Joomunited

	Zalomení
		Version: 1.4.7
		Author: Honza Skypala


== Log ==
	: 
Log: showing 20 of 402019-04-08 13:51:39 [info] Elementor Pro/Upgrades - _v_2_5_4_form Start  
2019-04-08 13:51:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.3',
  'to' => '2.5.4',
)]
2019-04-08 13:51:39 [info] Elementor Pro/Upgrades - _v_2_5_4_form Finished 
2019-04-08 13:51:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.3',
  'to' => '2.5.4',
)]
2019-04-08 18:42:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.11',
  'to' => '2.5.12',
)]
2019-05-09 03:49:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.12',
  'to' => '2.5.15',
)]
2019-05-09 03:50:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.4',
  'to' => '2.5.8',
)]
2019-06-17 00:02:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.15',
  'to' => '2.5.16',
)]
2019-06-17 00:03:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.8',
  'to' => '2.5.9',
)]
2019-07-10 22:54:39 [info] elementor::elementor_updater Started 
2019-07-10 22:54:39 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Start  
2019-07-10 22:54:39 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Finished 
2019-07-10 22:54:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.16',
  'to' => '2.6.1',
)]
2019-07-10 22:54:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.16',
  'to' => '2.6.1',
)]
2019-07-10 22:54:40 [info] elementor::elementor_updater Started 
2019-07-10 22:54:40 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Start  
2019-07-10 22:54:40 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Finished 
2019-07-10 22:54:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.16',
  'to' => '2.6.1',
)]
2019-07-10 22:54:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.16',
  'to' => '2.6.1',
)]
2019-07-10 22:54:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.9',
  'to' => '2.5.12',
)]

JS: showing 2 of 2JS: 2019-05-05 22:29:54 [error X 13][https://behaviolabs.com/dev/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.12:2:75425] setting getter-only property \"type\" 
JS: 2019-05-22 09:47:23 [error X 1][https://behaviolabs.com/dev/wp-content/plugins/elementor/assets/js/common.min.js?ver=2.5.15:2:11813] e is null 

PHP: showing 1 of 1PHP: 2019-06-16 00:40:25 [notice X 19][/var/www/vhosts/behaviolabs.com/www/dev/wp-content/plugins/elementor/includes/managers/image.php::33] Undefined index: size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
```
</details>

**Comment by manektechmayank** [comment]
I have same issue please some help.
I just drag & drop the slides widget and got following.

![image](https://user-images.githubusercontent.com/31854318/61941341-e7d54a80-afb4-11e9-956c-b48297b29998.png)

![image](https://user-images.githubusercontent.com/31854318/61941355-ec016800-afb4-11e9-93c6-7f0be0d2659d.png)

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.7

Feel free to update

Thanks!

**Comment by thefoximilien** [comment]
This issue still persists. Can we reopen this? (Version 2.8.4)
