### ISSUE TITLE
Bug After v2.5.13 Update: Broken Woocommerce number of columns in the grid view on Desktop

### ISSUE THREAD

**Issue by hubert-jaworski** [elementor/elementor#8555]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I just upgraded my Elementor Pro to 2.5.13.
This has broken the number of columns adjustment of the grid view in Woocommerce pages on Desktop for me.

Regardless of the widgets' settings, on Desktop it's always using the theme settings for the number of columns. That's OK for the shop page. Not for Product Related or Product Upsell widgets.

![2019-07-12 18_59_44-Customize_ Products – My Blog](https://user-images.githubusercontent.com/37505434/61145482-da5d9200-a4d7-11e9-8042-18f3fa61e0c2.png)

Case 1: Product Related widget, number of columns set to 2 on Desktop.

![2019-07-12 19_00_19-Elementor _ Single product Test #1](https://user-images.githubusercontent.com/37505434/61145510-ef3a2580-a4d7-11e9-9e99-94ee1aa2b71a.png)

Case 2: Product Related widget, number of columns set to 6 on Desktop.

![2019-07-12 19_00_41-Elementor _ Single product Test #1](https://user-images.githubusercontent.com/37505434/61145522-f82af700-a4d7-11e9-996f-29f37dae82e5.png)

It works on Tablet and Mobile though.

Case 3: Product Related widget, number of columns set to 2 on Tablet.

![2019-07-12 19_01_07-Elementor _ Single product Test #1](https://user-images.githubusercontent.com/37505434/61145552-0e38b780-a4d8-11e9-9c03-0cc89653ad70.png)

Case 4: Product Related widget, number of columns set to 4 on Tablet.

![2019-07-12 19_01_25-Elementor _ Single product Test #1](https://user-images.githubusercontent.com/37505434/61145568-142e9880-a4d8-11e9-9074-5bca605ab055.png)

**This happens regardless of the active theme.** I tested that on OceanWP, TwentyNineteen and Generate Press themes. 

## Steps to reproduce

1. Install clear WordPress
2. Install Elementor, Elementor Pro and Woocommerce plugins.
3. Add some products to Woocommerce.
4. Go to Appearance/Customize then WooCommerce and (depending on the theme) set the shop columns to an arbitrary number.
5. Create an Elementor Template for a Single Product, add the Product Related widget and set the number of the columns of the widget to a different number.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
https://pastebin.com/yGpHLnCX
</details>

**Comment by arielk** [comment]
Fixed in Pro v2.5.14

**Comment by fxaviers** [comment]
Here the bug still remains in Related Products. 
E v2.6.2 and EPro v2.5.14

**Comment by fxaviers** [comment]
@arielk Some ETA to fix this issue? TIA

**Comment by arielk** [comment]
As I wrote above, the original issue was resolved in v2.5.14, can you please add more details about your issue, which theme are you using? link to the page?

**Comment by fxaviers** [comment]
I find out the cause of the error.
It was necessary to recreate the CSS files. Even though I modified the page multiple times, this file was persistent and changed the correct number of columns.
To avoid this kind of problem, would not it be simpler, when installing an update, to have an automated routine to recreate CSS files (similar to what currently happens with database upgrade)?
