### ISSUE TITLE
Frontend.min.css overriding the theme styles which is bad

### ISSUE THREAD

**Issue by etwordpress01** [elementor/elementor#8804]
Hi, We are using your page builder in our premium theme. Many of our customers are facing issue with Frontend.min.css which is overriding  the theme figure and img tags styles.

http://prntscr.com/opx3xl

Have you any solution for that? It should be like that  http://prntscr.com/opx481

http://amentotech.com/projects/elementor/

Thanks again

**Comment by shilo-ey** [comment]
I merged this issue with #7331 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by etwordpress01** [comment]
Hi, I don't think that solutions is provided in reference

I think elementor should not add styles global, it should have parent or class names. 
Very bad, lot of themes facing these issues and they have to add important in css query which is bad.

Or at-least there should be hook which could load  frontend.min.css before the theme styles, We are using elementor page builder in premium themes and lot of our customers have purchased this premium plugin( elementor ) but your support is quite slow as compared to Brizy Plugin 

Thanks

**Comment by rpuig** [comment]
One year has passed, and elementor is still showing this Bug. I dont like using important in style declarations as it slows everything down!

**Comment by leecollings-sb** [comment]
> One year has passed, and elementor is still showing this Bug. I dont like using important in style declarations as it slows everything down!

Make that two years, and Elementor is still showing this bug... This stylesheet shoudl have the option to be disabled, or surely it makes sense if you check both the 'disable default fonts and colours', to be able to disable this default styling?

Why has this been closed and not addressed?
