### ISSUE TITLE
Feature Request - Schema implementation for FAQ

### ISSUE THREAD

**Issue by Biblothecaire** [elementor/elementor#9053]
I see a similar post in 2017 with a lot of +1 but i don't see answer or developement so i allow to re-open a ticket about this.
If need, 2017 post = https://github.com/elementor/elementor/issues/2385

It would be great to be able to set schema.org on elements.
I speak about this : https://developers.google.com/search/docs/data-types/faqpage?fbclid=IwAR2gAof3xvezIwXEF2dTsCICeeI7o4WQkRDsG1kRcMxbfXR4ta4wp2QhoDg#content-guidelines

Other people speak the same on other site / plugin : https://wordpress.org/support/topic/faq-schema-with-yoast-and-elementor/

1) do you plan to develop a specific section on this?
2) If no, how can we do it manually by ourselves?

Thanks for your help

**Comment by bainternet** [comment]
@Biblothecaire 

Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

As for your request,
1) There are no current plans to implement something like this as we feel this is more of a 3rd party plugin area.
2) Either use a 3rd party plugin for that or develop is your self using [Our API](http://developers.elementor.com)

thanks for the feedback.

**Comment by silkogelman** [comment]
unless 3rd party plugins are able to hook into the output of Elementors core & pro widgets, there is a risk in not adopting Schema Markup options by Elementor for their core and pro Widgets. 

And that’s the current necessity for creating ‘Widget clones’ that have the requested schema feature. Please allow me to explain 😶->😐

Elementor core and pro widgets are great, we as content editors and site devs want to use them. And it’s good for Elementor as a community that we keep using them. But what we don’t need is extra ’schema maintenance’ work that can be avoided. 

So if a widget can generate detailed schema markup (detailed, like ‘faq questions and answers, reviews & rating stars for every review on the page, not just on the page level like ‘this page is a recipe’ or ‘this page has an average rating of 4 out of 5’) and update it when widget content is updated, that would be great. 

But if Elementor decides it doesn’t need to provide Schema markup output option for their core & pro widgets, we need to migrate away from those widgets and move to widgets that provide a better solution for these needs. (We = every Elementor site that needs their SEO to be competitive)

And it is already happening.

As an example have a look at FAQ schema widget:
https://powerpackelements.com/elementor-widgets/faq/
https://www.youtube.com/watch?v=bN2g-fDuqss

It basically is Elementors Accordion / Toggle widget that also generates a bit of Schema Markup data. (Probably JDON-LD, I haven’t tested)

Extra todo for content creators: copy paste the content in the other widget (that is the same, the clone), but does have the ability to output Schema Markup. 

It makes no sense to me, so I hope there is good reasoning behind Elementor not supporting item-level Schema Markup for their widgets. 

Can you please explain?
Supporting detailed Schema Markup output is a HUGE chance for Elementor to shine, separate it from complicated other solutions or other Pagebuilders that are starting to provide it in a simple way that ‘just works’. 

Or is there an alternative to or reason not to add the Schema Markup output ability that we’re unaware of?

Elementors current inability to provide detailed item level Schema Markup output in a simple, maintainable way is a huge disadvantage for SEO and businesses that care about their search engine rankings in a competitive way.

Having to use 3rd party clone widgets when the same widget is built into Elementor seems weird, when the only goal is enabling functionality that is basically a core need for every Elementor user.

**Comment by silkogelman** [comment]
Other thoughts (completely not sure if this is feasible, developer input is very much appreciated 😊):
instead of widgetmakers creating their own Schema markup outputs (sometimes resulting in conflicting Schema output parts), maybe we need a Schema API for Elementor widgets. One that enables widgets to easily hook into (and dictates) the Schema output generation process, making it context aware, etc. That would allow all Elementor widgets (core/pro/3rd party) to upgrade their feature set, working seamlessly together in terms of Schema markup output, railing the value Elementor can provide as a page builder vs alternatives.

Elementor core/pro widgets could then set the example of using that Schema API.

Yoast developed an API like that for Gutenberg 
https://developer.yoast.com/features/schema/api/
but block makers don’t always want to rely on a specific SEO plugin solution, example:
https://wordpress.org/support/topic/integrates-with-yoasts-schema-api/
That would not be the case with Elementor Schema API, as Elementor widgets already depend on Elementor.

**Comment by silkogelman** [comment]
> 1. There are no current plans to implement something like this as we feel this is more of a 3rd party plugin area.

That means that its not a good choice as a site builder / content editor to use Elementor Pro widgets like Toggle / Accordion for FAQs, and not even Testimonial Widget, right?

Because for those, and probably other scenarios, once the site (business) decides it wants to get competitive in terms of SEO, it wants Schema markup support. And those Widgets don't support that in a maintainable way. (Managing Schema code through Elementors' Custom Attributes feature is a burden.)

Sites that built their content with those widgets eventually need to migrate all their content to other 3rd party widgets that DO support Schema in a content editor friendly way.

FAQ Schema supporting 3rd party widget as alternative for Toggle / Accordion:
https://powerpackelements.com/elementor-widgets/faq/

I was hoping Elementor has some sort of Schema API in the works, and use their own core & Pro widgets as an example.

**Comment by projectpi-ca** [comment]
I couldn’t find a FAQ Schema plugin that doesn’t render anything on the front end, so I created one and released it for free.

Check out this “FAQ Schema for Elementor” plugin
https://projectpi.ca/project/elementor-faq-schema-plugin/

**Comment by DorShahar** [comment]
Hey all,

This issue has been resolved in Elementor v3.2.0

Feel free to update!

**Comment by FrostStudios** [comment]
Finally! One extra plugin less - as this schema stuff is highly required in terms of SEO, love that it's now finally implemented. This issue has stopped me from using Elementor for FAQ sections, until now. 
Hope it works as expected ;)

**Comment by GreenballParis** [comment]
this is not working at all : FAQPAGE schema is still not implemented in ELEMENTOR 1 year after it's released and hundred of posts have indicated and proven that this is good for SEO. I really don't understand this waiting period.
