### ISSUE TITLE
Advanced image display order for Gallery Pro 

### ISSUE THREAD

**Issue by luxpatrick** [elementor/elementor#9269]
- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

With multiple in the new gallery pro selected the widget adds the images one category after another. This means that the user views just one category after another, not all images mixed together. For examples if you have categories like flowers, trees and mushrooms they are all groups together. Nor makes this sense nor doest it look good. I don't think that was the logic behind the widget. 

**Describe the solution you'd like**
Mix the images and add an order like date, random, etc.

**Comment by mileight** [comment]
hi. Any news in random and individual image url link?

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.8.1

Feel free to update

Thanks!

**Comment by ClaudioRohrbach** [comment]
I work with Elementor PRO V.3.0.10 and still can't find the ordering options described in #9487 and #9269 even though the tickets are both closed.

I would like to sort the images of mulitple galleries in chronological order (by upload date), when displaying "all".
As stated by @luxpatrick, displaying the images gallery by gallery does not make much sense.
What's the status on this particular feature?

**Comment by MichaelCampanella** [comment]
When is this going to be addressed? As of writing this (Elementor 3.8.1) this is not resolved. @shilo-ey why did you close this ticket when it's not resolved?
