### ISSUE TITLE
Slider background images still not responsive / srcset based, increasing load resources!

### ISSUE THREAD

**Issue by whatsnewsisyphus** [elementor/elementor#9719]
Hello All,
Thanks for developing Elementor.
I see that the slider element still doesn't use responsive images for the backgrounds, adding quite a bit of load time and resources to the page. It's not really acceptable in this day and age.

https://css-tricks.com/responsive-images-css/
https://aclaes.com/responsive-background-images-with-srcset-and-sizes/
http://scottjehl.github.io/picturefill/
https://afarkas.github.io/lazysizes/index.html

**Comment by swinggraphics** [comment]
I just came into the Issues section to comment on this, too. @elementor Please use intermediate image sizes in the generated code. To do this correctly, there should be a control (for the slider as a whole) to set which size is used for each breakpoint.

**Comment by whatsnewsisyphus** [comment]
> I just came into the Issues section to comment on this, too. @elementor Please use intermediate image sizes in the generated code. To do this correctly, there should be a control (for the slider as a whole) to set which size is used for each breakpoint.

They actually don't have to put anything on the front end, there has been an internet standard for handling this on the backend for a longtime, as with all normal wordpress images, the browser selects the appropriate size from an array of images in the backend. It's bizarre that they introduced a feature in 2019 that doesn't use responsive design.

**Comment by swinggraphics** [comment]
> They actually don't have to put anything on the front end, there has been an internet standard for handling this on the backend for a longtime, as with all normal wordpress images, the browser selects the appropriate size from an array of images in the backend. It's bizarre that they introduced a feature in 2019 that doesn't use responsive design.

Yes, if they chose to output an image element instead of using background-image on a div. I see pluses and minuses to both. I fight with WP constantly over what it includes in its srcset attribute, so I would love to be able to just specify one to three sizes in the editor, whether it appears as a background or img.

**Comment by therealgilles** [comment]
I think there are two issues here:
1) The slider does not allow to choose a specific thumbnail size.
2) srcset does not exist for background images and image-set is not quite equivalent. It may be possible to reproduce the srcset functionality with different css media queries, not sure.

Implementing #1 should be fairly straightforward and done first. If #2 is implemented, it should be done for all background images, not just for the slider.

**Comment by whatsnewsisyphus** [comment]
on 1) What instance would you have where you know the "thumbnail size" needed by a browser(by which I am assuming you mean thumbnail as in wordpress sized images)
2) With this done, 1) could default to a smaller thumbnail

Anyhow, Elementor come on, it's 2020 and this is what we were discussing among CSS designer/devs circa 2013! It's things like this that make people install ridiculous addons that bloat their size to several MBS

**Comment by therealgilles** [comment]
1) I have an image that is 1000 x 1000 but I know the slide is 200 x 200 max. I would like to be able to use a wordpress sized image that is closer to 200 x 200, maybe 500 x 500 or 300 x 300 (if these sizes are available). I know I could resize the image myself but I want the bigger size to be able to display it full size via lightbox.

2) Correct.

I honestly would prefer if the Wordpress team tackled this issue themselves.

**Comment by whatsnewsisyphus** [comment]
Wordpress is unlikely to tackle background images as it's not neatly
compartmentalized, or one that you could easily compartmentalize since it's
a very varied parameter and is not even element specific, not to mention
asynchronous loading for slider elements. Sliders have been doing this fine
for almost a decade now, Elementor started a bit hands on and never got
around to revamping some of its foundations for best practices.

*~d*

**Comment by tdechangy** [comment]
+1000 !  to achieve this, whatever the way. The World needs slow footprint on our attention and even more on our (still) green planet. Reducing load size by 5 -10 - 20 times the original size (when not even worth!) is a kind of a mission, not just a "trick".

Hoping to read seriously implicated answers from elementor to address this (who said that life would always be easy > but even more interesting), why not with Wordpress core team itself.

Regards.

**Comment by swinggraphics** [comment]
This is a very simple thing for Elementor to handle, and a perfect example of increasing the consistency of their interface. When you add an Image widget, Elementor lets you choose an image size. That should be the same for Slides. Most controls (with some frustrating exceptions) let you change their settings for tablets and phones. This is (maybe) not needed for image widgets, but should definitely be available for Slides.

**Comment by tdechangy** [comment]
@swinggraphics your suggestion is also interesting but doesn't match the initial subject of this post. What we would have is this marvelous functionality of srcset or equivalent, which ensure perfect responsiveness and reliability. Choosing custom sizes is in fact somehow outdated compared to it. Two reasons here : You have to spend time setting sizes for each image on each device size (so boring); what happens if for any reason you removed an image size for any reason ?

So as said, I think that your proposal is a kind of option but doesn't answer the needs for modern internet and lower our footprint with ease.

Waiting for Elementor's team implication.

**Comment by EricJammin** [comment]
+1

It makes optimizing a site almost impossible if the image carousel is used, as it will load the largest size selected, even on small mobile. That's not an ideal workflow when we have to be dealing with 30 inch hd displays , retina mobile devices, and everything in between, for the most modern websites.

Other image elements within elementor already utilize srcset, why doesn't this one?

**Comment by wwdes** [comment]
+1
Please implement.

**Comment by LucaRosaldi** [comment]
+1

This is very much needed for performance. Srcset would be ideal for this case, especially for full width sliders which are too heavy for mobile devices.

**Comment by TAGdevelop** [comment]
+12 
I am speaking for a team - that would love to use the Elementor Slider - but we don't because it lacks proper mobile functionality. Our desktop image is usually a very different aspect ratio then the mobile we currently use -

Also loading as a background image... I am not sure if that is best idea - seems like a render blocking issue nightmare - I am not sure if lazy load is possible with background images??? Maybe someone that knows more than I can chime in.

**Comment by e1creative** [comment]
@arielk Has this been fixed in Elementor????

**Comment by dbfischer** [comment]
+1
It is really unbelievable that the size of the images in the slider is not responsive even with the new flexbox containers.
In 2024 there are monitors with 4K or 8K and still iPhones with viewport 320px, where big images make no sense.
So why is it not possible to select the image resolution in SlideShow as it is possible with Classic image background?

**Comment by speedxcz** [comment]
It is unbelievable that even in 2024 this problem has not been solved. The main thing is that we all have Elementor AI spammed, but the essential problems are still not solved.
