### ISSUE TITLE
Copy and Paste Style Does not show in Editor in Elementor V2.8.0

### ISSUE THREAD

**Issue by sprad001** [elementor/elementor#9811]
This problem carries over from the Elementor V2.8 Beta 4, which a few of us has reported.
When copying the attributes of a widget and pasting it into another one, the values get pasted but the change is not reflected on the widget in the editor, but when initiating a preview the change can be seen in the preview. See recording https://www.screencast.com/t/omuM0zSkME.
This test was done in Firefox but previously I have experienced the same in Chrome.
Prior to this test, after activation of Elementor V2.8.0 I cleared the browser cache, rebuilt all the CSS where I could do that and did a hard browser reload, otherwise not even the values would paste as it would be expected.

[system-info-1.txt](https://github.com/elementor/elementor/files/3942501/system-info-1.txt)

**Comment by lauragonzalezz** [comment]
I updated a website to elementor 2.8 and it didn't copy and paste Column styles at all. It didn't change attributes, or reflect on the editor, or reflect on the preview, or show in the actual page. I tried duplicating columns but it didn't do anything either. Had to go back to 2.7.6 where everything worked as expected.
[system-info.txt](https://github.com/elementor/elementor/files/3945333/system-info.txt)

**Comment by black-eye** [comment]
I have the similar issues, but with inconsistent behavior. Sometimes the style get pasted, sometimes not. First I though it was because it was 3rd party widget, but then I realized, it once worked and once not.

**Comment by bartistiek** [comment]
I have the same issue

**Comment by sprad001** [comment]
**@lauragonzalezz** 
> 
> 
> I updated a website to elementor 2.8 and it didn't copy and paste Column styles at all. It didn't change attributes, or reflect on the editor, or reflect on the preview, or show in the actual page. I tried duplicating columns but it didn't do anything either. Had to go back to 2.7.6 where everything worked as expected.

Have you tried to do this? Clear the browser cache, rebuilt all the CSS where can and do a hard browser reload. This will not solve the problem in the preview but at least you should have the settings values pasted correctly and see the changes on the front end.

Hard browser reload or refresh can be done by holding CTRL button down and press F5, in case you do not know how to do that.

**Comment by webcolor-in** [comment]
+1 

I am facing exact same problem

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.8.1

Feel free to update

Thanks!

**Comment by webfocusdesign** [comment]
The issue persists for me in Elementor 2.8.1. The changelog from 2.8.1 mentions fixing this for columns but it affects everything and, on regular widgets it's still present.

After looking at this a little more closely I have isolated a potential use case where this happens. It seems to happen on sites with older Elementor installs that have used FOntAwesome 4.x and updated to 5. In that case, when looking in the Chrome dev tools console I see a 403 failure to load FontAwsome 4.7.0. In my case on my sandbox site :

Failed to load resource: the server responded with a status of 403 () https://sandbox.pixelyzed.com/astra/wp-content/plugins/elementor/assets/lib/font-awesome/css/?ver=4.7.0

Noteworthy that I actually have the setting to load FontAwesome 4 support at all "OFF" and not on so I have no idea why Elementor is still trying to load FontAwesome 4.7 and failing to do so.

On another site where I installed Elementor post the FontAwesome 5 upgrade (I forget what E version that was), Elementor is not loading or trying to load FontAwesome 4 so there's no 403 ressources loading error like in my Sandbox and copy paste works fine there.

**Comment by sprad001** [comment]
The same here, I am **still having the same problem** after clearing cache, rebuilding CSSs and hard reload of browser.

**Comment by iNewLegend** [comment]
@sprad001, please check if there no errors in console (CTRL + SHIFT + J in chrome).

**Comment by sprad001** [comment]
@iNewLegend I have this **post.php?post=10597&action=elementor:1 Unchecked runtime.lastError: The message port closed before a response was received.**

**Comment by black-eye** [comment]
Still having the issues when pasting styles too. On some of the instances of the SAME widget it works, on some not. But as I wrote earlier it's 3rd party widget, so I contacted the addon developer too.

No errors in console.

**Comment by webfocusdesign** [comment]
Issue still present in 2.8.2.

**Comment by webfocusdesign** [comment]
> @iNewLegend, I have these errors show up straight after Paste Style
> 
> _editor-modules.min.js?ver=2.8.1:2 Uncaught TypeError: n.attributes[e.name].each is not a function at Object. (editor-modules.min.js?ver=2.8.1:2) at Function.each (load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,underscore,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse&ver=5.3:2) at i.getStyleControls (editor-modules.min.js?ver=2.8.1:2) at i.renderStyles (editor.min.js?ver=2.8.1:2) at i.renderUI (editor.min.js?ver=2.8.1:2) at i.onRender (editor.min.js?ver=2.8.1:2) at i.onRender (editor.min.js?ver=2.8.1:31) at load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,underscore,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse&ver=5.3:9_

I get the exact same error in console (Chrome).

**Comment by sprad001** [comment]
@webfocusdesign, I got those errors in Firefox so looks like the same errors in both browsers.
I wonder if we should open another issue for this problem for V2.8.2 since this is apparently closed.

**Comment by sprad001** [comment]
I opened a new case for the V2.8.2 https://github.com/elementor/elementor/issues/9904
If you still have the same problem then please add your report there.

**Comment by JohnPixle** [comment]
I am having the same error, in my case it messes the contact forms styling in the editor, but not on the frontend. There is ticket #9846 if you guys face similar issues with forms. Tried editing with Safe mode and the issue persists, so clearly an issue. Running on latest El version.

**Comment by sprad001** [comment]
@JohnPixle for me the Piotnet Addons Pro caused the styling issue. Do you use that plugin?

**Comment by JohnPixle** [comment]
@sprad001 Hm... No I don't... And the issue is there fr me even after editing the page in Safe Mode, which indicates that this is not a third-party plugin or theme issue :/

**Comment by sprad001** [comment]
@JohnPixle, after deactivating all plugins but the Piotnet one, all came good with the Style Paste. Reactivating it brought back the issue.
Did you rebuild all the CSS, emptied the browser cache and hard loaded the browser with the CTRL+F5?
