### ISSUE TITLE
Inner section copy / paste / duplicate issue

### ISSUE THREAD

**Issue by OCpublishing** [elementor/elementor#9863]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Since 2.8.0 it seems I have eratic behavior regarding inner section copy/paste or duplicate. Sometimes it works, sometimes it does not. Even inside the same column an inner section does not duplicate with right click on the section handler or on the navigator. Drag and drop move the inner section far from where it is supposed to land and sometimes it even empty after moved.
Am I the only one experiencing this weird behavior since 2.8.0? And by the way 2.8.1 did not fix any issue regarding this problem

I did not do anything special. In fact I am using a model template that I use for months for each and every article I write and never had this issue before (no new plugin either)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

I was wondering if it is something on my side which will a support ticket or if it is a problem lots of others user experience.

**Comment by black-eye** [comment]
+1 Paste style still doesn't work in inner section.

**Comment by black-eye** [comment]
+ When I try to move a column from one section to another I got this error:
TypeError: n is undefinededitor.min.js:31:36402
After this, I'm not able to move columns anymore.

**Comment by TomRaraAvis** [comment]
+1 for can't duplicate inner section

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.8.2

Feel free to update

Thanks!

**Comment by OCpublishing** [comment]
@shilo-ey 
Hi Shilo-ey. I have updated and the problem is still here. I have a support ticket about this issue documented with videos of the problem.
Thanks for the update though

**Comment by shilo-ey** [comment]
Will check with support @OCpublishing 

Thanks

**Comment by vikaskhunteta** [comment]
Hi @shilo-ey 

I have been using **Elementor v2.9.14 & Elementor Pro v2.10.3** on multiple sites, since latest update I have been facing issue while duplicating section(not inner section) which is inside another section.

There is no problem in duplicating or copying or moving inner section inside a section but when I duplicate or move a section which is inside another section it doesn't work, if I move the section then it hides or removes from the edit area and can't bring back.

I didn't create new issue as there are multiple similar issues but in all of them, in the last you said to update to latest version, which we already have in this case.

I tried to reproduce same bug on latest WP default theme and the result was same.

Please fix the issue in upcoming release. Let me know should I create new issue or you will open this thread again?
