### ISSUE TITLE
[BUG] image Carousel - Auto play not working

### ISSUE THREAD

**Issue by tilnox** [elementor/elementor#9872]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

**Image carousel** 

**autoplay** doesn't work: is off and it still plays
**infinite loop** doesnt work: is off and it still loops

**settings**
![Dec-13-2019 18-54-57](https://user-images.githubusercontent.com/49846018/70824395-16c05180-1dda-11ea-9edb-3a88d25e97ad.gif)

**ON plugins**
![Screen Shot 2019-12-13 at 18 52 13](https://user-images.githubusercontent.com/49846018/70824408-1e7ff600-1dda-11ea-9af8-d72ff66fd9f0.png)

**testing link**
https://www.testing-elementor.marabarros.com/slideshow-2/

**theme**: hello

## Steps to reproduce

the settings
![Dec-13-2019 18-54-57](https://user-images.githubusercontent.com/49846018/70824395-16c05180-1dda-11ea-9edb-3a88d25e97ad.gif)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

I'm working on the slider on the domain it supposes to exist, but when bugs happen, I test it on clean Wordpress installation without all the extra plugins or strange themes, a version ready to test for incompatibilities, the error occurred on both versions.

## Environment
<summary>System Info</summary>
![System Info](https://user-images.githubusercontent.com/49846018/70825378-2ccf1180-1ddc-11ea-9a3a-5b25e46acf43.png)

Thank you

**Comment by doctor-damager** [comment]
Hello there, it has to do with the css class: "swiper-pagination-Slider"

for now my solution on this is to replace the element until its officialy fixed:

`if ($(".swiper-pagination").length) {

            $(".swiper-pagination").replaceWith("<div class='swiper-pagination simple-image-slider-pagination'></div>");
            
            var mySwiper = new Swiper('.swiper-container', {
                autoplay: {
                    delay: 3000,
                },
                pagination: {
                    el: '.swiper-pagination',
                    clickable: true,

                },
            });

        }`

**Comment by shilo-ey** [comment]
Hi @tilnox 

This issue has been resolved in our latest versions. feel free to update.

Thanks

**Comment by luismts** [comment]
+1

Versión 3.0.11

**Comment by chwalch** [comment]
Hi @shilo-ey,

I still experience this issue. I tried Image and media carousel and both of them are not working.
I'm on the latest Elementor and Elementor Pro version.

Any idea?

Many thanks,
Christoph
